#!/bin/bash

case $1 in
preparo)
  cd html && mkdir -p a b c d e f g h i j k l m n o p r s t u v z && cd ..
  ;;
artikolojn)
  . bin/xml_download.sh && bin/xml2txt.sh && bin/analizu_revo_prefix.sh '{}'
  ;;
# ĉar kompleta kuro daŭras tre longe, ni permesas kuri nur por kelkaj literoj
# kio signifas 2000..3000 artikoloj en unu kuro
a-d)
  . bin/xml_download.sh && bin/xml2txt.sh [a-d]  && bin/analizu_revo_novajn.sh
  ;;
e-j)
  . bin/xml_download.sh && bin/xml2txt.sh [e-j]  && bin/analizu_revo_novajn.sh
  ;;
k-m)
  . bin/xml_download.sh && bin/xml2txt.sh [k-m]  && bin/analizu_revo_novajn.sh
  ;;
n-r)
  . bin/xml_download.sh && bin/xml2txt.sh [n-r] && bin/analizu_revo_novajn.sh
  ;;
s-z)
  . bin/xml_download.sh && bin/xml2txt.sh [s-z]  && bin/analizu_revo_novajn.sh
  ;;
*)
  echo "Sola argumento povas esti nur 'preparo', 'artikolojn', 'a-d', 'e-j', 'k-m', 'n-r' aŭ 's-z'."
  ;;  
esac