#!/bin/bash

# mi ne ekzakte memoras kial mi aldonis . en la komenco de komandoj,
# sed supozeble uzi source (.) necesis por vidi la eligon de la skriptoj en docker-eligo...

case $1 in
preparo)
  echo "Certigu, ke vi ligis aŭ kopiis la dosierujojn dtd/ xsl/ kaj owl/ el voko-grundo tien ĉi!"
  echo "Kreiĝas nun se ne jam ekzistas labor-dosierujoj xml/ txt/ html/ tmp/"
  mkdir -p xml txt html tmp
  cd html && mkdir -p a b c d e f g h i j k l m n o p r s t u v z && cd ..
  cp web/stilo.css html/
  cp web/klarigoj.html html/
  ;;
artikolojn)
  . bin/xml_download.sh && bin/xml2txt.sh && bin/analizu_revo_prefix.sh '{}'
  ;;
# ĉar kompleta kuro daŭras tre longe, ni permesas kuri nur por kelkaj literoj
# kio signifas 2000..3000 artikoloj en unu kuro
tage)
  if [ ! -d html ]; then
    echo "ERARO: unuafoje necesas prepari la dosierujojn per celo preparo)"
    exit 1
  fi
  literoj=(e-j a-d e-j k-m n-r s-z a-d)
  LITEROJ=${literoj[ $(date +'%w') ]}  
  . bin/xml_download.sh && bin/xml2txt.sh [${LITEROJ}] && bin/analizu_revo_novajn.sh
  ;;
## la sekvaj estas intencitaj por uzi el GH-ago, do fine ili sinkronigas la rezultojn
a-d)
  . bin/xml_download.sh && bin/xml2txt.sh [a-d] && bin/analizu_revo_novajn.sh && bin/async.sh [a-d]
  ;;
e-j)
  . bin/xml_download.sh && bin/xml2txt.sh [e-j] && bin/analizu_revo_novajn.sh && bin/async.sh [e-j]
  ;;
k-m)
  . bin/xml_download.sh && bin/xml2txt.sh [k-m] && bin/analizu_revo_novajn.sh && bin/async.sh [k-m]
  ;;
n-r)
  . bin/xml_download.sh && bin/xml2txt.sh [n-r] && bin/analizu_revo_novajn.sh && bin/async.sh [n-r]
  ;;
s-z)
  . bin/xml_download.sh && bin/xml2txt.sh [s-z] && bin/analizu_revo_novajn.sh && bin/async.sh [s-z]
  ;;
test)
  echo "ŝargas abel.xml kaj konvertas xml/abel.xml al txt/abel.txt per xml2txt.sh"
  curl -q -o xml/abel.xml https://raw.githubusercontent.com/revuloj/revo-fonto/master/revo/abel.xml
  bin/xml2txt.sh abel
  echo "kontroli enhavon de txt/abel.txt"
  wc txt/abel.txt
  # la rezulto havu pli ol 20 liniojn da teksto
  set -- $(wc -l txt/abel.txt) ; [[ "$1" -gt 20 ]]
  ;;
*)
  echo "Sola argumento povas esti nur 'preparo', 'artikolojn', 'a-d', 'e-j', 'k-m', 'n-r' aŭ 's-z'."
  ;;  
esac