/*************
 *  radikoj 
*************/

r('abel','best') --> "abel".
r('abi','subst') --> "abi".
r('abomen','tr') --> "abomen".
r('abon','tr') --> "abon".
r('abrikot','subst') --> "abrikot".
r('abrupt','adj') --> "abrupt".
r('absolut','adj') --> "absolut".
r('abstin','ntr') --> "abstin".
r('absurd','adj') --> "absurd".
r('abund','adj') --> "abund".
r('acid','adj') --> "acid".
r('aĉet','tr') --> "aĉet".
r('adapt','tr') --> "adapt".
r('adici','tr') --> "adici".
r('adjektiv','subst') --> "adjektiv".
r('administr','tr') --> "administr".
r('admir','tr') --> "admir".
r('admon','tr') --> "admon".
r('adopt','tr') --> "adopt".
r('ador','tr') --> "ador".
r('adres','subst') --> "adres".
r('adverb','subst') --> "adverb".
r('advokat','best') --> "advokat".
r('aer','subst') --> "aer".
r('afabl','adj') --> "afabl".
r('afer','subst') --> "afer".
r('afiŝ','subst') --> "afiŝ".
r('aflikt','tr') --> "aflikt".
r('afrank','tr') --> "afrank".
r('afrik','subst') --> "afrik".
r('ag','ntr') --> "ag".
r('agent','best') --> "agent".
r('agit','tr') --> "agit".
r('agl','best') --> "agl".
r('agord','tr') --> "agord".
r('agrabl','adj') --> "agrabl".
r('aĝ','subst') --> "aĝ".
r('ajl','subst') --> "ajl".
r('akademi','subst') --> "akademi".
r('akcel','tr') --> "akcel".
r('akcent','tr') --> "akcent".
r('akcept','tr') --> "akcept".
r('akci','subst') --> "akci".
r('akcident','subst') --> "akcident".
r('akir','tr') --> "akir".
r('akn','subst') --> "akn".
r('akompan','tr') --> "akompan".
r('akord','subst') --> "akord".
r('akr','adj') --> "akr".
r('akrid','best') --> "akrid".
r('aks','subst') --> "aks".
r('akt','subst') --> "akt".
r('aktiv','adj') --> "aktiv".
r('aktor','best') --> "aktor".
r('aktual','adj') --> "aktual".
r('akurat','adj') --> "akurat".
r('akuz','tr') --> "akuz".
r('akv','subst') --> "akv".
r('alarm','tr') --> "alarm".
r('alaŭd','best') --> "alaŭd".
r('album','subst') --> "album".
r('ale','subst') --> "ale".
r('alfabet','subst') --> "alfabet".
r('alg','best') --> "alg".
r('ali','adj') --> "ali".
r('alkohol','subst') --> "alkohol".
r('almoz','subst') --> "almoz".
r('alt','adj') --> "alt".
r('altern','ntr') --> "altern".
r('alternativ','subst') --> "alternativ".
r('alud','tr') --> "alud".
r('alumet','subst') --> "alumet".
r('alumini','subst') --> "alumini".
r('am','tr') --> "am".
r('amar','adj') --> "amar".
r('amas','subst') --> "amas".
r('amator','best') --> "amator".
r('ambasad','subst') --> "ambasad".
r('ambasador','best') --> "ambasador".
r('amerik','subst') --> "amerik".
r('amik','best') --> "amik".
r('ampleks','subst') --> "ampleks".
r('ampol','subst') --> "ampol".
r('amuz','tr') --> "amuz".
r('anas','best') --> "anas".
r('anekdot','subst') --> "anekdot".
r('angil','best') --> "angil".
r('angul','subst') --> "angul".
r('anĝel','best') --> "anĝel".
r('anim','subst') --> "anim".
r('animal','best') --> "animal".
r('anonc','tr') --> "anonc".
r('anser','best') --> "anser".
r('aparat','subst') --> "aparat".
r('apart','adj') --> "apart".
r('apartament','subst') --> "apartament".
r('aparten','ntr') --> "aparten".
r('aper','ntr') --> "aper".
r('apertur','subst') --> "apertur".
r('apetit','subst') --> "apetit".
r('aplaŭd','tr') --> "aplaŭd".
r('aplik','tr') --> "aplik".
r('apog','tr') --> "apog".
r('apostol','best') --> "apostol".
r('apotek','subst') --> "apotek".
r('apr','best') --> "apr".
r('april','subst') --> "april".
r('aprob','tr') --> "aprob".
r('arane','best') --> "arane".
r('aranĝ','tr') --> "aranĝ".
r('arb','subst') --> "arb".
r('arbitr','adj') --> "arbitr".
r('arbust','subst') --> "arbust".
r('ard','ntr') --> "ard".
r('arĝent','subst') --> "arĝent".
r('ark','subst') --> "ark".
r('arm','subst') --> "arm".
r('arme','subst') --> "arme".
r('art','subst') --> "art".
r('arteri','subst') --> "arteri".
r('artik','subst') --> "artik".
r('artikol','subst') --> "artikol".
r('asekur','tr') --> "asekur".
r('asemble','subst') --> "asemble".
r('asert','tr') --> "asert".
r('asfalt','subst') --> "asfalt".
r('asist','ntr') --> "asist".
r('asoci','subst') --> "asoci".
r('aspekt','subst') --> "aspekt".
r('atak','tr') --> "atak".
r('atend','tr') --> "atend".
r('atent','tr') --> "atent".
r('atest','tr') --> "atest".
r('ating','tr') --> "ating".
r('atlantik','subst') --> "atlantik".
r('atom','subst') --> "atom".
r('av','parc') --> "av".
r('avantaĝ','subst') --> "avantaĝ".
r('avar','adj') --> "avar".
r('aven','subst') --> "aven".
r('aventur','subst') --> "aventur".
r('avenu','subst') --> "avenu".
r('avert','tr') --> "avert".
r('avid','adj') --> "avid".
r('aŭd','tr') --> "aŭd".
r('aŭdac','tr') --> "aŭdac".
r('aŭgust','subst') --> "aŭgust".
r('aŭskult','tr') --> "aŭskult".
r('aŭstrali','subst') --> "aŭstrali".
r('aŭt','subst') --> "aŭt".
r('aŭtobus','subst') --> "aŭtobus".
r('aŭtomat','subst') --> "aŭtomat".
r('aŭtomobil','subst') --> "aŭtomobil".
r('aŭtor','best') --> "aŭtor".
r('aŭtoritat','subst') --> "aŭtoritat".
r('aŭtun','subst') --> "aŭtun".
r('azen','best') --> "azen".
r('azi','subst') --> "azi".
r('babil','ntr') --> "babil".
r('bacil','best') --> "bacil".
r('bagatel','subst') --> "bagatel".
r('bak','tr') --> "bak".
r('bakteri','best') --> "bakteri".
r('bal','subst') --> "bal".
r('bala','tr') --> "bala".
r('balanc','tr') --> "balanc".
r('balbut','ntr') --> "balbut".
r('balon','subst') --> "balon".
r('balot','ntr') --> "balot".
r('bambu','subst') --> "bambu".
r('ban','tr') --> "ban".
r('banan','subst') --> "banan".
r('bandaĝ','subst') --> "bandaĝ".
r('bank','subst') --> "bank".
r('bant','subst') --> "bant".
r('bapt','tr') --> "bapt".
r('bar','tr') --> "bar".
r('barakt','ntr') --> "barakt".
r('barb','subst') --> "barb".
r('barbir','best') --> "barbir".
r('barel','subst') --> "barel".
r('bark','subst') --> "bark".
r('bask','subst') --> "bask".
r('baston','subst') --> "baston".
r('bat','tr') --> "bat".
r('batal','ntr') --> "batal".
r('baz','subst') --> "baz".
r('bazar','subst') --> "bazar".
r('beb','best') --> "beb".
r('bedaŭr','tr') --> "bedaŭr".
r('bek','subst') --> "bek".
r('bel','adj') --> "bel".
r('ben','tr') --> "ben".
r('bend','subst') --> "bend".
r('benk','subst') --> "benk".
r('benzin','subst') --> "benzin".
r('ber','subst') --> "ber".
r('best','best') --> "best".
r('bet','subst') --> "bet".
r('betul','subst') --> "betul".
r('bezon','tr') --> "bezon".
r('bibliotek','subst') --> "bibliotek".
r('bicikl','subst') --> "bicikl".
r('bien','subst') --> "bien".
r('bier','subst') --> "bier".
r('bifstek','subst') --> "bifstek".
r('bild','subst') --> "bild".
r('bilet','subst') --> "bilet".
r('bind','tr') --> "bind".
r('bird','best') --> "bird".
r('blank','adj') --> "blank".
r('blasfem','ntr') --> "blasfem".
r('blek','ntr') --> "blek".
r('blind','adj') --> "blind".
r('blok','subst') --> "blok".
r('blond','adj') --> "blond".
r('blov','ntr') --> "blov".
r('blu','adj') --> "blu".
r('bluz','subst') --> "bluz".
r('boat','subst') --> "boat".
r('boj','ntr') --> "boj".
r('bol','ntr') --> "bol".
r('bombon','subst') --> "bombon".
r('bon','adj') --> "bon".
r('bor','tr') --> "bor".
r('bord','subst') --> "bord".
r('bors','subst') --> "bors".
r('bot','subst') --> "bot".
r('botel','subst') --> "botel".
r('bov','best') --> "bov".
r('bovl','subst') --> "bovl".
r('bracelet','subst') --> "bracelet".
r('brak','subst') --> "brak".
r('branĉ','subst') --> "branĉ".
r('brand','subst') --> "brand".
r('brasik','subst') --> "brasik".
r('brav','adj') --> "brav".
r('bred','tr') --> "bred".
r('brems','subst') --> "brems".
r('bret','subst') --> "bret".
r('brid','tr') --> "brid".
r('brik','subst') --> "brik".
r('bril','ntr') --> "bril".
r('brokant','ntr') --> "brokant".
r('bronz','subst') --> "bronz".
r('bros','subst') --> "bros".
r('broŝur','subst') --> "broŝur".
r('brov','subst') --> "brov".
r('bru','ntr') --> "bru".
r('brul','ntr') --> "brul".
r('brun','adj') --> "brun".
r('brust','subst') --> "brust".
r('brut','subst') --> "brut".
r('bub','subst') --> "bub".
r('buĉ','tr') --> "buĉ".
r('bud','subst') --> "bud".
r('buĝet','subst') --> "buĝet".
r('buk','subst') --> "buk".
r('buked','subst') --> "buked".
r('bukl','subst') --> "bukl".
r('bul','subst') --> "bul".
r('bulb','subst') --> "bulb".
r('bulk','subst') --> "bulk".
r('bulten','subst') --> "bulten".
r('bulvard','subst') --> "bulvard".
r('burĝ','subst') --> "burĝ".
r('burĝon','subst') --> "burĝon".
r('buŝ','subst') --> "buŝ".
r('buter','subst') --> "buter".
r('butik','subst') --> "butik".
r('buton','subst') --> "buton".
r('ced','ntr') --> "ced".
r('cel','tr') --> "cel".
r('cement','subst') --> "cement".
r('centimetr','subst') --> "centimetr".
r('centr','subst') --> "centr".
r('central','subst') --> "central".
r('cep','subst') --> "cep".
r('cerb','subst') --> "cerb".
r('cert','adj') --> "cert".
r('cerv','best') --> "cerv".
r('ceter','adj') --> "ceter".
r('cifer','subst') --> "cifer".
r('cigar','subst') --> "cigar".
r('cigared','subst') --> "cigared".
r('cign','best') --> "cign".
r('cikad','best') --> "cikad".
r('cikatr','subst') --> "cikatr".
r('cikl','subst') --> "cikl".
r('cikoni','best') --> "cikoni".
r('cinam','subst') --> "cinam".
r('cindr','subst') --> "cindr".
r('cir','subst') --> "cir".
r('cirkel','subst') --> "cirkel".
r('cirkl','subst') --> "cirkl".
r('cirkonstanc','subst') --> "cirkonstanc".
r('cirkul','ntr') --> "cirkul".
r('cirkuler','subst') --> "cirkuler".
r('cirkvit','subst') --> "cirkvit".
r('cit','tr') --> "cit".
r('citron','subst') --> "citron".
r('civil','adj') --> "civil".
r('civiliz','tr') --> "civiliz".
r('civit','subst') --> "civit".
r('ĉagren','tr') --> "ĉagren".
r('ĉambr','subst') --> "ĉambr".
r('ĉap','subst') --> "ĉap".
r('ĉapel','subst') --> "ĉapel".
r('ĉapitr','subst') --> "ĉapitr".
r('ĉar','subst') --> "ĉar".
r('ĉarm','adj') --> "ĉarm".
r('ĉas','tr') --> "ĉas".
r('ĉek','subst') --> "ĉek".
r('ĉel','subst') --> "ĉel".
r('ĉemiz','subst') --> "ĉemiz".
r('ĉen','subst') --> "ĉen".
r('ĉeriz','subst') --> "ĉeriz".
r('ĉerk','subst') --> "ĉerk".
r('ĉerp','tr') --> "ĉerp".
r('ĉes','ntr') --> "ĉes".
r('ĉeval','best') --> "ĉeval".
r('ĉiel','subst') --> "ĉiel".
r('ĉif','tr') --> "ĉif".
r('ĉifon','subst') --> "ĉifon".
r('ĉokolad','subst') --> "ĉokolad".
r('daktil','subst') --> "daktil".
r('danc','ntr') --> "danc".
r('dand','subst') --> "dand".
r('danĝer','subst') --> "danĝer".
r('dank','tr') --> "dank".
r('dat','subst') --> "dat".
r('daŭr','ntr') --> "daŭr".
r('debet','subst') --> "debet".
r('dec','adj') --> "dec".
r('decembr','subst') --> "decembr".
r('decid','tr') --> "decid".
r('dediĉ','tr') --> "dediĉ".
r('defend','tr') --> "defend".
r('deficit','subst') --> "deficit".
r('degel','ntr') --> "degel".
r('deĵor','ntr') --> "deĵor".
r('deklar','tr') --> "deklar".
r('dekliv','subst') --> "dekliv".
r('dekoraci','subst') --> "dekoraci".
r('dekstr','adj') --> "dekstr".
r('deleg','tr') --> "deleg".
r('delikat','adj') --> "delikat".
r('delir','ntr') --> "delir".
r('demand','tr') --> "demand".
r('dens','adj') --> "dens".
r('dent','subst') --> "dent".
r('denunc','tr') --> "denunc".
r('depon','tr') --> "depon".
r('deput','tr') --> "deput".
r('desegn','tr') --> "desegn".
r('desert','subst') --> "desert".
r('destin','tr') --> "destin".
r('detal','adj') --> "detal".
r('determin','tr') --> "determin".
r('detru','tr') --> "detru".
r('dev','ntr') --> "dev".
r('dezert','subst') --> "dezert".
r('dezir','tr') --> "dezir".
r('di','best') --> "di".
r('diabl','best') --> "diabl".
r('dialog','subst') --> "dialog".
r('diant','subst') --> "diant".
r('diet','subst') --> "diet".
r('difekt','tr') --> "difekt".
r('diferenc','subst') --> "diferenc".
r('difin','tr') --> "difin".
r('digest','tr') --> "digest".
r('dik','adj') --> "dik".
r('dikt','tr') --> "dikt".
r('diligent','adj') --> "diligent".
r('dimanĉ','subst') --> "dimanĉ".
r('dimensi','subst') --> "dimensi".
r('dir','tr') --> "dir".
r('direkt','tr') --> "direkt".
r('direktor','best') --> "direktor".
r('disk','subst') --> "disk".
r('diskut','ntr') --> "diskut".
r('dispon','ntr') --> "dispon".
r('disput','ntr') --> "disput".
r('distanc','subst') --> "distanc".
r('disting','tr') --> "disting".
r('distr','tr') --> "distr".
r('distribu','tr') --> "distribu".
r('diven','tr') --> "diven".
r('divers','adj') --> "divers".
r('divid','tr') --> "divid".
r('dogan','subst') --> "dogan".
r('doktor','best') --> "doktor".
r('dokument','subst') --> "dokument".
r('dolĉ','adj') --> "dolĉ".
r('dolor','tr') --> "dolor".
r('dom','subst') --> "dom".
r('domaĝ','subst') --> "domaĝ".
r('don','tr') --> "don".
r('donac','tr') --> "donac".
r('dorlot','tr') --> "dorlot".
r('dorm','ntr') --> "dorm".
r('dorn','subst') --> "dorn".
r('dors','subst') --> "dors".
r('dot','tr') --> "dot".
r('drak','best') --> "drak".
r('dram','subst') --> "dram".
r('drap','subst') --> "drap".
r('drat','subst') --> "drat".
r('dres','tr') --> "dres".
r('dron','ntr') --> "dron".
r('dub','ntr') --> "dub".
r('dung','tr') --> "dung".
r('duŝ','subst') --> "duŝ".
r('eben','adj') --> "eben".
r('ebri','adj') --> "ebri".
r('eduk','tr') --> "eduk".
r('edz','best') --> "edz".
r('efekt','subst') --> "efekt".
r('efektiv','adj') --> "efektiv".
r('efik','ntr') --> "efik".
r('egal','adj') --> "egal".
r('egoist','best') --> "egoist".
r('ekip','tr') --> "ekip".
r('eklezi','subst') --> "eklezi".
r('ekonomi','subst') --> "ekonomi".
r('ekran','subst') --> "ekran".
r('ekscit','tr') --> "ekscit".
r('ekskurs','subst') --> "ekskurs".
r('eksped','tr') --> "eksped".
r('eksperiment','subst') --> "eksperiment".
r('eksplod','ntr') --> "eksplod".
r('ekspluat','tr') --> "ekspluat".
r('eksport','tr') --> "eksport".
r('ekspozici','subst') --> "ekspozici".
r('ekstaz','subst') --> "ekstaz".
r('ekstrem','adj') --> "ekstrem".
r('ekvator','subst') --> "ekvator".
r('ekvilibr','subst') --> "ekvilibr".
r('ekzakt','adj') --> "ekzakt".
r('ekzamen','subst') --> "ekzamen".
r('ekzekut','tr') --> "ekzekut".
r('ekzempl','subst') --> "ekzempl".
r('ekzerc','tr') --> "ekzerc".
r('ekzist','ntr') --> "ekzist".
r('elast','adj') --> "elast".
r('elefant','best') --> "elefant".
r('elegant','adj') --> "elegant".
r('elekt','tr') --> "elekt".
r('elektr','subst') --> "elektr".
r('elektronik','subst') --> "elektronik".
r('element','subst') --> "element".
r('emajl','subst') --> "emajl".
r('embaras','subst') --> "embaras".
r('emerit','best') --> "emerit".
r('eminent','adj') --> "eminent".
r('emoci','tr') --> "emoci".
r('energi','subst') --> "energi".
r('enigm','subst') --> "enigm".
r('enket','subst') --> "enket".
r('entrepren','tr') --> "entrepren".
r('enu','ntr') --> "enu".
r('envi','tr') --> "envi".
r('epidemi','subst') --> "epidemi".
r('epok','subst') --> "epok".
r('erar','ntr') --> "erar".
r('escept','tr') --> "escept".
r('esenc','subst') --> "esenc".
r('eskap','ntr') --> "eskap".
r('esper','tr') --> "esper".
r('esperant','subst') --> "esperant".
r('esplor','tr') --> "esplor".
r('esprim','tr') --> "esprim".
r('est','ntr') --> "est".
r('establ','tr') --> "establ".
r('estim','tr') --> "estim".
r('esting','tr') --> "esting".
r('etaĝ','subst') --> "etaĝ".
r('etap','subst') --> "etap".
r('etat','subst') --> "etat".
r('etend','tr') --> "etend".
r('etern','adj') --> "etern".
r('event','subst') --> "event".
r('evident','adj') --> "evident".
r('evit','tr') --> "evit".
r('evolu','ntr') --> "evolu".
r('eŭrop','subst') --> "eŭrop".
r('ezok','best') --> "ezok".
r('fab','subst') --> "fab".
r('fabel','subst') --> "fabel".
r('fabrik','subst') --> "fabrik".
r('fac','subst') --> "fac".
r('facil','adj') --> "facil".
r('faden','subst') --> "faden".
r('fag','subst') --> "fag".
r('fajenc','subst') --> "fajenc".
r('fajf','ntr') --> "fajf".
r('fajr','subst') --> "fajr".
r('fak','subst') --> "fak".
r('fakt','subst') --> "fakt".
r('fal','ntr') --> "fal".
r('falĉ','tr') --> "falĉ".
r('fald','tr') --> "fald".
r('fals','tr') --> "fals".
r('fam','adj') --> "fam".
r('famili','subst') --> "famili".
r('familiar','adj') --> "familiar".
r('fand','tr') --> "fand".
r('fanfaron','ntr') --> "fanfaron".
r('fantazi','subst') --> "fantazi".
r('far','tr') --> "far".
r('farb','subst') --> "farb".
r('farm','tr') --> "farm".
r('fart','ntr') --> "fart".
r('farun','subst') --> "farun".
r('fasad','subst') --> "fasad".
r('fask','subst') --> "fask".
r('fason','subst') --> "fason".
r('fast','ntr') --> "fast".
r('favor','tr') --> "favor".
r('faŭk','subst') --> "faŭk".
r('fazan','subst') --> "fazan".
r('fazeol','subst') --> "fazeol".
r('fe','best') --> "fe".
r('febr','subst') --> "febr".
r('februar','subst') --> "februar".
r('feĉ','subst') --> "feĉ".
r('federaci','subst') --> "federaci".
r('fel','subst') --> "fel".
r('feliĉ','adj') --> "feliĉ".
r('felt','subst') --> "felt".
r('fend','subst') --> "fend".
r('fenestr','subst') --> "fenestr".
r('fenomen','subst') --> "fenomen".
r('fer','subst') --> "fer".
r('feri','subst') --> "feri".
r('ferm','tr') --> "ferm".
r('fervor','subst') --> "fervor".
r('fest','tr') --> "fest".
r('festen','subst') --> "festen".
r('fianĉ','parc') --> "fianĉ".
r('fid','tr') --> "fid".
r('fidel','adj') --> "fidel".
r('fier','adj') --> "fier".
r('fig','subst') --> "fig".
r('figur','subst') --> "figur".
r('fikci','subst') --> "fikci".
r('fiks','tr') --> "fiks".
r('fil','parc') --> "fil".
r('film','subst') --> "film".
r('fin','tr') --> "fin".
r('financ','subst') --> "financ".
r('fingr','subst') --> "fingr".
r('firm','adj') --> "firm".
r('fiŝ','best') --> "fiŝ".
r('fizik','subst') --> "fizik".
r('flag','subst') --> "flag".
r('flagr','ntr') --> "flagr".
r('flam','subst') --> "flam".
r('flan','subst') --> "flan".
r('flank','subst') --> "flank".
r('flar','tr') --> "flar".
r('flat','tr') --> "flat".
r('flav','adj') --> "flav".
r('fleg','tr') --> "fleg".
r('fleks','tr') --> "fleks".
r('flik','tr') --> "flik".
r('flirt','ntr') --> "flirt".
r('flor','subst') --> "flor".
r('flos','subst') --> "flos".
r('flu','ntr') --> "flu".
r('flug','ntr') --> "flug".
r('fluid','adj') --> "fluid".
r('flustr','tr') --> "flustr".
r('foir','subst') --> "foir".
r('foj','subst') --> "foj".
r('fojn','subst') --> "fojn".
r('foli','subst') --> "foli".
r('fond','tr') --> "fond".
r('fonograf','subst') --> "fonograf".
r('font','subst') --> "font".
r('fontan','subst') --> "fontan".
r('forges','tr') --> "forges".
r('forĝ','tr') --> "forĝ".
r('fork','subst') --> "fork".
r('form','tr') --> "form".
r('formik','best') --> "formik".
r('formul','subst') --> "formul".
r('forn','subst') --> "forn".
r('fort','adj') --> "fort".
r('fortik','adj') --> "fortik".
r('fos','tr') --> "fos".
r('fost','subst') --> "fost".
r('fotel','subst') --> "fotel".
r('fotograf','best') --> "fotograf".
r('frag','subst') --> "frag".
r('frak','subst') --> "frak".
r('frakas','tr') --> "frakas".
r('framb','subst') --> "framb".
r('frand','tr') --> "frand".
r('franĝ','subst') --> "franĝ".
r('frap','tr') --> "frap".
r('frat','parc') --> "frat".
r('fraŭl','best') --> "fraŭl".
r('fraz','subst') --> "fraz".
r('fremd','adj') --> "fremd".
r('frenez','adj') --> "frenez".
r('freŝ','adj') --> "freŝ".
r('fripon','best') --> "fripon".
r('frit','tr') --> "frit".
r('friz','tr') --> "friz".
r('fromaĝ','subst') --> "fromaĝ".
r('front','subst') --> "front".
r('frost','subst') --> "frost".
r('frot','tr') --> "frot".
r('fru','adv') --> "fru".
r('frukt','subst') --> "frukt".
r('frunt','subst') --> "frunt".
r('fuĝ','ntr') --> "fuĝ".
r('fulg','subst') --> "fulg".
r('fulm','subst') --> "fulm".
r('fum','subst') --> "fum".
r('fund','subst') --> "fund".
r('fundament','subst') --> "fundament".
r('funebr','subst') --> "funebr".
r('funel','subst') --> "funel".
r('fung','subst') --> "fung".
r('funkci','subst') --> "funkci".
r('funt','subst') --> "funt".
r('furaĝ','subst') --> "furaĝ".
r('furioz','adj') --> "furioz".
r('fuŝ','tr') --> "fuŝ".
r('gaj','adj') --> "gaj".
r('gajn','tr') --> "gajn".
r('gal','subst') --> "gal".
r('galoŝ','subst') --> "galoŝ".
r('gant','subst') --> "gant".
r('garaĝ','subst') --> "garaĝ".
r('garanti','ntr') --> "garanti".
r('garb','subst') --> "garb".
r('gard','tr') --> "gard".
r('garn','tr') --> "garn".
r('gas','subst') --> "gas".
r('gast','subst') --> "gast".
r('gazet','subst') --> "gazet".
r('gelaten','subst') --> "gelaten".
r('generaci','subst') --> "generaci".
r('general','subst') --> "general".
r('geni','subst') --> "geni".
r('gent','subst') --> "gent".
r('genu','subst') --> "genu".
r('geografi','subst') --> "geografi".
r('gest','subst') --> "gest".
r('girland','subst') --> "girland".
r('glaci','subst') --> "glaci".
r('glad','tr') --> "glad".
r('glas','subst') --> "glas".
r('glat','adj') --> "glat".
r('glav','subst') --> "glav".
r('glit','ntr') --> "glit".
r('glob','subst') --> "glob".
r('glor','tr') --> "glor".
r('glu','tr') --> "glu".
r('glut','tr') --> "glut".
r('gobi','best') --> "gobi".
r('golf','subst') --> "golf".
r('gorĝ','subst') --> "gorĝ".
r('graci','adj') --> "graci".
r('grad','subst') --> "grad".
r('grajn','subst') --> "grajn".
r('gram','subst') --> "gram".
r('gramatik','subst') --> "gramatik".
r('grand','adj') --> "grand".
r('grandioz','adj') --> "grandioz".
r('gras','subst') --> "gras".
r('grat','tr') --> "grat".
r('gratul','tr') --> "gratul".
r('grav','adj') --> "grav".
r('graved','adj') --> "graved".
r('greg','subst') --> "greg".
r('gren','subst') --> "gren".
r('ges','subst') --> "ges".
r('grimac','subst') --> "grimac".
r('grimp','ntr') --> "grimp".
r('grinc','ntr') --> "grinc".
r('grip','subst') --> "grip".
r('griz','adj') --> "griz".
r('grot','subst') --> "grot".
r('gru','best') --> "gru".
r('grumbl','ntr') --> "grumbl".
r('grund','subst') --> "grund".
r('grup','subst') --> "grup".
r('gudr','subst') --> "gudr".
r('gum','subst') --> "gum".
r('gust','subst') --> "gust".
r('gut','subst') --> "gut".
r('gvardi','subst') --> "gvardi".
r('gvid','tr') --> "gvid".
r('ĝarden','subst') --> "ĝarden".
r('ĝem','ntr') --> "ĝem".
r('ĝemel','best') --> "ĝemel".
r('ĝen','tr') --> "ĝen".
r('ĝendarm','best') --> "ĝendarm".
r('ĝeneral','adj') --> "ĝeneral".
r('ĝentil','adj') --> "ĝentil".
r('ĝerm','subst') --> "ĝerm".
r('ĝib','subst') --> "ĝib".
r('ĝoj','ntr') --> "ĝoj".
r('ĝu','tr') --> "ĝu".
r('ĝust','adj') --> "ĝust".
r('hajl','subst') --> "hajl".
r('hak','tr') --> "hak".
r('hal','subst') --> "hal".
r('halt','ntr') --> "halt".
r('hangar','subst') --> "hangar".
r('har','subst') --> "har".
r('haring','best') --> "haring".
r('harmoni','subst') --> "harmoni".
r('hav','tr') --> "hav".
r('haven','subst') --> "haven".
r('haŭt','subst') --> "haŭt".
r('hazard','subst') --> "hazard".
r('heĝ','subst') --> "heĝ".
r('hejm','subst') --> "hejm".
r('hejt','tr') --> "hejt".
r('hektar','subst') --> "hektar".
r('hel','adj') --> "hel".
r('helikopter','subst') --> "helikopter".
r('help','tr') --> "help".
r('hepat','subst') --> "hepat".
r('herb','subst') --> "herb".
r('hered','tr') --> "hered".
r('hero','subst') --> "hero".
r('herold','subst') --> "herold".
r('hezit','ntr') --> "hezit".
r('higien','subst') --> "higien".
r('himn','subst') --> "himn".
r('hirund','best') --> "hirund".
r('histori','subst') --> "histori".
r('hok','subst') --> "hok".
r('hom','best') --> "hom".
r('honest','adj') --> "honest".
r('honor','tr') --> "honor".
r('hont','ntr') --> "hont".
r('hor','subst') --> "hor".
r('horde','subst') --> "horde".
r('horizont','subst') --> "horizont".
r('horizontal','adj') --> "horizontal".
r('horloĝ','subst') --> "horloĝ".
r('hospital','subst') --> "hospital".
r('hotel','subst') --> "hotel".
r('huf','subst') --> "huf".
r('human','adj') --> "human".
r('humid','adj') --> "humid".
r('humil','adj') --> "humil".
r('humor','subst') --> "humor".
r('hund','best') --> "hund".
r('ide','subst') --> "ide".
r('ideal','subst') --> "ideal".
r('ident','adj') --> "ident".
r('ignor','tr') --> "ignor".
r('ilustr','tr') --> "ilustr".
r('imag','tr') --> "imag".
r('imit','tr') --> "imit".
r('imperi','subst') --> "imperi".
r('impet','ntr') --> "impet".
r('implik','tr') --> "implik".
r('import','tr') --> "import".
r('impost','subst') --> "impost".
r('impres','tr') --> "impres".
r('impuls','subst') --> "impuls".
r('imun','adj') --> "imun".
r('incit','tr') --> "incit".
r('ind','adj') --> "ind".
r('indiferent','adj') --> "indiferent".
r('indign','tr') --> "indign".
r('indik','tr') --> "indik".
r('individu','subst') --> "individu".
r('indulg','tr') --> "indulg".
r('industri','subst') --> "industri".
r('infan','best') --> "infan".
r('infekt','tr') --> "infekt".
r('infer','subst') --> "infer".
r('influ','tr') --> "influ".
r('inform','tr') --> "inform".
r('inĝenier','best') --> "inĝenier".
r('iniciat','tr') --> "iniciat".
r('injekt','tr') --> "injekt".
r('ink','subst') --> "ink".
r('inklin','adj') --> "inklin".
r('insekt','best') --> "insekt".
r('insid','ntr') --> "insid".
r('insign','subst') --> "insign".
r('insist','ntr') --> "insist".
r('inspektor','best') --> "inspektor".
r('inspir','tr') --> "inspir".
r('instal','tr') --> "instal".
r('instanc','subst') --> "instanc".
r('instig','tr') --> "instig".
r('instinkt','subst') --> "instinkt".
r('instru','tr') --> "instru".
r('instrument','subst') --> "instrument".
r('insul','subst') --> "insul".
r('insult','tr') --> "insult".
r('intelekt','subst') --> "intelekt".
r('inteligent','adj') --> "inteligent".
r('intenc','tr') --> "intenc".
r('interes','tr') --> "interes".
r('intern','adj') --> "intern".
r('interpelaci','subst') --> "interpelaci".
r('interpret','tr') --> "interpret".
r('intest','subst') --> "intest".
r('intim','adj') --> "intim".
r('inund','subst') --> "inund".
r('invalid','subst') --> "invalid".
r('invent','tr') --> "invent".
r('invit','tr') --> "invit".
r('ir','ntr') --> "ir".
r('ironi','subst') --> "ironi".
r('izol','tr') --> "izol".
r('jak','subst') --> "jak".
r('januar','subst') --> "januar".
r('jar','subst') --> "jar".
r('jubile','subst') --> "jubile".
r('jug','subst') --> "jug".
r('juĝ','tr') --> "juĝ".
r('juk','ntr') --> "juk".
r('juli','subst') --> "juli".
r('jun','adj') --> "jun".
r('jung','tr') --> "jung".
r('juni','subst') --> "juni".
r('jup','subst') --> "jup".
r('jur','subst') --> "jur".
r('just','adj') --> "just".
r('juvel','subst') --> "juvel".
r('ĵaluz','adj') --> "ĵaluz".
r('ĵaŭd','subst') --> "ĵaŭd".
r('ĵet','tr') --> "ĵet".
r('ĵur','tr') --> "ĵur".
r('ĵurnal','subst') --> "ĵurnal".
r('kaban','subst') --> "kaban".
r('kabinet','subst') --> "kabinet".
r('kaĉ','subst') --> "kaĉ".
r('kadr','subst') --> "kadr".
r('kaduk','adj') --> "kaduk".
r('kaf','subst') --> "kaf".
r('kaĝ','subst') --> "kaĝ".
r('kahel','subst') --> "kahel".
r('kaj','subst') --> "kaj".
r('kajer','subst') --> "kajer".
r('kajut','subst') --> "kajut".
r('kaka','subst') --> "kaka".
r('kakt','subst') --> "kakt".
r('kal','subst') --> "kal".
r('kaldron','subst') --> "kaldron".
r('kalendar','subst') --> "kalendar".
r('kalkan','subst') --> "kalkan".
r('kalkul','ntr') --> "kalkul".
r('kalson','subst') --> "kalson".
r('kalumni','tr') --> "kalumni".
r('kalv','adj') --> "kalv".
r('kamarad','best') --> "kamarad".
r('kamel','best') --> "kamel".
r('kamen','subst') --> "kamen".
r('kamion','subst') --> "kamion".
r('kamp','subst') --> "kamp".
r('kanal','subst') --> "kanal".
r('kandel','subst') --> "kandel".
r('kandidat','best') --> "kandidat".
r('kankr','best') --> "kankr".
r('kant','ntr') --> "kant".
r('kanzon','subst') --> "kanzon".
r('kap','subst') --> "kap".
r('kapabl','adj') --> "kapabl".
r('kapital','subst') --> "kapital".
r('kapr','best') --> "kapr".
r('kapric','subst') --> "kapric".
r('kapt','tr') --> "kapt".
r('kar','adj') --> "kar".
r('karaf','subst') --> "karaf".
r('karakter','subst') --> "karakter".
r('karb','subst') --> "karb".
r('kares','tr') --> "kares".
r('karn','subst') --> "karn".
r('karnaval','subst') --> "karnaval".
r('karot','subst') --> "karot".
r('karp','best') --> "karp".
r('kart','subst') --> "kart".
r('karton','subst') --> "karton".
r('kas','subst') --> "kas".
r('kaserol','subst') --> "kaserol".
r('kasked','subst') --> "kasked".
r('kastel','subst') --> "kastel".
r('kaŝ','tr') --> "kaŝ".
r('kaŝtan','subst') --> "kaŝtan".
r('kat','best') --> "kat".
r('katalog','subst') --> "katalog".
r('katar','subst') --> "katar".
r('kategori','subst') --> "kategori".
r('katen','subst') --> "katen".
r('kav','subst') --> "kav".
r('kavern','subst') --> "kavern".
r('kaŭĉuk','subst') --> "kaŭĉuk".
r('kaŭz','tr') --> "kaŭz".
r('kaz','subst') --> "kaz".
r('kejl','subst') --> "kejl".
r('kel','subst') --> "kel".
r('kelk','adj') --> "kelk".
r('kelner','best') --> "kelner".
r('kemi','subst') --> "kemi".
r('kern','subst') --> "kern".
r('kest','subst') --> "kest".
r('kilogram','subst') --> "kilogram".
r('kilometr','subst') --> "kilometr".
r('kin','subst') --> "kin".
r('kirurg','best') --> "kirurg".
r('kirurgi','subst') --> "kirurgi".
r('kis','tr') --> "kis".
r('kitel','subst') --> "kitel".
r('klar','adj') --> "klar".
r('klas','subst') --> "klas".
r('klasik','adj') --> "klasik".
r('kler','adj') --> "kler".
r('klient','best') --> "klient".
r('klimat','subst') --> "klimat".
r('klin','tr') --> "klin".
r('kling','subst') --> "kling".
r('klinik','subst') --> "klinik".
r('klopod','ntr') --> "klopod".
r('klub','subst') --> "klub".
r('knab','best') --> "knab".
r('kned','tr') --> "kned".
r('kok','best') --> "kok".
r('koket','adj') --> "koket".
r('kokos','subst') --> "kokos".
r('kol','subst') --> "kol".
r('kolegi','subst') --> "kolegi".
r('kolekt','tr') --> "kolekt".
r('kolektiv','subst') --> "kolektiv".
r('koler','ntr') --> "koler".
r('kolizi','ntr') --> "kolizi".
r('kolomb','best') --> "kolomb".
r('kolon','subst') --> "kolon".
r('kolonel','best') --> "kolonel".
r('kolor','subst') --> "kolor".
r('kolumn','subst') --> "kolumn".
r('kom','subst') --> "kom".
r('komand','subst') --> "komand".
r('komb','tr') --> "komb".
r('kombin','tr') --> "kombin".
r('komedi','subst') --> "komedi".
r('komenc','tr') --> "komenc".
r('komerc','ntr') --> "komerc".
r('komfort','adj') --> "komfort".
r('komik','adj') --> "komik".
r('komisar','best') --> "komisar".
r('komisi','tr') --> "komisi".
r('komision','subst') --> "komision".
r('komitat','subst') --> "komitat".
r('kompani','subst') --> "kompani".
r('kompar','tr') --> "kompar".
r('kompat','tr') --> "kompat".
r('kompens','tr') --> "kompens".
r('kompetent','adj') --> "kompetent".
r('komplement','subst') --> "komplement".
r('komplet','adj') --> "komplet".
r('komplez','ntr') --> "komplez".
r('komplik','tr') --> "komplik".
r('kompon','tr') --> "kompon".
r('kompren','tr') --> "kompren".
r('kompromit','tr') --> "kompromit".
r('komun','adj') --> "komun".
r('komunik','tr') --> "komunik".
r('kon','tr') --> "kon".
r('koncentr','tr') --> "koncentr".
r('koncept','subst') --> "koncept".
r('koncern','tr') --> "koncern".
r('koncert','subst') --> "koncert".
r('kondamn','tr') --> "kondamn".
r('kondiĉ','subst') --> "kondiĉ".
r('konduk','tr') --> "konduk".
r('kondut','ntr') --> "kondut".
r('konferenc','subst') --> "konferenc".
r('konfes','tr') --> "konfes".
r('konfid','tr') --> "konfid".
r('konfidenc','subst') --> "konfidenc".
r('konfirm','tr') --> "konfirm".
r('konfit','tr') --> "konfit".
r('konfuz','tr') --> "konfuz".
r('kongres','subst') --> "kongres".
r('konjekt','tr') --> "konjekt".
r('konklud','tr') --> "konklud".
r('konkord','subst') --> "konkord".
r('konkur','ntr') --> "konkur".
r('konkurs','subst') --> "konkurs".
r('konsci','tr') --> "konsci".
r('konscienc','subst') --> "konscienc".
r('konsekvenc','subst') --> "konsekvenc".
r('konsent','ntr') --> "konsent".
r('konserv','tr') --> "konserv".
r('konsider','tr') --> "konsider".
r('konsil','tr') --> "konsil".
r('konsist','ntr') --> "konsist".
r('konsol','tr') --> "konsol".
r('konstant','adj') --> "konstant".
r('konstat','tr') --> "konstat".
r('konstituci','subst') --> "konstituci".
r('konstru','tr') --> "konstru".
r('konsul','best') --> "konsul".
r('konsult','tr') --> "konsult".
r('konsum','tr') --> "konsum".
r('kontant','adj') --> "kontant".
r('kontent','adj') --> "kontent".
r('kontest','tr') --> "kontest".
r('kontrakt','ntr') --> "kontrakt".
r('kontrol','tr') --> "kontrol".
r('konval','subst') --> "konval".
r('konven','ntr') --> "konven".
r('konversaci','subst') --> "konversaci".
r('konvink','tr') --> "konvink".
r('kopi','tr') --> "kopi".
r('kor','subst') --> "kor".
r('korb','subst') --> "korb".
r('kord','subst') --> "kord".
r('korekt','tr') --> "korekt".
r('korespond','ntr') --> "korespond".
r('koridor','subst') --> "koridor".
r('kork','subst') --> "kork".
r('korn','subst') --> "korn".
r('kornik','best') --> "kornik".
r('korp','subst') --> "korp".
r('kort','subst') --> "kort".
r('korv','best') --> "korv".
r('kosm','subst') --> "kosm".
r('kost','ntr') --> "kost".
r('kostum','subst') --> "kostum".
r('kot','subst') --> "kot".
r('koton','subst') --> "koton".
r('kovert','subst') --> "kovert".
r('kovr','tr') --> "kovr".
r('kraĉ','ntr') --> "kraĉ".
r('krad','subst') --> "krad".
r('krajon','subst') --> "krajon".
r('kran','subst') --> "kran".
r('krani','subst') --> "krani".
r('kravat','subst') --> "kravat".
r('kre','tr') --> "kre".
r('kred','tr') --> "kred".
r('kredit','subst') --> "kredit".
r('krem','subst') --> "krem".
r('krepusk','subst') --> "krepusk".
r('kresk','ntr') --> "kresk".
r('krest','subst') --> "krest".
r('kret','subst') --> "kret".
r('krev','ntr') --> "krev".
r('kri','ntr') --> "kri".
r('krim','subst') --> "krim".
r('kripl','adj') --> "kripl".
r('kristal','subst') --> "kristal".
r('kritik','tr') --> "kritik".
r('kriz','subst') --> "kriz".
r('kroĉ','tr') --> "kroĉ".
r('krokodil','best') --> "krokodil".
r('kron','subst') --> "kron".
r('kruc','subst') --> "kruc".
r('kruĉ','subst') --> "kruĉ".
r('krud','adj') --> "krud".
r('kruel','adj') --> "kruel".
r('krur','subst') --> "krur".
r('krust','subst') --> "krust".
r('krut','adj') --> "krut".
r('kub','subst') --> "kub".
r('kubut','subst') --> "kubut".
r('kudr','tr') --> "kudr".
r('kugl','subst') --> "kugl".
r('kuir','tr') --> "kuir".
r('kuk','subst') --> "kuk".
r('kukol','best') --> "kukol".
r('kukum','subst') --> "kukum".
r('kukurb','subst') --> "kukurb".
r('kul','best') --> "kul".
r('kuler','subst') --> "kuler".
r('kulp','adj') --> "kulp".
r('kult','subst') --> "kult".
r('kultur','subst') --> "kultur".
r('kunikl','best') --> "kunikl".
r('kupon','subst') --> "kupon".
r('kupr','subst') --> "kupr".
r('kur','ntr') --> "kur".
r('kurac','tr') --> "kurac".
r('kuraĝ','adj') --> "kuraĝ".
r('kurb','adj') --> "kurb".
r('kurent','subst') --> "kurent".
r('kurioz','adj') --> "kurioz".
r('kurs','subst') --> "kurs".
r('kurten','subst') --> "kurten".
r('kusen','subst') --> "kusen".
r('kuŝ','ntr') --> "kuŝ".
r('kutim','ntr') --> "kutim".
r('kuv','subst') --> "kuv".
r('kuz','parc') --> "kuz".
r('kvadrat','subst') --> "kvadrat".
r('kvalit','subst') --> "kvalit".
r('kvant','subst') --> "kvant".
r('kvartal','subst') --> "kvartal".
r('kverk','subst') --> "kverk".
r('kviet','adj') --> "kviet".
r('labor','ntr') --> "labor".
r('laboratori','subst') --> "laboratori".
r('lac','adj') --> "lac".
r('lacert','best') --> "lacert".
r('laĉ','subst') --> "laĉ".
r('lad','subst') --> "lad".
r('lag','subst') --> "lag".
r('lak','subst') --> "lak".
r('lakt','subst') --> "lakt".
r('lam','adj') --> "lam".
r('lamen','subst') --> "lamen".
r('lamp','subst') --> "lamp".
r('lan','subst') --> "lan".
r('land','subst') --> "land".
r('lang','subst') --> "lang".
r('lantern','subst') --> "lantern".
r('lap','subst') --> "lap".
r('lard','subst') --> "lard".
r('larĝ','adj') --> "larĝ".
r('larm','subst') --> "larm".
r('larv','subst') --> "larv".
r('las','tr') --> "las".
r('last','adj') --> "last".
r('latitud','subst') --> "latitud".
r('latun','subst') --> "latun".
r('lav','tr') --> "lav".
r('laŭb','subst') --> "laŭb".
r('laŭd','tr') --> "laŭd".
r('laŭt','adj') --> "laŭt".
r('lecion','subst') --> "lecion".
r('led','subst') --> "led".
r('leg','tr') --> "leg".
r('legom','subst') --> "legom".
r('leĝ','subst') --> "leĝ".
r('lek','tr') --> "lek".
r('lekci','subst') --> "lekci".
r('leon','best') --> "leon".
r('lepor','best') --> "lepor".
r('lern','tr') --> "lern".
r('lert','adj') --> "lert".
r('lesiv','subst') --> "lesiv".
r('leter','subst') --> "leter".
r('lev','tr') --> "lev".
r('leŭtenant','best') --> "leŭtenant".
r('liber','adj') --> "liber".
r('libr','subst') --> "libr".
r('lice','subst') --> "lice".
r('licenc','subst') --> "licenc".
r('lift','subst') --> "lift".
r('lig','tr') --> "lig".
r('lign','subst') --> "lign".
r('likv','adj') --> "likv".
r('lili','subst') --> "lili".
r('lim','subst') --> "lim".
r('limak','best') --> "limak".
r('lin','subst') --> "lin".
r('lingv','subst') --> "lingv".
r('lini','subst') --> "lini".
r('lip','subst') --> "lip".
r('list','subst') --> "list".
r('lit','subst') --> "lit".
r('liter','subst') --> "liter".
r('literatur','subst') --> "literatur".
r('litr','subst') --> "litr".
r('liver','tr') --> "liver".
r('log','tr') --> "log".
r('logik','subst') --> "logik".
r('loĝ','ntr') --> "loĝ".
r('lojal','adj') --> "lojal".
r('lok','subst') --> "lok".
r('lokomotiv','subst') --> "lokomotiv".
r('long','adj') --> "long".
r('longitud','subst') --> "longitud".
r('lot','ntr') --> "lot".
r('lotus','subst') --> "lotus".
r('lu','tr') --> "lu".
r('lubrik','tr') --> "lubrik".
r('lud','tr') --> "lud".
r('luk','subst') --> "luk".
r('luks','subst') --> "luks".
r('lukt','ntr') --> "lukt".
r('lul','tr') --> "lul".
r('lum','subst') --> "lum".
r('lun','subst') --> "lun".
r('lund','subst') --> "lund".
r('lup','best') --> "lup".
r('maĉ','tr') --> "maĉ".
r('magazen','subst') --> "magazen".
r('magi','subst') --> "magi".
r('maiz','subst') --> "maiz".
r('maj','subst') --> "maj".
r('majest','adj') --> "majest".
r('majstr','best') --> "majstr".
r('maksimum','subst') --> "maksimum".
r('makul','subst') --> "makul".
r('maleol','subst') --> "maleol".
r('malic','adj') --> "malic".
r('malv','subst') --> "malv".
r('mam','subst') --> "mam".
r('man','subst') --> "man".
r('mandat','subst') --> "mandat".
r('manĝ','tr') --> "manĝ".
r('manier','subst') --> "manier".
r('manik','subst') --> "manik".
r('manipul','tr') --> "manipul".
r('mank','ntr') --> "mank".
r('manovr','ntr') --> "manovr".
r('mantel','subst') --> "mantel".
r('map','subst') --> "map".
r('mar','subst') --> "mar".
r('marĉ','subst') --> "marĉ".
r('mard','subst') --> "mard".
r('mark','subst') --> "mark".
r('marmelad','subst') --> "marmelad".
r('marŝ','ntr') --> "marŝ".
r('mart','subst') --> "mart".
r('martel','subst') --> "martel".
r('mas','subst') --> "mas".
r('mason','tr') --> "mason".
r('mast','subst') --> "mast".
r('mastr','best') --> "mastr".
r('maŝin','subst') --> "maŝin".
r('mat','subst') --> "mat".
r('matematik','subst') --> "matematik".
r('maten','subst') --> "maten".
r('materi','subst') --> "materi".
r('material','subst') --> "material".
r('matrac','subst') --> "matrac".
r('matur','adj') --> "matur".
r('mebl','subst') --> "mebl".
r('medicin','subst') --> "medicin".
r('medikament','subst') --> "medikament".
r('medit','ntr') --> "medit".
r('mediterane','sdubst') --> "mediterane".
r('mekanik','subst') --> "mekanik".
r('mekanism','subst') --> "mekanism".
r('melk','tr') --> "melk".
r('melon','subst') --> "melon".
r('membr','subst') --> "membr".
r('memor','ntr') --> "memor".
r('menci','tr') --> "menci".
r('mend','tr') --> "mend".
r('mens','subst') --> "mens".
r('mensog','ntr') --> "mensog".
r('menton','subst') --> "menton".
r('menu','subst') --> "menu".
r('meqanik','subst') --> "meqanik".
r('meqanism','subst') --> "meqanism".
r('merit','tr') --> "merit".
r('merkred','subst') --> "merkred".
r('mesaĝ','subst') --> "mesaĝ".
r('met','tr') --> "met".
r('metal','subst') --> "metal".
r('metalurgi','subst') --> "metalurgi".
r('meti','subst') --> "meti".
r('metod','subst') --> "metod".
r('metr','subst') --> "metr".
r('mez','subst') --> "mez".
r('mezur','tr') --> "mezur".
r('miel','subst') --> "miel".
r('mien','subst') --> "mien".
r('migr','ntr') --> "migr".
r('miks','tr') --> "miks".
r('mild','adj') --> "mild".
r('miliard','nombr') --> "miliard".
r('milimetr','subst') --> "milimetr".
r('milion','nombr') --> "milion".
r('milit','ntr') --> "milit".
r('min','subst') --> "min".
r('minac','tr') --> "minac".
r('mineral','subst') --> "mineral".
r('minimum','subst') --> "minimum".
r('ministeri','subst') --> "ministeri".
r('ministr','best') --> "ministr".
r('minut','subst') --> "minut".
r('mir','ntr') --> "mir".
r('mirtel','subst') --> "mirtel".
r('mister','subst') --> "mister".
r('mistifik','tr') --> "mistifik".
r('mizer','subst') --> "mizer".
r('mod','subst') --> "mod".
r('model','subst') --> "model".
r('moder','adj') --> "moder".
r('modern','adj') --> "modern".
r('modest','adj') --> "modest".
r('modif','tr') --> "modif".
r('mok','tr') --> "mok".
r('mol','adj') --> "mol".
r('moment','subst') --> "moment".
r('mon','subst') --> "mon".
r('monat','subst') --> "monat".
r('mond','subst') --> "mond".
r('monstr','subst') --> "monstr".
r('mont','subst') --> "mont".
r('montr','tr') --> "montr".
r('monument','subst') --> "monument".
r('mor','subst') --> "mor".
r('moral','subst') --> "moral".
r('mord','tr') --> "mord".
r('mort','ntr') --> "mort".
r('moskit','best') --> "moskit".
r('moŝt','best') --> "moŝt".
r('motor','subst') --> "motor".
r('mov','tr') --> "mov".
r('mozaik','subst') --> "mozaik".
r('muel','tr') --> "muel".
r('muĝ','ntr') --> "muĝ".
r('mul','best') --> "mul".
r('mult','adj') --> "mult".
r('multiplik','tr') --> "multiplik".
r('munt','tr') --> "munt".
r('mur','subst') --> "mur".
r('murmur','ntr') --> "murmur".
r('mus','best') --> "mus".
r('musk','subst') --> "musk".
r('muskol','subst') --> "muskol".
r('muŝ','best') --> "muŝ".
r('mut','adj') --> "mut".
r('muze','subst') --> "muze".
r('muzel','subst') --> "muzel".
r('muzik','subst') --> "muzik".
r('naci','subst') --> "naci".
r('nadl','subst') --> "nadl".
r('naĝ','ntr') --> "naĝ".
r('naiv','adj') --> "naiv".
r('najbar','best') --> "najbar".
r('najl','subst') --> "najl".
r('najtingal','best') --> "najtingal".
r('nask','tr') --> "nask".
r('natur','subst') --> "natur".
r('naŭz','tr') --> "naŭz".
r('naz','subst') --> "naz".
r('nebul','subst') --> "nebul".
r('neces','adj') --> "neces".
r('neglekt','tr') --> "neglekt".
r('neĝ','subst') --> "neĝ".
r('nep','parc') --> "nep".
r('nepr','adv') --> "nepr".
r('nerv','subst') --> "nerv".
r('nervoz','adj') --> "nervoz".
r('nest','subst') --> "nest".
r('net','adj') --> "net".
r('nev','parc') --> "nev".
r('nigr','adj') --> "nigr".
r('nilon','subst') --> "nilon".
r('nivel','subst') --> "nivel".
r('nobl','adj') --> "nobl".
r('nod','subst') --> "nod".
r('nokt','subst') --> "nokt".
r('nom','tr') --> "nom".
r('nombr','subst') --> "nombr".
r('nord','subst') --> "nord".
r('normal','adj') --> "normal".
r('not','tr') --> "not".
r('nov','adj') --> "nov".
r('novembr','subst') --> "novembr".
r('nub','subst') --> "nub".
r('nud','adj') --> "nud".
r('nuk','subst') --> "nuk".
r('nuks','subst') --> "nuks".
r('numer','subst') --> "numer".
r('nun','adv') --> "nun".
r('nutr','tr') --> "nutr".
r('obe','tr') --> "obe".
r('objekt','subst') --> "objekt".
r('oblikv','adj') --> "oblikv".
r('observ','tr') --> "observ".
r('obstakl','obst') --> "obstakl".
r('obstin','adj') --> "obstin".
r('ocean','subst') --> "ocean".
r('odor','ntr') --> "odor".
r('ofend','tr') --> "ofend".
r('ofer','tr') --> "ofer".
r('ofert','tr') --> "ofert".
r('ofic','subst') --> "ofic".
r('oficial','adj') --> "oficial".
r('oficir','best') --> "oficir".
r('oft','adv') --> "oft".
r('okaz','ntr') --> "okaz".
r('okcident','subst') --> "okcident".
r('oktobr','subst') --> "oktobr".
r('okul','subst') --> "okul".
r('okup','tr') --> "okup".
r('ole','subst') --> "ole".
r('oliv','subst') --> "oliv".
r('ombr','subst') --> "ombr".
r('ombrel','subst') --> "ombrel".
r('ond','subst') --> "ond".
r('onkl','parc') --> "onkl".
r('oper','subst') --> "oper".
r('operaci','subst') --> "operaci".
r('opini','tr') --> "opini".
r('opon','ntr') --> "opon".
r('oportun','adj') --> "oportun".
r('opozici','subst') --> "opozici".
r('or','subst') --> "or".
r('orakol','subst') --> "orakol".
r('oranĝ','subst') --> "oranĝ".
r('orator','subst') --> "orator".
r('ord','subst') --> "ord".
r('ordinar','adj') --> "ordinar".
r('ordon','tr') --> "ordon".
r('orel','subst') --> "orel".
r('orf','best') --> "orf".
r('organ','subst') --> "organ".
r('organiz','tr') --> "organiz".
r('orient','subst') --> "orient".
r('origin','subst') --> "origin".
r('original','adj') --> "original".
r('orkestr','subst') --> "orkestr".
r('ornam','tr') --> "ornam".
r('ort','adj') --> "ort".
r('ortografi','subst') --> "ortografi".
r('osced','ntr') --> "osced".
r('ost','subst') --> "ost".
r('ov','subst') --> "ov".
r('oval','adj') --> "oval".
r('pac','subst') --> "pac".
r('pacienc','subst') --> "pacienc".
r('pacifik','subst') --> "pacifik".
r('paĉj','subst') --> "paĉj".
r('paf','tr') --> "paf".
r('pag','tr') --> "pag".
r('paĝ','subst') --> "paĝ".
r('pajl','subst') --> "pajl".
r('pak','tr') --> "pak".
r('pal','adj') --> "pal".
r('palac','subst') --> "palac".
r('palat','subst') --> "palat".
r('palis','subst') --> "palis".
r('palm','subst') --> "palm".
r('palp','tr') --> "palp".
r('palpebr','subst') --> "palpebr".
r('palt','subst') --> "palt".
r('pan','subst') --> "pan".
r('pane','subst') --> "pane".
r('panj','subst') --> "panj".
r('pantalon','subst') --> "pantalon".
r('pantofl','subst') --> "pantofl".
r('pap','best') --> "pap".
r('papag','best') --> "papag".
r('paper','subst') --> "paper".
r('papili','best') --> "papili".
r('par','subst') --> "par".
r('paradiz','subst') --> "paradiz".
r('paralel','adj') --> "paralel".
r('paraŝut','subst') --> "paraŝut".
r('pardon','tr') --> "pardon".
r('parenc','parc') --> "parenc".
r('parfum','subst') --> "parfum".
r('park','subst') --> "park".
r('park','tr') --> "park".
r('parlament','subst') --> "parlament".
r('parol','ntr') --> "parol".
r('part','subst') --> "part".
r('parti','subst') --> "parti".
r('pas','ntr') --> "pas".
r('pasaĝer','best') --> "pasaĝer".
r('paser','best') --> "paser".
r('pasi','subst') --> "pasi".
r('pask','subst') --> "pask".
r('pasport','subst') --> "pasport".
r('past','subst') --> "past".
r('pastr','best') --> "pastr".
r('paŝ','ntr') --> "paŝ".
r('paŝt','tr') --> "paŝt".
r('pat','subst') --> "pat".
r('patr','parc') --> "patr".
r('patron','best') --> "patron".
r('pav','best') --> "pav".
r('paŭz','subst') --> "paŭz".
r('pec','subst') --> "pec".
r('pejzaĝ','subst') --> "pejzaĝ".
r('pek','ntr') --> "pek".
r('pekl','tr') --> "pekl".
r('pel','tr') --> "pel".
r('pelt','subst') --> "pelt".
r('pen','ntr') --> "pen".
r('pend','ntr') --> "pend".
r('pendol','subst') --> "pendol".
r('penetr','ntr') --> "penetr".
r('penik','subst') --> "penik".
r('pens','tr') --> "pens".
r('pensi','subst') --> "pensi".
r('pent','tr') --> "pent".
r('pentr','tr') --> "pentr".
r('perd','tr') --> "perd".
r('pere','ntr') --> "pere".
r('perfekt','adj') --> "perfekt".
r('perfid','tr') --> "perfid".
r('period','subst') --> "period".
r('perl','subst') --> "perl".
r('permes','tr') --> "permes".
r('peron','subst') --> "peron".
r('persekut','tr') --> "persekut".
r('persik','subst') --> "persik".
r('persist','ntr') --> "persist".
r('person','best') --> "person".
r('perspektiv','subst') --> "perspektiv".
r('pes','tr') --> "pes".
r('pet','tr') --> "pet".
r('petol','ntr') --> "petol".
r('petrol','subst') --> "petrol".
r('pez','adj') --> "pez".
r('pi','adj') --> "pi".
r('pian','subst') --> "pian".
r('pice','subst') --> "pice".
r('pied','subst') --> "pied".
r('pig','best') --> "pig".
r('pik','tr') --> "pik".
r('pil','subst') --> "pil".
r('pilk','subst') --> "pilk".
r('pilot','best') --> "pilot".
r('pin','subst') --> "pin".
r('pinĉ','tr') --> "pinĉ".
r('pingl','subst') --> "pingl".
r('pint','subst') --> "pint".
r('pioĉ','subst') --> "pioĉ".
r('pionir','best') --> "pionir".
r('pip','subst') --> "pip".
r('pipr','subst') --> "pipr".
r('pir','subst') --> "pir".
r('piz','subst') --> "piz".
r('plac','subst') --> "plac".
r('plaĉ','ntr') --> "plaĉ".
r('plad','subst') --> "plad".
r('plafon','subst') --> "plafon".
r('plag','subst') --> "plag".
r('plan','subst') --> "plan".
r('pland','subst') --> "pland".
r('planed','subst') --> "planed".
r('plank','subst') --> "plank".
r('plant','tr') --> "plant".
r('plast','subst') --> "plast".
r('plastik','subst') --> "plastik".
r('plat','adj') --> "plat".
r('platan','subst') --> "platan".
r('plaŭd','ntr') --> "plaŭd".
r('plekt','tr') --> "plekt".
r('plen','adj') --> "plen".
r('plend','ntr') --> "plend".
r('plet','subst') --> "plet".
r('plezur','subst') --> "plezur".
r('plonĝ','ntr') --> "plonĝ".
r('plor','ntr') --> "plor".
r('plug','tr') --> "plug".
r('plum','subst') --> "plum".
r('plumb','subst') --> "plumb".
r('plur','adj') --> "plur".
r('plural','subst') --> "plural".
r('pluv','subst') --> "pluv".
r('poem','subst') --> "poem".
r('poet','best') --> "poet".
r('poezi','subst') --> "poezi".
r('polic','subst') --> "polic".
r('politik','subst') --> "politik".
r('polur','subst') --> "polur".
r('polv','subst') --> "polv".
r('pom','subst') --> "pom".
r('pont','subst') --> "pont".
r('popol','subst') --> "popol".
r('popular','adj') --> "popular".
r('porcelan','subst') --> "porcelan".
r('porci','subst') --> "porci".
r('pord','subst') --> "pord".
r('pork','best') --> "pork".
r('port','tr') --> "port".
r('portret','subst') --> "portret".
r('posed','tr') --> "posed".
r('posten','subst') --> "posten".
r('postul','tr') --> "postul".
r('poŝ','subst') --> "poŝ".
r('poŝt','subst') --> "poŝt".
r('pot','subst') --> "pot".
r('potenc','subst') --> "potenc".
r('pov','tr') --> "pov".
r('pozici','subst') --> "pozici".
r('praktik','subst') --> "praktik".
r('prav','adj') --> "prav".
r('precip','adv') --> "precip".
r('preciz','adj') --> "preciz".
r('prefer','tr') --> "prefer".
r('preĝ','ntr') --> "preĝ".
r('preleg','subst') --> "preleg".
r('prem','tr') --> "prem".
r('premi','subst') --> "premi".
r('pren','tr') --> "pren".
r('prepar','tr') --> "prepar".
r('pres','tr') --> "pres".
r('preskrib','tr') --> "preskrib".
r('pret','adj') --> "pret".
r('pretekst','subst') --> "pretekst".
r('pretend','tr') --> "pretend".
r('prez','subst') --> "prez".
r('prezent','tr') --> "prezent".
r('prezid','ntr') --> "prezid".
r('princ','subst') --> "princ".
r('princip','subst') --> "princip".
r('printemp','subst') --> "printemp".
r('privat','adj') --> "privat".
r('probabl','adj') --> "probabl".
r('problem','subst') --> "problem".
r('proced','ntr') --> "proced".
r('proces','subst') --> "proces".
r('produkt','tr') --> "produkt".
r('profesi','subst') --> "profesi".
r('profesor','best') --> "profesor".
r('profet','best') --> "profet".
r('profit','ntr') --> "profit".
r('profund','adj') --> "profund".
r('program','subst') --> "program".
r('progres','ntr') --> "progres".
r('projekt','subst') --> "projekt".
r('prokrast','tr') --> "prokrast".
r('proksim','adj') --> "proksim".
r('prolet','best') --> "prolet".
r('proletari','best') --> "proletari".
r('promen','ntr') --> "promen".
r('promes','tr') --> "promes".
r('pronom','subst') --> "pronom".
r('prononc','tr') --> "prononc".
r('propagand','subst') --> "propagand".
r('propon','tr') --> "propon".
r('propozici','subst') --> "propozici".
r('propr','adj') --> "propr".
r('prosper','ntr') --> "prosper".
r('protekt','tr') --> "protekt".
r('protest','ntr') --> "protest".
r('prov','tr') --> "prov".
r('proverb','subst') --> "proverb".
r('provinc','subst') --> "provinc".
r('proviz','tr') --> "proviz".
r('provok','tr') --> "provok".
r('proz','subst') --> "proz".
r('prudent','adj') --> "prudent".
r('prun','subst') --> "prun".
r('prunt','tr') --> "prunt".
r('pruv','tr') --> "pruv".
r('psikologi','subst') --> "psikologi".
r('publik','subst') --> "publik".
r('pudr','subst') --> "pudr".
r('pugn','subst') --> "pugn".
r('pulm','subst') --> "pulm".
r('pulv','subst') --> "pulv".
r('pulvor','subst') --> "pulvor".
r('pump','tr') --> "pump".
r('pun','tr') --> "pun".
r('punkt','subst') --> "punkt".
r('punt','subst') --> "punt".
r('pup','subst') --> "pup".
r('pupil','subst') --> "pupil".
r('pur','adj') --> "pur".
r('pus','subst') --> "pus".
r('puŝ','tr') --> "puŝ".
r('put','subst') --> "put".
r('putr','ntr') --> "putr".
r('qemi','subst') --> "qemi".
r('qor','subst') --> "qor".
r('rab','tr') --> "rab".
r('rabat','subst') --> "rabat".
r('raci','subst') --> "raci".
r('rad','subst') --> "rad".
r('radi','subst') --> "radi".
r('radiator','subst') --> "radiator".
r('radik','subst') --> "radik".
r('rafan','subst') --> "rafan".
r('rajd','ntr') --> "rajd".
r('rajt','subst') --> "rajt".
r('rakont','tr') --> "rakont".
r('ramp','ntr') --> "ramp".
r('ran','best') --> "ran".
r('rand','subst') --> "rand".
r('rang','subst') --> "rang".
r('rapid','adj') --> "rapid".
r('raport','tr') --> "raport".
r('ras','subst') --> "ras".
r('rat','best') --> "rat".
r('rav','tr') --> "rav".
r('raŭk','adj') --> "raŭk".
r('raŭp','best') --> "raŭp".
r('raz','tr') --> "raz".
r('reakci','subst') --> "reakci".
r('real','adj') --> "real".
r('recenz','tr') --> "recenz".
r('recept','subst') --> "recept".
r('reciprok','adj') --> "reciprok".
r('redakt','tr') --> "redakt".
r('redukt','tr') --> "redukt".
r('reflekt','tr') --> "reflekt".
r('reg','tr') --> "reg".
r('regal','tr') --> "regal".
r('regiment','subst') --> "regiment".
r('region','subst') --> "region".
r('registr','tr') --> "registr".
r('regn','subst') --> "regn".
r('regul','subst') --> "regul".
r('reĝ','best') --> "reĝ".
r('reĝim','subst') --> "reĝim".
r('reklam','subst') --> "reklam".
r('rekomend','tr') --> "rekomend".
r('rekompenc','tr') --> "rekompenc".
r('rekord','subst') --> "rekord".
r('rekt','adj') --> "rekt".
r('rel','subst') --> "rel".
r('relativ','adj') --> "relativ".
r('religi','subst') --> "religi".
r('rem','ntr') --> "rem".
r('ren','subst') --> "ren".
r('rendevu','subst') --> "rendevu".
r('renkont','tr') --> "renkont".
r('rent','subst') --> "rent".
r('renvers','tr') --> "renvers".
r('respekt','subst') --> "respekt".
r('respond','tr') --> "respond".
r('respublik','subst') --> "respublik".
r('rest','ntr') --> "rest".
r('restoraci','subst') --> "restoraci".
r('ret','subst') --> "ret".
r('rev','ntr') --> "rev".
r('revizi','tr') --> "revizi".
r('revoluci','subst') --> "revoluci".
r('revu','subst') --> "revu".
r('rezerv','tr') --> "rezerv".
r('rezign','tr') --> "rezign".
r('rezist','ntr') --> "rezist".
r('rezon','ntr') --> "rezon".
r('rezult','ntr') --> "rezult".
r('rib','subst') --> "rib".
r('ribel','ntr') --> "ribel".
r('ricev','tr') --> "ricev".
r('riĉ','adj') --> "riĉ".
r('rid','ntr') --> "rid".
r('rifuĝ','ntr') --> "rifuĝ".
r('rifuz','tr') --> "rifuz".
r('rigard','tr') --> "rigard".
r('rigard','ntr') --> "rigard".
r('rigid','adj') --> "rigid".
r('rikolt','tr') --> "rikolt".
r('rilat','ntr') --> "rilat".
r('rim','subst') --> "rim".
r('rimark','tr') --> "rimark".
r('rimed','subst') --> "rimed".
r('rimen','subst') --> "rimen".
r('ring','subst') --> "ring".
r('rip','subst') --> "rip".
r('ripar','tr') --> "ripar".
r('ripet','tr') --> "ripet".
r('ripoz','ntr') --> "ripoz".
r('riproĉ','tr') --> "riproĉ".
r('risk','tr') --> "risk".
r('ritm','subst') --> "ritm".
r('rivel','tr') --> "rivel".
r('river','subst') --> "river".
r('riverenc','subst') --> "riverenc".
r('rivolu','subst') --> "rivolu".
r('riz','subst') --> "riz".
r('rob','subst') --> "rob".
r('rok','subst') --> "rok".
r('rol','subst') --> "rol".
r('roman','subst') --> "roman".
r('romp','tr') --> "romp".
r('rond','subst') --> "rond".
r('ronk','ntr') --> "ronk".
r('ros','subst') --> "ros".
r('rost','tr') --> "rost".
r('roz','subst') --> "roz".
r('ruband','subst') --> "ruband".
r('ruben','subst') --> "ruben".
r('ruĝ','adj') --> "ruĝ".
r('ruin','subst') --> "ruin".
r('rul','tr') --> "rul".
r('rust','subst') --> "rust".
r('ruz','adj') --> "ruz".
r('sabat','subst') --> "sabat".
r('sabl','subst') --> "sabl".
r('sag','subst') --> "sag".
r('sagac','adj') --> "sagac".
r('saĝ','adj') --> "saĝ".
r('sak','subst') --> "sak".
r('sal','subst') --> "sal".
r('salajr','subst') --> "salajr".
r('salat','subst') --> "salat".
r('salik','subst') --> "salik".
r('salon','subst') --> "salon".
r('salt','ntr') --> "salt".
r('salut','tr') --> "salut".
r('sam','adj') --> "sam".
r('san','adj') --> "san".
r('sandviĉ','subst') --> "sandviĉ".
r('sang','subst') --> "sang".
r('sankt','adj') --> "sankt".
r('sap','subst') --> "sap".
r('sark','tr') --> "sark".
r('sat','adj') --> "sat".
r('satir','subst') --> "satir".
r('sav','tr') --> "sav".
r('saŭc','subst') --> "saŭc".
r('scen','subst') --> "scen".
r('sci','tr') --> "sci".
r('scienc','subst') --> "scienc".
r('sciur','best') --> "sciur".
r('seg','tr') --> "seg".
r('seĝ','subst') --> "seĝ".
r('sek','adj') --> "sek".
r('sekal','subst') --> "sekal".
r('sekc','tr') --> "sekc".
r('sekci','subst') --> "sekci".
r('sekret','subst') --> "sekret".
r('sekretari','best') --> "sekretari".
r('seks','subst') --> "seks".
r('sekund','subst') --> "sekund".
r('sekur','adj') --> "sekur".
r('sekv','tr') --> "sekv".
r('sem','tr') --> "sem".
r('semajn','subst') --> "semajn".
r('senat','subst') --> "senat".
r('senc','subst') --> "senc".
r('send','tr') --> "send".
r('sens','subst') --> "sens".
r('sent','tr') --> "sent".
r('septembr','subst') --> "septembr".
r('serĉ','tr') --> "serĉ".
r('seren','adj') --> "seren".
r('seri','subst') --> "seri".
r('serioz','adj') --> "serioz".
r('serpent','best') --> "serpent".
r('serur','subst') --> "serur".
r('serv','tnr') --> "serv".
r('sever','adj') --> "sever".
r('sezon','subst') --> "sezon".
r('sid','ntr') --> "sid".
r('sign','subst') --> "sign".
r('signal','subst') --> "signal".
r('signif','tr') --> "signif".
r('silent','ntr') --> "silent".
r('silk','subst') --> "silk".
r('simbol','subst') --> "simbol".
r('simi','best') --> "simi".
r('simil','adj') --> "simil".
r('simpati','subst') --> "simpati".
r('simpl','adj') --> "simpl".
r('sin','subst') --> "sin".
r('sincer','adj') --> "sincer".
r('sindikat','subst') --> "sindikat".
r('singular','subst') --> "singular".
r('sinjor','best') --> "sinjor".
r('sistem','subst') --> "sistem".
r('sitel','subst') --> "sitel".
r('situ','subst') --> "situ".
r('situaci','subst') --> "situaci".
r('skal','subst') --> "skal".
r('skatol','subst') --> "skatol".
r('ski','subst') --> "ski".
r('sklav','best') --> "sklav".
r('skorpi','best') --> "skorpi".
r('skrap','tr') --> "skrap".
r('skrib','tr') --> "skrib".
r('sku','tr') --> "sku".
r('skulpt','tr') --> "skulpt".
r('sled','subst') --> "sled".
r('sobr','adj') --> "sobr".
r('soci','subst') --> "soci".
r('social','adj') --> "social".
r('societ','subst') --> "societ".
r('sof','subst') --> "sof".
r('soif','ntr') --> "soif".
r('sojl','subst') --> "sojl".
r('sol','adj') --> "sol".
r('soldat','best') --> "soldat".
r('solen','adj') --> "solen".
r('solid','adj') --> "solid".
r('solidar','adj') --> "solidar".
r('solv','tr') --> "solv".
r('somer','subst') --> "somer".
r('son','ntr') --> "son".
r('sonĝ','subst') --> "sonĝ".
r('sonor','ntr') --> "sonor".
r('sopir','ntr') --> "sopir".
r('sorb','tr') --> "sorb".
r('sorĉ','tr') --> "sorĉ".
r('sorg','subst') --> "sorg".
r('sort','subst') --> "sort".
r('sovaĝ','adj') --> "sovaĝ".
r('spac','subst') --> "spac".
r('spec','subst') --> "spec".
r('special','adj') --> "special".
r('specimen','subst') --> "specimen".
r('spegul','subst') --> "spegul".
r('spektakl','subst') --> "spektakl".
r('spert','adj') --> "spert".
r('spez','subst') --> "spez".
r('spic','subst') --> "spic".
r('spik','subst') --> "spik".
r('spinac','subst') --> "spinac".
r('spir','ntr') --> "spir".
r('spirit','subst') --> "spirit".
r('spit','adv') --> "spit".
r('split','subst') --> "split".
r('spong','subst') --> "spong".
r('sport','subst') --> "sport".
r('sprit','adj') --> "sprit".
r('spur','subst') --> "spur".
r('staci','subst') --> "staci".
r('stadi','subst') --> "stadi".
r('stadion','subst') --> "stadion".
r('stal','subst') --> "stal".
r('stamen','subst') --> "stamen".
r('stamp','tr') --> "stamp".
r('stan','subst') --> "stan".
r('standard','subst') --> "standard".
r('stang','subst') --> "stang".
r('star','ntr') --> "star".
r('start','ntr') --> "start".
r('stat','subst') --> "stat".
r('statu','subst') --> "statu".
r('statur','subst') --> "statur".
r('stel','subst') --> "stel".
r('sterk','subst') --> "sterk".
r('stern','tr') --> "stern".
r('stil','subst') --> "stil".
r('stomak','subst') --> "stomak".
r('strang','adj') --> "strang".
r('strat','subst') --> "strat".
r('streĉ','tr') --> "streĉ".
r('strek','tr') --> "strek".
r('stri','subst') --> "stri".
r('strig','best') --> "strig".
r('strik','subst') --> "strik".
r('struktur','subst') --> "struktur".
r('strut','best') --> "strut".
r('stud','tr') --> "stud".
r('student','best') --> "student".
r('stult','adj') --> "stult".
r('stump','subst') --> "stump".
r('subit','adv') --> "subit".
r('subjekt','subst') --> "subjekt".
r('substanc','subst') --> "substanc".
r('substantiv','subst') --> "substantiv".
r('subtil','adj') --> "subtil".
r('subtrah','tr') --> "subtrah".
r('suĉ','tr') --> "suĉ".
r('sud','subst') --> "sud".
r('sufer','tr') --> "sufer".
r('sufer','ntr') --> "sufer".
r('sufiĉ','adj') --> "sufiĉ".
r('sufok','tr') --> "sufok".
r('suk','subst') --> "suk".
r('sukces','ntr') --> "sukces".
r('suker','subst') --> "suker".
r('sulk','subst') --> "sulk".
r('sultan','best') --> "sultan".
r('sum','subst') --> "sum".
r('sun','subst') --> "sun".
r('sup','subst') --> "sup".
r('suplement','subst') --> "suplement".
r('supoz','tr') --> "supoz".
r('supr','adv') --> "supr".
r('surd','adj') --> "surd".
r('surfac','subst') --> "surfac".
r('surpriz','tr') --> "surpriz".
r('surtut','subst') --> "surtut".
r('suspekt','tr') --> "suspekt".
r('susur','ntr') --> "susur".
r('svat','tr') --> "svat".
r('sven','ntr') --> "sven".
r('sving','tr') --> "sving".
r('ŝaf','best') --> "ŝaf".
r('ŝajn','ntr') --> "ŝajn".
r('ŝakal','best') --> "ŝakal".
r('ŝanc','subst') --> "ŝanc".
r('ŝancel','tr') --> "ŝancel".
r('ŝanĝ','tr') --> "ŝanĝ".
r('ŝarg','tr') --> "ŝarg".
r('ŝarĝ','tr') --> "ŝarĝ".
r('ŝat','tr') --> "ŝat".
r('ŝaŭm','subst') --> "ŝaŭm".
r('ŝel','subst') --> "ŝel".
r('ŝerc','ntr') --> "ŝerc".
r('ŝink','subst') --> "ŝink".
r('ŝip','subst') --> "ŝip".
r('ŝir','tr') --> "ŝir".
r('ŝirm','tr') --> "ŝirm".
r('ŝlos','tr') --> "ŝlos".
r('ŝmir','tr') --> "ŝmir".
r('ŝnur','subst') --> "ŝnur".
r('ŝofor','best') --> "ŝofor".
r('ŝov','tr') --> "ŝov".
r('ŝovel','tr') --> "ŝovel".
r('ŝpar','tr') --> "ŝpar".
r('ŝpin','tr') --> "ŝpin".
r('ŝpruc','ntr') --> "ŝpruc".
r('ŝrank','subst') --> "ŝrank".
r('ŝraŭb','subst') --> "ŝraŭb".
r('ŝtal','subst') --> "ŝtal".
r('ŝtat','subst') --> "ŝtat".
r('ŝtel','tr') --> "ŝtel".
r('ŝtip','subst') --> "ŝtip".
r('ŝtof','subst') --> "ŝtof".
r('ŝton','subst') --> "ŝton".
r('ŝtop','tr') --> "ŝtop".
r('ŝtrump','subst') --> "ŝtrump".
r('ŝtup','subst') --> "ŝtup".
r('ŝu','subst') --> "ŝu".
r('ŝuld','tr') --> "ŝuld".
r('ŝultr','subst') --> "ŝultr".
r('ŝut','tr') --> "ŝut".
r('ŝveb','ntr') --> "ŝveb".
r('ŝvel','ntr') --> "ŝvel".
r('ŝvit','ntr') --> "ŝvit".
r('tabak','subst') --> "tabak".
r('tabel','subst') --> "tabel".
r('tabl','subst') --> "tabl".
r('tabul','subst') --> "tabul".
r('tag','subst') --> "tag".
r('tajl','tr') --> "tajl".
r('tajlor','best') --> "tajlor".
r('tajp','tr') --> "tajp".
r('taks','tr') --> "taks".
r('takt','subst') --> "takt".
r('tali','subst') --> "tali".
r('tapet','subst') --> "tapet".
r('tapiŝ','subst') --> "tapiŝ".
r('tarif','subst') --> "tarif".
r('tas','subst') --> "tas".
r('task','subst') --> "task".
r('taŭg','ntr') --> "taŭg".
r('te','subst') --> "te".
r('teatr','subst') --> "teatr".
r('ted','tr') --> "ted".
r('teg','tr') --> "teg".
r('tegment','subst') --> "tegment".
r('tegol','subst') --> "tegol".
r('teknik','subst') --> "teknik".
r('teks','tr') --> "teks".
r('tekst','subst') --> "tekst".
r('telefon','subst') --> "telefon".
r('telegraf','subst') --> "telegraf".
r('telegram','subst') --> "telegram".
r('teler','subst') --> "teler".
r('televid','subst') --> "televid".
r('tem','subst') --> "tem".
r('temp','subst') --> "temp".
r('temperatur','subst') --> "temperatur".
r('tempest','subst') --> "tempest".
r('ten','tr') --> "ten".
r('tend','subst') --> "tend".
r('tendenc','subst') --> "tendenc".
r('tener','adj') --> "tener".
r('tent','tr') --> "tent".
r('teori','subst') --> "teori".
r('teqnik','subst') --> "teqnik".
r('ter','subst') --> "ter".
r('teras','subst') --> "teras".
r('teren','subst') --> "teren".
r('teritori','subst') --> "teritori".
r('termometr','subst') --> "termometr".
r('tern','ntr') --> "tern".
r('terur','subst') --> "terur".
r('testud','best') --> "testud".
r('tig','subst') --> "tig".
r('tigr','best') --> "tigr".
r('tikl','tr') --> "tikl".
r('tim','tr') --> "tim".
r('tim','ntr') --> "tim".
r('tinktur','subst') --> "tinktur".
r('tint','ntr') --> "tint".
r('tip','subst') --> "tip".
r('tir','tr') --> "tir".
r('titol','subst') --> "titol".
r('tol','subst') --> "tol".
r('toler','tr') --> "toler".
r('tomat','subst') --> "tomat".
r('tomb','subst') --> "tomb".
r('ton','subst') --> "ton".
r('tond','tr') --> "tond".
r('tondr','ntr') --> "tondr".
r('tord','tr') --> "tord".
r('torent','subst') --> "torent".
r('tort','subst') --> "tort".
r('tradici','subst') --> "tradici".
r('traduk','tr') --> "traduk".
r('traf','tr') --> "traf".
r('trafik','subst') --> "trafik".
r('tragedi','subst') --> "tragedi".
r('tragik','adj') --> "tragik".
r('trajn','subst') --> "trajn".
r('trajt','subst') --> "trajt".
r('trakt','tr') --> "trakt".
r('traktat','subst') --> "traktat".
r('traktor','subst') --> "traktor".
r('tram','subst') --> "tram".
r('tranĉ','tr') --> "tranĉ".
r('trankvil','adj') --> "trankvil".
r('trejn','tr') --> "trejn".
r('trem','ntr') --> "trem".
r('tremp','tr') --> "tremp".
r('tren','tr') --> "tren".
r('trezor','subst') --> "trezor".
r('tribunal','subst') --> "tribunal".
r('trik','tr') --> "trik".
r('trikot','subst') --> "trikot".
r('trink','tr') --> "trink".
r('tritik','subst') --> "tritik".
r('tromp','tr') --> "tromp".
r('trotuar','subst') --> "trotuar".
r('trov','tr') --> "trov".
r('tru','subst') --> "tru".
r('trud','tr') --> "trud".
r('trumpet','subst') --> "trumpet".
r('trunk','subst') --> "trunk".
r('trup','subst') --> "trup".
r('tualet','subst') --> "tualet".
r('tub','subst') --> "tub".
r('tuber','subst') --> "tuber".
r('tuf','subst') --> "tuf".
r('tuk','subst') --> "tuk".
r('tumult','subst') --> "tumult".
r('tun','subst') --> "tun".
r('tunel','subst') --> "tunel".
r('tur','subst') --> "tur".
r('turism','subst') --> "turism".
r('turist','best') --> "turist".
r('turment','tr') --> "turment".
r('turn','tr') --> "turn".
r('tus','ntr') --> "tus".
r('tuŝ','tr') --> "tuŝ".
r('tut','adj') --> "tut".
r('ung','subst') --> "ung".
r('uniform','subst') --> "uniform".
r('unik','adj') --> "unik".
r('universal','adj') --> "universal".
r('universitat','subst') --> "universitat".
r('urb','subst') --> "urb".
r('urĝ','tr') --> "urĝ".
r('urs','best') --> "urs".
r('util','adj') --> "util".
r('uz','tr') --> "uz".
r('vad','ntr') --> "vad".
r('vag','ntr') --> "vag".
r('vagon','subst') --> "vagon".
r('vakcin','subst') --> "vakcin".
r('vaks','subst') --> "vaks".
r('val','subst') --> "val".
r('valid','adj') --> "valid".
r('valiz','subst') --> "valiz".
r('valor','subst') --> "valor".
r('van','adj') --> "van".
r('vang','subst') --> "vang".
r('vant','adj') --> "vant".
r('vapor','subst') --> "vapor".
r('var','subst') --> "var".
r('vari','ntr') --> "vari".
r('varm','adj') --> "varm".
r('vart','tr') --> "vart".
r('vast','adj') --> "vast".
r('vat','subst') --> "vat".
r('vaz','subst') --> "vaz".
r('vegetal','subst') --> "vegetal".
r('vegetar','adj') --> "vegetar".
r('vejn','subst') --> "vejn".
r('vek','tr') --> "vek".
r('vel','subst') --> "vel".
r('velk','ntr') --> "velk".
r('velur','subst') --> "velur".
r('ven','ntr') --> "ven".
r('vend','tr') --> "vend".
r('vendred','subst') --> "vendred".
r('venen','subst') --> "venen".
r('venĝ','tr') --> "venĝ".
r('venk','tr') --> "venk".
r('vent','subst') --> "vent".
r('ventr','subst') --> "ventr".
r('ver','subst') --> "ver".
r('verb','subst') --> "verb".
r('verd','adj') --> "verd".
r('verg','subst') --> "verg".
r('verk','tr') --> "verk".
r('verm','best') --> "verm".
r('vers','subst') --> "vers".
r('verŝ','tr') --> "verŝ".
r('vert','subst') --> "vert".
r('vertic','subst') --> "vertic".
r('vertikal','adj') --> "vertikal".
r('veruk','subst') --> "veruk".
r('vesp','best') --> "vesp".
r('vesper','subst') --> "vesper".
r('vest','subst') --> "vest".
r('veŝt','subst') --> "veŝt".
r('vet','ntr') --> "vet".
r('veter','subst') --> "veter".
r('vetur','ntr') --> "vetur".
r('vezik','subst') --> "vezik".
r('viadukt','subst') --> "viadukt".
r('viand','subst') --> "viand".
r('vic','subst') --> "vic".
r('vid','tr') --> "vid".
r('vidv','best') --> "vidv".
r('vigl','adj') --> "vigl".
r('viktim','subst') --> "viktim".
r('vilaĝ','subst') --> "vilaĝ".
r('vin','subst') --> "vin".
r('vind','tr') --> "vind".
r('vintr','subst') --> "vintr".
r('viol','subst') --> "viol".
r('violon','subst') --> "violon".
r('vip','subst') --> "vip".
r('vir','best') --> "vir".
r('virg','adj') --> "virg".
r('virt','adj') --> "virt".
r('viŝ','tr') --> "viŝ".
r('vit','subst') --> "vit".
r('vitr','subst') --> "vitr".
r('viv','ntr') --> "viv".
r('vizaĝ','subst') --> "vizaĝ".
r('vizit','tr') --> "vizit".
r('voĉ','subst') --> "voĉ".
r('voj','subst') --> "voj".
r('vojaĝ','ntr') --> "vojaĝ".
r('vok','tr') --> "vok".
r('vol','tr') --> "vol".
r('volb','subst') --> "volb".
r('volont','adv') --> "volont".
r('volum','subst') --> "volum".
r('volumen','subst') --> "volumen".
r('volv','tr') --> "volv".
r('vom','tr') --> "vom".
r('vort','subst') --> "vort".
r('vost','subst') --> "vost".
r('vual','subst') --> "vual".
r('vulkan','subst') --> "vulkan".
r('vulp','best') --> "vulp".
r('vultur','best') --> "vultur".
r('vund','tr') --> "vund".
r('zink','subst') --> "zink".
r('zon','subst') --> "zon".
r('zoologi','subst') --> "zoologi".
r('zorg','ntr') --> "zorg".
r('zum','ntr') --> "zum".


/*****************
  personaj pronomoj kiel rad. 
*****************/

r('mi','adj') --> "mi".
r('ci','adj') --> "ci".
r('li','adj') --> "li".
r('ŝi','adj') --> "ŝi".
r('ĝi','adj') --> "ĝi".
r('oni','adj') --> "oni".
r('ni','adj') --> "ni".
r('vi','adj') --> "vi".
r('ili','adj') --> "ili".
r('si','adj') --> "si".

/**************
 * nombroj kiel radiko 
**************/
r('unu','nombr') --> "unu".
r('du','nombr') --> "du".
r('tri','nombr') --> "tri".
r('kvar','nombr') --> "kvar".
r('kvin','nombr') --> "kvin".
r('ses','nombr') --> "ses".
r('sep','nombr') --> "sep".
r('ok','nombr') --> "ok".
r('naŭ','nombr') --> "naŭ".
r('dek','nombr') --> "dek".
r('cent','nombr') --> "cent".
r('mil','nombr') --> "mil".

/*****************
 * kelkaj prepozicioj kaj prim. adv, 
   kiuj estas uzeblaj radike 
******************/

r('ĉirkaŭ','adv') --> "ĉirkaŭ".
r('anstataŭ','adv') --> "anstataŭ".
r('al','adv') --> "al".
r('antaŭ','adv') --> "antaŭ".
r('apud','adv') --> "apud".
r('ĉirkaŭ','adv') --> "ĉirkaŭ".
r('ekster','adv') --> "ekster".
r('el','adv') --> "el".
r('en','adv') --> "en".
r('ĝis','adv') --> "ĝis".
r('inter','adv') --> "inter".
r('kontraŭ','adv') --> "kontraŭ".
r('krom','adv') --> "krom".
r('kun','adv') --> "kun".
r('post','adv') --> "post".
r('preter','adv') --> "preter".
r('pri','adv') --> "pri".
r('sub','adv') --> "sub".
r('super','adv') --> "super".
r('sur','adv') --> "sur".
r('trans','adv') --> "trans".
r('ĵus','adj') --> "ĵus".
r('for','adj') --> "for".
r('hodiaŭ','adj') --> "hodiaŭ".
r('hieraŭ','adj') --> "hieraŭ".
r('morgaŭ','adj') --> "morgaŭ".

/**********
 * afiksoj kiel radikoj
**********/

r('aĉ','adj') --> "aĉ".
r('aĵ','subst') --> "aĵ".
r('an','best') --> "an".
r('ar','subst') --> "ar".
r('dis','adv') --> "dis".
r('ebl','adv') --> "ebl".
r('ec','subst') --> "ec".
r('eg','adj') --> "eg".
r('ej','subst') --> "ej".
r('ek','intj') --> "ek".
r('eks','adj') --> "eks".
r('em','adj') --> "em".
r('er','subst') --> "er".
r('estr','best') --> "estr".
r('et','adj') --> "et".
r('id','best') --> "id".
r('ig','tr') --> "ig".
r('iĝ','ntr') --> "iĝ".
r('il','subst') --> "il".
r('in','best') --> "in".
r('ing','subst') --> "ing".
r('mal','subst') --> "mal".
r('re','adv') --> "re".
r('uj','subst') --> "uj".
r('ul','best') --> "ul".
r('um','ntr') --> "um".




