% nomoj fremdaj
% analoge al nr - nomoradiko...
% PLIBONIGU: eble aldonu nf_ - deriveblan version por
% derivado: nf_('Alfred',pers) -> Alfred-a, Alfred-on
nf('Aleksandroviĉ',pers).
nf('Albert',pers).
nf('Alfred',pers).
nf('Bean',pers).
nf('Berlioz',pers).
nf('Brendon',pers).
nf('Bricard',pers).
nf('Bright',pers).
nf('Cebaot',pers).
nf('Cecil',pers).
nf('Charles',pers).
nf('Charlotte',pers).
nf('Christoph',pers).
nf('Christopher',pers).
nf('Clark',pers).
nf('David',pers).
nf('Dublin',subst).
nf('Duncan',pers).
nf('Ertl',pers).
nf('Eugênio',pers).
nf('Facebook',subst).
nf('Federico',pers).
nf('Franz',pers).
nf('Gandhi',pers).
nf('Giorgio',pers).
nf('Google',subst).
nf('Grimm',pers).
nf('Gudzinskas',pers).
nf('Hans',pers).
nf('Harry',pers).
nf('Instagram',subst).
nf('Izrael',subst).
nf('Kafka',pers).
nf('Kalocsay',pers).
nf('Margarita',pers).
nf('Mark',pers).
nf('Mary',pers).
nf('Matos',pers).
nf('Murphy',pers).
nf('Niels',pers).
nf('Netflix',subst).
nf('Qomolangma',pers).
nf('Pereira',pers).
nf('Perrault',pers).
nf('Reiersøl',pers).
nf('Robert',pers).
nf('Rudolf',pers).
nf('Rytjkov',pers).
nf('Sartre',pers).
nf('Shakespeare',pers).
nf('Silfer',pers).
nf('Stalin',pers).
nf('Steiner',pers).
nf('Swift',pers).
nf('Sydney',subst).
nf('Szathmàri',pers).
nf('Thebais',pers).
nf('Vaŝington',pers).
nf('Veronika',pers).
nf('Vinař',pers).
nf('Volapük',subst).
nf('Wheatstone',pers).
nf('Wüster',pers).
nf('Youtube',subst).
nf('Zamenhof',pers).
nf('Zoom',subst).

