% nomoj fremdaj
% analoge al nr - nomoradiko...
% PLIBONIGU: eble aldonu nf_ - deriveblan version por
% derivado: nf_('Alfred',pers) -> Alfred-a, Alfred-on
nf('Abraham',pers).
nf('Adam',pers).
nf('Aleksandroviĉ',pers).
nf('Albert',pers).
nf('Alfred',pers).
nf('Andersen',pers).
nf('Antwerpen',subst).
nf('Bean',pers).
nf('Benjamen',pers).
nf('Benjamin',pers).
nf('Berlioz',pers).
nf('Boulogne',subst).
nf('Brendon',pers).
nf('Bricard',pers).
nf('Bright',pers).
nf('Britain',pers).
nf('Cambridge',subst).
nf('Cebaot',pers).
nf('Cecil',pers).
nf('Charles',pers).
nf('Charlotte',pers).
nf('Christoph',pers).
nf('Christopher',pers).
nf('Clark',pers).
nf('Clemency',pers).
nf('Daniel',pers).
nf('David',pers).
nf('Donald',pers).
nf('Dresden',subst).
nf('Dublin',subst).
nf('Duisburg',subst).
nf('Duncan',pers).
nf('Einstein',pers).
nf('Ertl',pers).
nf('Ester',pers).
nf('Eugênio',pers).
nf('Facebook',subst).
nf('Federico',pers).
nf('Franz',pers).
nf('Gandhi',pers).
nf('Giorgio',pers).
nf('Google',subst).
nf('Grabovski',pers).
nf('Grimm',pers).
nf('Gudzinskas',pers).
nf('Hans',pers).
nf('Harry',pers).
nf('Heine',pers).
nf('Instagram',subst).
nf('Isaak',best).
nf('Izrael',subst).
nf('Jakob',pers).
nf('Jehuda',pers).
nf('Jeremia',pers).
nf('Jerome',pers).
nf('Jerusalem',subst).
nf('Jesaja',pers).
nf('Joseph',pers).
nf('Kafka',pers).
nf('Kalocsay',pers).
nf('Kraków',subst).
nf('Margarita',pers).
nf('Mark',pers).
nf('Mary',pers).
nf('Matos',pers).
nf('Michael',pers).
nf('Murphy',pers).
nf('Natan',pers).
nf('Niels',pers).
nf('Netflix',subst).
nf('Oliver',pers).
nf('Qomolangma',pers).
nf('Pereira',pers).
nf('Perrault',pers).
nf('Peter',pers).
nf('Peterburg',subst).
nf('Praha',subst).
nf('Reiersøl',pers).
nf('Robert',pers).
nf('Rudolf',pers).
nf('Rytjkov',pers).
nf('Sartre',pers).
nf('Shakespeare',pers).
nf('Silfer',pers).
nf('Simon',pers).
nf('Stalin',pers).
nf('Steiner',pers).
nf('Swift',pers).
nf('Sydney',subst).
nf('Szathmàri',pers).
nf('Thebais',pers).
nf('Vaŝington',pers).
nf('Veronika',pers).
nf('Vinař',pers).
nf('Volapük',subst).
nf('Washington',pers).
nf('Wheatstone',pers).
nf('Wüster',pers).
nf('Youtube',subst).
nf('Zamenhof',pers).
nf('Zoom',subst).

