v('ŭoŭ',intj,'').
v('ŝŝ',intj,'').
v('ŝpruc',intj,'*').
v('ĉit',intj,'').
v('zzz',intj,'').
v('ve',intj,'*').
v('vaŭ',intj,'').
v('ups',intj,'').
v('tus',intj,'*').
v('ts',intj,'').
v('trateratra',intj,'').
v('tpr',intj,'').
v('tin',intj,'').
v('tiktak',intj,'').
v('ta',intj,'').
v('sss',intj,'').
v('snuf',intj,'').
v('rukt',intj,'*').
v('ruk',intj,'').
v('raĉ',intj,'').
v('pum',intj,'').
v('plaŭ',intj,'').
v('pland',intj,'*').
v('pep',intj,'*').
v('paf',intj,'*').
v('pa',intj,'').
v('oj',intj,'').
v('mu',intj,'').
v('miaŭ',intj,'1').
v('mek',intj,'').
v('maĉ',intj,'*').
v('lo',intj,'').
v('kŭaks',intj,'').
v('kvivit',intj,'').
v('kvak',intj,'').
v('kva',intj,'').
v('kurre',intj,'').
v('kriĉ',intj,'').
v('kraŝ',intj,'').
v('krak',intj,'*').
v('knar',intj,'4').
v('kluk',intj,'4').
v('klak',intj,'3').
v('ia',intj,'').
v('huŝ',intj,'').
v('hura',intj,'3').
v('huj',intj,'').
v('hu',intj,'').
v('hrr',intj,'').
v('hot',intj,'').
v('hop',intj,'').
v('ho',intj,'*').
v('hm',intj,'').
v('hihi',intj,'').
v('help',intj,'*').
v('hej',intj,'').
v('he',intj,'1').
v('halt',intj,'*').
v('ha',intj,'*').
v('gut',intj,'*').
v('glut',intj,'*').
v('glu',intj,'').
v('fu',intj,'').
v('frap',intj,'*').
v('fi',intj,'*').
v('fek',intj,'9').
v('ehe',intj,'').
v('dirlididi',intj,'').
v('bum',intj,'').
v('brr',intj,'').
v('boj',intj,'*').
v('blabla',intj,'').
v('baŭ',intj,'').
v('bat',intj,'*').
v('baf',intj,'').
v('bac',intj,'').
v('aŭ',intj,'').
v('aĥ',intj,'').
v('aĉ',intj,'1').
v('aj',intj,'').
v('aha',intj,'').
