/*************
   pretaj vortoj 
*************/
v('aĉ',intj,'1').
v('adiaŭ',intj,'*').
v('aj',intj,'').
%v('ajn',adv,'*').
v('ajn',advpart,'*'). % ĝis nun ni ne havas gramatikan regulon pro ĝi
v('aĥ',intj,'').
v('al',prep,'*').
v('almenaŭ',adv,'*').
v('ambaŭ',pron,'*').
v('ankaŭ',adv,'*').
v('ankoraŭ',adv,'*').
v('anstataŭ',prep,'*').
v('anstataŭ',infprep,'*').
v('antaŭ',prep,'*').
v('antaŭ',infprep,'*').
v('apenaŭ',adv,'*').
v('apud',prep,'*').
v('aŭ',konj,'*').
v('baldaŭ',adv,'*').
v('cent',nombr,'*').
v('ĉar',konj,'*').
v('ĉe',prep,'*').
%v('ĉi',adv,'*'). 
v('ĉi',advpart,'*'). % ĝis nun ni ne havas gramatikan regulon pro ĝi
v('ĉial',adv,'*').
v('ĉiam',adv,'*').
v('ĉiel',adv,'*').
v('ĉies',pron,'*').
v('ĉiom',adv,'*').
v('ĉirkaŭ',prep,'*').
v('ĉu',adv,'*').
v('da',prep,'*').
v('de',prep,'*').
v('dek',nombr,'*').
v('des',adv,'*').
v('do',konj,'*').
v('du',nombr,'*').
v('dum',prep,'*').
v('eĉ',adv,'*').
v('ek',intj,'*').
v('ekster',prep,'*').
v('el',prep,'*').
v('en',prep,'*').
v('fi',intj,'*').
v('for',adv,'*').
v('ĝis',prep,'*').
v('ho',intj,'*').
v('hieraŭ',adv,'*').
v('hodiaŭ',adv,'*').
v('hura',intj,'3').
v('ial',adv,'*').
v('iam',adv,'*').
v('iel',adv,'*').
v('inter',prep,'*').
v('iom',adv,'*').
v('ja',adv,'*').
v('jam',adv,'*').
v('je',prep,'*').
v('jen',adv,'*').
v('jes',intj,'*').
v('ju',adv,'*').
v('ĵus',adv,'*').
v('kaj',konj,'*').
v('ke',subj,'*').
v('kial',adv,'*').
v('kiam',adv,'*').
v('kiel',adv,'*').
v('kies',pron,'*').
v('kiom',adv,'*').
v('kontraŭ',prep,'*').
v('krom',prep,'*').
v('krom',infprep,'*').
v('kun',prep,'*').
v('kvankam',subj,'*').
v('kvar',nombr,'*').
v('kvazaŭ',subj,'*').
v('kvin',nombr,'*').
v('la',art,'*').
v('l''',art,'*').
v('laŭ',prep,'*').
v('malgraŭ',prep,'*').
v('mem',adv,'*').
v('mil',nombr,'*').
v('minus',konj,'8').
v('morgaŭ',adv,'*').
v('naŭ',nombr,'*').
v('ne',adv,'*').
v('ne',intj,'*').
v('nek',konj,'*').
v('nenial',adv,'*').
v('neniam',adv,'*').
v('neniel',adv,'*').
v('nenies',pron,'*').
v('ies',pron,'*').
v('kiom',adv,'*').
v('neniom',adv,'*').
v('nu',intj,'*').
v('nul',nombr,'*').
v('nun',adv,'*').
v('nur',adv,'*').
v('ok',nomr,'*').
v('ol',konj,'*').
v('per',prep,'*').
v('plej',adv,'*').
v('pli',adv,'*').
v('plu',adv,'*').
v('plus',konj,'8').
v('po',prep,'*').
v('por',prep,'*').
v('por',infprep,'*').
v('post',prep,'*').
v('preskaŭ',adv,'*').
v('preter',prep,'*').
v('pri',prep,'*').
v('pro',prep,'*').
v('ri',perspron,''). % neoficiala perspron.
v('se',subj,'*').
v('sed',konj,'*').
v('sen',prep,'*').
v('sen',infprep,'*').
v('sep',nombr,'*').
v('ses',nombr,'*').
v('sub',prep,'*').
v('super',prep,'*').
v('sur',prep,'*').
v('tamen',konj,'*').
v('tial',adv,'*').
v('tiam',adv,'*').
v('tiel',adv,'*').
v('ties',pron,'*').
v('tiom',adv,'*').
v('tra',prep,'*').
v('trans',prep,'*').
v('tre',adv,'*').
v('tri',nombr,'*').
v('tro',adv,'*').
v('tuj',adv,'*').
v('unu',nombr,'*').
v('ve',intj,'*').




