evi('agitator',"agitatoro").
evi('algxeb',"alĝebro").
evi('alial',"alial").
evi('aliam',"aliam").
evi('aliel',"aliel").
evi('alies',"alies").
evi('aliom',"aliom").
evi('aliu',"aliu").
evi('alpinism',"alpinismo").
evi('anarki1',"anarkisto").
evi('anarki',"anarkismo").
evi('apelac1',"apelaci").
evi('apel',"apeli").
evi('arhxiepiskop',"arĥiepiskopo").
evi('arhxipelag',"arĥipelago").
evi('bidual',"bidualo").
evi('bilion',"biliono").
evi('ciklom',"ciklometria").
evi('cinism',"cinismo").
evi('demons1',"demonstracio").
evi('difere1',"diferencii").
evi('digxit',"diĝita").
evi('efelid',"efelido").
evi('eskadr1',"eskadrono").
evi('fanatism',"fanatismo").
evi('federal',"federala").
evi('foliol',"foliolo").
evi('fosf',"fosfo").
evi('frizur',"frizuro").
evi('gangli1',"gangliono").
evi('hemisf',"hemisfero").
evi('humanitar',"humanitara").
evi('impulsiv',"impulsiva").
evi('insurekci',"insurekcii").
evi('insurekt',"insurekti").
evi('insurgent',"insurgento").
evi('kabin',"kabino").
evi('katarakt',"katarakto").
evi('kauxkazi',"Kaŭkazio").
evi('koksal',"koksalgio").
evi('kolcxid',"Kolĉido").
evi('kolokasi',"kolokasio").
evi('kolokv',"kolokvo").
evi('konfuzi',"Konfuzio").
evi('konspiraci',"konspiracio").
evi('kript1',"kripta").
evi('legal',"legala").
evi('legume1',"legumenaco").
evi('legume',"legumeno").
evi('letal',"letala").
evi('limet',"limeto").
evi('limfat1',"limfata").
evi('literator',"literatoro").
evi('maroder',"marodero").
evi('mengzi',"Mengzio").
evi('merd',"merdo").
evi('mutil',"mutili").
evi('muzulman',"muzulmano").
evi('na',"na").
evi('ningx',"ninĝo").
evi('ninjxa',"ninĵao").
evi('ninjx',"ninĵo").
evi('opak',"opaka").
evi('perfor',"perfori").
evi('pingvi',"pingvino").
evi('semino',"seminormo").
evi('skadro',"skadrono").
evi('spektator',"spektatoro").
evi('subjek1',"subjektiva").
evi('sximpa',"ŝimpanzo").
evi('tehxnologi',"teĥnologio").
evi('tomograf',"tomografo").
evi('tsetse',"tsetseo").
evi('vatt',"Vatto").
evi('videoklip',"videoklipo").
