/*************
   pretaj vortoj 
*************/

v('adiaw','intj') --> "adiaŭ".
v('ajn','advpart') --> "ajn".
v('al','prep') --> "al".
v('almenaw','adv') --> "almenaŭ".
v('ambaw','pron') --> "ambaŭ".
v('ankaw','adv') --> "ankaŭ".
v('ankoraw','adv') --> "ankoraŭ".
v('anstataw','prep') --> "anstataŭ".
v('anstataw','infprep') --> "anstataŭ".
v('antaw','prep') --> "antaŭ".
v('antaw','infprep') --> "antaŭ".
v('apenaw','adv') --> "apenaŭ".
v('apud','prep') --> "apud".
v('aw','konj') --> "aŭ".
v('baldaw','adv') --> "baldaŭ".
v('cent','nombr') --> "cent".
v('cxar','konj') --> "ĉar".
v('cxe','prep') --> "ĉe".
v('cxi','adv') --> "ĉi".
v('cxial','adv') --> "ĉial".
v('cxiam','adv') --> "ĉiam".
v('cxiel','adv') --> "ĉiel".
v('cxiom','adv') --> "ĉiom".
v('cxirkaw','prep') --> "ĉirkaŭ".
v('cxu','adv') --> "ĉu".
v('da','prep') --> "da".
v('de','prep') --> "de".
v('dek','nombr') --> "dek".
v('des','adv') --> "des".
v('do','konj') --> "do".
v('du','nombr') --> "du".
v('dum','prep') --> "dum".
v('ecx','adv') --> "eĉ".
v('ekster','prep') --> "ekster".
v('el','prep') --> "el".
v('en','prep') --> "en".
v('for','adv') --> "for".
v('gxis','prep') --> "ĝis".
v('ho','intj') --> "ho".
v('hieraw','adv') --> "hieraŭ".
v('hodiaw','adv') --> "hodiaŭ".
v('hura','intj') --> "hura".
v('ial','adv') --> "ial".
v('iam','adv') --> "iam".
v('iel','adv') --> "iel".
v('inter','prep') --> "inter".
v('iom','adv') --> "iom".
v('ja','adv') --> "ja".
v('jam','adv') --> "jam".
v('je','prep') --> "je".
v('jen','adv') --> "jen".
v('jes','intj') --> "jes".
v('ju','adv') --> "ju".
v('jxus','adv') --> "ĵus".
v('kaj','konj') --> "kaj".
v('ke','subj') --> "ke".
v('kial','adv') --> "kial".
v('kiam','adv') --> "kiam".
v('kiel','adv') --> "kiel".
v('cxies','pron') --> "ĉies".
v('kies','pron') --> "kies".
v('kiom','adv') --> "kiom".
v('kontraw','prep') --> "kontraŭ".
v('krom','prep') --> "krom".
v('krom','infprep') --> "krom".
v('kun','prep') --> "kun".
v('kvankam','subj') --> "kvankam".
v('kvar','nombr') --> "kvar".
v('kvazaw','subj') --> "kvazaŭ".
v('kvin','nombr') --> "kvin".
v('la','art') --> "la".
v('l''','art') --> "l'".
v('law','prep') --> "laŭ".
v('malgraw','prep') --> "malgraŭ".
v('mem','adv') --> "mem".
v('mil','nombr') --> "mil".
v('minus','konj') --> "minus".
v('morgaw','adv') --> "morgaŭ".
v('naw','nombr') --> "naŭ".
v('ne','adv') --> "ne".
v('ne','intj') --> "ne".
v('nek','konj') --> "nek".
v('nenial','adv') --> "nenial".
v('neniam','adv') --> "neniam".
v('neniel','adv') --> "neniel".
v('nenies','pron') --> "nenies".
v('ies','pron') --> "ies".
v('kiom','adv') --> "kiom".
v('neniom','adv') --> "neniom".
v('nu','intj') --> "nu".
v('nul','nombr') --> "nul".
v('nun','adv') --> "nun".
v('nur','adv') --> "nur".
v('ok','nomr') --> "ok".
v('ol','konj') --> "ol".
v('per','prep') --> "per".
v('plej','adv') --> "plej".
v('pli','adv') --> "pli".
v('plu','adv') --> "plu".
v('plus','konj') --> "plus".
v('po','prep') --> "po".
v('por','prep') --> "por".
v('por','infprep') --> "por".
v('post','prep') --> "post".
v('preskaw','adv') --> "preskaŭ".
v('preter','prep') --> "preter".
v('pri','prep') --> "pri".
v('pro','prep') --> "pro".
v('se','subj') --> "se".
v('sed','konj') --> "sed".
v('sen','prep') --> "sen".
v('sen','infprep') --> "sen".
v('sep','nombr') --> "sep".
v('ses','nombr') --> "ses".
v('sub','prep') --> "sub".
v('super','prep') --> "super".
v('sur','prep') --> "sur".
v('tamen','konj') --> "tamen".
v('tial','adv') --> "tial".
v('tiam','adv') --> "tiam".
v('tiel','adv') --> "tiel".
v('ties','pron') --> "ties".
v('tiom','adv') --> "tiom".
v('tra','prep') --> "tra".
v('trans','prep') --> "trans".
v('tre','adv') --> "tre".
v('tri','nombr') --> "tri".
v('tro','adv') --> "tro".
v('tuj','adv') --> "tuj".
v('unu','nombr') --> "unu".
v('ve','intj') --> "ve".




