/*************
   pretaj vortoj 
*************/

v('adiaw','intj').
v('ajn','advpart').
v('al','prep').
v('almenaw','adv').
v('ambaw','pron').
v('ankaw','adv').
v('ankoraw','adv').
v('anstataw','prep').
v('anstataw','infprep').
v('antaw','prep').
v('antaw','infprep').
v('apenaw','adv').
v('apud','prep').
v('aw','konj').
v('baldaw','adv').
v('cent','nombr').
v('cxar','konj').
v('cxe','prep').
v('cxi','adv').
v('cxial','adv').
v('cxiam','adv').
v('cxiel','adv').
v('cxiom','adv').
v('cxirkaw','prep').
v('cxu','adv').
v('da','prep').
v('de','prep').
v('dek','nombr').
v('des','adv').
v('do','konj').
v('du','nombr').
v('dum','prep').
v('ecx','adv').
v('ekster','prep').
v('el','prep').
v('en','prep').
v('for','adv').
v('gxis','prep').
v('ho','intj').
v('hieraw','adv').
v('hodiaw','adv').
v('hura','intj').
v('ial','adv').
v('iam','adv').
v('iel','adv').
v('inter','prep').
v('iom','adv').
v('ja','adv').
v('jam','adv').
v('je','prep').
v('jen','adv').
v('jes','intj').
v('ju','adv').
v('jxus','adv').
v('kaj','konj').
v('ke','subj').
v('kial','adv').
v('kiam','adv').
v('kiel','adv').
v('cxies','pron').
v('kies','pron').
v('kiom','adv').
v('kontraw','prep').
v('krom','prep').
v('krom','infprep').
v('kun','prep').
v('kvankam','subj').
v('kvar','nombr').
v('kvazaw','subj').
v('kvin','nombr').
v('la','art').
v('l''','art').
v('law','prep').
v('malgraw','prep').
v('mem','adv').
v('mil','nombr').
v('minus','konj').
v('morgaw','adv').
v('naw','nombr').
v('ne','adv').
v('ne','intj').
v('nek','konj').
v('nenial','adv').
v('neniam','adv').
v('neniel','adv').
v('nenies','pron').
v('ies','pron').
v('kiom','adv').
v('neniom','adv').
v('nu','intj').
v('nul','nombr').
v('nun','adv').
v('nur','adv').
v('ok','nomr').
v('ol','konj').
v('per','prep').
v('plej','adv').
v('pli','adv').
v('plu','adv').
v('plus','konj').
v('po','prep').
v('por','prep').
v('por','infprep').
v('post','prep').
v('preskaw','adv').
v('preter','prep').
v('pri','prep').
v('pro','prep').
v('se','subj').
v('sed','konj').
v('sen','prep').
v('sen','infprep').
v('sep','nombr').
v('ses','nombr').
v('sub','prep').
v('super','prep').
v('sur','prep').
v('tamen','konj').
v('tial','adv').
v('tiam','adv').
v('tiel','adv').
v('ties','pron').
v('tiom','adv').
v('tra','prep').
v('trans','prep').
v('tre','adv').
v('tri','nombr').
v('tro','adv').
v('tuj','adv').
v('unu','nombr').
v('ve','intj').




