fv('Zamenhof',pers).
fv('Gandhi',pers).
fv('Niels',pers).
fv('Sartre',pers).
fv('Harry',pers).
fv('Volapük',subst).
fv('Aleksandroviĉ',pers).
fv('Berlioz',pers).
fv('Bricard',pers).
fv('Bright',pers).
fv('Cebaot',pers).
fv('Izrael',subst).
fv('Murphy',pers).
fv('Reiersøl',pers).
fv('Vaŝington',pers).
fv('Wüster',pers).
fv('Brendon',pers).
fv('Clark',pers).
fv('Cecil',pers).
fv('Bean',pers).
fv('Thebais',pers).
fv('Rudolf',pers).
fv('Steiner',pers).
fv('Shakespeare',pers).
fv('Charles',pers).
fv('Wheatstone',pers).
fv('Alfred',pers).

