nr('Ŝopen',subst).
nr('Ŝlesvigholstini',subst).
nr('Ŝlejer',subst).
nr('Ŝiva',subst).
nr('Ŝengen',subst).
nr('Ŝem',subst).
nr('Ŝekspir',subst).
nr('Ŝari',subst).
nr('Ĵul',pers).
nr('Ĵerzej',subst).
nr('Ĥiron',subst).
nr('Ĥi',subst).
nr('Ĥerone',subst).
nr('Ĥeops',subst).
nr('Ĥaron',subst).
nr('Ĥaribd',subst).
nr('Ĥanuk',subst).
nr('Ĥam',subst).
nr('Ĝoĉi',subst).
nr('Ĝibuti',subst).
nr('Ĝerald',pers).
nr('Ĝenov',subst).
nr('Ĝenev',subst).
nr('Ĝarkand',subst).
nr('Ĝakart',subst).
nr('Ĉini',subst).
nr('Ĉingis',pers).
nr('Ĉili',subst).
nr('Ĉikag',subst).
nr('Ĉeĥi',subst).
nr('Ĉatisgar',subst).
nr('Ĉad',subst).
nr('Zimbabv',subst).
nr('Zeŭs',subst).
nr('Zeland',subst).
nr('Zaratuŝtr',subst).
nr('Zamenhof',pers).
nr('Zambi',subst).
nr('Vulgat',subst).
nr('Volter',subst).
nr('Volt',subst).
nr('Volg',subst).
nr('Volfgang',subst).
nr('Vodu',subst).
nr('Vladimir',pers).
nr('Vjetnami',subst).
nr('Viŝnu',subst).
nr('Vizbaden',subst).
nr('Vitruvi',subst).
nr('Viskonsin',subst).
nr('Virgini',subst).
nr('Vindoz',subst).
nr('Vincent',pers).
nr('Vinaj',subst).
nr('Vilhelm',subst).
nr('Viktori',subst).
nr('Viktor',pers).
nr('Vezuvi',subst).
nr('Vermont',subst).
nr('Vergili',subst).
nr('Venus',subst).
nr('Venezuel',subst).
nr('Vener',subst).
nr('Vencesla',pers).
nr('Vaĝrajan',subst).
nr('Vatikan',subst).
nr('Vat',pers).
nr('Varsovi',subst).
nr('Varingjen',subst).
nr('Valter',pers).
nr('Valoni',subst).
nr('Valeri',pers).
nr('Valenten',subst).
nr('Vajroĉan',subst).
nr('Vajoming',subst).
nr('Vahabism',subst).
nr('Utreĥt',subst).
nr('Utarpradeŝ',subst).
nr('Utarakand',subst).
nr('Utah',subst).
nr('Uson',subst).
nr('Urugvaj',subst).
nr('Uran',subst).
nr('Ural',subst).
nr('Uniks',subst).
nr('Unikod',subst).
nr('Ugand',subst).
nr('Tviter',subst).
nr('Turus',subst).
nr('Turkmeni',subst).
nr('Turki',subst).
nr('Tunizi',subst).
nr('Tucidid',subst).
nr('Troj',subst).
nr('Tripur',subst).
nr('Tripitak',subst).
nr('Trinidad',subst).
nr('Toskani',subst).
nr('Tora',subst).
nr('Tomas',pers).
nr('Toki',subst).
nr('Togoland',subst).
nr('Tobi',subst).
nr('Tobag',subst).
nr('Tinĉj',subst).
nr('Timote',pers).
nr('Timor',subst).
nr('Tigris',subst).
nr('Tife',subst).
nr('Tician',subst).
nr('Tibet',subst).
nr('Tiberi',pers).
nr('Tet',subst).
nr('Teravad',subst).
nr('Teofil',pers).
nr('Teodor',subst).
nr('Teobald',pers).
nr('Tenesi',subst).
nr('Telangan',subst).
nr('Teksas',subst).
nr('Taĝiki',subst).
nr('Tasmani',subst).
nr('Tanzani',subst).
nr('Tales',subst).
nr('Tade',subst).
nr('Svisi',subst).
nr('Svedi',subst).
nr('Surinam',subst).
nr('Suna',subst).
nr('Sumeri',subst).
nr('Sukot',subst).
nr('Sudan',subst).
nr('Strasburg',subst).
nr('Strabon',subst).
nr('Sten',subst).
nr('Stefan',pers).
nr('Stanislav',subst).
nr('Somali',subst).
nr('Solutre',subst).
nr('Sokrat',pers).
nr('Sloveni',subst).
nr('Slovaki',subst).
nr('Slavon',subst).
nr('Skoti',subst).
nr('Skiti',subst).
nr('Skeld',subst).
nr('Skajp',subst).
nr('Sirius',subst).
nr('Siriak',subst).
nr('Siri',subst).
nr('Sirdarj',subst).
nr('Sirakuz',subst).
nr('Simon',pers).
nr('Simeon',pers).
nr('Silvestr',pers).
nr('Silvan',pers).
nr('Silezi',subst).
nr('Sikim',subst).
nr('Sigmund',subst).
nr('Sigismund',pers).
nr('Siberi',subst).
nr('Sergi',pers).
nr('Septuagint',subst).
nr('Senek',subst).
nr('Senegal',subst).
nr('Selim',pers).
nr('Sebastian',pers).
nr('Scil',subst).
nr('Scientologi',subst).
nr('Saĥalin',subst).
nr('Saĥalen',subst).
nr('Saturn',subst).
nr('Saskaĉevan',subst).
nr('Sarland',subst).
nr('Santeri',subst).
nr('Sanskrit',subst).
nr('Samg',subst).
nr('Sambr',subst).
nr('Salomon',pers).
nr('Salomon',subst).
nr('Salafism',subst).
nr('Sajan',subst).
nr('Sahar',subst).
nr('Sadam',subst).
nr('Ruso',subst).
nr('Rusi',subst).
nr('Rurik',pers).
nr('Rudolf',subst).
nr('Ruand',subst).
nr('Roĝer',subst).
nr('Roterdam',subst).
nr('Romi',subst).
nr('Rome',pers).
nr('Rom',subst).
nr('Roland',pers).
nr('Rodrig',subst).
nr('Rodos',subst).
nr('Rodolf',pers).
nr('Rodezi',subst).
nr('Robert',subst).
nr('Riman',subst).
nr('Rikard',pers).
nr('Riad',subst).
nr('Renat',pers).
nr('Remington',subst).
nr('Rejnland-Palatinat',subst).
nr('Rejn',subst).
nr('Rejki',subst).
nr('Regensburg',subst).
nr('Reformaci',subst).
nr('Raŭm',subst).
nr('Raĥel',subst).
nr('Raĝastan',subst).
nr('Ramajan',subst).
nr('Rajmund',subst).
nr('Rafael',pers).
nr('Puŝkin',subst).
nr('Purim',subst).
nr('Ptoleme',subst).
nr('Prusi',subst).
nr('Promete',subst).
nr('Principe',subst).
nr('Prag',subst).
nr('Pozidon',subst).
nr('Portugali',subst).
nr('Pompej',subst).
nr('Poluks',subst).
nr('Poli',subst).
nr('Pluton',subst).
nr('Plut',subst).
nr('Plini',pers).
nr('Plejad',subst).
nr('Plaŭt',subst).
nr('Platon',pers).
nr('Pjanĝ',subst).
nr('Pitagor',subst).
nr('Pinokj',subst).
nr('Pinjin',subst).
nr('Pilat',subst).
nr('Petr',pers).
nr('Peterburg',subst).
nr('Peru',subst).
nr('Perse',subst).
nr('Pentekost',subst).
nr('Pensilvani',subst).
nr('Pegaz',subst).
nr('Paŭl',pers).
nr('Patrik',subst).
nr('Pasteŭr',subst).
nr('Paskal',pers).
nr('Pask',subst).
nr('Pasion',subst).
nr('Pariz',subst).
nr('Paralimpik',subst).
nr('Paraklet',subst).
nr('Paragvaj',subst).
nr('Papu',subst).
nr('Panĝab',subst).
nr('Pange',subst).
nr('Pali',subst).
nr('Palaŭ',subst).
nr('Pakistan',subst).
nr('Pacifik',subst).
nr('Pabl',pers).
nr('Oĥock',subst).
nr('Oziris',subst).
nr('Ovidi',pers).
nr('Otoman',subst).
nr('Osvald',pers).
nr('Ostend',subst).
nr('Osman',pers).
nr('Oskar',pers).
nr('Oskar',subst).
nr('Oris',subst).
nr('Orion',subst).
nr('Orfe',subst).
nr('Oregon',subst).
nr('Onufri',subst).
nr('Ontari',subst).
nr('Onesim',pers).
nr('Omar',pers).
nr('Oman',subst).
nr('Om',pers).
nr('Oliver',pers).
nr('Olimpik',subst).
nr('Olimp',subst).
nr('Oklahom',subst).
nr('Okcidental',subst).
nr('Oka',subst).
nr('Ohi',subst).
nr('Odr',subst).
nr('Odiŝ',subst).
nr('Odise',pers).
nr('Oceani',subst).
nr('Ob',subst).
nr('Noŭruz',subst).
nr('Novosibirsk',subst).
nr('Norvegi',subst).
nr('Nordrejn-Vestfali',subst).
nr('Noaĥ',pers).
nr('Niĉiren',subst).
nr('Nirvan',subst).
nr('Nimeg',subst).
nr('Nil',subst).
nr('Nikola',pers).
nr('Nikodem',pers).
nr('Neŭton',pers).
nr('Nevad',subst).
nr('Nestor',pers).
nr('Neptun',subst).
nr('Neper',subst).
nr('Nepal',subst).
nr('Nederland',subst).
nr('Nebrask',subst).
nr('Namur',subst).
nr('Namibi',subst).
nr('Muzaik',subst).
nr('Muhamad',subst).
nr('Mozel',subst).
nr('Mozart',subst).
nr('Mozambik',subst).
nr('Moz',subst).
nr('Moskv',subst).
nr('Mors',subst).
nr('Morfe',subst).
nr('Montenegr',subst).
nr('Montan',subst).
nr('Mongoli',subst).
nr('Monak',subst).
nr('Mocart',subst).
nr('Miŝna',subst).
nr('Miŝn',subst).
nr('Miĥael',pers).
nr('Miĉigan',subst).
nr('Mizoram',subst).
nr('Misuri',subst).
nr('Misur',subst).
nr('Misisipi',subst).
nr('Misisip',subst).
nr('Mirz',pers).
nr('Minotaŭr',subst).
nr('Minesot',subst).
nr('Mikrosoft',subst).
nr('Midelburg',subst).
nr('Meĥlen',subst).
nr('Mezopotami',subst).
nr('Metodi',pers).
nr('Merkur',subst).
nr('Mendelev',subst).
nr('Mence',subst).
nr('Meksiki',subst).
nr('Meksik',subst).
nr('Meklenburgo-Antaŭpomeri',subst).
nr('Megalaj',subst).
nr('Mediterane',subst).
nr('Medi',subst).
nr('Mede',subst).
nr('Maŭric',pers).
nr('Maĥ',subst).
nr('Mate',pers).
nr('Mastriĥt',subst).
nr('Masaĉusec',subst).
nr('Marten',pers).
nr('Mars',subst).
nr('Marok',subst).
nr('Marks',subst).
nr('Mark',pers).
nr('Mariland',subst).
nr('Mari',pers).
nr('Marcial',subst).
nr('Marcel',pers).
nr('Manitob',subst).
nr('Manipur',subst).
nr('Manik',subst).
nr('Malt',subst).
nr('Malkolm',pers).
nr('Malik',subst).
nr('Malavi',subst).
nr('Malajzi',subst).
nr('Maksimilian',pers).
nr('Makintoŝ',subst).
nr('Makedoni',subst).
nr('Majn',subst).
nr('Majenc',subst).
nr('Mahomet',subst).
nr('Mahavir',subst).
nr('Maharaŝtr',subst).
nr('Mahajan',subst).
nr('Mahabarat',subst).
nr('Magreb',subst).
nr('Madjapradeŝ',subst).
nr('Madejr',subst).
nr('Luter',subst).
nr('Luksemburgi',subst).
nr('Luksemburg',subst).
nr('Luk',pers).
nr('Luizian',subst).
nr('Ludovik',pers).
nr('Lucian',pers).
nr('Loĵban',subst).
nr('Loven',subst).
nr('London',subst).
nr('Loglan',subst).
nr('Liĥtenŝtejn',subst).
nr('Litovi',subst).
nr('Lionel',pers).
nr('Linuks',subst).
nr('Limburg',subst).
nr('Lilit',subst).
nr('Liguri',subst).
nr('Lieĝ',subst).
nr('Lier',subst).
nr('Libi',subst).
nr('Liberi',subst).
nr('Liban',subst).
nr('Lesot',subst).
nr('Lesb',subst).
nr('Lepsik',subst).
nr('Leopold',pers).
nr('Leonard',subst).
nr('Len',subst).
nr('Lelistad',subst).
nr('Lejbnic',subst).
nr('Lebeg',subst).
nr('Leandr',pers).
nr('Laŭrenc',pers).
nr('Laŭrazi',subst).
nr('Lazar',pers).
nr('Latvi',subst).
nr('Latin',subst).
nr('Lati',subst).
nr('Laptev',subst).
nr('Laplac',subst).
nr('Laos',subst).
nr('Laert',pers).
nr('Ladisla',pers).
nr('Labrador',subst).
nr('Kvirin',subst).
nr('Kuvajt',subst).
nr('Kulomb',pers).
nr('Ksitigarb',subst).
nr('Ksenofont',subst).
nr('Ksenofon',subst).
nr('Ksaver',subst).
nr('Kron',subst).
nr('Kroati',subst).
nr('Kriŝn',subst).
nr('Kristofor',pers).
nr('Kristian',subst).
nr('Krist',subst).
nr('Koŝi',subst).
nr('Kortrejk',subst).
nr('Korneli',pers).
nr('Korei',subst).
nr('Koran',subst).
nr('Kopernik',subst).
nr('Kopenhag',subst).
nr('Konstantinopol',subst).
nr('Konstanten',pers).
nr('Konrad',pers).
nr('Kong',subst).
nr('Konfuce',subst).
nr('Konektikut',subst).
nr('Komeni',subst).
nr('Kolĥid',subst).
nr('Kolumbi',subst).
nr('Kolorad',subst).
nr('Kolonj',subst).
nr('Kolombi',subst).
nr('Kluĉevskaj',subst).
nr('Klement',subst).
nr('Klaŭdi',pers).
nr('Kirgizi',subst).
nr('Kipr',subst).
nr('Kimri',subst).
nr('Keral',subst).
nr('Kepler',subst).
nr('Kentuki',subst).
nr('Kenj',subst).
nr('Kelvin',pers).
nr('Kebeki',subst).
nr('Kaŭkaz',subst).
nr('Kaŝmir',subst).
nr('Kazimir',subst).
nr('Kazaĥi',subst).
nr('Kastor',subst).
nr('Kaspi',subst).
nr('Kasiope',subst).
nr('Kartezi',subst).
nr('Karon',subst).
nr('Karolin',subst).
nr('Karol',pers).
nr('Karnatak',subst).
nr('Karloreĝ',subst).
nr('Karesm',subst).
nr('Kara',subst).
nr('Kaprikorn',subst).
nr('Kapitol',subst).
nr('Kansas',subst).
nr('Kamĉatk',subst).
nr('Kampin',subst).
nr('Kamil',pers).
nr('Kameruni',subst).
nr('Kamerun',subst).
nr('Kamboĝ',subst).
nr('Kam',subst).
nr('Kalvin',subst).
nr('Kalvari',subst).
nr('Kaloĉaj',subst).
nr('Kaboverd',subst).
nr('Kabal',subst).
nr('Justinian',pers).
nr('Justen',pers).
nr('Jupiter',subst).
nr('Jul',subst).
nr('Jugoslavi',subst).
nr('Jugoslav',subst).
nr('Jozef',pers).
nr('Jork',subst).
nr('Jordani',subst).
nr('Jordan',pers).
nr('Jomkipur',subst).
nr('Johan',pers).
nr('Joakim',pers).
nr('Jid',subst).
nr('Jesu',subst).
nr('Jerusalem',subst).
nr('Jenisej',subst).
nr('Jemen',subst).
nr('Jehov',subst).
nr('Jazon',pers).
nr('Jaroslav',subst).
nr('Japani',subst).
nr('Jansen',subst).
nr('Jamajk',subst).
nr('Jama',subst).
nr('Jakobi',subst).
nr('Jakob',subst).
nr('Izis',subst).
nr('Izidor',pers).
nr('Iv',pers).
nr('Itali',subst).
nr('Istanbul',subst).
nr('Israel',subst).
nr('Island',subst).
nr('Isel',subst).
nr('Irtiŝ',subst).
nr('Irland',subst).
nr('Irene',subst).
nr('Irak',subst).
nr('Iova',subst).
nr('Interlingva',subst).
nr('Inocent',pers).
nr('Indr',subst).
nr('Indiana',subst).
nr('Ilinojs',subst).
nr('Iliad',subst).
nr('Ignac',pers).
nr('Idah',subst).
nr('Id',subst).
nr('Husejn',pers).
nr('Hungari',subst).
nr('Humbert',pers).
nr('Hug',subst).
nr('Hudson',subst).
nr('Hubert',pers).
nr('Horus',subst).
nr('Horaci',subst).
nr('Honkong',subst).
nr('Homer',subst).
nr('Holand',subst).
nr('Hispani',subst).
nr('Hipolit',subst).
nr('Hipokrat',subst).
nr('Hindustan',subst).
nr('Hindukuŝ',subst).
nr('Hinajan',subst).
nr('Himaĉalpradeŝ',subst).
nr('Himalaj',subst).
nr('Hilbert',subst).
nr('Hieronim',pers).
nr('Heĝir',subst).
nr('Heziod',subst).
nr('Hevisid',subst).
nr('Herodot',subst).
nr('Hermit',subst).
nr('Hermes',subst).
nr('Herman',pers).
nr('Herkul',pers).
nr('Hercegovin',subst).
nr('Herakl',subst).
nr('Henrik',subst).
nr('Henegovi',subst).
nr('Hektor',subst).
nr('Havaj',subst).
nr('Hasan',pers).
nr('Harold',pers).
nr('Harlem',subst).
nr('Harian',subst).
nr('Hanafism',subst).
nr('Hampŝir',subst).
nr('Hamburg',subst).
nr('Haman',subst).
nr('Halovin',subst).
nr('Haloven',subst).
nr('Hag',subst).
nr('Hades',subst).
nr('Gvine',subst).
nr('Gvajan',subst).
nr('Guĝarat',subst).
nr('Gustav',pers).
nr('Gujan',subst).
nr('Gronland',subst).
nr('Groningen',subst).
nr('Grenad',subst).
nr('Greki',subst).
nr('Gregori',pers).
nr('Gravet',subst).
nr('Gotam',subst).
nr('Gonzal',pers).
nr('Gontran',pers).
nr('Gondvan',subst).
nr('Golgot',subst).
nr('Godfred',subst).
nr('Goa',subst).
nr('Glagolic',subst).
nr('Ginevr',subst).
nr('Gilgameŝ',subst).
nr('Gilbert',pers).
nr('Gervaz',pers).
nr('Germani',subst).
nr('Gerard',subst).
nr('Georg',pers).
nr('Gent',subst).
nr('Gemar',subst).
nr('Gelderland',subst).
nr('Ge',subst).
nr('Gaŭs',subst).
nr('Gaston',subst).
nr('Gaspar',pers).
nr('Gana',subst).
nr('Galilej',subst).
nr('Galez',subst).
nr('Gabriel',subst).
nr('Gabon',subst).
nr('Frisi',subst).
nr('Freŭd',subst).
nr('Frederik',pers).
nr('Frankfurt',subst).
nr('Francisk',pers).
nr('Franci',subst).
nr('Fortunat',pers).
nr('Fob',subst).
nr('Florid',subst).
nr('Florian',pers).
nr('Florenc',subst).
nr('Flevoland',subst).
nr('Flandri',subst).
nr('Finni',subst).
nr('Finland',subst).
nr('Filipin',subst).
nr('Filip',pers).
nr('Filibert',pers).
nr('Figar',subst).
nr('Fernand',pers).
nr('Ferdinand',pers).
nr('Fenici',subst).
nr('Feliks',pers).
nr('Fejsbuk',subst).
nr('Farenhejt',subst).
nr('Farad',subst).
nr('Fanar',subst).
nr('Fabrici',pers).
nr('Fabian',pers).
nr('Fabi',pers).
nr('Eŭzebi',pers).
nr('Eŭrop',subst).
nr('Eŭrial',subst).
nr('Eŭrazi',subst).
nr('Eŭler',subst).
nr('Eŭklid',subst).
nr('Eŭgen',pers).
nr('Eŭfrat',subst).
nr('Ezop',subst).
nr('Etiopi',subst).
nr('Estoni',subst).
nr('Esperanti',subst).
nr('Esperant',subst).
nr('Ernest',pers).
nr('Eritre',subst).
nr('Erik',pers).
nr('Erasm',subst).
nr('Epikur',subst).
nr('Epifani',subst).
nr('Ene',pers).
nr('Emilian',pers).
nr('Emil',pers).
nr('Emanuel',pers).
nr('Elize',subst).
nr('Eli',pers).
nr('Elb',subst).
nr('Ekvador',subst).
nr('Ejnŝtejn',subst).
nr('Ejnstejn',subst).
nr('Egipti',subst).
nr('Efes',subst).
nr('Edvard',pers).
nr('Eduard',pers).
nr('Edmund',pers).
nr('Edgar',pers).
nr('Eden',subst).
nr('Duŝanbe',subst).
nr('Dublin',subst).
nr('Drent',subst).
nr('Donald',pers).
nr('Dominik',pers).
nr('Dirak',subst).
nr('Dioskur',subst).
nr('Dionizi',pers).
nr('Dieg',pers).
nr('Dian',pers).
nr('Demokrit',subst).
nr('Demetri',pers).
nr('Delavar',subst).
nr('Dejm',subst).
nr('Dedekind',subst).
nr('David',pers).
nr('Darmapad',subst).
nr('Darm',subst).
nr('Danub',subst).
nr('Daniel',pers).
nr('Dani',subst).
nr('Damian',pers).
nr('Damask',subst).
nr('Dakot',subst).
nr('Dagobert',pers).
nr('Ciril',pers).
nr('Ciprian',pers).
nr('Cion',subst).
nr('Ciceron',subst).
nr('Cezar',pers).
nr('Cerber',subst).
nr('Celsi',subst).
nr('Celesten',pers).
nr('Cefe',subst).
nr('Buĥor',subst).
nr('Buĥar',subst).
nr('Butan',subst).
nr('Burund',subst).
nr('Bulgari',subst).
nr('Bule',subst).
nr('Bruĝ',subst).
nr('Brusel',subst).
nr('Brunsvik',subst).
nr('Brunej',subst).
nr('Brun',pers).
nr('Briti',subst).
nr('Bremen',subst).
nr('Brem',subst).
nr('Brazilj',subst).
nr('Brazili',subst).
nr('Brazil',subst).
nr('Brandenburg',subst).
nr('Brabant',subst).
nr('Bosni',subst).
nr('Boris',pers).
nr('Borel',subst).
nr('Bonifac',pers).
nr('Bonaventur',pers).
nr('Bomarŝe',subst).
nr('Bolivi',subst).
nr('Boleslav',pers).
nr('Bodidarm',subst).
nr('Blazi',pers).
nr('Bizanti',subst).
nr('Bizanci',subst).
nr('Bizanc',subst).
nr('Birm',subst).
nr('Bihar',subst).
nr('Bibli',subst).
nr('Besarabi',subst).
nr('Bertrand',pers).
nr('Bernard',pers).
nr('Berlin',subst).
nr('Bering',subst).
nr('Beovulf',subst).
nr('Beograd',subst).
nr('Benjamen',pers).
nr('Bengal',subst).
nr('Benedikt',pers).
nr('Belgi',subst).
nr('Behemot',subst).
nr('Baĥ',subst).
nr('Bazil',pers).
nr('Batu',subst).
nr('Bartolome',pers).
nr('Barnab',pers).
nr('Barbad',subst).
nr('Barat',subst).
nr('Bankok',subst).
nr('Banaĥ',subst).
nr('Baltik',subst).
nr('Baltazar',pers).
nr('Balkaŝ',subst).
nr('Balduen',pers).
nr('Baktri',subst).
nr('Bajkal',subst).
nr('Baham',subst).
nr('Bagdad',subst).
nr('Bagavadgit',subst).
nr('Baden-Virtemberg',subst).
nr('Babiloni',subst).
nr('Babilon',subst).
nr('Babel',subst).
nr('Aŭstri',subst).
nr('Aŭstrali',subst).
nr('Aŭrelian',pers).
nr('Aŭgusten',pers).
nr('Aŝok',subst).
nr('Aĥil',pers).
nr('Azov',subst).
nr('Azi',subst).
nr('Azeri',subst).
nr('Azerbajĝan',subst).
nr('Avogadr',subst).
nr('Avicen',subst).
nr('Avest',subst).
nr('Avalokiteŝvar',subst).
nr('Atlantik',subst).
nr('Atlantid',subst).
nr('Atlant',subst).
nr('Atalant',subst).
nr('Aski',subst).
nr('Asiri',subst).
nr('Asen',subst).
nr('Asam',subst).
nr('Arĥimed',subst).
nr('Arunaĉalpradeŝ',subst).
nr('Artur',pers).
nr('Artemid',subst).
nr('Arnold',pers).
nr('Arnhem',subst).
nr('Armeni',subst).
nr('Arkt',subst).
nr('Arkansas',subst).
nr('Arizon',subst).
nr('Aristotel',pers).
nr('Aristofan',subst).
nr('Argonaŭt',subst).
nr('Argentin',subst).
nr('Ares',subst).
nr('Aral',subst).
nr('Apolon',subst).
nr('Antverpen',subst).
nr('Antonen',pers).
nr('Anton',pers).
nr('Antarkt',subst).
nr('Anselm',pers).
nr('Angol',subst).
nr('Angli',subst).
nr('Angar',subst).
nr('Andromed',subst).
nr('Andre',pers).
nr('Andrapradeŝ',subst).
nr('Andor',subst).
nr('Anatoli',subst).
nr('Anatol',pers).
nr('Anastazi',pers).
nr('Anabaz',subst).
nr('Amudarj',subst).
nr('Amsterdam',subst).
nr('Amper',pers).
nr('Amerik',subst).
nr('Ambrozi',pers).
nr('Amazon',subst).
nr('Amade',pers).
nr('Alĝeri',subst).
nr('Alzac',subst).
nr('Altaj',subst).
nr('Altair',subst).
nr('Almat',subst).
nr('Alfred',pers).
nr('Alfons',pers).
nr('Aleksandri',subst).
nr('Aleksandr',pers).
nr('Albert',pers).
nr('Albert',subst).
nr('Albani',subst).
nr('Alask',subst).
nr('Alan',pers).
nr('Alah',subst).
nr('Alabam',subst).
nr('Akad',subst).
nr('Ahmadism',subst).
nr('Agni',subst).
nr('Afrodit',subst).
nr('Afrik',subst).
nr('Adrian',pers).
nr('Adolf',pers).
nr('Adam',pers).
nr('Adalbert',pers).
nr('Abidarm',subst).
nr('Abel',subst).
nr('Abas',pers).
nr_('ŝopen',subst).
nr_('ŝlesvigholstini',subst).
nr_('ŝlejer',subst).
nr_('ŝiva',subst).
nr_('ŝengen',subst).
nr_('ŝem',subst).
nr_('ŝekspir',subst).
nr_('ŝari',subst).
nr_('ĵul',pers).
nr_('ĵerzej',subst).
nr_('ĥiron',subst).
nr_('ĥi',subst).
nr_('ĥerone',subst).
nr_('ĥeops',subst).
nr_('ĥaron',subst).
nr_('ĥaribd',subst).
nr_('ĥanuk',subst).
nr_('ĥam',subst).
nr_('ĝoĉi',subst).
nr_('ĝibuti',subst).
nr_('ĝerald',pers).
nr_('ĝenov',subst).
nr_('ĝenev',subst).
nr_('ĝarkand',subst).
nr_('ĝakart',subst).
nr_('ĉini',subst).
nr_('ĉingis',pers).
nr_('ĉili',subst).
nr_('ĉikag',subst).
nr_('ĉeĥi',subst).
nr_('ĉatisgar',subst).
nr_('ĉad',subst).
nr_('zimbabv',subst).
nr_('zeŭs',subst).
nr_('zeland',subst).
nr_('zaratuŝtr',subst).
nr_('zamenhof',pers).
nr_('zambi',subst).
nr_('vulgat',subst).
nr_('volter',subst).
nr_('volt',subst).
nr_('volg',subst).
nr_('volfgang',subst).
nr_('vodu',subst).
nr_('vladimir',pers).
nr_('vjetnami',subst).
nr_('viŝnu',subst).
nr_('vizbaden',subst).
nr_('vitruvi',subst).
nr_('viskonsin',subst).
nr_('virgini',subst).
nr_('vindoz',subst).
nr_('vincent',pers).
nr_('vinaj',subst).
nr_('vilhelm',subst).
nr_('viktori',subst).
nr_('viktor',pers).
nr_('vezuvi',subst).
nr_('vermont',subst).
nr_('vergili',subst).
nr_('venus',subst).
nr_('venezuel',subst).
nr_('vener',subst).
nr_('vencesla',pers).
nr_('vaĝrajan',subst).
nr_('vatikan',subst).
nr_('vat',pers).
nr_('varsovi',subst).
nr_('varingjen',subst).
nr_('valter',pers).
nr_('valoni',subst).
nr_('valeri',pers).
nr_('valenten',subst).
nr_('vajroĉan',subst).
nr_('vajoming',subst).
nr_('vahabism',subst).
nr_('utreĥt',subst).
nr_('utarpradeŝ',subst).
nr_('utarakand',subst).
nr_('utah',subst).
nr_('uson',subst).
nr_('urugvaj',subst).
nr_('uran',subst).
nr_('ural',subst).
nr_('uniks',subst).
nr_('unikod',subst).
nr_('ugand',subst).
nr_('tviter',subst).
nr_('turus',subst).
nr_('turkmeni',subst).
nr_('turki',subst).
nr_('tunizi',subst).
nr_('tucidid',subst).
nr_('troj',subst).
nr_('tripur',subst).
nr_('tripitak',subst).
nr_('trinidad',subst).
nr_('toskani',subst).
nr_('tora',subst).
nr_('tomas',pers).
nr_('toki',subst).
nr_('togoland',subst).
nr_('tobi',subst).
nr_('tobag',subst).
nr_('tinĉj',subst).
nr_('timote',pers).
nr_('timor',subst).
nr_('tigris',subst).
nr_('tife',subst).
nr_('tician',subst).
nr_('tibet',subst).
nr_('tiberi',pers).
nr_('tet',subst).
nr_('teravad',subst).
nr_('teofil',pers).
nr_('teodor',subst).
nr_('teobald',pers).
nr_('tenesi',subst).
nr_('telangan',subst).
nr_('teksas',subst).
nr_('taĝiki',subst).
nr_('tasmani',subst).
nr_('tanzani',subst).
nr_('tales',subst).
nr_('tade',subst).
nr_('svisi',subst).
nr_('svedi',subst).
nr_('surinam',subst).
nr_('suna',subst).
nr_('sumeri',subst).
nr_('sukot',subst).
nr_('sudan',subst).
nr_('strasburg',subst).
nr_('strabon',subst).
nr_('sten',subst).
nr_('stefan',pers).
nr_('stanislav',subst).
nr_('somali',subst).
nr_('solutre',subst).
nr_('sokrat',pers).
nr_('sloveni',subst).
nr_('slovaki',subst).
nr_('slavon',subst).
nr_('skoti',subst).
nr_('skiti',subst).
nr_('skeld',subst).
nr_('skajp',subst).
nr_('sirius',subst).
nr_('siriak',subst).
nr_('siri',subst).
nr_('sirdarj',subst).
nr_('sirakuz',subst).
nr_('simon',pers).
nr_('simeon',pers).
nr_('silvestr',pers).
nr_('silvan',pers).
nr_('silezi',subst).
nr_('sikim',subst).
nr_('sigmund',subst).
nr_('sigismund',pers).
nr_('siberi',subst).
nr_('sergi',pers).
nr_('septuagint',subst).
nr_('senek',subst).
nr_('senegal',subst).
nr_('selim',pers).
nr_('sebastian',pers).
nr_('scil',subst).
nr_('scientologi',subst).
nr_('saĥalin',subst).
nr_('saĥalen',subst).
nr_('saturn',subst).
nr_('saskaĉevan',subst).
nr_('sarland',subst).
nr_('santeri',subst).
nr_('sanskrit',subst).
nr_('samg',subst).
nr_('sambr',subst).
nr_('salomon',pers).
nr_('salomon',subst).
nr_('salafism',subst).
nr_('sajan',subst).
nr_('sahar',subst).
nr_('sadam',subst).
nr_('ruso',subst).
nr_('rusi',subst).
nr_('rurik',pers).
nr_('rudolf',subst).
nr_('ruand',subst).
nr_('roĝer',subst).
nr_('roterdam',subst).
nr_('romi',subst).
nr_('rome',pers).
nr_('rom',subst).
nr_('roland',pers).
nr_('rodrig',subst).
nr_('rodos',subst).
nr_('rodolf',pers).
nr_('rodezi',subst).
nr_('robert',subst).
nr_('riman',subst).
nr_('rikard',pers).
nr_('riad',subst).
nr_('renat',pers).
nr_('remington',subst).
nr_('rejnland-Palatinat',subst).
nr_('rejn',subst).
nr_('rejki',subst).
nr_('regensburg',subst).
nr_('reformaci',subst).
nr_('raŭm',subst).
nr_('raĥel',subst).
nr_('raĝastan',subst).
nr_('ramajan',subst).
nr_('rajmund',subst).
nr_('rafael',pers).
nr_('puŝkin',subst).
nr_('purim',subst).
nr_('ptoleme',subst).
nr_('prusi',subst).
nr_('promete',subst).
nr_('principe',subst).
nr_('prag',subst).
nr_('pozidon',subst).
nr_('portugali',subst).
nr_('pompej',subst).
nr_('poluks',subst).
nr_('poli',subst).
nr_('pluton',subst).
nr_('plut',subst).
nr_('plini',pers).
nr_('plejad',subst).
nr_('plaŭt',subst).
nr_('platon',pers).
nr_('pjanĝ',subst).
nr_('pitagor',subst).
nr_('pinokj',subst).
nr_('pinjin',subst).
nr_('pilat',subst).
nr_('petr',pers).
nr_('peterburg',subst).
nr_('peru',subst).
nr_('perse',subst).
nr_('pentekost',subst).
nr_('pensilvani',subst).
nr_('pegaz',subst).
nr_('paŭl',pers).
nr_('patrik',subst).
nr_('pasteŭr',subst).
nr_('paskal',pers).
nr_('pask',subst).
nr_('pasion',subst).
nr_('pariz',subst).
nr_('paralimpik',subst).
nr_('paraklet',subst).
nr_('paragvaj',subst).
nr_('papu',subst).
nr_('panĝab',subst).
nr_('pange',subst).
nr_('pali',subst).
nr_('palaŭ',subst).
nr_('pakistan',subst).
nr_('pacifik',subst).
nr_('pabl',pers).
nr_('oĥock',subst).
nr_('oziris',subst).
nr_('ovidi',pers).
nr_('otoman',subst).
nr_('osvald',pers).
nr_('ostend',subst).
nr_('osman',pers).
nr_('oskar',pers).
nr_('oskar',subst).
nr_('oris',subst).
nr_('orion',subst).
nr_('orfe',subst).
nr_('oregon',subst).
nr_('onufri',subst).
nr_('ontari',subst).
nr_('onesim',pers).
nr_('omar',pers).
nr_('oman',subst).
nr_('om',pers).
nr_('oliver',pers).
nr_('olimpik',subst).
nr_('olimp',subst).
nr_('oklahom',subst).
nr_('okcidental',subst).
nr_('oka',subst).
nr_('ohi',subst).
nr_('odr',subst).
nr_('odiŝ',subst).
nr_('odise',pers).
nr_('oceani',subst).
nr_('ob',subst).
nr_('noŭruz',subst).
nr_('novosibirsk',subst).
nr_('norvegi',subst).
nr_('nordrejn-Vestfali',subst).
nr_('noaĥ',pers).
nr_('niĉiren',subst).
nr_('nirvan',subst).
nr_('nimeg',subst).
nr_('nil',subst).
nr_('nikola',pers).
nr_('nikodem',pers).
nr_('neŭton',pers).
nr_('nevad',subst).
nr_('nestor',pers).
nr_('neptun',subst).
nr_('neper',subst).
nr_('nepal',subst).
nr_('nederland',subst).
nr_('nebrask',subst).
nr_('namur',subst).
nr_('namibi',subst).
nr_('muzaik',subst).
nr_('muhamad',subst).
nr_('mozel',subst).
nr_('mozart',subst).
nr_('mozambik',subst).
nr_('moz',subst).
nr_('moskv',subst).
nr_('mors',subst).
nr_('morfe',subst).
nr_('montenegr',subst).
nr_('montan',subst).
nr_('mongoli',subst).
nr_('monak',subst).
nr_('mocart',subst).
nr_('miŝna',subst).
nr_('miŝn',subst).
nr_('miĥael',pers).
nr_('miĉigan',subst).
nr_('mizoram',subst).
nr_('misuri',subst).
nr_('misur',subst).
nr_('misisipi',subst).
nr_('misisip',subst).
nr_('mirz',pers).
nr_('minotaŭr',subst).
nr_('minesot',subst).
nr_('mikrosoft',subst).
nr_('midelburg',subst).
nr_('meĥlen',subst).
nr_('mezopotami',subst).
nr_('metodi',pers).
nr_('merkur',subst).
nr_('mendelev',subst).
nr_('mence',subst).
nr_('meksiki',subst).
nr_('meksik',subst).
nr_('meklenburgo-Antaŭpomeri',subst).
nr_('megalaj',subst).
nr_('mediterane',subst).
nr_('medi',subst).
nr_('mede',subst).
nr_('maŭric',pers).
nr_('maĥ',subst).
nr_('mate',pers).
nr_('mastriĥt',subst).
nr_('masaĉusec',subst).
nr_('marten',pers).
nr_('mars',subst).
nr_('marok',subst).
nr_('marks',subst).
nr_('mark',pers).
nr_('mariland',subst).
nr_('mari',pers).
nr_('marcial',subst).
nr_('marcel',pers).
nr_('manitob',subst).
nr_('manipur',subst).
nr_('manik',subst).
nr_('malt',subst).
nr_('malkolm',pers).
nr_('malik',subst).
nr_('malavi',subst).
nr_('malajzi',subst).
nr_('maksimilian',pers).
nr_('makintoŝ',subst).
nr_('makedoni',subst).
nr_('majn',subst).
nr_('majenc',subst).
nr_('mahomet',subst).
nr_('mahavir',subst).
nr_('maharaŝtr',subst).
nr_('mahajan',subst).
nr_('mahabarat',subst).
nr_('magreb',subst).
nr_('madjapradeŝ',subst).
nr_('madejr',subst).
nr_('luter',subst).
nr_('luksemburgi',subst).
nr_('luksemburg',subst).
nr_('luk',pers).
nr_('luizian',subst).
nr_('ludovik',pers).
nr_('lucian',pers).
nr_('loĵban',subst).
nr_('loven',subst).
nr_('london',subst).
nr_('loglan',subst).
nr_('liĥtenŝtejn',subst).
nr_('litovi',subst).
nr_('lionel',pers).
nr_('linuks',subst).
nr_('limburg',subst).
nr_('lilit',subst).
nr_('liguri',subst).
nr_('lieĝ',subst).
nr_('lier',subst).
nr_('libi',subst).
nr_('liberi',subst).
nr_('liban',subst).
nr_('lesot',subst).
nr_('lesb',subst).
nr_('lepsik',subst).
nr_('leopold',pers).
nr_('leonard',subst).
nr_('len',subst).
nr_('lelistad',subst).
nr_('lejbnic',subst).
nr_('lebeg',subst).
nr_('leandr',pers).
nr_('laŭrenc',pers).
nr_('laŭrazi',subst).
nr_('lazar',pers).
nr_('latvi',subst).
nr_('latin',subst).
nr_('lati',subst).
nr_('laptev',subst).
nr_('laplac',subst).
nr_('laos',subst).
nr_('laert',pers).
nr_('ladisla',pers).
nr_('labrador',subst).
nr_('kvirin',subst).
nr_('kuvajt',subst).
nr_('kulomb',pers).
nr_('ksitigarb',subst).
nr_('ksenofont',subst).
nr_('ksenofon',subst).
nr_('ksaver',subst).
nr_('kron',subst).
nr_('kroati',subst).
nr_('kriŝn',subst).
nr_('kristofor',pers).
nr_('kristian',subst).
nr_('krist',subst).
nr_('koŝi',subst).
nr_('kortrejk',subst).
nr_('korneli',pers).
nr_('korei',subst).
nr_('koran',subst).
nr_('kopernik',subst).
nr_('kopenhag',subst).
nr_('konstantinopol',subst).
nr_('konstanten',pers).
nr_('konrad',pers).
nr_('kong',subst).
nr_('konfuce',subst).
nr_('konektikut',subst).
nr_('komeni',subst).
nr_('kolĥid',subst).
nr_('kolumbi',subst).
nr_('kolorad',subst).
nr_('kolonj',subst).
nr_('kolombi',subst).
nr_('kluĉevskaj',subst).
nr_('klement',subst).
nr_('klaŭdi',pers).
nr_('kirgizi',subst).
nr_('kipr',subst).
nr_('kimri',subst).
nr_('keral',subst).
nr_('kepler',subst).
nr_('kentuki',subst).
nr_('kenj',subst).
nr_('kelvin',pers).
nr_('kebeki',subst).
nr_('kaŭkaz',subst).
nr_('kaŝmir',subst).
nr_('kazimir',subst).
nr_('kazaĥi',subst).
nr_('kastor',subst).
nr_('kaspi',subst).
nr_('kasiope',subst).
nr_('kartezi',subst).
nr_('karon',subst).
nr_('karolin',subst).
nr_('karol',pers).
nr_('karnatak',subst).
nr_('karloreĝ',subst).
nr_('karesm',subst).
nr_('kara',subst).
nr_('kaprikorn',subst).
nr_('kapitol',subst).
nr_('kansas',subst).
nr_('kamĉatk',subst).
nr_('kampin',subst).
nr_('kamil',pers).
nr_('kameruni',subst).
nr_('kamerun',subst).
nr_('kamboĝ',subst).
nr_('kam',subst).
nr_('kalvin',subst).
nr_('kalvari',subst).
nr_('kaloĉaj',subst).
nr_('kaboverd',subst).
nr_('kabal',subst).
nr_('justinian',pers).
nr_('justen',pers).
nr_('jupiter',subst).
nr_('jul',subst).
nr_('jugoslavi',subst).
nr_('jugoslav',subst).
nr_('jozef',pers).
nr_('jork',subst).
nr_('jordani',subst).
nr_('jordan',pers).
nr_('jomkipur',subst).
nr_('johan',pers).
nr_('joakim',pers).
nr_('jid',subst).
nr_('jesu',subst).
nr_('jerusalem',subst).
nr_('jenisej',subst).
nr_('jemen',subst).
nr_('jehov',subst).
nr_('jazon',pers).
nr_('jaroslav',subst).
nr_('japani',subst).
nr_('jansen',subst).
nr_('jamajk',subst).
nr_('jama',subst).
nr_('jakobi',subst).
nr_('jakob',subst).
nr_('izis',subst).
nr_('izidor',pers).
nr_('iv',pers).
nr_('itali',subst).
nr_('istanbul',subst).
nr_('israel',subst).
nr_('island',subst).
nr_('isel',subst).
nr_('irtiŝ',subst).
nr_('irland',subst).
nr_('irene',subst).
nr_('irak',subst).
nr_('iova',subst).
nr_('interlingva',subst).
nr_('inocent',pers).
nr_('indr',subst).
nr_('indiana',subst).
nr_('ilinojs',subst).
nr_('iliad',subst).
nr_('ignac',pers).
nr_('idah',subst).
nr_('id',subst).
nr_('husejn',pers).
nr_('hungari',subst).
nr_('humbert',pers).
nr_('hug',subst).
nr_('hudson',subst).
nr_('hubert',pers).
nr_('horus',subst).
nr_('horaci',subst).
nr_('honkong',subst).
nr_('homer',subst).
nr_('holand',subst).
nr_('hispani',subst).
nr_('hipolit',subst).
nr_('hipokrat',subst).
nr_('hindustan',subst).
nr_('hindukuŝ',subst).
nr_('hinajan',subst).
nr_('himaĉalpradeŝ',subst).
nr_('himalaj',subst).
nr_('hilbert',subst).
nr_('hieronim',pers).
nr_('heĝir',subst).
nr_('heziod',subst).
nr_('hevisid',subst).
nr_('herodot',subst).
nr_('hermit',subst).
nr_('hermes',subst).
nr_('herman',pers).
nr_('herkul',pers).
nr_('hercegovin',subst).
nr_('herakl',subst).
nr_('henrik',subst).
nr_('henegovi',subst).
nr_('hektor',subst).
nr_('havaj',subst).
nr_('hasan',pers).
nr_('harold',pers).
nr_('harlem',subst).
nr_('harian',subst).
nr_('hanafism',subst).
nr_('hampŝir',subst).
nr_('hamburg',subst).
nr_('haman',subst).
nr_('halovin',subst).
nr_('haloven',subst).
nr_('hag',subst).
nr_('hades',subst).
nr_('gvine',subst).
nr_('gvajan',subst).
nr_('guĝarat',subst).
nr_('gustav',pers).
nr_('gujan',subst).
nr_('gronland',subst).
nr_('groningen',subst).
nr_('grenad',subst).
nr_('greki',subst).
nr_('gregori',pers).
nr_('gravet',subst).
nr_('gotam',subst).
nr_('gonzal',pers).
nr_('gontran',pers).
nr_('gondvan',subst).
nr_('golgot',subst).
nr_('godfred',subst).
nr_('goa',subst).
nr_('glagolic',subst).
nr_('ginevr',subst).
nr_('gilgameŝ',subst).
nr_('gilbert',pers).
nr_('gervaz',pers).
nr_('germani',subst).
nr_('gerard',subst).
nr_('georg',pers).
nr_('gent',subst).
nr_('gemar',subst).
nr_('gelderland',subst).
nr_('ge',subst).
nr_('gaŭs',subst).
nr_('gaston',subst).
nr_('gaspar',pers).
nr_('gana',subst).
nr_('galilej',subst).
nr_('galez',subst).
nr_('gabriel',subst).
nr_('gabon',subst).
nr_('frisi',subst).
nr_('freŭd',subst).
nr_('frederik',pers).
nr_('frankfurt',subst).
nr_('francisk',pers).
nr_('franci',subst).
nr_('fortunat',pers).
nr_('fob',subst).
nr_('florid',subst).
nr_('florian',pers).
nr_('florenc',subst).
nr_('flevoland',subst).
nr_('flandri',subst).
nr_('finni',subst).
nr_('finland',subst).
nr_('filipin',subst).
nr_('filip',pers).
nr_('filibert',pers).
nr_('figar',subst).
nr_('fernand',pers).
nr_('ferdinand',pers).
nr_('fenici',subst).
nr_('feliks',pers).
nr_('fejsbuk',subst).
nr_('farenhejt',subst).
nr_('farad',subst).
nr_('fanar',subst).
nr_('fabrici',pers).
nr_('fabian',pers).
nr_('fabi',pers).
nr_('eŭzebi',pers).
nr_('eŭrop',subst).
nr_('eŭrial',subst).
nr_('eŭrazi',subst).
nr_('eŭler',subst).
nr_('eŭklid',subst).
nr_('eŭgen',pers).
nr_('eŭfrat',subst).
nr_('ezop',subst).
nr_('etiopi',subst).
nr_('estoni',subst).
nr_('esperanti',subst).
nr_('esperant',subst).
nr_('ernest',pers).
nr_('eritre',subst).
nr_('erik',pers).
nr_('erasm',subst).
nr_('epikur',subst).
nr_('epifani',subst).
nr_('ene',pers).
nr_('emilian',pers).
nr_('emil',pers).
nr_('emanuel',pers).
nr_('elize',subst).
nr_('eli',pers).
nr_('elb',subst).
nr_('ekvador',subst).
nr_('ejnŝtejn',subst).
nr_('ejnstejn',subst).
nr_('egipti',subst).
nr_('efes',subst).
nr_('edvard',pers).
nr_('eduard',pers).
nr_('edmund',pers).
nr_('edgar',pers).
nr_('eden',subst).
nr_('duŝanbe',subst).
nr_('dublin',subst).
nr_('drent',subst).
nr_('donald',pers).
nr_('dominik',pers).
nr_('dirak',subst).
nr_('dioskur',subst).
nr_('dionizi',pers).
nr_('dieg',pers).
nr_('dian',pers).
nr_('demokrit',subst).
nr_('demetri',pers).
nr_('delavar',subst).
nr_('dejm',subst).
nr_('dedekind',subst).
nr_('david',pers).
nr_('darmapad',subst).
nr_('darm',subst).
nr_('danub',subst).
nr_('daniel',pers).
nr_('dani',subst).
nr_('damian',pers).
nr_('damask',subst).
nr_('dakot',subst).
nr_('dagobert',pers).
nr_('ciril',pers).
nr_('ciprian',pers).
nr_('cion',subst).
nr_('ciceron',subst).
nr_('cezar',pers).
nr_('cerber',subst).
nr_('celsi',subst).
nr_('celesten',pers).
nr_('cefe',subst).
nr_('buĥor',subst).
nr_('buĥar',subst).
nr_('butan',subst).
nr_('burund',subst).
nr_('bulgari',subst).
nr_('bule',subst).
nr_('bruĝ',subst).
nr_('brusel',subst).
nr_('brunsvik',subst).
nr_('brunej',subst).
nr_('brun',pers).
nr_('briti',subst).
nr_('bremen',subst).
nr_('brem',subst).
nr_('brazilj',subst).
nr_('brazili',subst).
nr_('brazil',subst).
nr_('brandenburg',subst).
nr_('brabant',subst).
nr_('bosni',subst).
nr_('boris',pers).
nr_('borel',subst).
nr_('bonifac',pers).
nr_('bonaventur',pers).
nr_('bomarŝe',subst).
nr_('bolivi',subst).
nr_('boleslav',pers).
nr_('bodidarm',subst).
nr_('blazi',pers).
nr_('bizanti',subst).
nr_('bizanci',subst).
nr_('bizanc',subst).
nr_('birm',subst).
nr_('bihar',subst).
nr_('bibli',subst).
nr_('besarabi',subst).
nr_('bertrand',pers).
nr_('bernard',pers).
nr_('berlin',subst).
nr_('bering',subst).
nr_('beovulf',subst).
nr_('beograd',subst).
nr_('benjamen',pers).
nr_('bengal',subst).
nr_('benedikt',pers).
nr_('belgi',subst).
nr_('behemot',subst).
nr_('baĥ',subst).
nr_('bazil',pers).
nr_('batu',subst).
nr_('bartolome',pers).
nr_('barnab',pers).
nr_('barbad',subst).
nr_('barat',subst).
nr_('bankok',subst).
nr_('banaĥ',subst).
nr_('baltik',subst).
nr_('baltazar',pers).
nr_('balkaŝ',subst).
nr_('balduen',pers).
nr_('baktri',subst).
nr_('bajkal',subst).
nr_('baham',subst).
nr_('bagdad',subst).
nr_('bagavadgit',subst).
nr_('baden-Virtemberg',subst).
nr_('babiloni',subst).
nr_('babilon',subst).
nr_('babel',subst).
nr_('aŭstri',subst).
nr_('aŭstrali',subst).
nr_('aŭrelian',pers).
nr_('aŭgusten',pers).
nr_('aŝok',subst).
nr_('aĥil',pers).
nr_('azov',subst).
nr_('azi',subst).
nr_('azeri',subst).
nr_('azerbajĝan',subst).
nr_('avogadr',subst).
nr_('avicen',subst).
nr_('avest',subst).
nr_('avalokiteŝvar',subst).
nr_('atlantik',subst).
nr_('atlantid',subst).
nr_('atlant',subst).
nr_('atalant',subst).
nr_('aski',subst).
nr_('asiri',subst).
nr_('asen',subst).
nr_('asam',subst).
nr_('arĥimed',subst).
nr_('arunaĉalpradeŝ',subst).
nr_('artur',pers).
nr_('artemid',subst).
nr_('arnold',pers).
nr_('arnhem',subst).
nr_('armeni',subst).
nr_('arkt',subst).
nr_('arkansas',subst).
nr_('arizon',subst).
nr_('aristotel',pers).
nr_('aristofan',subst).
nr_('argonaŭt',subst).
nr_('argentin',subst).
nr_('ares',subst).
nr_('aral',subst).
nr_('apolon',subst).
nr_('antverpen',subst).
nr_('antonen',pers).
nr_('anton',pers).
nr_('antarkt',subst).
nr_('anselm',pers).
nr_('angol',subst).
nr_('angli',subst).
nr_('angar',subst).
nr_('andromed',subst).
nr_('andre',pers).
nr_('andrapradeŝ',subst).
nr_('andor',subst).
nr_('anatoli',subst).
nr_('anatol',pers).
nr_('anastazi',pers).
nr_('anabaz',subst).
nr_('amudarj',subst).
nr_('amsterdam',subst).
nr_('amper',pers).
nr_('amerik',subst).
nr_('ambrozi',pers).
nr_('amazon',subst).
nr_('amade',pers).
nr_('alĝeri',subst).
nr_('alzac',subst).
nr_('altaj',subst).
nr_('altair',subst).
nr_('almat',subst).
nr_('alfred',pers).
nr_('alfons',pers).
nr_('aleksandri',subst).
nr_('aleksandr',pers).
nr_('albert',pers).
nr_('albert',subst).
nr_('albani',subst).
nr_('alask',subst).
nr_('alan',pers).
nr_('alah',subst).
nr_('alabam',subst).
nr_('akad',subst).
nr_('ahmadism',subst).
nr_('agni',subst).
nr_('afrodit',subst).
nr_('afrik',subst).
nr_('adrian',pers).
nr_('adolf',pers).
nr_('adam',pers).
nr_('adalbert',pers).
nr_('abidarm',subst).
nr_('abel',subst).
nr_('abas',pers).
