/*************
   pretaj vortoj 
*************/
v('aĉ','intj') --> "aĉ".
v('adiaŭ','intj') --> "adiaŭ".
v('ajn','advpart') --> "ajn".
v('aĥ','intj') --> "aĥ".
v('al','prep') --> "al".
v('almenaŭ','adv') --> "almenaŭ".
v('ambaŭ','pron') --> "ambaŭ".
v('ankaŭ','adv') --> "ankaŭ".
v('ankoraŭ','adv') --> "ankoraŭ".
v('anstataŭ','prep') --> "anstataŭ".
v('anstataŭ','infprep') --> "anstataŭ".
v('antaŭ','prep') --> "antaŭ".
v('antaŭ','infprep') --> "antaŭ".
v('apenaŭ','adv') --> "apenaŭ".
v('apud','prep') --> "apud".
v('aŭ','konj') --> "aŭ".
v('baldaŭ','adv') --> "baldaŭ".
v('cent','nombr') --> "cent".
v('ĉar','konj') --> "ĉar".
v('ĉe','prep') --> "ĉe".
v('ĉi','advpart') --> "ĉi".
v('ĉial','adv') --> "ĉial".
v('ĉiam','adv') --> "ĉiam".
v('ĉiel','adv') --> "ĉiel".
v('ĉiom','adv') --> "ĉiom".
v('ĉirkaŭ','prep') --> "ĉirkaŭ".
v('ĉu','adv') --> "ĉu".
v('da','prep') --> "da".
v('de','prep') --> "de".
v('dek','nombr') --> "dek".
v('des','adv') --> "des".
v('do','konj') --> "do".
v('du','nombr') --> "du".
v('dum','prep') --> "dum".
v('eĉ','adv') --> "eĉ".
v('ekster','prep') --> "ekster".
v('el','prep') --> "el".
v('en','prep') --> "en".
v('fi','intj') --> "fi".
v('for','adv') --> "for".
v('ĝis','prep') --> "ĝis".
v('ho','intj') --> "ho".
v('hieraŭ','adv') --> "hieraŭ".
v('hodiaŭ','adv') --> "hodiaŭ".
v('hura','intj') --> "hura".
v('ial','adv') --> "ial".
v('iam','adv') --> "iam".
v('iel','adv') --> "iel".
v('inter','prep') --> "inter".
v('iom','adv') --> "iom".
v('ja','adv') --> "ja".
v('jam','adv') --> "jam".
v('je','prep') --> "je".
v('jen','adv') --> "jen".
v('jes','intj') --> "jes".
v('ju','adv') --> "ju".
v('ĵus','adv') --> "ĵus".
v('kaj','konj') --> "kaj".
v('ke','subj') --> "ke".
v('kial','adv') --> "kial".
v('kiam','adv') --> "kiam".
v('kiel','adv') --> "kiel".
v('ĉies','pron') --> "ĉies".
v('kies','pron') --> "kies".
v('kiom','adv') --> "kiom".
v('kontraŭ','prep') --> "kontraŭ".
v('krom','prep') --> "krom".
v('krom','infprep') --> "krom".
v('kun','prep') --> "kun".
v('kvankam','subj') --> "kvankam".
v('kvar','nombr') --> "kvar".
v('kvazaŭ','subj') --> "kvazaŭ".
v('kvin','nombr') --> "kvin".
v('la','art') --> "la".
v('l''','art') --> "l'".
v('laŭ','prep') --> "laŭ".
v('malgraŭ','prep') --> "malgraŭ".
v('mem','adv') --> "mem".
v('mil','nombr') --> "mil".
v('minus','konj') --> "minus".
v('morgaŭ','adv') --> "morgaŭ".
v('naŭ','nombr') --> "naŭ".
v('ne','adv') --> "ne".
v('ne','intj') --> "ne".
v('nek','konj') --> "nek".
v('nenial','adv') --> "nenial".
v('neniam','adv') --> "neniam".
v('neniel','adv') --> "neniel".
v('nenies','pron') --> "nenies".
v('ies','pron') --> "ies".
v('kiom','adv') --> "kiom".
v('neniom','adv') --> "neniom".
v('nu','intj') --> "nu".
v('nul','nombr') --> "nul".
v('nun','adv') --> "nun".
v('nur','adv') --> "nur".
v('ok','nomr') --> "ok".
v('ol','konj') --> "ol".
v('per','prep') --> "per".
v('plej','adv') --> "plej".
v('pli','adv') --> "pli".
v('plu','adv') --> "plu".
v('plus','konj') --> "plus".
v('po','prep') --> "po".
v('por','prep') --> "por".
v('por','infprep') --> "por".
v('post','prep') --> "post".
v('preskaŭ','adv') --> "preskaŭ".
v('preter','prep') --> "preter".
v('pri','prep') --> "pri".
v('pro','prep') --> "pro".
v('se','subj') --> "se".
v('sed','konj') --> "sed".
v('sen','prep') --> "sen".
v('sen','infprep') --> "sen".
v('sep','nombr') --> "sep".
v('ses','nombr') --> "ses".
v('sub','prep') --> "sub".
v('super','prep') --> "super".
v('sur','prep') --> "sur".
v('tamen','konj') --> "tamen".
v('tial','adv') --> "tial".
v('tiam','adv') --> "tiam".
v('tiel','adv') --> "tiel".
v('ties','pron') --> "ties".
v('tiom','adv') --> "tiom".
v('tra','prep') --> "tra".
v('trans','prep') --> "trans".
v('tre','adv') --> "tre".
v('tri','nombr') --> "tri".
v('tro','adv') --> "tro".
v('tuj','adv') --> "tuj".
v('unu','nombr') --> "unu".
v('ve','intj') --> "ve".




