v(ŭoŭ,intj,+).
v(ŭaŭ,intj,+).
v(ŝŝ,intj,+).
v(ŝpruc,intj,*).
v(ŝmac,intj,*).
v(ĉit,intj,+).
v(ĉirp,intj,+).
v(zzz,intj,+).
v(vaŭ,intj,+).
v(ups,intj,+).
v(tus,intj,*).
v(ts,intj,+).
v(trateratra,intj,+).
v(tpr,intj,+).
v(tin,intj,+).
v(tiktak,intj,+).
v(ta,intj,+).
v(sss,intj,+).
v(snuf,intj,+).
v(sal,intj,+).
v(rukt,intj,*).
v(ruk,intj,+).
v(ronk,intj,*).
v(raĉ,intj,+).
v(pum,intj,+).
v(pu,intj,+).
v(plaŭ,intj,+).
v(pland,intj,*).
v(pep,intj,*).
v(paf,intj,*).
v(pa,intj,+).
v(okej,intj,+).
v(oj,intj,+).
v(oh,intj,+).
v('o kej',intj,+).
v(mu,intj,+).
v(miaŭ,intj,'1').
v(mek,intj,+).
v(maĉ,intj,*).
v(kŭaks,intj,+).
v(kvivit,intj,+).
v(kvak,intj,+).
v(kva,intj,+).
v(kurre,intj,+).
v(kriĉ,intj,+).
v(kraŝ,intj,+).
v(krak,intj,*).
v(knar,intj,'4').
v(kluk,intj,'4').
v(klak,intj,'3').
v(jej,intj,+).
v(ia,intj,+).
v(huŝ,intj,+).
v(huj,intj,+).
v(hu,intj,+).
v(hrr,intj,+).
v(hot,intj,+).
v(hop,intj,+).
v(hm,intj,+).
v(hihi,intj,+).
v(heŭreka,intj,+).
v(hej,intj,+).
v(he,intj,'1').
v(ha,intj,*).
v(gut,intj,*).
v('gruk-ru',intj,+).
v(glut,intj,*).
v(glu,intj,+).
v(fu,intj,+).
v(frap,intj,*).
v(fek,intj,'9').
v(ej,intj,+).
v(ehe,intj,+).
v(eh,intj,+).
v(dirlididi,intj,+).
v(bum,intj,+).
v(brr,intj,+).
v(boj,intj,*).
v(blabla,intj,+).
v(be,intj,+).
v(baŭ,intj,+).
v(bat,intj,*).
v(baf,intj,+).
v(bac,intj,+).
v(ba,intj,+).
v(aŭ,intj,+).
v(aha,intj,+).
v(ah,intj,+).
