nr('Ŝverin',subst,+).
nr('Ŝopen',subst,+).
nr('Ŝlejer',pers,+).
nr('Ŝjian',subst,+).
nr('Ŝiva',subst,+).
nr('Ŝiv',subst,+).
nr('Ŝinkansen',subst,+).
nr('Ŝimŝon',subst,+).
nr('Ŝiller',subst,*).
nr('Ŝil',subst,+).
nr('Ŝijaism',subst,+).
nr('Ŝetland',subst,'10').
nr('Ŝenĵen',subst,+).
nr('Ŝenjang',subst,+).
nr('Ŝengen',subst,+).
nr('Ŝem',subst,'10').
nr('Ŝekspir',subst,+).
nr('Ŝari',subst,+).
nr('Ŝanĥaj',subst,+).
nr('Ŝanhaj',subst,'10').
nr('Ŝandong',subst,+).
nr('Ĵul',pers,+).
nr('Ĵub',subst,+).
nr('Ĵerzej',subst,+).
nr('Ĥiron',subst,+).
nr('Ĥi',subst,+).
nr('Ĥerone',subst,+).
nr('Ĥeops',subst,+).
nr('Ĥebron',subst,+).
nr('Ĥartum',subst,+).
nr('Ĥaron',subst,+).
nr('Ĥarkov',subst,+).
nr('Ĥarkiv',subst,+).
nr('Ĥariĝism',subst,+).
nr('Ĥaribd',subst,+).
nr('Ĥanuk',subst,+).
nr('Ĥam',subst,+).
nr('Ĝoĉi',subst,+).
nr('Ĝingis',pers,+).
nr('Ĝid',subst,+).
nr('Ĝibuti',subst,'10').
nr('Ĝibut',subst,+).
nr('Ĝibraltar',subst,'10').
nr('Ĝerald',pers,+).
nr('Ĝenov',subst,+).
nr('Ĝenev',subst,'10').
nr('Ĝav',subst,+).
nr('Ĝarkand',subst,+).
nr('Ĝakart',subst,'10').
nr('Ĝajpur',subst,+).
nr('Ĉornobil',subst,+).
nr('Ĉongĉing',subst,+).
nr('Ĉitagong',subst,+).
nr('Ĉini',subst,+).
nr('Ĉingis',pers,+).
nr('Ĉili',subst,'10').
nr('Ĉikag',subst,'10').
nr('Ĉeĥoslovaki',subst,+).
nr('Ĉeĥi',subst,+).
nr('Ĉernobil',subst,+).
nr('Ĉengdu',subst,+).
nr('Ĉenaj',subst,'10').
nr('Ĉatisgar',subst,+).
nr('Ĉangĝoŭ',subst,+).
nr('Ĉangĉun',subst,+).
nr('Ĉad',subst,'10').
nr('Zurik',subst,'10').
nr('Zoroastr',subst,+).
nr('Zimbabv',subst,'10').
nr('Zib',subst,+).
nr('Zeŭs',subst,'10').
nr('Zeland',subst,'10').
nr('Zaratuŝtr',subst,+).
nr('Zanzibar',subst,'10').
nr('Zamenhof',pers,*).
nr('Zambi',subst,'10').
nr('Zairi',subst,+).
nr('Zair',subst,+).
nr('Zagreb',subst,'10').
nr('Vurtemberg',subst,+).
nr('Vultav',subst,+).
nr('Vulgat',subst,+).
nr('Vulfil',pers,+).
nr('Vuhan',subst,+).
nr('Vroclav',subst,+).
nr('Volter',subst,+).
nr('Volt',subst,+).
nr('Volsung',subst,+).
nr('Volg',subst,'10').
nr('Volfgang',pers,+).
nr('Volapuk',subst,+).
nr('Vogez',subst,'10').
nr('Vodu',subst,+).
nr('Vladimir',pers,+).
nr('Vjetnami',subst,+).
nr('Vjentjan',subst,+).
nr('Vjentian',subst,+).
nr('Viŝnu',subst,+).
nr('Vizbaden',subst,+).
nr('Vittenberg',subst,+).
nr('Vitruvi',subst,+).
nr('Vitenberg',subst,+).
nr('Vit',subst,+).
nr('Viskonsin',subst,+).
nr('Virtemberg',subst,+).
nr('Virgini',subst,+).
nr('Vindoz',subst,+).
nr('Vindhuk',subst,+).
nr('Vincent',pers,'10').
nr('Vinaj',subst,+).
nr('Vilnius',subst,+).
nr('Viln',subst,+).
nr('Vilhelm',pers,*).
nr('Viktori',subst,+).
nr('Viktor',pers,+).
nr('Vikipedi',subst,+).
nr('Vien',subst,'10').
nr('Viborg',subst,+).
nr('Vezuvi',subst,+).
nr('Vezer',subst,+).
nr('Vestminstr',subst,+).
nr('Vestfali',subst,+).
nr('Versajl',subst,+).
nr('Veron',subst,+).
nr('Vermont',subst,+).
nr('Vergili',pers,+).
nr('Venus',subst,+).
nr('Venezuel',subst,'8').
nr('Vener',subst,+).
nr('Veneci',subst,'10').
nr('Vencesla',pers,+).
nr('Velington',subst,+).
nr('Vaŭd',subst,+).
nr('Vaŝinton',subst,+).
nr('Vaŝington',subst,*).
nr('Vaĝrajan',subst,+).
nr('Vatikan',subst,'10').
nr('Vat',pers,+).
nr('Varsovi',subst,*).
nr('Varn',subst,'10').
nr('Varingjen',subst,+).
nr('Vanuatu',subst,'10').
nr('Vankuver',subst,'10').
nr('Valter',pers,+).
nr('Valoni',subst,+).
nr('Valhal',subst,+).
nr('Valet',subst,+).
nr('Valeri',pers,+).
nr('Valenten',pers,+).
nr('Valenci',subst,'10').
nr('Valdorf',subst,+).
nr('Vajroĉan',subst,+).
nr('Vajoming',subst,+).
nr('Vajmar',subst,+).
nr('Vahabism',subst,+).
nr('Vagadugu',subst,+).
nr('Vaduz',subst,+).
nr('Uzbeki',subst,+).
nr('Utreĥt',subst,+).
nr('Utarpradeŝ',subst,+).
nr('Utarakand',subst,+).
nr('Utah',subst,+).
nr('Uson',subst,'9').
nr('Urumĉi',subst,+).
nr('Urugvaj',subst,'8').
nr('Urdu',subst,+).
nr('Uran',subst,+).
nr('Ural',subst,'10').
nr('Upsal',subst,'10').
nr('Uniks',subst,+).
nr('Unikod',subst,+).
nr('Unesk',subst,+).
nr('Ulster',subst,+).
nr('Ulis',subst,+).
nr('Ulanbator',subst,'10').
nr('Ulamban',subst,+).
nr('Ukraini',subst,+).
nr('Ugand',subst,'10').
nr('Uen',subst,+).
nr('Tviter',subst,+).
nr('Tver',subst,+).
nr('Tuval',subst,'10').
nr('Turkmeni',subst,+).
nr('Turki',subst,+).
nr('Turingi',subst,+).
nr('Tunizi',subst,'8').
nr('Tuniz',subst,+).
nr('Tunis',subst,+).
nr('Tuluz',subst,+).
nr('Tukidid',pers,+).
nr('Tucidid',pers,+).
nr('Trondhejm',subst,+).
nr('Troj',subst,+).
nr('Trocki',pers,+).
nr('Tripur',subst,+).
nr('Tripol',subst,+).
nr('Tripitak',subst,+).
nr('Trinidad',subst,'10').
nr('Trevir',subst,+).
nr('Trent',subst,+).
nr('Transilvani',subst,+).
nr('Tot',subst,+).
nr('Toskani',subst,+).
nr('Toront',subst,'10').
nr('Torin',subst,'10').
nr('Tora',subst,+).
nr('Tong',subst,'10').
nr('Tomas',pers,+).
nr('Tolstoj',pers,+).
nr('Toled',subst,+).
nr('Tokipon',subst,+).
nr('Toki',subst,'10').
nr('Tokaj',subst,+).
nr('Tog',subst,'10').
nr('Tobi',pers,+).
nr('Tobag',subst,'10').
nr('Tjanĝin',subst,+).
nr('Titikak',subst,+).
nr('Tirol',subst,+).
nr('Tiran',subst,+).
nr('Tinĉj',subst,+).
nr('Timur',subst,+).
nr('Timote',pers,+).
nr('Timor',subst,'10').
nr('Timbuktu',subst,+).
nr('Tigris',subst,'10').
nr('Tiflis',subst,+).
nr('Tife',subst,+).
nr('Tician',subst,+).
nr('Tibet',subst,'10').
nr('Tiberi',pers,+).
nr('Tiber',subst,+).
nr('Tet',subst,+).
nr('Tesalonik',subst,+).
nr('Teravad',subst,+).
nr('Teofil',pers,+).
nr('Teodor',pers,*).
nr('Teobald',pers,+).
nr('Tenesi',subst,+).
nr('Temistokl',pers,+).
nr('Telegram',subst,+).
nr('Telaviv',subst,'10').
nr('Telangan',subst,+).
nr('Tel-Aviv',subst,+).
nr('Teksas',subst,'10').
nr('Teheran',subst,'10').
nr('Tegucigalp',subst,+).
nr('Tegu',subst,+).
nr('Teb',subst,+).
nr('Tbilis',subst,+).
nr('Taŝkent',subst,+).
nr('Taĵ',subst,+).
nr('Taĥ',subst,+).
nr('Taĝiki',subst,+).
nr('Tatr',subst,+).
nr('Tatari',subst,+).
nr('Tasmani',subst,'10').
nr('Tars',subst,+).
nr('Tanzani',subst,'10').
nr('Tantal',subst,+).
nr('Tanatos',subst,+).
nr('Tampere',subst,'10').
nr('Tamiz',subst,'10').
nr('Tamilnad',subst,+).
nr('Talin',subst,+).
nr('Tales',pers,+).
nr('Tajvan',subst,'10').
nr('Tajpe',subst,+).
nr('Tahiti',subst,+).
nr('Tade',pers,+).
nr('Sĥeld',subst,+).
nr('Svisi',subst,+).
nr('Svedi',subst,+).
nr('Svalbard',subst,+).
nr('Suĝoŭ',subst,+).
nr('Suv',subst,+).
nr('Surinam',subst,'10').
nr('Surat',subst,+).
nr('Surabaj',subst,+).
nr('Suomi',subst,+).
nr('Suna',subst,+).
nr('Sumeri',subst,+).
nr('Sumer',subst,'10').
nr('Sumatr',subst,'10').
nr('Sulaves',subst,+).
nr('Sukot',subst,+).
nr('Suez',subst,+).
nr('Sudan',subst,'8').
nr('Stutgart',subst,+).
nr('Strasburg',subst,'10').
nr('Strabon',subst,+).
nr('Stokholm',subst,'10').
nr('Stiri',subst,+).
nr('Sten',subst,+).
nr('Stefan',pers,*).
nr('Stanislav',pers,+).
nr('Stalin',pers,+).
nr('Srilank',subst,'10').
nr('Spinoz',pers,+).
nr('Spicberg',subst,+).
nr('Spartak',pers,+).
nr('Spart',subst,+).
nr('Soveti',subst,'10').
nr('Sorbon',subst,+).
nr('Sopot',subst,+).
nr('Somali',subst,+).
nr('Solutre',subst,+).
nr('Solon',pers,+).
nr('Sokrat',pers,+).
nr('Sofokl',pers,+).
nr('Sofi',pers,*).
nr('Sofi',subst,'10').
nr('Sodom',subst,+).
nr('Smirn',subst,+).
nr('Sloveni',subst,+).
nr('Slovaki',subst,+).
nr('Slavon',subst,+).
nr('Skoti',subst,+).
nr('Skopj',subst,+).
nr('Skiti',subst,+).
nr('Skeld',subst,+).
nr('Skandinavi',subst,+).
nr('Skajp',subst,+).
nr('Siĉŭan',subst,+).
nr('Siĉuan',subst,+).
nr('Sizif',subst,+).
nr('Sirtis',subst,+).
nr('Sirt',subst,+).
nr('Sirius',subst,+).
nr('Siriak',subst,+).
nr('Siri',subst,'8').
nr('Sirdarj',subst,+).
nr('Sirakuz',subst,+).
nr('Sirakus',subst,+).
nr('Singapur',subst,'10').
nr('Sinaj',subst,+).
nr('Simon',pers,+).
nr('Simeon',pers,+).
nr('Silvestr',pers,+).
nr('Silvan',pers,+).
nr('Silezi',subst,'10').
nr('Silen',subst,+).
nr('Sikst',pers,+).
nr('Sikim',subst,+).
nr('Sigmund',pers,+).
nr('Sigismund',pers,+).
nr('Sieraleon',subst,'10').
nr('Sidnej',subst,+).
nr('Sicili',subst,'10').
nr('Siberi',subst,'10').
nr('Sevilj',subst,+).
nr('Sevil',subst,+).
nr('Sevastopol',subst,+).
nr('Seul',subst,'10').
nr('Sergi',pers,+).
nr('Serafen',pers,+).
nr('Septuagint',subst,+).
nr('Septembr',subst,*).
nr('Senek',subst,+).
nr('Senegal',subst,'10').
nr('Selim',pers,+).
nr('Sejŝel',subst,'10').
nr('Sejn',subst,+).
nr('Seborg',subst,+).
nr('Sebastian',pers,+).
nr('Scil',subst,+).
nr('Scientologi',subst,+).
nr('Saŭl',subst,+).
nr('Saĥalin',subst,+).
nr('Saĥalen',subst,+).
nr('Savoj',subst,+).
nr('Saud',subst,'10').
nr('Saturn',subst,+).
nr('Saskaĉevan',subst,+).
nr('Sartr',pers,+).
nr('Sardini',subst,+).
nr('Saratov',subst,+).
nr('Sarajev',subst,'10').
nr('Sar',subst,+).
nr('Sapf',pers,'10').
nr('Santome',subst,'10').
nr('Santiag',subst,'10').
nr('Santeri',subst,+).
nr('Sanskrit',subst,'10').
nr('Sansalvador',subst,+).
nr('Sanpaŭl',subst,'10').
nr('Sanmarin',subst,'10').
nr('Sankt-Peterburg',subst,+).
nr('Sanfrancisk',subst,'10').
nr('Sana',subst,+).
nr('San-Salvador',subst,+).
nr('San-Paŭl',subst,+).
nr('Samson',subst,+).
nr('Samos',subst,+).
nr('Samo',subst,'10').
nr('Samir',subst,+).
nr('Samg',subst,+).
nr('Sambr',subst,+).
nr('Samarkand',subst,'10').
nr('Samari',subst,+).
nr('Salvador',subst,'10').
nr('Salomon',subst,'10').
nr('Salomon',pers,+).
nr('Salcburg',subst,+).
nr('Salafism',subst,+).
nr('Sajgon',subst,+).
nr('Sajan',subst,+).
nr('Sahel',subst,+).
nr('Sahar',subst,'10').
nr('Sadam',pers,+).
nr('Sad',subst,+).
nr('Ruso',subst,+).
nr('Rusi',subst,+).
nr('Rurik',pers,+).
nr('Rumani',subst,+).
nr('Rudolf',pers,+).
nr('Rubikon',subst,+).
nr('Ruand',subst,'10').
nr('Roĝer',pers,+).
nr('Roterdam',subst,'10').
nr('Romi',subst,+).
nr('Rome',pers,+).
nr('Romanĉi',subst,+).
nr('Rom',subst,'10').
nr('Roland',pers,+).
nr('Rogaci',subst,+).
nr('Rodrig',pers,+).
nr('Rodos',subst,+).
nr('Rodop',subst,+).
nr('Rodolf',pers,+).
nr('Rodezi',subst,+).
nr('Rodan',subst,+).
nr('Robinson',pers,+).
nr('Robert',pers,+).
nr('Riodeĵanejr',subst,'10').
nr('Rio-de-Ĵanejr',subst,+).
nr('Riman',pers,+).
nr('Rikard',pers,+).
nr('Rig',subst,+).
nr('Riad',subst,+).
nr('Reuni',subst,'10').
nr('Renat',pers,+).
nr('Rems',subst,+).
nr('Remington',subst,+).
nr('Rejnland-Palatinat',subst,+).
nr('Rejn',subst,'10').
nr('Rejms',subst,+).
nr('Rejkjavik',subst,'10').
nr('Rejki',subst,+).
nr('Regensburg',subst,+).
nr('Reformaci',subst,'1').
nr('Recif',subst,+).
nr('Raŭm',subst,'10').
nr('Raŝid',pers,+).
nr('Raĥel',pers,+).
nr('Raĝastan',subst,+).
nr('Rangun',subst,+).
nr('Ramajan',subst,+).
nr('Rajmund',pers,+).
nr('Rafael',pers,+).
nr('Rabat',subst,+).
nr('Puŝkin',subst,+).
nr('Putin',subst,+).
nr('Purim',subst,+).
nr('Pune',subst,+).
nr('Ptolome',pers,+).
nr('Ptoleme',pers,+).
nr('Psiĥ',subst,+).
nr('Prusi',subst,+).
nr('Provenc',subst,+).
nr('Promete',subst,+).
nr('Principe',subst,'10').
nr('Pretori',subst,+).
nr('Prag',subst,'10').
nr('Pozidon',subst,+).
nr('Postskript',subst,+).
nr('Posejdon',subst,+).
nr('Portvila',subst,+).
nr('Portugali',subst,+).
nr('Portospen',subst,+).
nr('Portorik',subst,+).
nr('Portoprinc',subst,+).
nr('Porto-Rik',subst,+).
nr('Portmoresb',subst,+).
nr('Port-Moresb',subst,+).
nr('Porfiri',pers,+).
nr('Ponti',pers,+).
nr('Pondiĉer',subst,+).
nr('Pompej',subst,+).
nr('Pomeri',subst,+).
nr('Poluks',subst,+).
nr('Polinezi',subst,'8').
nr('Poli',subst,+).
nr('Pocdam',subst,+).
nr('Pnompen',subst,+).
nr('Pluton',subst,+).
nr('Plut',subst,+).
nr('Plini',pers,+).
nr('Plejad',subst,+).
nr('Plaŭt',pers,+).
nr('Platon',pers,+).
nr('Pjonjang',subst,+).
nr('Pjongjang',subst,+).
nr('Pjanĝ',subst,+).
nr('Piz',subst,+).
nr('Pitagor',subst,+).
nr('Pisidi',subst,+).
nr('Pirr',subst,+).
nr('Pirene',subst,'10').
nr('Pinokj',subst,+).
nr('Pinjin',subst,+).
nr('Pilzen',subst,+).
nr('Pilsen',subst,+).
nr('Pilat',subst,+).
nr('Picburg',subst,+).
nr('Peŝavar',subst,+).
nr('Petr',pers,*).
nr('Peterburg',subst,'10').
nr('Peru',subst,'8').
nr('Pert',subst,+).
nr('Perse',subst,+).
nr('Penz',subst,+).
nr('Pentekost',subst,*).
nr('Pentateŭk',subst,+).
nr('Pensilvani',subst,'10').
nr('Peloponez',subst,+).
nr('Pekin',subst,'10').
nr('Pegaz',subst,+).
nr('Pedr',pers,+).
nr('Paŭl',pers,*).
nr('Patrik',pers,+).
nr('Patagoni',subst,+).
nr('Pasteŭr',pers,+).
nr('Paskal',pers,+).
nr('Pask',subst,*).
nr('Pasion',subst,+).
nr('Parnas',subst,'10').
nr('Parmenid',pers,+).
nr('Parkinson',pers,+).
nr('Park',subst,+).
nr('Pariz',subst,*).
nr('Paris',subst,+).
nr('Parc',subst,+).
nr('Paramarib',subst,+).
nr('Paralimpik',subst,+).
nr('Paraklet',subst,+).
nr('Paragvaj',subst,'8').
nr('Papu',subst,'10').
nr('Paol',pers,+).
nr('Panĝab',subst,+).
nr('Pange',subst,+).
nr('Pandemoni',subst,+).
nr('Panam',subst,'8').
nr('Pamir',subst,+).
nr('Pamfili',subst,+).
nr('Pali',subst,+).
nr('Palestin',subst,'10').
nr('Palerm',subst,+).
nr('Palaŭ',subst,'10').
nr('Pakistan',subst,'8').
nr('Pafos',subst,+).
nr('Pad',subst,+).
nr('Pacifik',subst,'8').
nr('Pabl',pers,+).
nr('Oĥock',subst,+).
nr('Oziris',subst,+).
nr('Ovidi',pers,+).
nr('Overisel',subst,+).
nr('Otav',subst,+).
nr('Osvald',pers,+).
nr('Ostend',subst,+).
nr('Osman',pers,+).
nr('Osl',subst,'10').
nr('Oskar',subst,+).
nr('Oskar',pers,+).
nr('Oseti',subst,+).
nr('Osak',subst,'10').
nr('Orong',subst,+).
nr('Orlean',subst,+).
nr('Orkad',subst,+).
nr('Ork',subst,+).
nr('Oris',subst,+).
nr('Orion',subst,+).
nr('Orfe',subst,+).
nr('Oregon',subst,+).
nr('Oomot',subst,+).
nr('Onufri',pers,+).
nr('Ontari',subst,+).
nr('Onesim',pers,+).
nr('Omsk',subst,+).
nr('Omdurman',subst,+).
nr('Omar',pers,+).
nr('Oman',subst,'10').
nr('Om',pers,+).
nr('Oliver',pers,+).
nr('Olimpik',subst,+).
nr('Olimpi',subst,'10').
nr('Olimp',subst,'10').
nr('Olav',pers,+).
nr('Oktobr',subst,*).
nr('Oksford',subst,'10').
nr('Oklahom',subst,+).
nr('Okinav',subst,'10').
nr('Okcitani',subst,+).
nr('Okcidental',subst,+).
nr('Oka',subst,+).
nr('Ohi',subst,+).
nr('Odr',subst,'10').
nr('Odiŝ',subst,+).
nr('Odise',pers,+).
nr('Odes',subst,'10').
nr('Oceani',subst,'10').
nr('Ob',subst,+).
nr('Nĝamen',subst,+).
nr('Nursultan',subst,+).
nr('Nurnberg',subst,+).
nr('Nurenberg',subst,'10').
nr('Nunavut',subst,+).
nr('Nukualof',subst,+).
nr('Nubi',subst,+).
nr('Nuakŝot',subst,+).
nr('Noŭruz',subst,+).
nr('Novosibirsk',subst,+).
nr('Novial',subst,+).
nr('Novgorod',subst,+).
nr('Novembr',subst,*).
nr('Norvegi',subst,+).
nr('Noaĥ',pers,+).
nr('Niĝeri',subst,'10').
nr('Niĝer',subst,'10').
nr('Niĉiren',subst,+).
nr('Nis',subst,+).
nr('Nirvan',subst,+).
nr('Niniv',subst,+).
nr('Ningb',subst,+).
nr('Nineve',subst,+).
nr('Nimeg',subst,+).
nr('Nil',subst,'10').
nr('Nikozi',subst,+).
nr('Nikosi',subst,+).
nr('Nikola',pers,*).
nr('Nikodem',pers,*).
nr('Nikaragv',subst,'8').
nr('Nik',subst,+).
nr('Nice',subst,+).
nr('Nic',subst,+).
nr('Nibelung',subst,+).
nr('Niame',subst,+).
nr('Niagar',subst,+).
nr('Neŭŝatel',subst,+).
nr('Neŭton',pers,+).
nr('Nevis',subst,'10').
nr('Nevad',subst,+).
nr('Nestor',pers,+).
nr('Neron',pers,+).
nr('Ner',pers,+).
nr('Neptun',subst,+).
nr('Nepjid',subst,+).
nr('Neper',subst,+).
nr('Nepal',subst,'10').
nr('Nekar',subst,+).
nr('Nederland',subst,'8').
nr('Nebrask',subst,+).
nr('Nazaret',subst,+).
nr('Naur',subst,'10').
nr('Nasaŭ',subst,+).
nr('Narcis',pers,+).
nr('Napoleon',pers,+).
nr('Napol',subst,'10').
nr('Nanĉan',subst,+).
nr('Nant',subst,+).
nr('Nankin',subst,+).
nr('Naning',subst,+).
nr('Namur',subst,+).
nr('Namibi',subst,'10').
nr('Najrobi',subst,+).
nr('Najrob',subst,+).
nr('Nagoj',subst,+).
nr('Nagasak',subst,'10').
nr('Muzaik',subst,+).
nr('Munĥen',subst,+).
nr('Munken',subst,'10').
nr('Mumbaj',subst,'10').
nr('Multan',subst,+).
nr('Mulhaŭz',subst,+).
nr('Muhamad',pers,+).
nr('Mozel',subst,+).
nr('Mozart',pers,+).
nr('Mozambik',subst,'10').
nr('Moz',subst,+).
nr('Mosul',subst,+).
nr('Moskv',subst,'10').
nr('Mose',subst,+).
nr('Mors',subst,+).
nr('Morfe',subst,+).
nr('Moresnet',subst,+).
nr('Moravi',subst,'10').
nr('Montreal',subst,'10').
nr('Montpelier',subst,'10').
nr('Montevide',subst,'10').
nr('Montenegr',subst,'10').
nr('Montekarl',subst,+).
nr('Montan',subst,+).
nr('Monrovi',subst,+).
nr('Mongoli',subst,+).
nr('Monak',subst,'10').
nr('Mombas',subst,+).
nr('Moluk',subst,+).
nr('Moloĥ',subst,+).
nr('Molier',pers,+).
nr('Moldavi',subst,+).
nr('Mohamed',pers,+).
nr('Mogadiŝ',subst,+).
nr('Mocart',pers,+).
nr('Mjanma',subst,+).
nr('Miŝna',subst,+).
nr('Miŝn',subst,+).
nr('Miĥael',pers,*).
nr('Miĉigan',subst,+).
nr('Mizoram',subst,+).
nr('Misuri',subst,+).
nr('Misur',subst,+).
nr('Misisipi',subst,+).
nr('Misisip',subst,+).
nr('Mirz',pers,+).
nr('Minsk',subst,+).
nr('Minotaŭr',subst,+).
nr('Minesot',subst,+).
nr('Milan',subst,'10').
nr('Mikrosoft',subst,+).
nr('Mikronezi',subst,'10').
nr('Miken',subst,+).
nr('Mikael',pers,+).
nr('Midelburg',subst,+).
nr('Midas',subst,+).
nr('Micen',subst,+).
nr('Meĥlen',subst,+).
nr('Mezopotami',subst,'10').
nr('Metodi',pers,+).
nr('Merkur',subst,+).
nr('Mengzi',subst,+).
nr('Menefr',subst,+).
nr('Mendelev',pers,+).
nr('Mence',subst,+).
nr('Memfis',subst,+).
nr('Melburn',subst,+).
nr('Melanezi',subst,'10').
nr('Meksiki',subst,!).
nr('Meksik',subst,'8').
nr('Mekong',subst,+).
nr('Meklenburgi',subst,+).
nr('Meklenburg',subst,+).
nr('Mekk',subst,+).
nr('Mek',subst,+).
nr('Megid',subst,+).
nr('Megalaj',subst,+).
nr('Mediĉ',subst,+).
nr('Mediterane',subst,'8').
nr('Medi',subst,+).
nr('Medeĝin',subst,+).
nr('Medelin',subst,+).
nr('Mede',subst,+).
nr('Medan',subst,+).
nr('Mec',subst,+).
nr('Maŭritani',subst,'10').
nr('Maŭrici',subst,'10').
nr('Maŭric',pers,+).
nr('Maŝhad',subst,+).
nr('Maĥ',subst,+).
nr('Matild',pers,+).
nr('Mate',pers,+).
nr('Mastriĥt',subst,+).
nr('Maskat',subst,+).
nr('Maseru',subst,+).
nr('Masaĉusec',subst,+).
nr('Marŝal',subst,'10').
nr('Martinik',subst,'10').
nr('Marten',pers,+).
nr('Mart',subst,*).
nr('Mart',pers,+).
nr('Marsejl',subst,'10').
nr('Mars',subst,+).
nr('Marok',subst,'8').
nr('Marks',pers,+).
nr('Mark',pers,+).
nr('Mariland',subst,+).
nr('Mari',pers,*).
nr('Margerit',pers,+).
nr('Margaret',pers,+).
nr('Marcial',pers,+).
nr('Marcel',pers,+).
nr('Maraton',subst,'10').
nr('Marakajb',subst,+).
nr('Maput',subst,+).
nr('Manĵusr',subst,+).
nr('Manĉestr',subst,+).
nr('Maniĥe',pers,+).
nr('Manitob',subst,+).
nr('Manipur',subst,+).
nr('Manil',subst,'10').
nr('Manik',subst,+).
nr('Manhejm',subst,+).
nr('Manhajm',subst,+).
nr('Manaŭs',subst,+).
nr('Manaŭ',subst,+).
nr('Manam',subst,+).
nr('Managv',subst,+).
nr('Mameluk',subst,+).
nr('Malt',subst,'10').
nr('Malkolm',pers,+).
nr('Malik',pers,+).
nr('Mali',subst,'10').
nr('Male',subst,+).
nr('Maldiv',subst,'10').
nr('Malavi',subst,'10').
nr('Malak',subst,+).
nr('Malajzi',subst,'10').
nr('Maksimilian',pers,+).
nr('Makintoŝ',subst,+).
nr('Makedoni',subst,+).
nr('Maka',subst,+).
nr('Majot',subst,'10').
nr('Majork',subst,+).
nr('Majn',subst,'10').
nr('Majkrosoft',subst,+).
nr('Majenc',subst,'10').
nr('Maj',subst,*).
nr('Mahomet',subst,+).
nr('Mahavir',subst,+).
nr('Maharaŝtr',subst,+).
nr('Mahajan',subst,+).
nr('Mahabarat',subst,+).
nr('Magreb',subst,+).
nr('Magelan',pers,+).
nr('Madrid',subst,'10').
nr('Madras',subst,+).
nr('Madjapradeŝ',subst,+).
nr('Madejr',subst,+).
nr('Madagaskar',subst,'10').
nr('Luzaci',subst,+).
nr('Luter',pers,*).
nr('Lusak',subst,+).
nr('Luksemburgi',subst,+).
nr('Luksemburg',subst,'10').
nr('Luk',pers,+).
nr('Luizian',subst,+).
nr('Luiz',pers,+).
nr('Ludovik',pers,*).
nr('Lucian',pers,+).
nr('Luci',pers,'10').
nr('Lucern',subst,'10').
nr('Luar',subst,+).
nr('Luand',subst,+).
nr('Loĵban',subst,+).
nr('Lozan',subst,+).
nr('Loven',subst,+).
nr('Losanĝeles',subst,'10').
nr('Los-Anĝeles',subst,+).
nr('Loren',subst,'10').
nr('London',subst,*).
nr('Lome',subst,+).
nr('Loglan',subst,+).
nr('Ljubljan',subst,+).
nr('Liĥtenŝtejn',subst,'10').
nr('Litv',subst,+).
nr('Litovi',subst,+).
nr('Litomiŝl',subst,+).
nr('Lisbon',subst,'10').
nr('Lionel',pers,+).
nr('Lion',subst,+).
nr('Linuks',subst,+).
nr('Lingvafranka',subst,+).
nr('Linc',subst,+).
nr('Limoĝ',subst,+).
nr('Limburg',subst,+).
nr('Limb',subst,+).
nr('Lim',subst,+).
nr('Lilongv',subst,+).
nr('Lill',subst,'10').
nr('Lilit',subst,+).
nr('Liki',subst,+).
nr('Liguri',subst,+).
nr('Lieĝ',subst,+).
nr('Lier',subst,+).
nr('Lidi',subst,+).
nr('Lidi',pers,+).
nr('Librevil',subst,+).
nr('Libi',subst,'8').
nr('Liberi',subst,'8').
nr('Liban',subst,'8').
nr('Lete',subst,+).
nr('Let',subst,+).
nr('Lesot',subst,'10').
nr('Lesb',subst,'10').
nr('Lepsik',subst,+).
nr('Leopold',pers,+).
nr('Leonard',pers,+).
nr('Leningrad',subst,+).
nr('Lenin',subst,+).
nr('Len',subst,+).
nr('Leman',subst,+).
nr('Lelistad',subst,+).
nr('Lejbnic',subst,+).
nr('Lebeg',pers,+).
nr('Lebanon',subst,+).
nr('Leandr',pers,+).
nr('Le',pers,+).
nr('Laŭzan',subst,+).
nr('Laŭrenc',pers,+).
nr('Laŭrazi',subst,+).
nr('Laŭr',pers,+).
nr('Lazar',pers,+).
nr('Latvi',subst,+).
nr('Laton',subst,+).
nr('Latin',subst,'10').
nr('Lati',subst,+).
nr('Laptev',subst,+).
nr('Laplac',pers,+).
nr('Laos',subst,'10').
nr('Lanĝoŭ',subst,+).
nr('Laknaŭ',subst,+).
nr('Lajpcig',subst,+).
nr('Laj',pers,+).
nr('Lahor',subst,+).
nr('Lagos',subst,'10').
nr('Lafonten',pers,+).
nr('Laert',pers,+).
nr('Ladisla',pers,+).
nr('Labrador',subst,+).
nr('Labak',subst,+).
nr('La-Valet',subst,+).
nr('Kvirin',subst,+).
nr('Kvinsland',subst,+).
nr('Kuvajt',subst,'10').
nr('Kuritib',subst,+).
nr('Kupidon',subst,+).
nr('Kunming',subst,+).
nr('Kulomb',pers,+).
nr('Kub',subst,'8').
nr('Kuala-Lumpur',subst,+).
nr('Ksitigarb',subst,+).
nr('Ksenofont',pers,+).
nr('Ksenofon',pers,+).
nr('Ksaver',pers,+).
nr('Kron',subst,+).
nr('Kroati',subst,+).
nr('Kriŝn',subst,+).
nr('Kristofor',pers,'10').
nr('Kristian',pers,+).
nr('Krist',subst,*).
nr('Krime',subst,'10').
nr('Krez',pers,+).
nr('Kret',subst,+).
nr('Krakov',subst,'10').
nr('Koŝi',subst,+).
nr('Kotdivuar',subst,+).
nr('Kostarik',subst,'8').
nr('Kosov',subst,'10').
nr('Kortrejk',subst,+).
nr('Korsik',subst,'10').
nr('Kornval',subst,'10').
nr('Korneli',pers,+).
nr('Korint',subst,+).
nr('Korfu',subst,+).
nr('Korei',subst,+).
nr('Kordob',subst,+).
nr('Koran',subst,*).
nr('Kopernik',pers,+).
nr('Kopenhag',subst,'10').
nr('Konstantinopol',subst,'10').
nr('Konstanten',pers,+).
nr('Konrad',pers,+).
nr('Kong',subst,'10').
nr('Konfuzi',subst,!).
nr('Konfuce',pers,+).
nr('Konektikut',subst,+).
nr('Konakri',subst,+).
nr('Komsomol',subst,+).
nr('Komor',subst,'10').
nr('Komod',subst,+).
nr('Komeni',subst,+).
nr('Kolĥid',subst,+).
nr('Kolĉid',subst,+).
nr('Kolumbi',subst,+).
nr('Kolumb',pers,'10').
nr('Koloĵvar',subst,+).
nr('Kolose',subst,+).
nr('Kolorad',subst,'10').
nr('Kolonj',subst,'10').
nr('Kolombi',subst,'10').
nr('Kolkat',subst,'10').
nr('Koblenc',subst,+).
nr('Kluĵ',subst,+).
nr('Kluĉevskaj',subst,+).
nr('Klement',pers,+).
nr('Klaŭdi',pers,+).
nr('Klaŭd',pers,+).
nr('Klar',pers,*).
nr('Kiŝinev',subst,+).
nr('Kit',subst,+).
nr('Kislev',subst,+).
nr('Kiron',subst,+).
nr('Kirk',subst,+).
nr('Kirilic',subst,+).
nr('Kiribat',subst,'10').
nr('Kirgizi',subst,+).
nr('Kiren',subst,+).
nr('Kipr',subst,'10').
nr('Kiot',subst,'10').
nr('Kinŝas',subst,'10').
nr('Kimri',subst,+).
nr('Kiliki',subst,+).
nr('Kijiv',subst,+).
nr('Kigali',subst,+).
nr('Kiev',subst,+).
nr('Keral',subst,+).
nr('Kepler',subst,+).
nr('Kentuki',subst,+).
nr('Kenj',subst,'10').
nr('Kenigsberg',subst,+).
nr('Kembriĝ',subst,'10').
nr('Kelvin',pers,+).
nr('Kebeki',subst,'10').
nr('Kebek',subst,'10').
nr('Kaŭn',subst,+).
nr('Kaŭlun',subst,+).
nr('Kaŭkazi',subst,'10').
nr('Kaŭkaz',subst,'10').
nr('Kaŝmir',subst,'10').
nr('Kazimir',pers,+).
nr('Kazaĥi',subst,+).
nr('Kazablank',subst,+).
nr('Katmandu',subst,'10').
nr('Katmand',subst,+).
nr('Katar',subst,'10').
nr('Kataluni',subst,+).
nr('Kastor',subst,+).
nr('Kaspi',subst,'10').
nr('Kasiope',subst,+).
nr('Kartveli',subst,+).
nr('Kartum',subst,+).
nr('Kartezi',pers,+).
nr('Kartag',subst,+).
nr('Karpat',subst,'10').
nr('Karon',subst,+).
nr('Karolin',subst,+).
nr('Karol',pers,+).
nr('Karnatak',subst,+).
nr('Karl',pers,+).
nr('Karinti',subst,+).
nr('Karibi',subst,+).
nr('Karib',subst,+).
nr('Karesm',subst,+).
nr('Karaĉi',subst,'10').
nr('Karakum',subst,+).
nr('Karakas',subst,+).
nr('Kara',subst,+).
nr('Kaprikorn',subst,+).
nr('Kapitoli',subst,+).
nr('Kapitol',subst,+).
nr('Kapadoki',subst,+).
nr('Kanton',subst,'10').
nr('Kanti',pers,+).
nr('Kantabri',subst,+).
nr('Kansas',subst,+).
nr('Kandahar',subst,+).
nr('Kanber',subst,+).
nr('Kanad',subst,'8').
nr('Kamĉatk',subst,+).
nr('Kampin',subst,+).
nr('Kampani',subst,+).
nr('Kampal',subst,+).
nr('Kamil',pers,+).
nr('Kameruni',subst,+).
nr('Kamerun',subst,'10').
nr('Kamboĝ',subst,'10').
nr('Kam',subst,+).
nr('Kalvin',pers,*).
nr('Kalvari',subst,+).
nr('Kaloĉaj',subst,+).
nr('Kalkut',subst,+).
nr('Kalips',subst,+).
nr('Kaliningrad',subst,+).
nr('Kalimantan',subst,+).
nr('Kaliforni',subst,'10').
nr('Kalez',subst,+).
nr('Kalabri',subst,+).
nr('Kair',subst,'10').
nr('Kabul',subst,+).
nr('Kaboverd',subst,'10').
nr('Kabe',pers,+).
nr('Kabal',subst,'1').
nr('Jutub',subst,+).
nr('Justinian',pers,+).
nr('Justen',pers,+).
nr('Jupiter',subst,+).
nr('Juni',subst,*).
nr('Junan',subst,+).
nr('Juli',subst,*).
nr('Juli',pers,'10').
nr('Jul',subst,+).
nr('Jukon',subst,+).
nr('Jugoslavi',subst,+).
nr('Jude',subst,+).
nr('Jozef',pers,*).
nr('Josu',pers,+).
nr('Josef',pers,+).
nr('Jork',subst,'10').
nr('Jordani',subst,'10').
nr('Jordan',subst,'10').
nr('Jomkipur',subst,+).
nr('Jokoham',subst,'10').
nr('Johanesburg',subst,+).
nr('Johan',pers,*).
nr('Joakim',pers,+).
nr('Jid',subst,+).
nr('Jesu',subst,'3').
nr('Jeruzalem',subst,+).
nr('Jerusalem',subst,'10').
nr('Jeriĥ',subst,+).
nr('Jenisej',subst,+).
nr('Jemen',subst,'10').
nr('Jekaterinburg',subst,+).
nr('Jehov',subst,+).
nr('Jazon',pers,+).
nr('Jav',subst,'10').
nr('Jav',subst,+).
nr('Jaund',subst,+).
nr('Jaroslav',pers,+).
nr('Japani',subst,+).
nr('Januar',subst,*).
nr('Jansen',subst,+).
nr('Jangzi',subst,+).
nr('Jamusukr',subst,+).
nr('Jamajk',subst,'10').
nr('Jama',subst,+).
nr('Jalt',subst,+).
nr('Jakobi',pers,+).
nr('Jakob',pers,+).
nr('Jaf',subst,+).
nr('Jadvig',pers,+).
nr('Izrael',subst,*).
nr('Izmir',subst,+).
nr('Izis',subst,+).
nr('Izidor',pers,+).
nr('Izid',subst,+).
nr('Izaak',pers,+).
nr('Ivan',pers,+).
nr('Iv',pers,+).
nr('Itali',subst,+).
nr('Istri',subst,+).
nr('Istanbul',subst,'10').
nr('Israel',subst,'9').
nr('Island',subst,'8').
nr('Islamabad',subst,+).
nr('Isel',subst,+).
nr('Isaak',pers,+).
nr('Irtiŝ',subst,+).
nr('Irland',subst,'8').
nr('Irene',pers,+).
nr('Iran',subst,'8').
nr('Irak',subst,'8').
nr('Iova',subst,+).
nr('Inĉon',subst,+).
nr('Inuktitut',subst,+).
nr('Interlingva',subst,+).
nr('Inocent',pers,+).
nr('Indus',subst,'10').
nr('Indr',subst,+).
nr('Indonezi',subst,'10').
nr('Indiana',subst,+).
nr('Ilz',pers,+).
nr('Iluminat',subst,+).
nr('Ilirik',subst,+).
nr('Iliri',subst,+).
nr('Ilion',subst,+).
nr('Ilinojs',subst,+).
nr('Iliad',subst,+).
nr('Ignac',pers,+).
nr('Idah',subst,+).
nr('Id',subst,+).
nr('Ibadism',subst,+).
nr('Ibadan',subst,+).
nr('Huston',subst,+).
nr('Husejn',pers,+).
nr('Hungari',subst,+).
nr('Humbert',pers,+).
nr('Hug',pers,+).
nr('Hudson',subst,+).
nr('Hubert',pers,+).
nr('Horus',subst,+).
nr('Horaci',pers,+).
nr('Honŝu',subst,'10').
nr('Honkong',subst,'10').
nr('Hongkong',subst,+).
nr('Hondur',subst,'10').
nr('Homer',subst,+).
nr('Holstini',subst,+).
nr('Holivud',subst,+).
nr('Holi',subst,+).
nr('Holand',subst,'10').
nr('Hokajd',subst,+).
nr('Hitler',subst,+).
nr('Hispaniol',subst,+).
nr('Hispani',subst,+).
nr('Hiroŝim',subst,'10').
nr('Hipolit',pers,+).
nr('Hipokrat',subst,+).
nr('Hindustan',subst,+).
nr('Hindukuŝ',subst,+).
nr('Hindi',subst,'10').
nr('Hinajan',subst,+).
nr('Himaĉalpradeŝ',subst,+).
nr('Himalaj',subst,'10').
nr('Hilel',subst,+).
nr('Hilbert',pers,+).
nr('Hieronim',pers,+).
nr('Heĝir',subst,+).
nr('Heziod',subst,+).
nr('Hevisid',pers,+).
nr('Herodot',pers,+).
nr('Herod',subst,+).
nr('Hermon',subst,+).
nr('Hermit',pers,+).
nr('Hermes',subst,+).
nr('Herman',pers,+).
nr('Hermagor',pers,+).
nr('Herkules',subst,+).
nr('Herkul',subst,+).
nr('Hercegovin',subst,'10').
nr('Herakl',subst,+).
nr('Her',subst,+).
nr('Henrik',pers,+).
nr('Henriet',pers,*).
nr('Henegovi',subst,+).
nr('Helsink',subst,'10').
nr('Helios',subst,+).
nr('Heli',subst,+).
nr('Helen',pers,+).
nr('Hektor',pers,+).
nr('Hekat',subst,+).
nr('Hefest',subst,+).
nr('Hefej',subst,+).
nr('Hedvig',pers,+).
nr('Havan',subst,'10').
nr('Havaj',subst,'10').
nr('Hasan',pers,+).
nr('Harold',pers,+).
nr('Harmon',subst,+).
nr('Harlem',subst,+).
nr('Harjan',subst,+).
nr('Harian',subst,+).
nr('Harc',subst,+).
nr('Harbin',subst,+).
nr('Harar',subst,+).
nr('Hanovr',subst,+).
nr('Hanover',subst,+).
nr('Hanoj',subst,'10').
nr('Hanibal',pers,+).
nr('Hangĝoŭ',subst,+).
nr('Hanafism',subst,+).
nr('Hamurab',pers,+).
nr('Hampŝir',subst,+).
nr('Hamlet',subst,+).
nr('Hamelen',subst,+).
nr('Hamburg',subst,'10').
nr('Haman',subst,+).
nr('Halovin',subst,+).
nr('Haloven',subst,+).
nr('Halifaks',subst,+).
nr('Halep',subst,+).
nr('Halaĥ',subst,+).
nr('Hajfong',subst,+).
nr('Hajderabad',subst,+).
nr('Haiti',subst,'10').
nr('Hagad',subst,+).
nr('Hag',subst,'10').
nr('Hadrian',pers,+).
nr('Hades',subst,+).
nr('Habsburg',subst,+).
nr('Gvine',subst,'8').
nr('Gvatemal',subst,'8').
nr('Gvajan',subst,+).
nr('Gvadelup',subst,'10').
nr('Gustav',pers,+).
nr('Guliver',subst,+).
nr('Gujan',subst,'10').
nr('Gugl',subst,+).
nr('Gronland',subst,'10').
nr('Groningen',subst,+).
nr('Groning',subst,+).
nr('Grizon',subst,'10').
nr('Greziljon',subst,+).
nr('Grenland',subst,+).
nr('Grenadin',subst,'10').
nr('Grenad',subst,'10').
nr('Greki',subst,+).
nr('Gregori',pers,'10').
nr('Gravet',subst,+).
nr('Gram',pers,+).
nr('Gotenburg',subst,'10').
nr('Gotam',pers,+).
nr('Gordi',subst,+).
nr('Gonzal',pers,+).
nr('Gontran',pers,+).
nr('Gondvan',subst,+).
nr('Gomor',subst,+).
nr('Goljat',subst,+).
nr('Golgot',subst,+).
nr('Golem',subst,+).
nr('Godfred',pers,+).
nr('Goa',subst,+).
nr('Glasgov',subst,+).
nr('Glagolic',subst,+).
nr('Giz',subst,+).
nr('Ginevr',subst,+).
nr('Gilgameŝ',subst,+).
nr('Gilbert',pers,+).
nr('Gibraltar',subst,+).
nr('Gervaz',pers,+).
nr('Gertrud',pers,+).
nr('Germani',subst,+).
nr('Gerard',pers,+).
nr('Georg',pers,*).
nr('Gent',subst,+).
nr('Gemar',subst,+).
nr('Gelderland',subst,+).
nr('Ge',subst,+).
nr('Gdinj',subst,+).
nr('Gdansk',subst,'10').
nr('Gaŭtam',pers,+).
nr('Gaŭs',pers,+).
nr('Gaza',subst,+).
nr('Gaston',pers,+).
nr('Gaspar',pers,+).
nr('Garon',subst,+).
nr('Ganimed',subst,+).
nr('Gang',subst,'10').
nr('Ganeŝ',subst,+).
nr('Gana',subst,'10').
nr('Gambi',subst,'10').
nr('Galilej',subst,+).
nr('Galile',subst,'10').
nr('Galici',subst,'10').
nr('Galez',pers,+).
nr('Galapag',subst,+).
nr('Gabriel',subst,+).
nr('Gabon',subst,'10').
nr('Gaberon',subst,+).
nr('Fuĝoŭ',subst,+).
nr('Fukuŝim',subst,+).
nr('Friul',subst,'10').
nr('Fritaŭn',subst,+).
nr('Frisi',subst,+).
nr('Frigi',subst,+).
nr('Freŭd',pers,+).
nr('Frederik',pers,+).
nr('Frankfurt',subst,'10').
nr('Francisk',pers,+).
nr('Franci',subst,+).
nr('Fortunat',pers,+).
nr('Fortalez',subst,'10').
nr('Formoz',subst,+).
nr('Fob',subst,+).
nr('Florid',subst,'10').
nr('Florian',pers,+).
nr('Florenc',subst,'10').
nr('Flevoland',subst,+).
nr('Flandri',subst,+).
nr('Fiĝi',subst,'10').
nr('Finni',subst,+).
nr('Finland',subst,+).
nr('Filipin',subst,'10').
nr('Filip',pers,+).
nr('Filibert',pers,+).
nr('Filadelfi',subst,'10').
nr('Figar',subst,+).
nr('Fero',subst,+).
nr('Fernand',pers,+).
nr('Ferdinand',pers,+).
nr('Fenŝu',subst,+).
nr('Fenoskandi',subst,+).
nr('Feniks',subst,+).
nr('Feniki',subst,+).
nr('Fenici',subst,+).
nr('Fengŝu',subst,+).
nr('Feliks',pers,+).
nr('Fejsbuk',subst,+).
nr('Februar',subst,*).
nr('Feb',subst,+).
nr('Faŭst',pers,+).
nr('Farenhejt',pers,+).
nr('Farad',subst,+).
nr('Fanar',subst,+).
nr('Fajsalabad',subst,+).
nr('Fabrici',pers,+).
nr('Fabian',pers,+).
nr('Fabi',pers,+).
nr('Eŭzebi',pers,+).
nr('Eŭzeb',pers,+).
nr('Eŭski',subst,+).
nr('Eŭrop',subst,*).
nr('Eŭrjal',subst,+).
nr('Eŭripid',pers,+).
nr('Eŭrial',subst,+).
nr('Eŭrazi',subst,+).
nr('Eŭler',pers,+).
nr('Eŭklid',pers,+).
nr('Eŭgen',pers,+).
nr('Eŭfrat',subst,'10').
nr('Eŭdoksi',pers,+).
nr('Eŭdoki',pers,+).
nr('Ezop',pers,+).
nr('Everest',subst,+).
nr('Evelin',pers,+).
nr('Etiopi',subst,+).
nr('Esĥil',pers,+).
nr('Estoni',subst,+).
nr('Esperanti',subst,+).
nr('Esperant',subst,*).
nr('Esfahan',subst,+).
nr('Eros',subst,+).
nr('Ernest',pers,*).
nr('Eritre',subst,'10').
nr('Erik',pers,+).
nr('Eridan',subst,+).
nr('Eri',subst,+).
nr('Erfurt',subst,+).
nr('Erevan',subst,+).
nr('Erasm',subst,+).
nr('Epiros',subst,+).
nr('Epir',subst,+).
nr('Epikur',pers,+).
nr('Epifani',subst,'2').
nr('Ene',pers,+).
nr('Emilian',pers,+).
nr('Emili',pers,*).
nr('Emil',pers,+).
nr('Emanuel',pers,+).
nr('Emaks',subst,+).
nr('Elize',subst,+).
nr('Elizabet',pers,*).
nr('Eliz',pers,+).
nr('Eli',pers,+).
nr('Eleonor',pers,+).
nr('Elefen',subst,+).
nr('Elb',subst,+).
nr('Elam',subst,'10').
nr('Ekvador',subst,'8').
nr('Ejnŝtejn',pers,+).
nr('Ejnstejn',pers,+).
nr('Ejfel',pers,+).
nr('Egipti',subst,+).
nr('Ege',subst,'10').
nr('Efez',subst,+).
nr('Efes',subst,+).
nr('Edvard',pers,+).
nr('Eduard',pers,+).
nr('Edmund',pers,+).
nr('Edip',subst,+).
nr('Edinburg',subst,'10').
nr('Edgar',pers,+).
nr('Eden',subst,'1').
nr('Edam',subst,+).
nr('Duŝanbe',subst,+).
nr('Duŝanb',subst,+).
nr('Duseldorf',subst,+).
nr('Durban',subst,+).
nr('Dunj',pers,+).
nr('Dublin',subst,'10').
nr('Dubaj',subst,+).
nr('Duala',subst,+).
nr('Dresden',subst,'10').
nr('Drent',subst,+).
nr('Dovr',subst,+).
nr('Dover',subst,+).
nr('Dorote',pers,+).
nr('Dopler',pers,+).
nr('Donguan',subst,+).
nr('Doneck',subst,+).
nr('Donald',pers,+).
nr('Don',subst,+).
nr('Dominik',subst,'10').
nr('Dominik',pers,+).
nr('Doha',subst,+).
nr('Doh',subst,+).
nr('Dodoma',subst,+).
nr('Dodom',subst,+).
nr('Dnepr',subst,+).
nr('Dirak',pers,+).
nr('Dioskur',subst,+).
nr('Dionizi',pers,+).
nr('Dioniz',subst,+).
nr('Diogen',subst,+).
nr('Dil',subst,+).
nr('Dieg',pers,+).
nr('Didaĥe',subst,+).
nr('Dian',pers,+).
nr('Detrojt',subst,+).
nr('Demokrit',pers,+).
nr('Demetri',pers,+).
nr('Deli',subst,+).
nr('Delhi',subst,'10').
nr('Delf',subst,+).
nr('Delavar',subst,+).
nr('Dekameron',subst,+).
nr('Dejm',subst,+).
nr('Dedekind',pers,+).
nr('Decembr',subst,*).
nr('David',pers,+).
nr('Darvin',pers,+).
nr('Darmapad',subst,+).
nr('Darm',subst,+).
nr('Dari',pers,+).
nr('Daresalam',subst,+).
nr('Danub',subst,'10').
nr('Daniel',pers,+).
nr('Dani',subst,+).
nr('Dancig',subst,'10').
nr('Dana',subst,+).
nr('Damian',pers,+).
nr('Damask',subst,'10').
nr('Dalmati',subst,+).
nr('Dalas',subst,'10').
nr('Dakot',subst,+).
nr('Dakar',subst,+).
nr('Dak',subst,'10').
nr('Dagobert',pers,+).
nr('Ciril',pers,+).
nr('Ciren',subst,+).
nr('Circe',subst,+).
nr('Ciprian',pers,+).
nr('Cipr',subst,+).
nr('Cion',subst,+).
nr('Cinda',subst,+).
nr('Ciceron',pers,+).
nr('Cibel',subst,+).
nr('Cezare',subst,+).
nr('Cezar',pers,'10').
nr('Ceres',subst,+).
nr('Cerber',subst,+).
nr('Celsi',subst,+).
nr('Celesten',pers,+).
nr('Celebes',subst,+).
nr('Cejlon',subst,+).
nr('Cefe',subst,+).
nr('Buĥor',subst,+).
nr('Buĥar',subst,+).
nr('Butan',subst,'10').
nr('Burund',subst,'10').
nr('Burkin',subst,'10').
nr('Burgundi',subst,+).
nr('Burgonj',subst,+).
nr('Burbon',subst,+).
nr('Bulonj',subst,*).
nr('Bulgari',subst,+).
nr('Bule',pers,+).
nr('Bukareŝt',subst,'10').
nr('Budapeŝt',subst,'10').
nr('Bruĝ',subst,+).
nr('Brut',subst,+).
nr('Brusel',subst,'10').
nr('Brunsvik',subst,+).
nr('Brunn',subst,+).
nr('Brunej',subst,'10').
nr('Brun',pers,+).
nr('Brn',subst,+).
nr('Briti',subst,+).
nr('Bristol',subst,+).
nr('Brisban',subst,+).
nr('Brier',subst,+).
nr('Brest',subst,+).
nr('Bremen',subst,+).
nr('Brem',subst,+).
nr('Brazilj',subst,'10').
nr('Brazili',subst,+).
nr('Brazil',subst,'8').
nr('Brazavil',subst,'10').
nr('Bratislav',subst,'10').
nr('Brandenburg',subst,+).
nr('Brajton',subst,'10').
nr('Brajl',subst,+).
nr('Brabant',subst,+).
nr('Botni',subst,+).
nr('Boston',subst,'10').
nr('Bospor',subst,'10').
nr('Bosni',subst,+).
nr('Borne',subst,'10').
nr('Born',subst,+).
nr('Boris',pers,+).
nr('Borel',pers,+).
nr('Bordoz',subst,+).
nr('Bopomof',subst,+).
nr('Bopal',subst,+).
nr('Bonn',subst,+).
nr('Bonifac',pers,+).
nr('Bonaventur',pers,+).
nr('Bombaj',subst,+).
nr('Bomarŝe',subst,+).
nr('Bolonj',subst,'10').
nr('Bolivud',subst,+).
nr('Bolivi',subst,'8').
nr('Boleslav',pers,+).
nr('Bohemi',subst,+).
nr('Bogot',subst,'10').
nr('Bofort',pers,+).
nr('Boeci',subst,+).
nr('Bodidarm',subst,+).
nr('Bocvan',subst,'10').
nr('Blis',subst,+).
nr('Blez',subst,+).
nr('Blazi',pers,+).
nr('Bjelostok',subst,+).
nr('Bjalistok',subst,'10').
nr('Biŝkek',subst,+).
nr('Bizanti',subst,+).
nr('Bizanci',subst,+).
nr('Bizanc',subst,'10').
nr('Bitini',subst,+).
nr('Bisaŭ',subst,'10').
nr('Birm',subst,'8').
nr('Bilba',subst,+).
nr('Bihar',subst,+).
nr('Bibli',subst,'1').
nr('Betleĥem',subst,+).
nr('Besarabi',subst,+).
nr('Bertrand',pers,+).
nr('Bertil',pers,+).
nr('Bert',pers,*).
nr('Bernard',pers,+).
nr('Bern',subst,'10').
nr('Berlin',subst,*).
nr('Bering',pers,+).
nr('Bergen',subst,'10').
nr('Beovulf',subst,+).
nr('Beograd',subst,'10').
nr('Benjamen',pers,+).
nr('Benin',subst,'10').
nr('Bengalur',subst,+).
nr('Bengal',subst,+).
nr('Beneluks',subst,+).
nr('Benedikt',pers,+).
nr('Belorusi',subst,+).
nr('Beliz',subst,'10').
nr('Belgi',subst,+).
nr('Belfast',subst,'10').
nr('Belarusi',subst,+).
nr('Bel-Horizont',subst,+).
nr('Bejrut',subst,+).
nr('Behemot',subst,+).
nr('Beatric',pers,+).
nr('Baĥ',pers,+).
nr('Bazil',pers,+).
nr('Bazik',subst,+).
nr('Bazel',subst,+).
nr('Bavari',subst,+).
nr('Batu',pers,+).
nr('Bastjan',pers,+).
nr('Bastian',pers,+).
nr('Bartolome',pers,+).
nr('Barnab',pers,+).
nr('Barejn',subst,'10').
nr('Barcelon',subst,'10').
nr('Barbud',subst,'10').
nr('Barbaros',subst,+).
nr('Barbad',subst,'10').
nr('Barat',subst,'10').
nr('Bankok',subst,'10').
nr('Bangladeŝ',subst,'10').
nr('Bangkok',subst,+).
nr('Bang',subst,+).
nr('Bandung',subst,+).
nr('Banaĥ',pers,+).
nr('Bamak',subst,+).
nr('Baltik',subst,+).
nr('Baltazar',pers,+).
nr('Balkaŝ',subst,+).
nr('Balkani',subst,+).
nr('Balkan',subst,'10').
nr('Balduen',pers,+).
nr('Bakĥ',subst,+).
nr('Baku',subst,+).
nr('Baktri',subst,+).
nr('Bakk',subst,+).
nr('Bajkal',subst,+).
nr('Baham',subst,'10').
nr('Baha',subst,+).
nr('Bagdad',subst,'10').
nr('Bagavadgit',subst,+).
nr('Badaĥoz',subst,+).
nr('Babiloni',subst,+).
nr('Babilon',subst,'10').
nr('Babel',subst,+).
nr('Bab',subst,+).
nr('Aŭvernj',subst,+).
nr('Aŭstronezi',subst,'10').
nr('Aŭstri',subst,+).
nr('Aŭstrali',subst,'8').
nr('Aŭrelian',pers,+).
nr('Aŭgusten',pers,+).
nr('Aŭgust',subst,*).
nr('Aŭgust',pers,*).
nr('Aŭgsburg',subst,'10').
nr('Aŝok',subst,+).
nr('Aŝgabat',subst,+).
nr('Aĥil',pers,+).
nr('Aĥen',subst,+).
nr('Azov',subst,+).
nr('Azi',subst,'8').
nr('Azeri',subst,+).
nr('Azerbajĝan',subst,'10').
nr('Avogadr',pers,+).
nr('Avicen',pers,+).
nr('Avest',subst,+).
nr('Avejr',subst,+).
nr('Avalokiteŝvar',subst,+).
nr('Atomium',subst,+).
nr('Atlantik',subst,'8').
nr('Atlantid',subst,+).
nr('Atlant',subst,+).
nr('Atik',subst,+).
nr('Aten',subst,'10').
nr('Atalant',subst,+).
nr('Asuncion',subst,+).
nr('Asturi',subst,+).
nr('Astan',subst,+).
nr('Aski',subst,+).
nr('Asiri',subst,'10').
nr('Asen',subst,+).
nr('Asam',subst,+).
nr('Arĥimed',pers,+).
nr('Arunaĉalpradeŝ',subst,+).
nr('Artur',pers,+).
nr('Artemis',subst,+).
nr('Artemid',subst,+).
nr('Arnulf',pers,+).
nr('Arnold',pers,+).
nr('Arnhem',subst,+).
nr('Arn',subst,+).
nr('Armeni',subst,+).
nr('Arkt',subst,'9').
nr('Arkimed',pers,+).
nr('Arkansas',subst,+).
nr('Arizon',subst,+).
nr('Aristotel',pers,+).
nr('Aristofan',subst,+).
nr('Argus',subst,+).
nr('Argonaŭt',subst,+).
nr('Argentin',subst,'10').
nr('Ares',subst,+).
nr('Areopag',subst,+).
nr('Aral',subst,+).
nr('Aragon',subst,+).
nr('April',subst,*).
nr('Apolon',subst,'10').
nr('Apol',subst,+).
nr('Api',subst,+).
nr('Anunciaci',subst,*).
nr('Antverpen',subst,'10').
nr('Antoni',pers,+).
nr('Antonen',pers,+).
nr('Anton',pers,*).
nr('Antioĥi',subst,+).
nr('Antil',subst,'10').
nr('Antigv',subst,'10').
nr('Antarkt',subst,'9').
nr('Antananariv',subst,+).
nr('Anselm',pers,+).
nr('Ann',pers,*).
nr('Ankar',subst,+).
nr('Angol',subst,'10').
nr('Angli',subst,+).
nr('Angkor',subst,+).
nr('Angar',subst,+).
nr('Andronik',pers,+).
nr('Andromed',subst,+).
nr('Andre',pers,+).
nr('Andrapradeŝ',subst,+).
nr('Andor',subst,'10').
nr('Andaluzi',subst,+).
nr('And',subst,'10').
nr('Anatoli',subst,+).
nr('Anatol',pers,+).
nr('Anastazi',pers,+).
nr('Anabaz',subst,+).
nr('Amudarj',subst,+).
nr('Amsterdam',subst,'10').
nr('Amper',pers,+).
nr('Amitab',subst,+).
nr('Amir',pers,+).
nr('Amerik',subst,'8').
nr('Ambrozi',pers,+).
nr('Amazon',subst,'10').
nr('Aman',subst,+).
nr('Amade',pers,+).
nr('Alĝeri',subst,'8').
nr('Alĝer',subst,+).
nr('Alzac',subst,'10').
nr('Altaj',subst,+).
nr('Altair',subst,+).
nr('Almat',subst,+).
nr('Alfred',pers,+).
nr('Alfons',pers,+).
nr('Alep',subst,+).
nr('Aleksandri',subst,'10').
nr('Aleksandr',pers,*).
nr('Alchejmer',pers,+).
nr('Alchajmer',pers,+).
nr('Albert',subst,+).
nr('Albert',pers,+).
nr('Albani',subst,+).
nr('Alask',subst,'10').
nr('Alan',pers,+).
nr('Alah',subst,+).
nr('Alabam',subst,+).
nr('Akr',subst,+).
nr('Aken',subst,+).
nr('Akad',subst,'10').
nr('Ahmadism',subst,+).
nr('Ahmadabad',subst,+).
nr('Agni',subst,+).
nr('Afrodit',subst,+).
nr('Afrik',subst,'8').
nr('Advent',subst,'1').
nr('Adriatik',subst,'10').
nr('Adrian',pers,+).
nr('Adonis',subst,+).
nr('Adolf',pers,+).
nr('Adiĝ',subst,+).
nr('Adisabeb',subst,+).
nr('Adis-Abeb',subst,+).
nr('Aden',subst,'10').
nr('Adelajd',subst,'10').
nr('Adan',subst,+).
nr('Adam',pers,+).
nr('Adalbert',pers,+).
nr('Acor',subst,'10').
nr('Abuĝ',subst,+).
nr('Abudabi',subst,+).
nr('Abraks',subst,+).
nr('Abraham',pers,+).
nr('Abiĝan',subst,+).
nr('Abidarm',subst,+).
nr('Abel',pers,+).
nr('Abas',pers,+).
nr_(ŝverin,subst,+).
nr_(ŝopen,subst,+).
nr_(ŝlejer,pers,+).
nr_(ŝjian,subst,+).
nr_(ŝiva,subst,+).
nr_(ŝiv,subst,+).
nr_(ŝinkansen,subst,+).
nr_(ŝimŝon,subst,+).
nr_(ŝiller,subst,*).
nr_(ŝil,subst,+).
nr_(ŝijaism,subst,+).
nr_(ŝetland,subst,'10').
nr_(ŝenĵen,subst,+).
nr_(ŝenjang,subst,+).
nr_(ŝengen,subst,+).
nr_(ŝem,subst,'10').
nr_(ŝekspir,subst,+).
nr_(ŝari,subst,+).
nr_(ŝanĥaj,subst,+).
nr_(ŝanhaj,subst,'10').
nr_(ŝandong,subst,+).
nr_(ĵul,pers,+).
nr_(ĵub,subst,+).
nr_(ĵerzej,subst,+).
nr_(ĥiron,subst,+).
nr_(ĥi,subst,+).
nr_(ĥerone,subst,+).
nr_(ĥeops,subst,+).
nr_(ĥebron,subst,+).
nr_(ĥartum,subst,+).
nr_(ĥaron,subst,+).
nr_(ĥarkov,subst,+).
nr_(ĥarkiv,subst,+).
nr_(ĥariĝism,subst,+).
nr_(ĥaribd,subst,+).
nr_(ĥanuk,subst,+).
nr_(ĥam,subst,+).
nr_(ĝoĉi,subst,+).
nr_(ĝingis,pers,+).
nr_(ĝid,subst,+).
nr_(ĝibuti,subst,'10').
nr_(ĝibut,subst,+).
nr_(ĝibraltar,subst,'10').
nr_(ĝerald,pers,+).
nr_(ĝenov,subst,+).
nr_(ĝenev,subst,'10').
nr_(ĝav,subst,+).
nr_(ĝarkand,subst,+).
nr_(ĝakart,subst,'10').
nr_(ĝajpur,subst,+).
nr_(ĉornobil,subst,+).
nr_(ĉongĉing,subst,+).
nr_(ĉitagong,subst,+).
nr_(ĉini,subst,+).
nr_(ĉingis,pers,+).
nr_(ĉili,subst,'10').
nr_(ĉikag,subst,'10').
nr_(ĉeĥoslovaki,subst,+).
nr_(ĉeĥi,subst,+).
nr_(ĉernobil,subst,+).
nr_(ĉengdu,subst,+).
nr_(ĉenaj,subst,'10').
nr_(ĉatisgar,subst,+).
nr_(ĉangĝoŭ,subst,+).
nr_(ĉangĉun,subst,+).
nr_(ĉad,subst,'10').
nr_(zurik,subst,'10').
nr_(zoroastr,subst,+).
nr_(zimbabv,subst,'10').
nr_(zib,subst,+).
nr_(zeŭs,subst,'10').
nr_(zeland,subst,'10').
nr_(zaratuŝtr,subst,+).
nr_(zanzibar,subst,'10').
nr_(zamenhof,pers,*).
nr_(zambi,subst,'10').
nr_(zairi,subst,+).
nr_(zair,subst,+).
nr_(zagreb,subst,'10').
nr_(vurtemberg,subst,+).
nr_(vultav,subst,+).
nr_(vulgat,subst,+).
nr_(vulfil,pers,+).
nr_(vuhan,subst,+).
nr_(vroclav,subst,+).
nr_(volter,subst,+).
nr_(volt,subst,+).
nr_(volsung,subst,+).
nr_(volg,subst,'10').
nr_(volfgang,pers,+).
nr_(volapuk,subst,+).
nr_(vogez,subst,'10').
nr_(vodu,subst,+).
nr_(vladimir,pers,+).
nr_(vjetnami,subst,+).
nr_(vjentjan,subst,+).
nr_(vjentian,subst,+).
nr_(viŝnu,subst,+).
nr_(vizbaden,subst,+).
nr_(vittenberg,subst,+).
nr_(vitruvi,subst,+).
nr_(vitenberg,subst,+).
nr_(vit,subst,+).
nr_(viskonsin,subst,+).
nr_(virtemberg,subst,+).
nr_(virgini,subst,+).
nr_(vindoz,subst,+).
nr_(vindhuk,subst,+).
nr_(vincent,pers,'10').
nr_(vinaj,subst,+).
nr_(vilnius,subst,+).
nr_(viln,subst,+).
nr_(vilhelm,pers,*).
nr_(viktori,subst,+).
nr_(viktor,pers,+).
nr_(vikipedi,subst,+).
nr_(vien,subst,'10').
nr_(viborg,subst,+).
nr_(vezuvi,subst,+).
nr_(vezer,subst,+).
nr_(vestminstr,subst,+).
nr_(vestfali,subst,+).
nr_(versajl,subst,+).
nr_(veron,subst,+).
nr_(vermont,subst,+).
nr_(vergili,pers,+).
nr_(venus,subst,+).
nr_(venezuel,subst,'8').
nr_(vener,subst,+).
nr_(veneci,subst,'10').
nr_(vencesla,pers,+).
nr_(velington,subst,+).
nr_(vaŭd,subst,+).
nr_(vaŝinton,subst,+).
nr_(vaŝington,subst,*).
nr_(vaĝrajan,subst,+).
nr_(vatikan,subst,'10').
nr_(vat,pers,+).
nr_(varsovi,subst,*).
nr_(varn,subst,'10').
nr_(varingjen,subst,+).
nr_(vanuatu,subst,'10').
nr_(vankuver,subst,'10').
nr_(valter,pers,+).
nr_(valoni,subst,+).
nr_(valhal,subst,+).
nr_(valet,subst,+).
nr_(valeri,pers,+).
nr_(valenten,pers,+).
nr_(valenci,subst,'10').
nr_(valdorf,subst,+).
nr_(vajroĉan,subst,+).
nr_(vajoming,subst,+).
nr_(vajmar,subst,+).
nr_(vahabism,subst,+).
nr_(vagadugu,subst,+).
nr_(vaduz,subst,+).
nr_(uzbeki,subst,+).
nr_(utreĥt,subst,+).
nr_(utarpradeŝ,subst,+).
nr_(utarakand,subst,+).
nr_(utah,subst,+).
nr_(uson,subst,'9').
nr_(urumĉi,subst,+).
nr_(urugvaj,subst,'8').
nr_(urdu,subst,+).
nr_(uran,subst,+).
nr_(ural,subst,'10').
nr_(upsal,subst,'10').
nr_(uniks,subst,+).
nr_(unikod,subst,+).
nr_(unesk,subst,+).
nr_(ulster,subst,+).
nr_(ulis,subst,+).
nr_(ulanbator,subst,'10').
nr_(ulamban,subst,+).
nr_(ukraini,subst,+).
nr_(ugand,subst,'10').
nr_(uen,subst,+).
nr_(tviter,subst,+).
nr_(tver,subst,+).
nr_(tuval,subst,'10').
nr_(turkmeni,subst,+).
nr_(turki,subst,+).
nr_(turingi,subst,+).
nr_(tunizi,subst,'8').
nr_(tuniz,subst,+).
nr_(tunis,subst,+).
nr_(tuluz,subst,+).
nr_(tukidid,pers,+).
nr_(tucidid,pers,+).
nr_(trondhejm,subst,+).
nr_(troj,subst,+).
nr_(trocki,pers,+).
nr_(tripur,subst,+).
nr_(tripol,subst,+).
nr_(tripitak,subst,+).
nr_(trinidad,subst,'10').
nr_(trevir,subst,+).
nr_(trent,subst,+).
nr_(transilvani,subst,+).
nr_(tot,subst,+).
nr_(toskani,subst,+).
nr_(toront,subst,'10').
nr_(torin,subst,'10').
nr_(tora,subst,+).
nr_(tong,subst,'10').
nr_(tomas,pers,+).
nr_(tolstoj,pers,+).
nr_(toled,subst,+).
nr_(tokipon,subst,+).
nr_(toki,subst,'10').
nr_(tokaj,subst,+).
nr_(tog,subst,'10').
nr_(tobi,pers,+).
nr_(tobag,subst,'10').
nr_(tjanĝin,subst,+).
nr_(titikak,subst,+).
nr_(tirol,subst,+).
nr_(tiran,subst,+).
nr_(tinĉj,subst,+).
nr_(timur,subst,+).
nr_(timote,pers,+).
nr_(timor,subst,'10').
nr_(timbuktu,subst,+).
nr_(tigris,subst,'10').
nr_(tiflis,subst,+).
nr_(tife,subst,+).
nr_(tician,subst,+).
nr_(tibet,subst,'10').
nr_(tiberi,pers,+).
nr_(tiber,subst,+).
nr_(tet,subst,+).
nr_(tesalonik,subst,+).
nr_(teravad,subst,+).
nr_(teofil,pers,+).
nr_(teodor,pers,*).
nr_(teobald,pers,+).
nr_(tenesi,subst,+).
nr_(temistokl,pers,+).
nr_(telegram,subst,+).
nr_(telaviv,subst,'10').
nr_(telangan,subst,+).
nr_('tel-Aviv',subst,+).
nr_(teksas,subst,'10').
nr_(teheran,subst,'10').
nr_(tegucigalp,subst,+).
nr_(tegu,subst,+).
nr_(teb,subst,+).
nr_(tbilis,subst,+).
nr_(taŝkent,subst,+).
nr_(taĵ,subst,+).
nr_(taĥ,subst,+).
nr_(taĝiki,subst,+).
nr_(tatr,subst,+).
nr_(tatari,subst,+).
nr_(tasmani,subst,'10').
nr_(tars,subst,+).
nr_(tanzani,subst,'10').
nr_(tantal,subst,+).
nr_(tanatos,subst,+).
nr_(tampere,subst,'10').
nr_(tamiz,subst,'10').
nr_(tamilnad,subst,+).
nr_(talin,subst,+).
nr_(tales,pers,+).
nr_(tajvan,subst,'10').
nr_(tajpe,subst,+).
nr_(tahiti,subst,+).
nr_(tade,pers,+).
nr_(sĥeld,subst,+).
nr_(svisi,subst,+).
nr_(svedi,subst,+).
nr_(svalbard,subst,+).
nr_(suĝoŭ,subst,+).
nr_(suv,subst,+).
nr_(surinam,subst,'10').
nr_(surat,subst,+).
nr_(surabaj,subst,+).
nr_(suomi,subst,+).
nr_(suna,subst,+).
nr_(sumeri,subst,+).
nr_(sumer,subst,'10').
nr_(sumatr,subst,'10').
nr_(sulaves,subst,+).
nr_(sukot,subst,+).
nr_(suez,subst,+).
nr_(sudan,subst,'8').
nr_(stutgart,subst,+).
nr_(strasburg,subst,'10').
nr_(strabon,subst,+).
nr_(stokholm,subst,'10').
nr_(stiri,subst,+).
nr_(sten,subst,+).
nr_(stefan,pers,*).
nr_(stanislav,pers,+).
nr_(stalin,pers,+).
nr_(srilank,subst,'10').
nr_(spinoz,pers,+).
nr_(spicberg,subst,+).
nr_(spartak,pers,+).
nr_(spart,subst,+).
nr_(soveti,subst,'10').
nr_(sorbon,subst,+).
nr_(sopot,subst,+).
nr_(somali,subst,+).
nr_(solutre,subst,+).
nr_(solon,pers,+).
nr_(sokrat,pers,+).
nr_(sofokl,pers,+).
nr_(sofi,pers,*).
nr_(sofi,subst,'10').
nr_(sodom,subst,+).
nr_(smirn,subst,+).
nr_(sloveni,subst,+).
nr_(slovaki,subst,+).
nr_(slavon,subst,+).
nr_(skoti,subst,+).
nr_(skopj,subst,+).
nr_(skiti,subst,+).
nr_(skeld,subst,+).
nr_(skandinavi,subst,+).
nr_(skajp,subst,+).
nr_(siĉŭan,subst,+).
nr_(siĉuan,subst,+).
nr_(sizif,subst,+).
nr_(sirtis,subst,+).
nr_(sirt,subst,+).
nr_(sirius,subst,+).
nr_(siriak,subst,+).
nr_(siri,subst,'8').
nr_(sirdarj,subst,+).
nr_(sirakuz,subst,+).
nr_(sirakus,subst,+).
nr_(singapur,subst,'10').
nr_(sinaj,subst,+).
nr_(simon,pers,+).
nr_(simeon,pers,+).
nr_(silvestr,pers,+).
nr_(silvan,pers,+).
nr_(silezi,subst,'10').
nr_(silen,subst,+).
nr_(sikst,pers,+).
nr_(sikim,subst,+).
nr_(sigmund,pers,+).
nr_(sigismund,pers,+).
nr_(sieraleon,subst,'10').
nr_(sidnej,subst,+).
nr_(sicili,subst,'10').
nr_(siberi,subst,'10').
nr_(sevilj,subst,+).
nr_(sevil,subst,+).
nr_(sevastopol,subst,+).
nr_(seul,subst,'10').
nr_(sergi,pers,+).
nr_(serafen,pers,+).
nr_(septuagint,subst,+).
nr_(septembr,subst,*).
nr_(senek,subst,+).
nr_(senegal,subst,'10').
nr_(selim,pers,+).
nr_(sejŝel,subst,'10').
nr_(sejn,subst,+).
nr_(seborg,subst,+).
nr_(sebastian,pers,+).
nr_(scil,subst,+).
nr_(scientologi,subst,+).
nr_(saŭl,subst,+).
nr_(saĥalin,subst,+).
nr_(saĥalen,subst,+).
nr_(savoj,subst,+).
nr_(saud,subst,'10').
nr_(saturn,subst,+).
nr_(saskaĉevan,subst,+).
nr_(sartr,pers,+).
nr_(sardini,subst,+).
nr_(saratov,subst,+).
nr_(sarajev,subst,'10').
nr_(sar,subst,+).
nr_(sapf,pers,'10').
nr_(santome,subst,'10').
nr_(santiag,subst,'10').
nr_(santeri,subst,+).
nr_(sanskrit,subst,'10').
nr_(sansalvador,subst,+).
nr_(sanpaŭl,subst,'10').
nr_(sanmarin,subst,'10').
nr_('sankt-Peterburg',subst,+).
nr_(sanfrancisk,subst,'10').
nr_(sana,subst,+).
nr_('san-Salvador',subst,+).
nr_('san-Paŭl',subst,+).
nr_(samson,subst,+).
nr_(samos,subst,+).
nr_(samo,subst,'10').
nr_(samir,subst,+).
nr_(samg,subst,+).
nr_(sambr,subst,+).
nr_(samarkand,subst,'10').
nr_(samari,subst,+).
nr_(salvador,subst,'10').
nr_(salomon,subst,'10').
nr_(salomon,pers,+).
nr_(salcburg,subst,+).
nr_(salafism,subst,+).
nr_(sajgon,subst,+).
nr_(sajan,subst,+).
nr_(sahel,subst,+).
nr_(sahar,subst,'10').
nr_(sadam,pers,+).
nr_(sad,subst,+).
nr_(ruso,subst,+).
nr_(rusi,subst,+).
nr_(rurik,pers,+).
nr_(rumani,subst,+).
nr_(rudolf,pers,+).
nr_(rubikon,subst,+).
nr_(ruand,subst,'10').
nr_(roĝer,pers,+).
nr_(roterdam,subst,'10').
nr_(romi,subst,+).
nr_(rome,pers,+).
nr_(romanĉi,subst,+).
nr_(rom,subst,'10').
nr_(roland,pers,+).
nr_(rogaci,subst,+).
nr_(rodrig,pers,+).
nr_(rodos,subst,+).
nr_(rodop,subst,+).
nr_(rodolf,pers,+).
nr_(rodezi,subst,+).
nr_(rodan,subst,+).
nr_(robinson,pers,+).
nr_(robert,pers,+).
nr_(riodeĵanejr,subst,'10').
nr_('rio-de-Ĵanejr',subst,+).
nr_(riman,pers,+).
nr_(rikard,pers,+).
nr_(rig,subst,+).
nr_(riad,subst,+).
nr_(reuni,subst,'10').
nr_(renat,pers,+).
nr_(rems,subst,+).
nr_(remington,subst,+).
nr_('rejnland-Palatinat',subst,+).
nr_(rejn,subst,'10').
nr_(rejms,subst,+).
nr_(rejkjavik,subst,'10').
nr_(rejki,subst,+).
nr_(regensburg,subst,+).
nr_(reformaci,subst,'1').
nr_(recif,subst,+).
nr_(raŭm,subst,'10').
nr_(raŝid,pers,+).
nr_(raĥel,pers,+).
nr_(raĝastan,subst,+).
nr_(rangun,subst,+).
nr_(ramajan,subst,+).
nr_(rajmund,pers,+).
nr_(rafael,pers,+).
nr_(rabat,subst,+).
nr_(puŝkin,subst,+).
nr_(putin,subst,+).
nr_(purim,subst,+).
nr_(pune,subst,+).
nr_(ptolome,pers,+).
nr_(ptoleme,pers,+).
nr_(psiĥ,subst,+).
nr_(prusi,subst,+).
nr_(provenc,subst,+).
nr_(promete,subst,+).
nr_(principe,subst,'10').
nr_(pretori,subst,+).
nr_(prag,subst,'10').
nr_(pozidon,subst,+).
nr_(postskript,subst,+).
nr_(posejdon,subst,+).
nr_(portvila,subst,+).
nr_(portugali,subst,+).
nr_(portospen,subst,+).
nr_(portorik,subst,+).
nr_(portoprinc,subst,+).
nr_('porto-Rik',subst,+).
nr_(portmoresb,subst,+).
nr_('port-Moresb',subst,+).
nr_(porfiri,pers,+).
nr_(ponti,pers,+).
nr_(pondiĉer,subst,+).
nr_(pompej,subst,+).
nr_(pomeri,subst,+).
nr_(poluks,subst,+).
nr_(polinezi,subst,'8').
nr_(poli,subst,+).
nr_(pocdam,subst,+).
nr_(pnompen,subst,+).
nr_(pluton,subst,+).
nr_(plut,subst,+).
nr_(plini,pers,+).
nr_(plejad,subst,+).
nr_(plaŭt,pers,+).
nr_(platon,pers,+).
nr_(pjonjang,subst,+).
nr_(pjongjang,subst,+).
nr_(pjanĝ,subst,+).
nr_(piz,subst,+).
nr_(pitagor,subst,+).
nr_(pisidi,subst,+).
nr_(pirr,subst,+).
nr_(pirene,subst,'10').
nr_(pinokj,subst,+).
nr_(pinjin,subst,+).
nr_(pilzen,subst,+).
nr_(pilsen,subst,+).
nr_(pilat,subst,+).
nr_(picburg,subst,+).
nr_(peŝavar,subst,+).
nr_(petr,pers,*).
nr_(peterburg,subst,'10').
nr_(peru,subst,'8').
nr_(pert,subst,+).
nr_(perse,subst,+).
nr_(penz,subst,+).
nr_(pentekost,subst,*).
nr_(pentateŭk,subst,+).
nr_(pensilvani,subst,'10').
nr_(peloponez,subst,+).
nr_(pekin,subst,'10').
nr_(pegaz,subst,+).
nr_(pedr,pers,+).
nr_(paŭl,pers,*).
nr_(patrik,pers,+).
nr_(patagoni,subst,+).
nr_(pasteŭr,pers,+).
nr_(paskal,pers,+).
nr_(pask,subst,*).
nr_(pasion,subst,+).
nr_(parnas,subst,'10').
nr_(parmenid,pers,+).
nr_(parkinson,pers,+).
nr_(park,subst,+).
nr_(pariz,subst,*).
nr_(paris,subst,+).
nr_(parc,subst,+).
nr_(paramarib,subst,+).
nr_(paralimpik,subst,+).
nr_(paraklet,subst,+).
nr_(paragvaj,subst,'8').
nr_(papu,subst,'10').
nr_(paol,pers,+).
nr_(panĝab,subst,+).
nr_(pange,subst,+).
nr_(pandemoni,subst,+).
nr_(panam,subst,'8').
nr_(pamir,subst,+).
nr_(pamfili,subst,+).
nr_(pali,subst,+).
nr_(palestin,subst,'10').
nr_(palerm,subst,+).
nr_(palaŭ,subst,'10').
nr_(pakistan,subst,'8').
nr_(pafos,subst,+).
nr_(pad,subst,+).
nr_(pacifik,subst,'8').
nr_(pabl,pers,+).
nr_(oĥock,subst,+).
nr_(oziris,subst,+).
nr_(ovidi,pers,+).
nr_(overisel,subst,+).
nr_(otav,subst,+).
nr_(osvald,pers,+).
nr_(ostend,subst,+).
nr_(osman,pers,+).
nr_(osl,subst,'10').
nr_(oskar,subst,+).
nr_(oskar,pers,+).
nr_(oseti,subst,+).
nr_(osak,subst,'10').
nr_(orong,subst,+).
nr_(orlean,subst,+).
nr_(orkad,subst,+).
nr_(ork,subst,+).
nr_(oris,subst,+).
nr_(orion,subst,+).
nr_(orfe,subst,+).
nr_(oregon,subst,+).
nr_(oomot,subst,+).
nr_(onufri,pers,+).
nr_(ontari,subst,+).
nr_(onesim,pers,+).
nr_(omsk,subst,+).
nr_(omdurman,subst,+).
nr_(omar,pers,+).
nr_(oman,subst,'10').
nr_(om,pers,+).
nr_(oliver,pers,+).
nr_(olimpik,subst,+).
nr_(olimpi,subst,'10').
nr_(olimp,subst,'10').
nr_(olav,pers,+).
nr_(oktobr,subst,*).
nr_(oksford,subst,'10').
nr_(oklahom,subst,+).
nr_(okinav,subst,'10').
nr_(okcitani,subst,+).
nr_(okcidental,subst,+).
nr_(oka,subst,+).
nr_(ohi,subst,+).
nr_(odr,subst,'10').
nr_(odiŝ,subst,+).
nr_(odise,pers,+).
nr_(odes,subst,'10').
nr_(oceani,subst,'10').
nr_(ob,subst,+).
nr_(nĝamen,subst,+).
nr_(nursultan,subst,+).
nr_(nurnberg,subst,+).
nr_(nurenberg,subst,'10').
nr_(nunavut,subst,+).
nr_(nukualof,subst,+).
nr_(nubi,subst,+).
nr_(nuakŝot,subst,+).
nr_(noŭruz,subst,+).
nr_(novosibirsk,subst,+).
nr_(novial,subst,+).
nr_(novgorod,subst,+).
nr_(novembr,subst,*).
nr_(norvegi,subst,+).
nr_(noaĥ,pers,+).
nr_(niĝeri,subst,'10').
nr_(niĝer,subst,'10').
nr_(niĉiren,subst,+).
nr_(nis,subst,+).
nr_(nirvan,subst,+).
nr_(niniv,subst,+).
nr_(ningb,subst,+).
nr_(nineve,subst,+).
nr_(nimeg,subst,+).
nr_(nil,subst,'10').
nr_(nikozi,subst,+).
nr_(nikosi,subst,+).
nr_(nikola,pers,*).
nr_(nikodem,pers,*).
nr_(nikaragv,subst,'8').
nr_(nik,subst,+).
nr_(nice,subst,+).
nr_(nic,subst,+).
nr_(nibelung,subst,+).
nr_(niame,subst,+).
nr_(niagar,subst,+).
nr_(neŭŝatel,subst,+).
nr_(neŭton,pers,+).
nr_(nevis,subst,'10').
nr_(nevad,subst,+).
nr_(nestor,pers,+).
nr_(neron,pers,+).
nr_(ner,pers,+).
nr_(neptun,subst,+).
nr_(nepjid,subst,+).
nr_(neper,subst,+).
nr_(nepal,subst,'10').
nr_(nekar,subst,+).
nr_(nederland,subst,'8').
nr_(nebrask,subst,+).
nr_(nazaret,subst,+).
nr_(naur,subst,'10').
nr_(nasaŭ,subst,+).
nr_(narcis,pers,+).
nr_(napoleon,pers,+).
nr_(napol,subst,'10').
nr_(nanĉan,subst,+).
nr_(nant,subst,+).
nr_(nankin,subst,+).
nr_(naning,subst,+).
nr_(namur,subst,+).
nr_(namibi,subst,'10').
nr_(najrobi,subst,+).
nr_(najrob,subst,+).
nr_(nagoj,subst,+).
nr_(nagasak,subst,'10').
nr_(muzaik,subst,+).
nr_(munĥen,subst,+).
nr_(munken,subst,'10').
nr_(mumbaj,subst,'10').
nr_(multan,subst,+).
nr_(mulhaŭz,subst,+).
nr_(muhamad,pers,+).
nr_(mozel,subst,+).
nr_(mozart,pers,+).
nr_(mozambik,subst,'10').
nr_(moz,subst,+).
nr_(mosul,subst,+).
nr_(moskv,subst,'10').
nr_(mose,subst,+).
nr_(mors,subst,+).
nr_(morfe,subst,+).
nr_(moresnet,subst,+).
nr_(moravi,subst,'10').
nr_(montreal,subst,'10').
nr_(montpelier,subst,'10').
nr_(montevide,subst,'10').
nr_(montenegr,subst,'10').
nr_(montekarl,subst,+).
nr_(montan,subst,+).
nr_(monrovi,subst,+).
nr_(mongoli,subst,+).
nr_(monak,subst,'10').
nr_(mombas,subst,+).
nr_(moluk,subst,+).
nr_(moloĥ,subst,+).
nr_(molier,pers,+).
nr_(moldavi,subst,+).
nr_(mohamed,pers,+).
nr_(mogadiŝ,subst,+).
nr_(mocart,pers,+).
nr_(mjanma,subst,+).
nr_(miŝna,subst,+).
nr_(miŝn,subst,+).
nr_(miĥael,pers,*).
nr_(miĉigan,subst,+).
nr_(mizoram,subst,+).
nr_(misuri,subst,+).
nr_(misur,subst,+).
nr_(misisipi,subst,+).
nr_(misisip,subst,+).
nr_(mirz,pers,+).
nr_(minsk,subst,+).
nr_(minotaŭr,subst,+).
nr_(minesot,subst,+).
nr_(milan,subst,'10').
nr_(mikrosoft,subst,+).
nr_(mikronezi,subst,'10').
nr_(miken,subst,+).
nr_(mikael,pers,+).
nr_(midelburg,subst,+).
nr_(midas,subst,+).
nr_(micen,subst,+).
nr_(meĥlen,subst,+).
nr_(mezopotami,subst,'10').
nr_(metodi,pers,+).
nr_(merkur,subst,+).
nr_(mengzi,subst,+).
nr_(menefr,subst,+).
nr_(mendelev,pers,+).
nr_(mence,subst,+).
nr_(memfis,subst,+).
nr_(melburn,subst,+).
nr_(melanezi,subst,'10').
nr_(meksiki,subst,!).
nr_(meksik,subst,'8').
nr_(mekong,subst,+).
nr_(meklenburgi,subst,+).
nr_(meklenburg,subst,+).
nr_(mekk,subst,+).
nr_(mek,subst,+).
nr_(megid,subst,+).
nr_(megalaj,subst,+).
nr_(mediĉ,subst,+).
nr_(mediterane,subst,'8').
nr_(medi,subst,+).
nr_(medeĝin,subst,+).
nr_(medelin,subst,+).
nr_(mede,subst,+).
nr_(medan,subst,+).
nr_(mec,subst,+).
nr_(maŭritani,subst,'10').
nr_(maŭrici,subst,'10').
nr_(maŭric,pers,+).
nr_(maŝhad,subst,+).
nr_(maĥ,subst,+).
nr_(matild,pers,+).
nr_(mate,pers,+).
nr_(mastriĥt,subst,+).
nr_(maskat,subst,+).
nr_(maseru,subst,+).
nr_(masaĉusec,subst,+).
nr_(marŝal,subst,'10').
nr_(martinik,subst,'10').
nr_(marten,pers,+).
nr_(mart,subst,*).
nr_(mart,pers,+).
nr_(marsejl,subst,'10').
nr_(mars,subst,+).
nr_(marok,subst,'8').
nr_(marks,pers,+).
nr_(mark,pers,+).
nr_(mariland,subst,+).
nr_(mari,pers,*).
nr_(margerit,pers,+).
nr_(margaret,pers,+).
nr_(marcial,pers,+).
nr_(marcel,pers,+).
nr_(maraton,subst,'10').
nr_(marakajb,subst,+).
nr_(maput,subst,+).
nr_(manĵusr,subst,+).
nr_(manĉestr,subst,+).
nr_(maniĥe,pers,+).
nr_(manitob,subst,+).
nr_(manipur,subst,+).
nr_(manil,subst,'10').
nr_(manik,subst,+).
nr_(manhejm,subst,+).
nr_(manhajm,subst,+).
nr_(manaŭs,subst,+).
nr_(manaŭ,subst,+).
nr_(manam,subst,+).
nr_(managv,subst,+).
nr_(mameluk,subst,+).
nr_(malt,subst,'10').
nr_(malkolm,pers,+).
nr_(malik,pers,+).
nr_(mali,subst,'10').
nr_(male,subst,+).
nr_(maldiv,subst,'10').
nr_(malavi,subst,'10').
nr_(malak,subst,+).
nr_(malajzi,subst,'10').
nr_(maksimilian,pers,+).
nr_(makintoŝ,subst,+).
nr_(makedoni,subst,+).
nr_(maka,subst,+).
nr_(majot,subst,'10').
nr_(majork,subst,+).
nr_(majn,subst,'10').
nr_(majkrosoft,subst,+).
nr_(majenc,subst,'10').
nr_(maj,subst,*).
nr_(mahomet,subst,+).
nr_(mahavir,subst,+).
nr_(maharaŝtr,subst,+).
nr_(mahajan,subst,+).
nr_(mahabarat,subst,+).
nr_(magreb,subst,+).
nr_(magelan,pers,+).
nr_(madrid,subst,'10').
nr_(madras,subst,+).
nr_(madjapradeŝ,subst,+).
nr_(madejr,subst,+).
nr_(madagaskar,subst,'10').
nr_(luzaci,subst,+).
nr_(luter,pers,*).
nr_(lusak,subst,+).
nr_(luksemburgi,subst,+).
nr_(luksemburg,subst,'10').
nr_(luk,pers,+).
nr_(luizian,subst,+).
nr_(luiz,pers,+).
nr_(ludovik,pers,*).
nr_(lucian,pers,+).
nr_(luci,pers,'10').
nr_(lucern,subst,'10').
nr_(luar,subst,+).
nr_(luand,subst,+).
nr_(loĵban,subst,+).
nr_(lozan,subst,+).
nr_(loven,subst,+).
nr_(losanĝeles,subst,'10').
nr_('los-Anĝeles',subst,+).
nr_(loren,subst,'10').
nr_(london,subst,*).
nr_(lome,subst,+).
nr_(loglan,subst,+).
nr_(ljubljan,subst,+).
nr_(liĥtenŝtejn,subst,'10').
nr_(litv,subst,+).
nr_(litovi,subst,+).
nr_(litomiŝl,subst,+).
nr_(lisbon,subst,'10').
nr_(lionel,pers,+).
nr_(lion,subst,+).
nr_(linuks,subst,+).
nr_(lingvafranka,subst,+).
nr_(linc,subst,+).
nr_(limoĝ,subst,+).
nr_(limburg,subst,+).
nr_(limb,subst,+).
nr_(lim,subst,+).
nr_(lilongv,subst,+).
nr_(lill,subst,'10').
nr_(lilit,subst,+).
nr_(liki,subst,+).
nr_(liguri,subst,+).
nr_(lieĝ,subst,+).
nr_(lier,subst,+).
nr_(lidi,subst,+).
nr_(lidi,pers,+).
nr_(librevil,subst,+).
nr_(libi,subst,'8').
nr_(liberi,subst,'8').
nr_(liban,subst,'8').
nr_(lete,subst,+).
nr_(let,subst,+).
nr_(lesot,subst,'10').
nr_(lesb,subst,'10').
nr_(lepsik,subst,+).
nr_(leopold,pers,+).
nr_(leonard,pers,+).
nr_(leningrad,subst,+).
nr_(lenin,subst,+).
nr_(len,subst,+).
nr_(leman,subst,+).
nr_(lelistad,subst,+).
nr_(lejbnic,subst,+).
nr_(lebeg,pers,+).
nr_(lebanon,subst,+).
nr_(leandr,pers,+).
nr_(le,pers,+).
nr_(laŭzan,subst,+).
nr_(laŭrenc,pers,+).
nr_(laŭrazi,subst,+).
nr_(laŭr,pers,+).
nr_(lazar,pers,+).
nr_(latvi,subst,+).
nr_(laton,subst,+).
nr_(latin,subst,'10').
nr_(lati,subst,+).
nr_(laptev,subst,+).
nr_(laplac,pers,+).
nr_(laos,subst,'10').
nr_(lanĝoŭ,subst,+).
nr_(laknaŭ,subst,+).
nr_(lajpcig,subst,+).
nr_(laj,pers,+).
nr_(lahor,subst,+).
nr_(lagos,subst,'10').
nr_(lafonten,pers,+).
nr_(laert,pers,+).
nr_(ladisla,pers,+).
nr_(labrador,subst,+).
nr_(labak,subst,+).
nr_('la-Valet',subst,+).
nr_(kvirin,subst,+).
nr_(kvinsland,subst,+).
nr_(kuvajt,subst,'10').
nr_(kuritib,subst,+).
nr_(kupidon,subst,+).
nr_(kunming,subst,+).
nr_(kulomb,pers,+).
nr_(kub,subst,'8').
nr_('kuala-Lumpur',subst,+).
nr_(ksitigarb,subst,+).
nr_(ksenofont,pers,+).
nr_(ksenofon,pers,+).
nr_(ksaver,pers,+).
nr_(kron,subst,+).
nr_(kroati,subst,+).
nr_(kriŝn,subst,+).
nr_(kristofor,pers,'10').
nr_(kristian,pers,+).
nr_(krist,subst,*).
nr_(krime,subst,'10').
nr_(krez,pers,+).
nr_(kret,subst,+).
nr_(krakov,subst,'10').
nr_(koŝi,subst,+).
nr_(kotdivuar,subst,+).
nr_(kostarik,subst,'8').
nr_(kosov,subst,'10').
nr_(kortrejk,subst,+).
nr_(korsik,subst,'10').
nr_(kornval,subst,'10').
nr_(korneli,pers,+).
nr_(korint,subst,+).
nr_(korfu,subst,+).
nr_(korei,subst,+).
nr_(kordob,subst,+).
nr_(koran,subst,*).
nr_(kopernik,pers,+).
nr_(kopenhag,subst,'10').
nr_(konstantinopol,subst,'10').
nr_(konstanten,pers,+).
nr_(konrad,pers,+).
nr_(kong,subst,'10').
nr_(konfuzi,subst,!).
nr_(konfuce,pers,+).
nr_(konektikut,subst,+).
nr_(konakri,subst,+).
nr_(komsomol,subst,+).
nr_(komor,subst,'10').
nr_(komod,subst,+).
nr_(komeni,subst,+).
nr_(kolĥid,subst,+).
nr_(kolĉid,subst,+).
nr_(kolumbi,subst,+).
nr_(kolumb,pers,'10').
nr_(koloĵvar,subst,+).
nr_(kolose,subst,+).
nr_(kolorad,subst,'10').
nr_(kolonj,subst,'10').
nr_(kolombi,subst,'10').
nr_(kolkat,subst,'10').
nr_(koblenc,subst,+).
nr_(kluĵ,subst,+).
nr_(kluĉevskaj,subst,+).
nr_(klement,pers,+).
nr_(klaŭdi,pers,+).
nr_(klaŭd,pers,+).
nr_(klar,pers,*).
nr_(kiŝinev,subst,+).
nr_(kit,subst,+).
nr_(kislev,subst,+).
nr_(kiron,subst,+).
nr_(kirk,subst,+).
nr_(kirilic,subst,+).
nr_(kiribat,subst,'10').
nr_(kirgizi,subst,+).
nr_(kiren,subst,+).
nr_(kipr,subst,'10').
nr_(kiot,subst,'10').
nr_(kinŝas,subst,'10').
nr_(kimri,subst,+).
nr_(kiliki,subst,+).
nr_(kijiv,subst,+).
nr_(kigali,subst,+).
nr_(kiev,subst,+).
nr_(keral,subst,+).
nr_(kepler,subst,+).
nr_(kentuki,subst,+).
nr_(kenj,subst,'10').
nr_(kenigsberg,subst,+).
nr_(kembriĝ,subst,'10').
nr_(kelvin,pers,+).
nr_(kebeki,subst,'10').
nr_(kebek,subst,'10').
nr_(kaŭn,subst,+).
nr_(kaŭlun,subst,+).
nr_(kaŭkazi,subst,'10').
nr_(kaŭkaz,subst,'10').
nr_(kaŝmir,subst,'10').
nr_(kazimir,pers,+).
nr_(kazaĥi,subst,+).
nr_(kazablank,subst,+).
nr_(katmandu,subst,'10').
nr_(katmand,subst,+).
nr_(katar,subst,'10').
nr_(kataluni,subst,+).
nr_(kastor,subst,+).
nr_(kaspi,subst,'10').
nr_(kasiope,subst,+).
nr_(kartveli,subst,+).
nr_(kartum,subst,+).
nr_(kartezi,pers,+).
nr_(kartag,subst,+).
nr_(karpat,subst,'10').
nr_(karon,subst,+).
nr_(karolin,subst,+).
nr_(karol,pers,+).
nr_(karnatak,subst,+).
nr_(karl,pers,+).
nr_(karinti,subst,+).
nr_(karibi,subst,+).
nr_(karib,subst,+).
nr_(karesm,subst,+).
nr_(karaĉi,subst,'10').
nr_(karakum,subst,+).
nr_(karakas,subst,+).
nr_(kara,subst,+).
nr_(kaprikorn,subst,+).
nr_(kapitoli,subst,+).
nr_(kapitol,subst,+).
nr_(kapadoki,subst,+).
nr_(kanton,subst,'10').
nr_(kanti,pers,+).
nr_(kantabri,subst,+).
nr_(kansas,subst,+).
nr_(kandahar,subst,+).
nr_(kanber,subst,+).
nr_(kanad,subst,'8').
nr_(kamĉatk,subst,+).
nr_(kampin,subst,+).
nr_(kampani,subst,+).
nr_(kampal,subst,+).
nr_(kamil,pers,+).
nr_(kameruni,subst,+).
nr_(kamerun,subst,'10').
nr_(kamboĝ,subst,'10').
nr_(kam,subst,+).
nr_(kalvin,pers,*).
nr_(kalvari,subst,+).
nr_(kaloĉaj,subst,+).
nr_(kalkut,subst,+).
nr_(kalips,subst,+).
nr_(kaliningrad,subst,+).
nr_(kalimantan,subst,+).
nr_(kaliforni,subst,'10').
nr_(kalez,subst,+).
nr_(kalabri,subst,+).
nr_(kair,subst,'10').
nr_(kabul,subst,+).
nr_(kaboverd,subst,'10').
nr_(kabe,pers,+).
nr_(kabal,subst,'1').
nr_(jutub,subst,+).
nr_(justinian,pers,+).
nr_(justen,pers,+).
nr_(jupiter,subst,+).
nr_(juni,subst,*).
nr_(junan,subst,+).
nr_(juli,subst,*).
nr_(juli,pers,'10').
nr_(jul,subst,+).
nr_(jukon,subst,+).
nr_(jugoslavi,subst,+).
nr_(jude,subst,+).
nr_(jozef,pers,*).
nr_(josu,pers,+).
nr_(josef,pers,+).
nr_(jork,subst,'10').
nr_(jordani,subst,'10').
nr_(jordan,subst,'10').
nr_(jomkipur,subst,+).
nr_(jokoham,subst,'10').
nr_(johanesburg,subst,+).
nr_(johan,pers,*).
nr_(joakim,pers,+).
nr_(jid,subst,+).
nr_(jesu,subst,'3').
nr_(jeruzalem,subst,+).
nr_(jerusalem,subst,'10').
nr_(jeriĥ,subst,+).
nr_(jenisej,subst,+).
nr_(jemen,subst,'10').
nr_(jekaterinburg,subst,+).
nr_(jehov,subst,+).
nr_(jazon,pers,+).
nr_(jav,subst,'10').
nr_(jav,subst,+).
nr_(jaund,subst,+).
nr_(jaroslav,pers,+).
nr_(japani,subst,+).
nr_(januar,subst,*).
nr_(jansen,subst,+).
nr_(jangzi,subst,+).
nr_(jamusukr,subst,+).
nr_(jamajk,subst,'10').
nr_(jama,subst,+).
nr_(jalt,subst,+).
nr_(jakobi,pers,+).
nr_(jakob,pers,+).
nr_(jaf,subst,+).
nr_(jadvig,pers,+).
nr_(izrael,subst,*).
nr_(izmir,subst,+).
nr_(izis,subst,+).
nr_(izidor,pers,+).
nr_(izid,subst,+).
nr_(izaak,pers,+).
nr_(ivan,pers,+).
nr_(iv,pers,+).
nr_(itali,subst,+).
nr_(istri,subst,+).
nr_(istanbul,subst,'10').
nr_(israel,subst,'9').
nr_(island,subst,'8').
nr_(islamabad,subst,+).
nr_(isel,subst,+).
nr_(isaak,pers,+).
nr_(irtiŝ,subst,+).
nr_(irland,subst,'8').
nr_(irene,pers,+).
nr_(iran,subst,'8').
nr_(irak,subst,'8').
nr_(iova,subst,+).
nr_(inĉon,subst,+).
nr_(inuktitut,subst,+).
nr_(interlingva,subst,+).
nr_(inocent,pers,+).
nr_(indus,subst,'10').
nr_(indr,subst,+).
nr_(indonezi,subst,'10').
nr_(indiana,subst,+).
nr_(ilz,pers,+).
nr_(iluminat,subst,+).
nr_(ilirik,subst,+).
nr_(iliri,subst,+).
nr_(ilion,subst,+).
nr_(ilinojs,subst,+).
nr_(iliad,subst,+).
nr_(ignac,pers,+).
nr_(idah,subst,+).
nr_(id,subst,+).
nr_(ibadism,subst,+).
nr_(ibadan,subst,+).
nr_(huston,subst,+).
nr_(husejn,pers,+).
nr_(hungari,subst,+).
nr_(humbert,pers,+).
nr_(hug,pers,+).
nr_(hudson,subst,+).
nr_(hubert,pers,+).
nr_(horus,subst,+).
nr_(horaci,pers,+).
nr_(honŝu,subst,'10').
nr_(honkong,subst,'10').
nr_(hongkong,subst,+).
nr_(hondur,subst,'10').
nr_(homer,subst,+).
nr_(holstini,subst,+).
nr_(holivud,subst,+).
nr_(holi,subst,+).
nr_(holand,subst,'10').
nr_(hokajd,subst,+).
nr_(hitler,subst,+).
nr_(hispaniol,subst,+).
nr_(hispani,subst,+).
nr_(hiroŝim,subst,'10').
nr_(hipolit,pers,+).
nr_(hipokrat,subst,+).
nr_(hindustan,subst,+).
nr_(hindukuŝ,subst,+).
nr_(hindi,subst,'10').
nr_(hinajan,subst,+).
nr_(himaĉalpradeŝ,subst,+).
nr_(himalaj,subst,'10').
nr_(hilel,subst,+).
nr_(hilbert,pers,+).
nr_(hieronim,pers,+).
nr_(heĝir,subst,+).
nr_(heziod,subst,+).
nr_(hevisid,pers,+).
nr_(herodot,pers,+).
nr_(herod,subst,+).
nr_(hermon,subst,+).
nr_(hermit,pers,+).
nr_(hermes,subst,+).
nr_(herman,pers,+).
nr_(hermagor,pers,+).
nr_(herkules,subst,+).
nr_(herkul,subst,+).
nr_(hercegovin,subst,'10').
nr_(herakl,subst,+).
nr_(her,subst,+).
nr_(henrik,pers,+).
nr_(henriet,pers,*).
nr_(henegovi,subst,+).
nr_(helsink,subst,'10').
nr_(helios,subst,+).
nr_(heli,subst,+).
nr_(helen,pers,+).
nr_(hektor,pers,+).
nr_(hekat,subst,+).
nr_(hefest,subst,+).
nr_(hefej,subst,+).
nr_(hedvig,pers,+).
nr_(havan,subst,'10').
nr_(havaj,subst,'10').
nr_(hasan,pers,+).
nr_(harold,pers,+).
nr_(harmon,subst,+).
nr_(harlem,subst,+).
nr_(harjan,subst,+).
nr_(harian,subst,+).
nr_(harc,subst,+).
nr_(harbin,subst,+).
nr_(harar,subst,+).
nr_(hanovr,subst,+).
nr_(hanover,subst,+).
nr_(hanoj,subst,'10').
nr_(hanibal,pers,+).
nr_(hangĝoŭ,subst,+).
nr_(hanafism,subst,+).
nr_(hamurab,pers,+).
nr_(hampŝir,subst,+).
nr_(hamlet,subst,+).
nr_(hamelen,subst,+).
nr_(hamburg,subst,'10').
nr_(haman,subst,+).
nr_(halovin,subst,+).
nr_(haloven,subst,+).
nr_(halifaks,subst,+).
nr_(halep,subst,+).
nr_(halaĥ,subst,+).
nr_(hajfong,subst,+).
nr_(hajderabad,subst,+).
nr_(haiti,subst,'10').
nr_(hagad,subst,+).
nr_(hag,subst,'10').
nr_(hadrian,pers,+).
nr_(hades,subst,+).
nr_(habsburg,subst,+).
nr_(gvine,subst,'8').
nr_(gvatemal,subst,'8').
nr_(gvajan,subst,+).
nr_(gvadelup,subst,'10').
nr_(gustav,pers,+).
nr_(guliver,subst,+).
nr_(gujan,subst,'10').
nr_(gugl,subst,+).
nr_(gronland,subst,'10').
nr_(groningen,subst,+).
nr_(groning,subst,+).
nr_(grizon,subst,'10').
nr_(greziljon,subst,+).
nr_(grenland,subst,+).
nr_(grenadin,subst,'10').
nr_(grenad,subst,'10').
nr_(greki,subst,+).
nr_(gregori,pers,'10').
nr_(gravet,subst,+).
nr_(gram,pers,+).
nr_(gotenburg,subst,'10').
nr_(gotam,pers,+).
nr_(gordi,subst,+).
nr_(gonzal,pers,+).
nr_(gontran,pers,+).
nr_(gondvan,subst,+).
nr_(gomor,subst,+).
nr_(goljat,subst,+).
nr_(golgot,subst,+).
nr_(golem,subst,+).
nr_(godfred,pers,+).
nr_(goa,subst,+).
nr_(glasgov,subst,+).
nr_(glagolic,subst,+).
nr_(giz,subst,+).
nr_(ginevr,subst,+).
nr_(gilgameŝ,subst,+).
nr_(gilbert,pers,+).
nr_(gibraltar,subst,+).
nr_(gervaz,pers,+).
nr_(gertrud,pers,+).
nr_(germani,subst,+).
nr_(gerard,pers,+).
nr_(georg,pers,*).
nr_(gent,subst,+).
nr_(gemar,subst,+).
nr_(gelderland,subst,+).
nr_(ge,subst,+).
nr_(gdinj,subst,+).
nr_(gdansk,subst,'10').
nr_(gaŭtam,pers,+).
nr_(gaŭs,pers,+).
nr_(gaza,subst,+).
nr_(gaston,pers,+).
nr_(gaspar,pers,+).
nr_(garon,subst,+).
nr_(ganimed,subst,+).
nr_(gang,subst,'10').
nr_(ganeŝ,subst,+).
nr_(gana,subst,'10').
nr_(gambi,subst,'10').
nr_(galilej,subst,+).
nr_(galile,subst,'10').
nr_(galici,subst,'10').
nr_(galez,pers,+).
nr_(galapag,subst,+).
nr_(gabriel,subst,+).
nr_(gabon,subst,'10').
nr_(gaberon,subst,+).
nr_(fuĝoŭ,subst,+).
nr_(fukuŝim,subst,+).
nr_(friul,subst,'10').
nr_(fritaŭn,subst,+).
nr_(frisi,subst,+).
nr_(frigi,subst,+).
nr_(freŭd,pers,+).
nr_(frederik,pers,+).
nr_(frankfurt,subst,'10').
nr_(francisk,pers,+).
nr_(franci,subst,+).
nr_(fortunat,pers,+).
nr_(fortalez,subst,'10').
nr_(formoz,subst,+).
nr_(fob,subst,+).
nr_(florid,subst,'10').
nr_(florian,pers,+).
nr_(florenc,subst,'10').
nr_(flevoland,subst,+).
nr_(flandri,subst,+).
nr_(fiĝi,subst,'10').
nr_(finni,subst,+).
nr_(finland,subst,+).
nr_(filipin,subst,'10').
nr_(filip,pers,+).
nr_(filibert,pers,+).
nr_(filadelfi,subst,'10').
nr_(figar,subst,+).
nr_(fero,subst,+).
nr_(fernand,pers,+).
nr_(ferdinand,pers,+).
nr_(fenŝu,subst,+).
nr_(fenoskandi,subst,+).
nr_(feniks,subst,+).
nr_(feniki,subst,+).
nr_(fenici,subst,+).
nr_(fengŝu,subst,+).
nr_(feliks,pers,+).
nr_(fejsbuk,subst,+).
nr_(februar,subst,*).
nr_(feb,subst,+).
nr_(faŭst,pers,+).
nr_(farenhejt,pers,+).
nr_(farad,subst,+).
nr_(fanar,subst,+).
nr_(fajsalabad,subst,+).
nr_(fabrici,pers,+).
nr_(fabian,pers,+).
nr_(fabi,pers,+).
nr_(eŭzebi,pers,+).
nr_(eŭzeb,pers,+).
nr_(eŭski,subst,+).
nr_(eŭrop,subst,*).
nr_(eŭrjal,subst,+).
nr_(eŭripid,pers,+).
nr_(eŭrial,subst,+).
nr_(eŭrazi,subst,+).
nr_(eŭler,pers,+).
nr_(eŭklid,pers,+).
nr_(eŭgen,pers,+).
nr_(eŭfrat,subst,'10').
nr_(eŭdoksi,pers,+).
nr_(eŭdoki,pers,+).
nr_(ezop,pers,+).
nr_(everest,subst,+).
nr_(evelin,pers,+).
nr_(etiopi,subst,+).
nr_(esĥil,pers,+).
nr_(estoni,subst,+).
nr_(esperanti,subst,+).
nr_(esperant,subst,*).
nr_(esfahan,subst,+).
nr_(eros,subst,+).
nr_(ernest,pers,*).
nr_(eritre,subst,'10').
nr_(erik,pers,+).
nr_(eridan,subst,+).
nr_(eri,subst,+).
nr_(erfurt,subst,+).
nr_(erevan,subst,+).
nr_(erasm,subst,+).
nr_(epiros,subst,+).
nr_(epir,subst,+).
nr_(epikur,pers,+).
nr_(epifani,subst,'2').
nr_(ene,pers,+).
nr_(emilian,pers,+).
nr_(emili,pers,*).
nr_(emil,pers,+).
nr_(emanuel,pers,+).
nr_(emaks,subst,+).
nr_(elize,subst,+).
nr_(elizabet,pers,*).
nr_(eliz,pers,+).
nr_(eli,pers,+).
nr_(eleonor,pers,+).
nr_(elefen,subst,+).
nr_(elb,subst,+).
nr_(elam,subst,'10').
nr_(ekvador,subst,'8').
nr_(ejnŝtejn,pers,+).
nr_(ejnstejn,pers,+).
nr_(ejfel,pers,+).
nr_(egipti,subst,+).
nr_(ege,subst,'10').
nr_(efez,subst,+).
nr_(efes,subst,+).
nr_(edvard,pers,+).
nr_(eduard,pers,+).
nr_(edmund,pers,+).
nr_(edip,subst,+).
nr_(edinburg,subst,'10').
nr_(edgar,pers,+).
nr_(eden,subst,'1').
nr_(edam,subst,+).
nr_(duŝanbe,subst,+).
nr_(duŝanb,subst,+).
nr_(duseldorf,subst,+).
nr_(durban,subst,+).
nr_(dunj,pers,+).
nr_(dublin,subst,'10').
nr_(dubaj,subst,+).
nr_(duala,subst,+).
nr_(dresden,subst,'10').
nr_(drent,subst,+).
nr_(dovr,subst,+).
nr_(dover,subst,+).
nr_(dorote,pers,+).
nr_(dopler,pers,+).
nr_(donguan,subst,+).
nr_(doneck,subst,+).
nr_(donald,pers,+).
nr_(don,subst,+).
nr_(dominik,subst,'10').
nr_(dominik,pers,+).
nr_(doha,subst,+).
nr_(doh,subst,+).
nr_(dodoma,subst,+).
nr_(dodom,subst,+).
nr_(dnepr,subst,+).
nr_(dirak,pers,+).
nr_(dioskur,subst,+).
nr_(dionizi,pers,+).
nr_(dioniz,subst,+).
nr_(diogen,subst,+).
nr_(dil,subst,+).
nr_(dieg,pers,+).
nr_(didaĥe,subst,+).
nr_(dian,pers,+).
nr_(detrojt,subst,+).
nr_(demokrit,pers,+).
nr_(demetri,pers,+).
nr_(deli,subst,+).
nr_(delhi,subst,'10').
nr_(delf,subst,+).
nr_(delavar,subst,+).
nr_(dekameron,subst,+).
nr_(dejm,subst,+).
nr_(dedekind,pers,+).
nr_(decembr,subst,*).
nr_(david,pers,+).
nr_(darvin,pers,+).
nr_(darmapad,subst,+).
nr_(darm,subst,+).
nr_(dari,pers,+).
nr_(daresalam,subst,+).
nr_(danub,subst,'10').
nr_(daniel,pers,+).
nr_(dani,subst,+).
nr_(dancig,subst,'10').
nr_(dana,subst,+).
nr_(damian,pers,+).
nr_(damask,subst,'10').
nr_(dalmati,subst,+).
nr_(dalas,subst,'10').
nr_(dakot,subst,+).
nr_(dakar,subst,+).
nr_(dak,subst,'10').
nr_(dagobert,pers,+).
nr_(ciril,pers,+).
nr_(ciren,subst,+).
nr_(circe,subst,+).
nr_(ciprian,pers,+).
nr_(cipr,subst,+).
nr_(cion,subst,+).
nr_(cinda,subst,+).
nr_(ciceron,pers,+).
nr_(cibel,subst,+).
nr_(cezare,subst,+).
nr_(cezar,pers,'10').
nr_(ceres,subst,+).
nr_(cerber,subst,+).
nr_(celsi,subst,+).
nr_(celesten,pers,+).
nr_(celebes,subst,+).
nr_(cejlon,subst,+).
nr_(cefe,subst,+).
nr_(buĥor,subst,+).
nr_(buĥar,subst,+).
nr_(butan,subst,'10').
nr_(burund,subst,'10').
nr_(burkin,subst,'10').
nr_(burgundi,subst,+).
nr_(burgonj,subst,+).
nr_(burbon,subst,+).
nr_(bulonj,subst,*).
nr_(bulgari,subst,+).
nr_(bule,pers,+).
nr_(bukareŝt,subst,'10').
nr_(budapeŝt,subst,'10').
nr_(bruĝ,subst,+).
nr_(brut,subst,+).
nr_(brusel,subst,'10').
nr_(brunsvik,subst,+).
nr_(brunn,subst,+).
nr_(brunej,subst,'10').
nr_(brun,pers,+).
nr_(brn,subst,+).
nr_(briti,subst,+).
nr_(bristol,subst,+).
nr_(brisban,subst,+).
nr_(brier,subst,+).
nr_(brest,subst,+).
nr_(bremen,subst,+).
nr_(brem,subst,+).
nr_(brazilj,subst,'10').
nr_(brazili,subst,+).
nr_(brazil,subst,'8').
nr_(brazavil,subst,'10').
nr_(bratislav,subst,'10').
nr_(brandenburg,subst,+).
nr_(brajton,subst,'10').
nr_(brajl,subst,+).
nr_(brabant,subst,+).
nr_(botni,subst,+).
nr_(boston,subst,'10').
nr_(bospor,subst,'10').
nr_(bosni,subst,+).
nr_(borne,subst,'10').
nr_(born,subst,+).
nr_(boris,pers,+).
nr_(borel,pers,+).
nr_(bordoz,subst,+).
nr_(bopomof,subst,+).
nr_(bopal,subst,+).
nr_(bonn,subst,+).
nr_(bonifac,pers,+).
nr_(bonaventur,pers,+).
nr_(bombaj,subst,+).
nr_(bomarŝe,subst,+).
nr_(bolonj,subst,'10').
nr_(bolivud,subst,+).
nr_(bolivi,subst,'8').
nr_(boleslav,pers,+).
nr_(bohemi,subst,+).
nr_(bogot,subst,'10').
nr_(bofort,pers,+).
nr_(boeci,subst,+).
nr_(bodidarm,subst,+).
nr_(bocvan,subst,'10').
nr_(blis,subst,+).
nr_(blez,subst,+).
nr_(blazi,pers,+).
nr_(bjelostok,subst,+).
nr_(bjalistok,subst,'10').
nr_(biŝkek,subst,+).
nr_(bizanti,subst,+).
nr_(bizanci,subst,+).
nr_(bizanc,subst,'10').
nr_(bitini,subst,+).
nr_(bisaŭ,subst,'10').
nr_(birm,subst,'8').
nr_(bilba,subst,+).
nr_(bihar,subst,+).
nr_(bibli,subst,'1').
nr_(betleĥem,subst,+).
nr_(besarabi,subst,+).
nr_(bertrand,pers,+).
nr_(bertil,pers,+).
nr_(bert,pers,*).
nr_(bernard,pers,+).
nr_(bern,subst,'10').
nr_(berlin,subst,*).
nr_(bering,pers,+).
nr_(bergen,subst,'10').
nr_(beovulf,subst,+).
nr_(beograd,subst,'10').
nr_(benjamen,pers,+).
nr_(benin,subst,'10').
nr_(bengalur,subst,+).
nr_(bengal,subst,+).
nr_(beneluks,subst,+).
nr_(benedikt,pers,+).
nr_(belorusi,subst,+).
nr_(beliz,subst,'10').
nr_(belgi,subst,+).
nr_(belfast,subst,'10').
nr_(belarusi,subst,+).
nr_('bel-Horizont',subst,+).
nr_(bejrut,subst,+).
nr_(behemot,subst,+).
nr_(beatric,pers,+).
nr_(baĥ,pers,+).
nr_(bazil,pers,+).
nr_(bazik,subst,+).
nr_(bazel,subst,+).
nr_(bavari,subst,+).
nr_(batu,pers,+).
nr_(bastjan,pers,+).
nr_(bastian,pers,+).
nr_(bartolome,pers,+).
nr_(barnab,pers,+).
nr_(barejn,subst,'10').
nr_(barcelon,subst,'10').
nr_(barbud,subst,'10').
nr_(barbaros,subst,+).
nr_(barbad,subst,'10').
nr_(barat,subst,'10').
nr_(bankok,subst,'10').
nr_(bangladeŝ,subst,'10').
nr_(bangkok,subst,+).
nr_(bang,subst,+).
nr_(bandung,subst,+).
nr_(banaĥ,pers,+).
nr_(bamak,subst,+).
nr_(baltik,subst,+).
nr_(baltazar,pers,+).
nr_(balkaŝ,subst,+).
nr_(balkani,subst,+).
nr_(balkan,subst,'10').
nr_(balduen,pers,+).
nr_(bakĥ,subst,+).
nr_(baku,subst,+).
nr_(baktri,subst,+).
nr_(bakk,subst,+).
nr_(bajkal,subst,+).
nr_(baham,subst,'10').
nr_(baha,subst,+).
nr_(bagdad,subst,'10').
nr_(bagavadgit,subst,+).
nr_(badaĥoz,subst,+).
nr_(babiloni,subst,+).
nr_(babilon,subst,'10').
nr_(babel,subst,+).
nr_(bab,subst,+).
nr_(aŭvernj,subst,+).
nr_(aŭstronezi,subst,'10').
nr_(aŭstri,subst,+).
nr_(aŭstrali,subst,'8').
nr_(aŭrelian,pers,+).
nr_(aŭgusten,pers,+).
nr_(aŭgust,subst,*).
nr_(aŭgust,pers,*).
nr_(aŭgsburg,subst,'10').
nr_(aŝok,subst,+).
nr_(aŝgabat,subst,+).
nr_(aĥil,pers,+).
nr_(aĥen,subst,+).
nr_(azov,subst,+).
nr_(azi,subst,'8').
nr_(azeri,subst,+).
nr_(azerbajĝan,subst,'10').
nr_(avogadr,pers,+).
nr_(avicen,pers,+).
nr_(avest,subst,+).
nr_(avejr,subst,+).
nr_(avalokiteŝvar,subst,+).
nr_(atomium,subst,+).
nr_(atlantik,subst,'8').
nr_(atlantid,subst,+).
nr_(atlant,subst,+).
nr_(atik,subst,+).
nr_(aten,subst,'10').
nr_(atalant,subst,+).
nr_(asuncion,subst,+).
nr_(asturi,subst,+).
nr_(astan,subst,+).
nr_(aski,subst,+).
nr_(asiri,subst,'10').
nr_(asen,subst,+).
nr_(asam,subst,+).
nr_(arĥimed,pers,+).
nr_(arunaĉalpradeŝ,subst,+).
nr_(artur,pers,+).
nr_(artemis,subst,+).
nr_(artemid,subst,+).
nr_(arnulf,pers,+).
nr_(arnold,pers,+).
nr_(arnhem,subst,+).
nr_(arn,subst,+).
nr_(armeni,subst,+).
nr_(arkt,subst,'9').
nr_(arkimed,pers,+).
nr_(arkansas,subst,+).
nr_(arizon,subst,+).
nr_(aristotel,pers,+).
nr_(aristofan,subst,+).
nr_(argus,subst,+).
nr_(argonaŭt,subst,+).
nr_(argentin,subst,'10').
nr_(ares,subst,+).
nr_(areopag,subst,+).
nr_(aral,subst,+).
nr_(aragon,subst,+).
nr_(april,subst,*).
nr_(apolon,subst,'10').
nr_(apol,subst,+).
nr_(api,subst,+).
nr_(anunciaci,subst,*).
nr_(antverpen,subst,'10').
nr_(antoni,pers,+).
nr_(antonen,pers,+).
nr_(anton,pers,*).
nr_(antioĥi,subst,+).
nr_(antil,subst,'10').
nr_(antigv,subst,'10').
nr_(antarkt,subst,'9').
nr_(antananariv,subst,+).
nr_(anselm,pers,+).
nr_(ann,pers,*).
nr_(ankar,subst,+).
nr_(angol,subst,'10').
nr_(angli,subst,+).
nr_(angkor,subst,+).
nr_(angar,subst,+).
nr_(andronik,pers,+).
nr_(andromed,subst,+).
nr_(andre,pers,+).
nr_(andrapradeŝ,subst,+).
nr_(andor,subst,'10').
nr_(andaluzi,subst,+).
nr_(and,subst,'10').
nr_(anatoli,subst,+).
nr_(anatol,pers,+).
nr_(anastazi,pers,+).
nr_(anabaz,subst,+).
nr_(amudarj,subst,+).
nr_(amsterdam,subst,'10').
nr_(amper,pers,+).
nr_(amitab,subst,+).
nr_(amir,pers,+).
nr_(amerik,subst,'8').
nr_(ambrozi,pers,+).
nr_(amazon,subst,'10').
nr_(aman,subst,+).
nr_(amade,pers,+).
nr_(alĝeri,subst,'8').
nr_(alĝer,subst,+).
nr_(alzac,subst,'10').
nr_(altaj,subst,+).
nr_(altair,subst,+).
nr_(almat,subst,+).
nr_(alfred,pers,+).
nr_(alfons,pers,+).
nr_(alep,subst,+).
nr_(aleksandri,subst,'10').
nr_(aleksandr,pers,*).
nr_(alchejmer,pers,+).
nr_(alchajmer,pers,+).
nr_(albert,subst,+).
nr_(albert,pers,+).
nr_(albani,subst,+).
nr_(alask,subst,'10').
nr_(alan,pers,+).
nr_(alah,subst,+).
nr_(alabam,subst,+).
nr_(akr,subst,+).
nr_(aken,subst,+).
nr_(akad,subst,'10').
nr_(ahmadism,subst,+).
nr_(ahmadabad,subst,+).
nr_(agni,subst,+).
nr_(afrodit,subst,+).
nr_(afrik,subst,'8').
nr_(advent,subst,'1').
nr_(adriatik,subst,'10').
nr_(adrian,pers,+).
nr_(adonis,subst,+).
nr_(adolf,pers,+).
nr_(adiĝ,subst,+).
nr_(adisabeb,subst,+).
nr_('adis-Abeb',subst,+).
nr_(aden,subst,'10').
nr_(adelajd,subst,'10').
nr_(adan,subst,+).
nr_(adam,pers,+).
nr_(adalbert,pers,+).
nr_(acor,subst,'10').
nr_(abuĝ,subst,+).
nr_(abudabi,subst,+).
nr_(abraks,subst,+).
nr_(abraham,pers,+).
nr_(abiĝan,subst,+).
nr_(abidarm,subst,+).
nr_(abel,pers,+).
nr_(abas,pers,+).
