evi('agitator',"agitatoro").
evi('algxeb',"alĝebro").
evi('alial',"alial").
evi('aliam',"aliam").
evi('aliel',"aliel").
evi('alies',"alies").
evi('aliom',"aliom").
evi('aliu',"aliu").
evi('alpinism',"alpinismo").
evi('apelac1',"apelaci").
evi('arhxiepiskop',"arĥiepiskopo").
evi('bidual',"bidualo").
evi('bilion',"biliono").
evi('ciklom',"ciklometria").
evi('cinism',"cinismo").
evi('difere1',"diferencii").
evi('digxit',"diĝita").
evi('fanatism',"fanatismo").
evi('federal',"federala").
evi('fekul',"fekulo").
evi('foliol',"foliolo").
evi('fosf',"fosfo").
evi('frizur',"frizuro").
evi('gangli1',"gangliono").
evi('humanitar',"humanitara").
evi('impulsiv',"impulsiva").
evi('insurekci',"insurekcii").
evi('insurgent',"insurgento").
evi('judais',"judaismo").
evi('kabin',"kabino").
evi('katarakt',"katarakto").
evi('kauxkazi',"Kaŭkazio").
evi('klerik1',"klerikala").
evi('koksal',"koksalgio").
evi('kolokv',"kolokvo").
evi('kompufon',"kompufono").
evi('konfuzi',"Konfuzio").
evi('konspiraci',"konspiracio").
evi('kortisol',"kortisolo").
evi('lapon',"lapono").
evi('legume1',"legumenaco").
evi('legume',"legumeno").
evi('letal',"letala").
evi('limet',"limeto").
evi('literator',"literatoro").
evi('maroder',"marodero").
evi('meksiki',"Meksikio").
evi('muzulman',"muzulmano").
evi('na',"na").
evi('negr',"negro").
evi('opak',"opaka").
evi('perfor',"perfori").
evi('piksel',"pikselo").
evi('pingvi',"pingvino").
evi('semino',"seminormo").
evi('sept1',"septo").
evi('spektator',"spektatoro").
evi('tehxnologi',"teĥnologio").
evi('tomograf',"tomografo").
evi('uk',"uk
").
evi('videoklip',"videoklipo").
