nr('Ŝverin',subst,'').
nr('Ŝopen',subst,'').
nr('Ŝlejer',subst,'').
nr('Ŝjian',subst,'').
nr('Ŝiva',subst,'').
nr('Ŝinkansen',subst,'').
nr('Ŝiller',subst,'*').
nr('Ŝil',subst,'').
nr('Ŝenĵen',subst,'').
nr('Ŝenjang',subst,'').
nr('Ŝengen',subst,'').
nr('Ŝem',subst,'').
nr('Ŝekspir',subst,'').
nr('Ŝari',subst,'').
nr('Ŝanhaj',subst,'').
nr('Ĵul',pers,'').
nr('Ĵub',subst,'').
nr('Ĵerzej',subst,'').
nr('Ĥiron',subst,'').
nr('Ĥi',subst,'').
nr('Ĥerone',subst,'').
nr('Ĥeops',subst,'').
nr('Ĥartum',subst,'').
nr('Ĥaron',subst,'').
nr('Ĥarkov',subst,'').
nr('Ĥaribd',subst,'').
nr('Ĥanuk',subst,'').
nr('Ĥam',subst,'').
nr('Ĝoĉi',subst,'').
nr('Ĝid',subst,'').
nr('Ĝibuti',subst,'').
nr('Ĝibut',subst,'').
nr('Ĝerald',pers,'').
nr('Ĝenov',subst,'').
nr('Ĝenev',subst,'').
nr('Ĝav',subst,'').
nr('Ĝarkand',subst,'').
nr('Ĝakart',subst,'').
nr('Ĝajpur',subst,'').
nr('Ĉongĉing',subst,'').
nr('Ĉitagong',subst,'').
nr('Ĉini',subst,'').
nr('Ĉingis',pers,'').
nr('Ĉili',subst,'').
nr('Ĉikag',subst,'').
nr('Ĉeĥoslovaki',subst,'').
nr('Ĉeĥi',subst,'').
nr('Ĉernobil',subst,'').
nr('Ĉengdu',subst,'').
nr('Ĉenaj',subst,'').
nr('Ĉatisgar',subst,'').
nr('Ĉangĝoŭ',subst,'').
nr('Ĉangĉun',subst,'').
nr('Ĉad',subst,'').
nr('Zurik',subst,'').
nr('Zimbabv',subst,'').
nr('Zib',subst,'').
nr('Zeŭs',subst,'').
nr('Zeland',subst,'').
nr('Zaratuŝtr',subst,'').
nr('Zamenhof',pers,'*').
nr('Zambi',subst,'').
nr('Zairi',subst,'').
nr('Zagreb',subst,'').
nr('Vurtemberg',subst,'').
nr('Vulgat',subst,'').
nr('Vuhan',subst,'').
nr('Volter',subst,'').
nr('Volt',subst,'').
nr('Volsung',subst,'').
nr('Volg',subst,'').
nr('Volfgang',pers,'').
nr('Volapuk',subst,'').
nr('Vodu',subst,'').
nr('Vladimir',pers,'').
nr('Vjetnami',subst,'').
nr('Vjentian',subst,'').
nr('Viŝnu',subst,'').
nr('Vizbaden',subst,'').
nr('Vitruvi',subst,'').
nr('Vit',subst,'').
nr('Viskonsin',subst,'').
nr('Virgini',subst,'').
nr('Vindoz',subst,'').
nr('Vindhuk',subst,'').
nr('Vincent',pers,'').
nr('Vinaj',subst,'').
nr('Viln',subst,'').
nr('Vilhelm',pers,'*').
nr('Viktori',subst,'').
nr('Viktor',pers,'').
nr('Vikipedi',subst,'').
nr('Vien',subst,'').
nr('Vezuvi',subst,'').
nr('Vezer',subst,'').
nr('Vestminstr',subst,'').
nr('Vestfali',subst,'').
nr('Vermont',subst,'').
nr('Vergili',pers,'').
nr('Venus',subst,'').
nr('Venezuel',subst,'8').
nr('Vener',subst,'').
nr('Veneci',subst,'').
nr('Vencesla',pers,'').
nr('Velington',subst,'').
nr('Vaŝington',subst,'*').
nr('Vaĝrajan',subst,'').
nr('Vatikan',subst,'').
nr('Vat',pers,'').
nr('Varsovi',subst,'*').
nr('Varingjen',subst,'').
nr('Vanuatu',subst,'').
nr('Valter',pers,'').
nr('Valoni',subst,'').
nr('Valet',subst,'').
nr('Valeri',pers,'').
nr('Valenten',pers,'').
nr('Valenci',subst,'').
nr('Valdorf',subst,'').
nr('Vajroĉan',subst,'').
nr('Vajoming',subst,'').
nr('Vajmar',subst,'').
nr('Vahabism',subst,'').
nr('Vagadugu',subst,'').
nr('Vaduz',subst,'').
nr('Uzbeki',subst,'').
nr('Utreĥt',subst,'').
nr('Utarpradeŝ',subst,'').
nr('Utarakand',subst,'').
nr('Utah',subst,'').
nr('Uson',subst,'9').
nr('Urumĉi',subst,'').
nr('Urugvaj',subst,'8').
nr('Uran',subst,'').
nr('Ural',subst,'').
nr('Uniks',subst,'').
nr('Unikod',subst,'').
nr('Unesk',subst,'').
nr('Ulanbator',subst,'').
nr('Ulamban',subst,'').
nr('Ukraini',subst,'').
nr('Ugand',subst,'').
nr('Tviter',subst,'').
nr('Tuval',subst,'').
nr('Turkmeni',subst,'').
nr('Turki',subst,'').
nr('Turingi',subst,'').
nr('Tunizi',subst,'8').
nr('Tuniz',subst,'').
nr('Tucidid',pers,'').
nr('Trondhejm',subst,'').
nr('Troj',subst,'').
nr('Tripur',subst,'').
nr('Tripol',subst,'').
nr('Tripitak',subst,'').
nr('Trinidad',subst,'').
nr('Trent',subst,'').
nr('Transilvani',subst,'').
nr('Toskani',subst,'').
nr('Toront',subst,'').
nr('Tora',subst,'').
nr('Tong',subst,'').
nr('Tomas',pers,'').
nr('Tokipon',subst,'').
nr('Toki',subst,'').
nr('Tokaj',subst,'').
nr('Togoland',subst,'').
nr('Tobi',pers,'').
nr('Tobag',subst,'').
nr('Tjanĝin',subst,'').
nr('Titikak',subst,'').
nr('Tirol',subst,'').
nr('Tiran',subst,'').
nr('Tinĉj',subst,'').
nr('Timote',pers,'').
nr('Timor',subst,'').
nr('Timbuktu',subst,'').
nr('Tigris',subst,'').
nr('Tiflis',subst,'').
nr('Tife',subst,'').
nr('Tician',subst,'').
nr('Tibet',subst,'').
nr('Tiberi',pers,'').
nr('Tiber',subst,'').
nr('Tet',subst,'').
nr('Teravad',subst,'').
nr('Teofil',pers,'').
nr('Teodor',pers,'*').
nr('Teobald',pers,'').
nr('Tenesi',subst,'').
nr('Telegram',subst,'').
nr('Telangan',subst,'').
nr('Teksas',subst,'').
nr('Teheran',subst,'').
nr('Tegucigalp',subst,'').
nr('Tegu',subst,'').
nr('Teb',subst,'').
nr('Taŝkent',subst,'').
nr('Taĝiki',subst,'').
nr('Tasmani',subst,'').
nr('Tars',subst,'').
nr('Tanzani',subst,'').
nr('Tantal',subst,'').
nr('Tamiz',subst,'').
nr('Talin',subst,'').
nr('Tales',subst,'').
nr('Tajpe',subst,'').
nr('Tahiti',subst,'').
nr('Tade',pers,'').
nr('Sĥeld',subst,'').
nr('Svisi',subst,'').
nr('Svedi',subst,'').
nr('Suĝoŭ',subst,'').
nr('Suv',subst,'').
nr('Surinam',subst,'').
nr('Surat',subst,'').
nr('Surabaj',subst,'').
nr('Suomi',subst,'').
nr('Suna',subst,'').
nr('Sumeri',subst,'').
nr('Sumatr',subst,'').
nr('Sulaves',subst,'').
nr('Sukot',subst,'').
nr('Suez',subst,'').
nr('Sudan',subst,'8').
nr('Stutgart',subst,'').
nr('Strasburg',subst,'').
nr('Strabon',subst,'').
nr('Stokholm',subst,'').
nr('Stiri',subst,'').
nr('Sten',subst,'').
nr('Stefan',pers,'*').
nr('Stanislav',pers,'').
nr('Srilank',subst,'').
nr('Spinoz',pers,'').
nr('Soveti',subst,'').
nr('Somali',subst,'').
nr('Solutre',subst,'').
nr('Sokrat',pers,'').
nr('Sofokl',pers,'').
nr('Sofi',pers,'*').
nr('Sofi',subst,'').
nr('Sloveni',subst,'').
nr('Slovaki',subst,'').
nr('Slavon',subst,'').
nr('Skoti',subst,'').
nr('Skopj',subst,'').
nr('Skiti',subst,'').
nr('Skeld',subst,'').
nr('Skandinavi',subst,'').
nr('Skajp',subst,'').
nr('Siĉŭan',subst,'').
nr('Siĉuan',subst,'').
nr('Sizif',subst,'').
nr('Sirius',subst,'').
nr('Siriak',subst,'').
nr('Siri',subst,'8').
nr('Sirdarj',subst,'').
nr('Sirakuz',subst,'').
nr('Singapur',subst,'').
nr('Simon',pers,'').
nr('Simeon',pers,'').
nr('Silvestr',pers,'').
nr('Silvan',pers,'').
nr('Silezi',subst,'').
nr('Sikim',subst,'').
nr('Sigmund',pers,'').
nr('Sigismund',pers,'').
nr('Sieraleon',subst,'').
nr('Sidnej',subst,'').
nr('Sicili',subst,'').
nr('Siberi',subst,'').
nr('Sevil',subst,'').
nr('Seul',subst,'').
nr('Sergi',pers,'').
nr('Serafen',pers,'').
nr('Septuagint',subst,'').
nr('Senek',subst,'').
nr('Senegal',subst,'').
nr('Selim',pers,'').
nr('Seborg',subst,'').
nr('Sebastian',pers,'').
nr('Scil',subst,'').
nr('Scientologi',subst,'').
nr('Saĥalen',subst,'').
nr('Savoj',subst,'').
nr('Saturn',subst,'').
nr('Saskaĉevan',subst,'').
nr('Sarajev',subst,'').
nr('Sar',subst,'').
nr('Santome',subst,'').
nr('Santiag',subst,'').
nr('Santeri',subst,'').
nr('Sanskrit',subst,'').
nr('Sansalvador',subst,'').
nr('Sanmarin',subst,'').
nr('Sana',subst,'').
nr('San-Paŭl',subst,'').
nr('Samos',subst,'').
nr('Samo',subst,'').
nr('Samir',subst,'').
nr('Samg',subst,'').
nr('Sambr',subst,'').
nr('Samarkand',subst,'').
nr('Samari',subst,'').
nr('Salvador',subst,'').
nr('Salomon',pers,'').
nr('Salomon',subst,'').
nr('Salafism',subst,'').
nr('Sajgon',subst,'').
nr('Sajan',subst,'').
nr('Sahel',subst,'').
nr('Sahar',subst,'').
nr('Sadam',pers,'').
nr('Sad',subst,'').
nr('Ruso',subst,'').
nr('Rusi',subst,'').
nr('Rurik',pers,'').
nr('Rumani',subst,'').
nr('Rudolf',pers,'').
nr('Rubikon',subst,'').
nr('Ruand',subst,'').
nr('Roĝer',pers,'').
nr('Roterdam',subst,'').
nr('Romi',subst,'').
nr('Rome',pers,'').
nr('Rom',subst,'').
nr('Roland',pers,'').
nr('Rogaci',subst,'').
nr('Rodrig',pers,'').
nr('Rodos',subst,'').
nr('Rodolf',pers,'').
nr('Rodezi',subst,'').
nr('Rodan',subst,'').
nr('Robert',pers,'').
nr('Rio-de-Ĵanejr',subst,'').
nr('Riman',pers,'').
nr('Rikard',pers,'').
nr('Rig',subst,'').
nr('Riad',subst,'').
nr('Renat',pers,'').
nr('Remington',subst,'').
nr('Rejnland-Palatinat',subst,'').
nr('Rejn',subst,'').
nr('Rejkjavik',subst,'').
nr('Rejki',subst,'').
nr('Regensburg',subst,'').
nr('Reformaci',subst,'1').
nr('Recif',subst,'').
nr('Raŭm',subst,'').
nr('Raŝid',subst,'').
nr('Raĥel',pers,'').
nr('Raĝastan',subst,'').
nr('Rangun',subst,'').
nr('Ramajan',subst,'').
nr('Rajmund',pers,'').
nr('Rafael',pers,'').
nr('Rabat',subst,'').
nr('Puŝkin',subst,'').
nr('Purim',subst,'').
nr('Pune',subst,'').
nr('Ptoleme',pers,'').
nr('Psiĥ',subst,'').
nr('Prusi',subst,'').
nr('Provenc',subst,'').
nr('Promete',subst,'').
nr('Principe',subst,'').
nr('Pretori',subst,'').
nr('Prag',subst,'').
nr('Pozidon',subst,'').
nr('Portvila',subst,'').
nr('Portugali',subst,'').
nr('Portospen',subst,'').
nr('Portoprinc',subst,'').
nr('Portmoresb',subst,'').
nr('Porfiri',pers,'').
nr('Ponti',pers,'').
nr('Pompej',subst,'').
nr('Pomeri',subst,'').
nr('Poluks',subst,'').
nr('Polinezi',subst,'8').
nr('Poli',subst,'').
nr('Pocdam',subst,'').
nr('Pnompen',subst,'').
nr('Pluton',subst,'').
nr('Plut',subst,'').
nr('Plini',pers,'').
nr('Plejad',subst,'').
nr('Plaŭt',pers,'').
nr('Platon',pers,'').
nr('Pjonjang',subst,'').
nr('Pjanĝ',subst,'').
nr('Pitagor',subst,'').
nr('Pinokj',subst,'').
nr('Pinjin',subst,'').
nr('Pilat',subst,'').
nr('Picburg',subst,'').
nr('Peŝavar',subst,'').
nr('Petr',pers,'*').
nr('Peterburg',subst,'').
nr('Peru',subst,'8').
nr('Pert',subst,'').
nr('Perse',subst,'').
nr('Pentekost',subst,'*').
nr('Pentateŭk',subst,'').
nr('Pensilvani',subst,'').
nr('Pekin',subst,'').
nr('Pegaz',subst,'').
nr('Paŭl',pers,'*').
nr('Patrik',pers,'').
nr('Pasteŭr',pers,'').
nr('Paskal',pers,'').
nr('Pask',subst,'*').
nr('Pasion',subst,'').
nr('Parkinson',pers,'').
nr('Park',subst,'').
nr('Pariz',subst,'*').
nr('Parc',subst,'').
nr('Paramarib',subst,'').
nr('Paralimpik',subst,'').
nr('Paraklet',subst,'').
nr('Paragvaj',subst,'8').
nr('Papu',subst,'').
nr('Panĝab',subst,'').
nr('Pange',subst,'').
nr('Panam',subst,'8').
nr('Pali',subst,'').
nr('Palestin',subst,'').
nr('Palerm',subst,'').
nr('Palaŭ',subst,'').
nr('Pakistan',subst,'8').
nr('Pacifik',subst,'8').
nr('Pabl',pers,'').
nr('Oĥock',subst,'').
nr('Oziris',subst,'').
nr('Ovidi',pers,'').
nr('Overisel',subst,'').
nr('Otoman',subst,'').
nr('Otav',subst,'').
nr('Osvald',pers,'').
nr('Ostend',subst,'').
nr('Osman',pers,'').
nr('Osl',subst,'').
nr('Oskar',pers,'').
nr('Oskar',subst,'').
nr('Osak',subst,'').
nr('Orlean',subst,'').
nr('Ork',subst,'').
nr('Oris',subst,'').
nr('Orion',subst,'').
nr('Orfe',subst,'').
nr('Oregon',subst,'').
nr('Oomot',subst,'').
nr('Onufri',pers,'').
nr('Ontari',subst,'').
nr('Onesim',pers,'').
nr('Omdurman',subst,'').
nr('Omar',pers,'').
nr('Oman',subst,'').
nr('Om',pers,'').
nr('Oliver',pers,'').
nr('Olimpik',subst,'').
nr('Olimp',subst,'').
nr('Olav',pers,'').
nr('Oksford',subst,'').
nr('Oklahom',subst,'').
nr('Okcidental',subst,'').
nr('Oka',subst,'').
nr('Ohi',subst,'').
nr('Odr',subst,'').
nr('Odiŝ',subst,'').
nr('Odise',pers,'').
nr('Oceani',subst,'').
nr('Ob',subst,'').
nr('Nĝamen',subst,'').
nr('Nursultan',subst,'').
nr('Nurenberg',subst,'').
nr('Nunavut',subst,'').
nr('Nukualof',subst,'').
nr('Nuakŝot',subst,'').
nr('Noŭruz',subst,'').
nr('Novosibirsk',subst,'').
nr('Novial',subst,'').
nr('Novgorod',subst,'').
nr('Norvegi',subst,'').
nr('Noaĥ',pers,'').
nr('Niĝer',subst,'').
nr('Niĉiren',subst,'').
nr('Nis',subst,'').
nr('Nirvan',subst,'').
nr('Ningb',subst,'').
nr('Nimeg',subst,'').
nr('Nil',subst,'').
nr('Nikozi',subst,'').
nr('Nikola',pers,'*').
nr('Nikodem',pers,'*').
nr('Nikaragv',subst,'8').
nr('Nik',subst,'').
nr('Nic',subst,'').
nr('Nibelung',subst,'').
nr('Niame',subst,'').
nr('Niagar',subst,'').
nr('Neŭŝatel',subst,'').
nr('Neŭton',pers,'').
nr('Nevad',subst,'').
nr('Nestor',pers,'').
nr('Neptun',subst,'').
nr('Nepjid',subst,'').
nr('Neper',subst,'').
nr('Nepal',subst,'').
nr('Nekar',subst,'').
nr('Nederland',subst,'8').
nr('Nebrask',subst,'').
nr('Naur',subst,'').
nr('Nasaŭ',subst,'').
nr('Narcis',pers,'').
nr('Napoleon',pers,'').
nr('Napol',subst,'').
nr('Nanĉan',subst,'').
nr('Nant',subst,'').
nr('Nankin',subst,'').
nr('Naning',subst,'').
nr('Namur',subst,'').
nr('Namibi',subst,'').
nr('Najrobi',subst,'').
nr('Nagoj',subst,'').
nr('Nagasak',subst,'').
nr('Muzaik',subst,'').
nr('Munken',subst,'').
nr('Mumbaj',subst,'').
nr('Multan',subst,'').
nr('Muhamad',pers,'').
nr('Mozel',subst,'').
nr('Mozart',pers,'').
nr('Mozambik',subst,'').
nr('Moz',subst,'').
nr('Moskv',subst,'').
nr('Mose',subst,'').
nr('Mors',subst,'').
nr('Morfe',subst,'').
nr('Montreal',subst,'').
nr('Montevide',subst,'').
nr('Montenegr',subst,'').
nr('Montekarl',subst,'').
nr('Montan',subst,'').
nr('Monrovi',subst,'').
nr('Mongoli',subst,'').
nr('Monak',subst,'').
nr('Moluk',subst,'').
nr('Molier',pers,'').
nr('Moldavi',subst,'').
nr('Mogadiŝ',subst,'').
nr('Mjanma',subst,'').
nr('Miŝn',subst,'').
nr('Miĥael',pers,'*').
nr('Miĉigan',subst,'').
nr('Mizoram',subst,'').
nr('Misuri',subst,'').
nr('Misur',subst,'').
nr('Misisipi',subst,'').
nr('Misisip',subst,'').
nr('Mirz',pers,'').
nr('Minsk',subst,'').
nr('Minotaŭr',subst,'').
nr('Minesot',subst,'').
nr('Milan',subst,'').
nr('Mikrosoft',subst,'').
nr('Mikronezi',subst,'').
nr('Midelburg',subst,'').
nr('Midas',subst,'').
nr('Meĥlen',subst,'').
nr('Mezopotami',subst,'').
nr('Metodi',pers,'').
nr('Merkur',subst,'').
nr('Mendelev',pers,'').
nr('Mence',subst,'').
nr('Memfis',subst,'').
nr('Melburn',subst,'').
nr('Meksik',subst,'8').
nr('Mekong',subst,'').
nr('Meklenburg',subst,'').
nr('Mekk',subst,'').
nr('Megalaj',subst,'').
nr('Mediĉ',subst,'').
nr('Mediterane',subst,'8').
nr('Medi',subst,'').
nr('Medeĝin',subst,'').
nr('Mede',subst,'').
nr('Medan',subst,'').
nr('Mec',subst,'').
nr('Maŭric',pers,'').
nr('Maŝhad',subst,'').
nr('Maĥ',subst,'').
nr('Mate',pers,'').
nr('Mastriĥt',subst,'').
nr('Maskat',subst,'').
nr('Maseru',subst,'').
nr('Masaĉusec',subst,'').
nr('Marŝal',subst,'').
nr('Marten',pers,'').
nr('Marsejl',subst,'').
nr('Mars',subst,'').
nr('Marok',subst,'8').
nr('Marks',pers,'').
nr('Mark',pers,'').
nr('Mariland',subst,'').
nr('Mari',pers,'*').
nr('Margaret',pers,'').
nr('Marcial',pers,'').
nr('Marcel',pers,'').
nr('Marakajb',subst,'').
nr('Maput',subst,'').
nr('Manĵusr',subst,'').
nr('Maniĥe',pers,'').
nr('Manitob',subst,'').
nr('Manipur',subst,'').
nr('Manil',subst,'').
nr('Manik',subst,'').
nr('Manhejm',subst,'').
nr('Manaŭs',subst,'').
nr('Manam',subst,'').
nr('Managv',subst,'').
nr('Mameluk',subst,'').
nr('Malt',subst,'').
nr('Malkolm',pers,'').
nr('Malik',pers,'').
nr('Male',subst,'').
nr('Malavi',subst,'').
nr('Malajzi',subst,'').
nr('Maksimilian',pers,'').
nr('Makintoŝ',subst,'').
nr('Makedoni',subst,'').
nr('Maka',subst,'').
nr('Majork',subst,'').
nr('Majn',subst,'').
nr('Majenc',subst,'').
nr('Mahomet',subst,'').
nr('Mahavir',subst,'').
nr('Maharaŝtr',subst,'').
nr('Mahajan',subst,'').
nr('Mahabarat',subst,'').
nr('Magreb',subst,'').
nr('Madrid',subst,'').
nr('Madjapradeŝ',subst,'').
nr('Madejr',subst,'').
nr('Madagaskar',subst,'').
nr('Luzaci',subst,'').
nr('Luter',pers,'*').
nr('Lusak',subst,'').
nr('Luksemburgi',subst,'').
nr('Luksemburg',subst,'').
nr('Luk',pers,'').
nr('Luizian',subst,'').
nr('Luiz',pers,'').
nr('Ludovik',pers,'*').
nr('Lucian',pers,'').
nr('Luar',subst,'').
nr('Luand',subst,'').
nr('Loĵban',subst,'').
nr('Loven',subst,'').
nr('Losanĝeles',subst,'').
nr('Loren',subst,'').
nr('London',subst,'*').
nr('Lome',subst,'').
nr('Loglan',subst,'').
nr('Ljubljan',subst,'').
nr('Liĥtenŝtejn',subst,'').
nr('Litv',subst,'').
nr('Litovi',subst,'').
nr('Litomiŝl',subst,'').
nr('Lisbon',subst,'').
nr('Lionel',pers,'').
nr('Lion',subst,'').
nr('Linuks',subst,'').
nr('Lingvafranka',subst,'').
nr('Linc',subst,'').
nr('Limburg',subst,'').
nr('Lim',subst,'').
nr('Lilit',subst,'').
nr('Liguri',subst,'').
nr('Lieĝ',subst,'').
nr('Lier',subst,'').
nr('Librevil',subst,'').
nr('Libi',subst,'8').
nr('Liberi',subst,'8').
nr('Liban',subst,'8').
nr('Lesot',subst,'').
nr('Lesb',subst,'').
nr('Lepsik',subst,'').
nr('Leopold',pers,'').
nr('Leonard',pers,'').
nr('Leningrad',subst,'').
nr('Len',subst,'').
nr('Lelistad',subst,'').
nr('Lejbnic',subst,'').
nr('Lebeg',pers,'').
nr('Lebanon',subst,'').
nr('Leandr',pers,'').
nr('Laŭrenc',pers,'').
nr('Laŭrazi',subst,'').
nr('Laŭr',pers,'').
nr('Lazar',pers,'').
nr('Latvi',subst,'').
nr('Latin',subst,'').
nr('Lati',subst,'').
nr('Laptev',subst,'').
nr('Laplac',pers,'').
nr('Laos',subst,'').
nr('Lanĝoŭ',subst,'').
nr('Laknaŭ',subst,'').
nr('Lahor',subst,'').
nr('Lagos',subst,'').
nr('Laert',pers,'').
nr('Ladisla',pers,'').
nr('Labrador',subst,'').
nr('Kvirin',subst,'').
nr('Kuvajt',subst,'').
nr('Kuritib',subst,'').
nr('Kupidon',subst,'').
nr('Kunming',subst,'').
nr('Kulomb',pers,'').
nr('Kub',subst,'8').
nr('Kuala-Lumpur',subst,'').
nr('Ksitigarb',subst,'').
nr('Ksenofon',pers,'').
nr('Ksaver',pers,'').
nr('Kron',subst,'').
nr('Kroati',subst,'').
nr('Kriŝn',subst,'').
nr('Kristofor',pers,'').
nr('Kristian',pers,'').
nr('Krist',subst,'*').
nr('Krime',subst,'').
nr('Kret',subst,'').
nr('Koŝi',subst,'').
nr('Kotdivuar',subst,'').
nr('Kostarik',subst,'8').
nr('Kosov',subst,'').
nr('Kortrejk',subst,'').
nr('Korneli',pers,'').
nr('Korfu',subst,'').
nr('Korei',subst,'').
nr('Kordob',subst,'').
nr('Koran',subst,'*').
nr('Kopernik',pers,'').
nr('Kopenhag',subst,'').
nr('Konstantinopol',subst,'').
nr('Konstanten',pers,'').
nr('Konrad',pers,'').
nr('Kong',subst,'').
nr('Konfuce',pers,'').
nr('Konektikut',subst,'').
nr('Konakri',subst,'').
nr('Komsomol',subst,'').
nr('Komod',subst,'').
nr('Komeni',subst,'').
nr('Kolĥid',subst,'').
nr('Kolumbi',subst,'').
nr('Kolumb',pers,'').
nr('Kolose',subst,'').
nr('Kolorad',subst,'').
nr('Kolonj',subst,'').
nr('Kolombi',subst,'').
nr('Kolkat',subst,'').
nr('Kluĵ',subst,'').
nr('Kluĉevskaj',subst,'').
nr('Klement',pers,'').
nr('Klaŭdi',pers,'').
nr('Klar',pers,'*').
nr('Kiŝinev',subst,'').
nr('Kit',subst,'').
nr('Kiribat',subst,'').
nr('Kirgizi',subst,'').
nr('Kipr',subst,'').
nr('Kiot',subst,'').
nr('Kinŝas',subst,'').
nr('Kimri',subst,'').
nr('Kiliki',subst,'').
nr('Kigali',subst,'').
nr('Kiev',subst,'').
nr('Keral',subst,'').
nr('Kepler',subst,'').
nr('Kentuki',subst,'').
nr('Kenj',subst,'').
nr('Kembriĝ',subst,'').
nr('Kelvin',pers,'').
nr('Kebeki',subst,'').
nr('Kebek',subst,'').
nr('Kaŭkaz',subst,'').
nr('Kaŝmir',subst,'').
nr('Kazimir',pers,'').
nr('Kazaĥi',subst,'').
nr('Kazablank',subst,'').
nr('Katmand',subst,'').
nr('Katar',subst,'').
nr('Kataluni',subst,'').
nr('Kastor',subst,'').
nr('Kaspi',subst,'').
nr('Kasiope',subst,'').
nr('Kartveli',subst,'').
nr('Kartezi',pers,'').
nr('Karolin',subst,'').
nr('Karol',pers,'').
nr('Karnatak',subst,'').
nr('Karloreĝ',subst,'').
nr('Karl',subst,'').
nr('Karinti',subst,'').
nr('Karib',subst,'').
nr('Karesm',subst,'').
nr('Karaĉi',subst,'').
nr('Karakas',subst,'').
nr('Kara',subst,'').
nr('Kaprikorn',subst,'').
nr('Kapitol',subst,'').
nr('Kapadoki',subst,'').
nr('Kanton',subst,'').
nr('Kantabri',subst,'').
nr('Kansas',subst,'').
nr('Kanber',subst,'').
nr('Kanad',subst,'8').
nr('Kamĉatk',subst,'').
nr('Kampin',subst,'').
nr('Kampani',subst,'').
nr('Kampal',subst,'').
nr('Kamil',pers,'').
nr('Kameruni',subst,'').
nr('Kamerun',subst,'').
nr('Kamboĝ',subst,'').
nr('Kam',subst,'').
nr('Kalvin',pers,'*').
nr('Kalvari',subst,'').
nr('Kaloĉaj',subst,'').
nr('Kaliningrad',subst,'').
nr('Kaliforni',subst,'').
nr('Kalez',subst,'').
nr('Kalabri',subst,'').
nr('Kair',subst,'').
nr('Kabul',subst,'').
nr('Kaboverd',subst,'').
nr('Kabe',pers,'').
nr('Kabal',subst,'1').
nr('Jutub',subst,'').
nr('Justinian',pers,'').
nr('Justen',pers,'').
nr('Jupiter',subst,'').
nr('Juli',pers,'').
nr('Jul',subst,'').
nr('Jugoslavi',subst,'').
nr('Jude',subst,'').
nr('Jozef',pers,'*').
nr('Jork',subst,'*').
nr('Jordani',subst,'').
nr('Jordan',subst,'').
nr('Jomkipur',subst,'').
nr('Jokoham',subst,'').
nr('Johanesburg',subst,'').
nr('Johan',pers,'*').
nr('Joakim',pers,'').
nr('Jesu',subst,'3').
nr('Jerusalem',subst,'').
nr('Jeriĥ',subst,'').
nr('Jenisej',subst,'').
nr('Jemen',subst,'').
nr('Jehov',subst,'').
nr('Jazon',pers,'').
nr('Jav',subst,'').
nr('Jaund',subst,'').
nr('Jaroslav',pers,'').
nr('Japani',subst,'').
nr('Jansen',subst,'').
nr('Jangzi',subst,'').
nr('Jamusukr',subst,'').
nr('Jamajk',subst,'').
nr('Jama',subst,'').
nr('Jakobi',pers,'').
nr('Jakob',pers,'').
nr('Izrael',subst,'*').
nr('Izmir',subst,'').
nr('Izis',subst,'').
nr('Izidor',pers,'').
nr('Iv',pers,'').
nr('Itali',subst,'').
nr('Istanbul',subst,'').
nr('Israel',subst,'9').
nr('Island',subst,'8').
nr('Islamabad',subst,'').
nr('Isel',subst,'').
nr('Isaak',pers,'').
nr('Irtiŝ',subst,'').
nr('Irland',subst,'8').
nr('Irene',pers,'').
nr('Iran',subst,'8').
nr('Irak',subst,'8').
nr('Iova',subst,'').
nr('Inĉon',subst,'').
nr('Inuktitut',subst,'').
nr('Interlingva',subst,'').
nr('Inocent',pers,'').
nr('Indus',subst,'').
nr('Indr',subst,'').
nr('Indiana',subst,'').
nr('Iluminat',subst,'').
nr('Ilinojs',subst,'').
nr('Iliad',subst,'').
nr('Ignac',pers,'').
nr('Idah',subst,'').
nr('Id',subst,'').
nr('Ibadan',subst,'').
nr('Husejn',pers,'').
nr('Hungari',subst,'').
nr('Humbert',pers,'').
nr('Hug',pers,'').
nr('Hudson',subst,'').
nr('Hubert',pers,'').
nr('Horus',subst,'').
nr('Horaci',pers,'').
nr('Honkong',subst,'').
nr('Homer',subst,'').
nr('Holstini',subst,'').
nr('Holand',subst,'').
nr('Hokajd',subst,'').
nr('Hispani',subst,'').
nr('Hiroŝim',subst,'').
nr('Hipolit',pers,'').
nr('Hipokrat',subst,'').
nr('Hindustan',subst,'').
nr('Hindukuŝ',subst,'').
nr('Hinajan',subst,'').
nr('Himaĉalpradeŝ',subst,'').
nr('Himalaj',subst,'').
nr('Hilel',subst,'').
nr('Hilbert',pers,'').
nr('Hieronim',pers,'').
nr('Heĝir',subst,'').
nr('Heziod',subst,'').
nr('Hevisid',pers,'').
nr('Herodot',subst,'').
nr('Herod',subst,'').
nr('Hermit',pers,'').
nr('Hermes',subst,'').
nr('Herman',pers,'').
nr('Herkul',pers,'').
nr('Hercegovin',subst,'').
nr('Herakl',subst,'').
nr('Henrik',pers,'').
nr('Henriet',pers,'*').
nr('Henegovi',subst,'').
nr('Helsink',subst,'').
nr('Helen',pers,'').
nr('Hektor',pers,'').
nr('Hefej',subst,'').
nr('Havan',subst,'').
nr('Havaj',subst,'').
nr('Hasan',pers,'').
nr('Harold',pers,'').
nr('Harlem',subst,'').
nr('Harian',subst,'').
nr('Harbin',subst,'').
nr('Harar',subst,'').
nr('Hanovr',subst,'').
nr('Hanoj',subst,'').
nr('Hanibal',pers,'').
nr('Hangĝoŭ',subst,'').
nr('Hanafism',subst,'').
nr('Hamurab',pers,'').
nr('Hampŝir',subst,'').
nr('Hamlet',subst,'').
nr('Hamburg',subst,'').
nr('Haman',subst,'').
nr('Haloven',subst,'').
nr('Halep',subst,'').
nr('Hajfong',subst,'').
nr('Hajderabad',subst,'').
nr('Haiti',subst,'').
nr('Hagad',subst,'').
nr('Hag',subst,'').
nr('Hades',subst,'').
nr('Gvine',subst,'8').
nr('Gvatemal',subst,'8').
nr('Guĝarat',subst,'').
nr('Gustav',pers,'').
nr('Gujan',subst,'').
nr('Gugl',subst,'').
nr('Gronland',subst,'').
nr('Groning',subst,'').
nr('Greziljon',subst,'').
nr('Grenad',subst,'').
nr('Greki',subst,'').
nr('Gregori',pers,'').
nr('Gravet',subst,'').
nr('Gotam',pers,'').
nr('Gonzal',pers,'').
nr('Gontran',pers,'').
nr('Gondvan',subst,'').
nr('Golgot',subst,'').
nr('Godfred',pers,'').
nr('Goa',subst,'').
nr('Glasgov',subst,'').
nr('Glagolic',subst,'').
nr('Giz',subst,'').
nr('Ginevr',subst,'').
nr('Gilgameŝ',subst,'').
nr('Gilbert',pers,'').
nr('Gervaz',pers,'').
nr('Germani',subst,'').
nr('Gerard',pers,'').
nr('Georg',pers,'*').
nr('Gent',subst,'').
nr('Gemar',subst,'').
nr('Gelderland',subst,'').
nr('Ge',subst,'').
nr('Gdinj',subst,'').
nr('Gdansk',subst,'').
nr('Gaŭs',pers,'').
nr('Gaston',pers,'').
nr('Gaspar',pers,'').
nr('Gana',subst,'').
nr('Gambi',subst,'').
nr('Galilej',subst,'').
nr('Galile',subst,'').
nr('Galez',pers,'').
nr('Gabriel',subst,'').
nr('Gabon',subst,'').
nr('Gaberon',subst,'').
nr('Fuĝoŭ',subst,'').
nr('Fritaŭn',subst,'').
nr('Frisi',subst,'').
nr('Freŭd',pers,'').
nr('Frederik',pers,'').
nr('Frankfurt',subst,'').
nr('Francisk',pers,'').
nr('Franci',subst,'').
nr('Fortunat',pers,'').
nr('Fortalez',subst,'').
nr('Fob',subst,'').
nr('Florid',subst,'').
nr('Florian',pers,'').
nr('Florenc',subst,'').
nr('Flevoland',subst,'').
nr('Flandri',subst,'').
nr('Fiĝi',subst,'').
nr('Finni',subst,'').
nr('Finland',subst,'').
nr('Filipin',subst,'').
nr('Filip',pers,'').
nr('Filibert',pers,'').
nr('Filadelfi',subst,'').
nr('Figar',subst,'').
nr('Fernand',pers,'').
nr('Ferdinand',pers,'').
nr('Fenoskandi',subst,'').
nr('Feniks',subst,'').
nr('Fenici',subst,'').
nr('Feliks',pers,'').
nr('Fejsbuk',subst,'').
nr('Farenhejt',pers,'').
nr('Farad',subst,'').
nr('Fanar',subst,'').
nr('Fajsalabad',subst,'').
nr('Fabrici',pers,'').
nr('Fabian',pers,'').
nr('Fabi',pers,'').
nr('Eŭzebi',pers,'').
nr('Eŭski',subst,'').
nr('Eŭrop',subst,'*').
nr('Eŭrjal',subst,'').
nr('Eŭripid',pers,'').
nr('Eŭrazi',subst,'').
nr('Eŭler',pers,'').
nr('Eŭklid',pers,'').
nr('Eŭgen',pers,'').
nr('Eŭfrat',subst,'').
nr('Ezop',pers,'').
nr('Everest',subst,'').
nr('Evelin',pers,'').
nr('Etiopi',subst,'').
nr('Esĥil',pers,'').
nr('Estoni',subst,'').
nr('Esperanti',subst,'').
nr('Esperant',subst,'*').
nr('Esfahan',subst,'').
nr('Ernest',pers,'*').
nr('Eritre',subst,'').
nr('Erik',pers,'').
nr('Eridan',subst,'').
nr('Eri',subst,'').
nr('Erfurt',subst,'').
nr('Erevan',subst,'').
nr('Erasm',subst,'').
nr('Epikur',subst,'').
nr('Epifani',subst,'2').
nr('Ene',pers,'').
nr('Emilian',pers,'').
nr('Emili',pers,'*').
nr('Emil',pers,'').
nr('Emanuel',pers,'').
nr('Emaks',subst,'').
nr('Elize',subst,'').
nr('Elizabet',pers,'*').
nr('Eliz',pers,'').
nr('Eli',pers,'').
nr('Elb',subst,'').
nr('Elam',subst,'').
nr('Ekvador',subst,'8').
nr('Ejnŝtejn',pers,'').
nr('Ejfel',subst,'').
nr('Egipti',subst,'').
nr('Efes',subst,'').
nr('Edvard',pers,'').
nr('Eduard',pers,'').
nr('Edmund',pers,'').
nr('Edip',subst,'').
nr('Edgar',pers,'').
nr('Eden',subst,'1').
nr('Edam',subst,'').
nr('Duŝanbe',subst,'').
nr('Duseldorf',subst,'').
nr('Durban',subst,'').
nr('Dunj',pers,'').
nr('Dublin',subst,'').
nr('Dubaj',subst,'').
nr('Duala',subst,'').
nr('Dresden',subst,'').
nr('Drent',subst,'').
nr('Dovr',subst,'').
nr('Dover',subst,'').
nr('Dorote',pers,'').
nr('Donguan',subst,'').
nr('Donald',pers,'').
nr('Don',subst,'').
nr('Dominik',pers,'').
nr('Doh',subst,'').
nr('Dodoma',subst,'').
nr('Dirak',pers,'').
nr('Dioskur',subst,'').
nr('Dionizi',pers,'').
nr('Dieg',pers,'').
nr('Dian',pers,'').
nr('Detrojt',subst,'').
nr('Demokrit',subst,'').
nr('Demetri',pers,'').
nr('Delhi',subst,'').
nr('Delavar',subst,'').
nr('Dekameron',subst,'').
nr('Dejm',subst,'').
nr('Dedekind',pers,'').
nr('David',pers,'').
nr('Darvin',pers,'').
nr('Darmapad',subst,'').
nr('Darm',subst,'').
nr('Daresalam',subst,'').
nr('Danub',subst,'').
nr('Daniel',pers,'').
nr('Dani',subst,'').
nr('Dana',subst,'').
nr('Damian',pers,'').
nr('Damask',subst,'').
nr('Dalmati',subst,'').
nr('Dakot',subst,'').
nr('Dakar',subst,'').
nr('Dak',subst,'').
nr('Dagobert',pers,'').
nr('Ciril',pers,'').
nr('Ciprian',pers,'').
nr('Cion',subst,'').
nr('Cinda',subst,'').
nr('Ciceron',subst,'').
nr('Cezar',pers,'').
nr('Cerber',subst,'').
nr('Celsi',subst,'').
nr('Celesten',pers,'').
nr('Cefe',subst,'').
nr('Buĥor',subst,'').
nr('Butan',subst,'').
nr('Burund',subst,'').
nr('Burkin',subst,'').
nr('Burbon',subst,'').
nr('Bulonj',subst,'*').
nr('Bulgari',subst,'').
nr('Bule',subst,'').
nr('Bukareŝt',subst,'').
nr('Budapeŝt',subst,'').
nr('Bruĝ',subst,'').
nr('Brusel',subst,'').
nr('Brunsvik',subst,'').
nr('Brunej',subst,'').
nr('Brun',pers,'').
nr('Briti',subst,'').
nr('Brisban',subst,'').
nr('Brier',subst,'').
nr('Brest',subst,'').
nr('Bremen',subst,'').
nr('Brem',subst,'').
nr('Brazilj',subst,'').
nr('Brazil',subst,'8').
nr('Brazavil',subst,'').
nr('Bratislav',subst,'').
nr('Brandenburg',subst,'').
nr('Brabant',subst,'').
nr('Bospor',subst,'').
nr('Bosni',subst,'').
nr('Boris',pers,'').
nr('Borel',pers,'').
nr('Bopal',subst,'').
nr('Bonifac',pers,'').
nr('Bonaventur',pers,'').
nr('Bomarŝe',subst,'').
nr('Bolivi',subst,'8').
nr('Boleslav',pers,'').
nr('Bohemi',subst,'').
nr('Bogot',subst,'').
nr('Bofort',pers,'').
nr('Bodidarm',subst,'').
nr('Bocvan',subst,'').
nr('Blis',subst,'').
nr('Blez',subst,'').
nr('Blazi',pers,'').
nr('Biŝkek',subst,'').
nr('Bizanci',subst,'').
nr('Bizanc',subst,'').
nr('Birm',subst,'8').
nr('Bihar',subst,'').
nr('Bibli',subst,'1').
nr('Besarabi',subst,'').
nr('Bertrand',pers,'').
nr('Bertil',pers,'').
nr('Bert',pers,'*').
nr('Bernard',pers,'').
nr('Bern',subst,'').
nr('Berlin',subst,'*').
nr('Bering',pers,'').
nr('Beovulf',subst,'').
nr('Beograd',subst,'').
nr('Benjamen',pers,'').
nr('Benin',subst,'').
nr('Bengalur',subst,'').
nr('Bengal',subst,'').
nr('Beneluks',subst,'').
nr('Benedikt',pers,'').
nr('Belorusi',subst,'').
nr('Beliz',subst,'').
nr('Belgi',subst,'').
nr('Belarusi',subst,'').
nr('Bel-Horizont',subst,'').
nr('Bejrut',subst,'').
nr('Behemot',subst,'').
nr('Baĥ',subst,'').
nr('Bazil',pers,'').
nr('Bazik',subst,'').
nr('Bazel',subst,'').
nr('Batu',pers,'').
nr('Bastian',pers,'').
nr('Bartolome',pers,'').
nr('Barnab',pers,'').
nr('Barcelon',subst,'').
nr('Barbaros',subst,'').
nr('Barbad',subst,'').
nr('Barat',subst,'').
nr('Bankok',subst,'').
nr('Bang',subst,'').
nr('Bandung',subst,'').
nr('Banaĥ',pers,'').
nr('Bamak',subst,'').
nr('Baltik',subst,'').
nr('Baltazar',pers,'').
nr('Balkaŝ',subst,'').
nr('Balkan',subst,'').
nr('Balduen',pers,'').
nr('Baku',subst,'').
nr('Baktri',subst,'').
nr('Bajkal',subst,'').
nr('Baham',subst,'').
nr('Baha',subst,'').
nr('Bagdad',subst,'').
nr('Bagavadgit',subst,'').
nr('Badaĥoz',subst,'').
nr('Babiloni',subst,'').
nr('Babilon',subst,'').
nr('Babel',subst,'').
nr('Bab',subst,'').
nr('Aŭvernj',subst,'').
nr('Aŭstri',subst,'').
nr('Aŭstrali',subst,'8').
nr('Aŭrelian',pers,'').
nr('Aŭgusten',pers,'').
nr('Aŭgust',pers,'').
nr('Aŭgsburg',subst,'').
nr('Aŝok',subst,'').
nr('Aŝgabat',subst,'').
nr('Aĥil',pers,'').
nr('Azov',subst,'').
nr('Azi',subst,'8').
nr('Azeri',subst,'').
nr('Azerbajĝan',subst,'').
nr('Avogadr',pers,'').
nr('Avicen',pers,'').
nr('Avest',subst,'').
nr('Avejr',subst,'').
nr('Avalokiteŝvar',subst,'').
nr('Atomium',subst,'').
nr('Atlantik',subst,'8').
nr('Atlantid',subst,'').
nr('Atlant',subst,'').
nr('Aten',subst,'').
nr('Atalant',subst,'').
nr('Asuncion',subst,'').
nr('Asturi',subst,'').
nr('Aski',subst,'').
nr('Asiri',subst,'').
nr('Asen',subst,'').
nr('Asam',subst,'').
nr('Arĥimed',pers,'').
nr('Arunaĉalpradeŝ',subst,'').
nr('Artur',pers,'').
nr('Artemid',subst,'').
nr('Arnulf',pers,'').
nr('Arnold',pers,'').
nr('Arnhem',subst,'').
nr('Armeni',subst,'').
nr('Arkt',subst,'9').
nr('Arkansas',subst,'').
nr('Arizon',subst,'').
nr('Aristotel',pers,'').
nr('Aristofan',subst,'').
nr('Argonaŭt',subst,'').
nr('Argentin',subst,'').
nr('Ares',subst,'').
nr('Areopag',subst,'').
nr('Aral',subst,'').
nr('Apolon',subst,'').
nr('Api',subst,'').
nr('Anunciaci',subst,'*').
nr('Antverpen',subst,'').
nr('Antoni',pers,'').
nr('Antonen',pers,'').
nr('Anton',pers,'*').
nr('Antil',subst,'').
nr('Antigv',subst,'').
nr('Antarkt',subst,'9').
nr('Antananariv',subst,'').
nr('Anselm',pers,'').
nr('Ann',pers,'*').
nr('Ankar',subst,'').
nr('Angol',subst,'').
nr('Angli',subst,'').
nr('Angar',subst,'').
nr('Andromed',subst,'').
nr('Andre',pers,'').
nr('Andrapradeŝ',subst,'').
nr('Andor',subst,'').
nr('Andaluzi',subst,'').
nr('And',subst,'').
nr('Anatoli',subst,'').
nr('Anatol',pers,'').
nr('Anastazi',pers,'').
nr('Anabaz',subst,'').
nr('Amudarj',subst,'').
nr('Amsterdam',subst,'').
nr('Amper',pers,'').
nr('Amitab',subst,'').
nr('Amir',pers,'').
nr('Amerik',subst,'8').
nr('Ambrozi',pers,'').
nr('Amazon',subst,'').
nr('Aman',subst,'').
nr('Amade',pers,'').
nr('Alĝeri',subst,'8').
nr('Alĝer',subst,'').
nr('Alzac',subst,'').
nr('Altaj',subst,'').
nr('Altair',subst,'').
nr('Almat',subst,'').
nr('Alfred',pers,'').
nr('Alfons',pers,'').
nr('Aleksandri',subst,'').
nr('Aleksandr',pers,'*').
nr('Albert',pers,'').
nr('Albert',subst,'').
nr('Albani',subst,'').
nr('Alask',subst,'').
nr('Alan',pers,'').
nr('Alah',subst,'').
nr('Alabam',subst,'').
nr('Akr',subst,'').
nr('Aken',subst,'').
nr('Akad',subst,'').
nr('Ahmadism',subst,'').
nr('Ahmadabad',subst,'').
nr('Agni',subst,'').
nr('Afrodit',subst,'').
nr('Afrik',subst,'8').
nr('Advent',subst,'1').
nr('Adriatik',subst,'').
nr('Adrian',pers,'').
nr('Adolf',pers,'').
nr('Adis-Abeb',subst,'').
nr('Adan',subst,'').
nr('Adam',pers,'').
nr('Adalbert',pers,'').
nr('Abuĝ',subst,'').
nr('Abudabi',subst,'').
nr('Abraham',pers,'').
nr('Abiĝan',subst,'').
nr('Abidarm',subst,'').
nr('Abel',pers,'').
nr('Abas',pers,'').
nr_('ŝverin',subst,'').
nr_('ŝopen',subst,'').
nr_('ŝlejer',subst,'').
nr_('ŝjian',subst,'').
nr_('ŝiva',subst,'').
nr_('ŝinkansen',subst,'').
nr_('ŝiller',subst,'*').
nr_('ŝil',subst,'').
nr_('ŝenĵen',subst,'').
nr_('ŝenjang',subst,'').
nr_('ŝengen',subst,'').
nr_('ŝem',subst,'').
nr_('ŝekspir',subst,'').
nr_('ŝari',subst,'').
nr_('ŝanhaj',subst,'').
nr_('ĵul',pers,'').
nr_('ĵub',subst,'').
nr_('ĵerzej',subst,'').
nr_('ĥiron',subst,'').
nr_('ĥi',subst,'').
nr_('ĥerone',subst,'').
nr_('ĥeops',subst,'').
nr_('ĥartum',subst,'').
nr_('ĥaron',subst,'').
nr_('ĥarkov',subst,'').
nr_('ĥaribd',subst,'').
nr_('ĥanuk',subst,'').
nr_('ĥam',subst,'').
nr_('ĝoĉi',subst,'').
nr_('ĝid',subst,'').
nr_('ĝibuti',subst,'').
nr_('ĝibut',subst,'').
nr_('ĝerald',pers,'').
nr_('ĝenov',subst,'').
nr_('ĝenev',subst,'').
nr_('ĝav',subst,'').
nr_('ĝarkand',subst,'').
nr_('ĝakart',subst,'').
nr_('ĝajpur',subst,'').
nr_('ĉongĉing',subst,'').
nr_('ĉitagong',subst,'').
nr_('ĉini',subst,'').
nr_('ĉingis',pers,'').
nr_('ĉili',subst,'').
nr_('ĉikag',subst,'').
nr_('ĉeĥoslovaki',subst,'').
nr_('ĉeĥi',subst,'').
nr_('ĉernobil',subst,'').
nr_('ĉengdu',subst,'').
nr_('ĉenaj',subst,'').
nr_('ĉatisgar',subst,'').
nr_('ĉangĝoŭ',subst,'').
nr_('ĉangĉun',subst,'').
nr_('ĉad',subst,'').
nr_('zurik',subst,'').
nr_('zimbabv',subst,'').
nr_('zib',subst,'').
nr_('zeŭs',subst,'').
nr_('zeland',subst,'').
nr_('zaratuŝtr',subst,'').
nr_('zamenhof',pers,'*').
nr_('zambi',subst,'').
nr_('zairi',subst,'').
nr_('zagreb',subst,'').
nr_('vurtemberg',subst,'').
nr_('vulgat',subst,'').
nr_('vuhan',subst,'').
nr_('volter',subst,'').
nr_('volt',subst,'').
nr_('volsung',subst,'').
nr_('volg',subst,'').
nr_('volfgang',pers,'').
nr_('volapuk',subst,'').
nr_('vodu',subst,'').
nr_('vladimir',pers,'').
nr_('vjetnami',subst,'').
nr_('vjentian',subst,'').
nr_('viŝnu',subst,'').
nr_('vizbaden',subst,'').
nr_('vitruvi',subst,'').
nr_('vit',subst,'').
nr_('viskonsin',subst,'').
nr_('virgini',subst,'').
nr_('vindoz',subst,'').
nr_('vindhuk',subst,'').
nr_('vincent',pers,'').
nr_('vinaj',subst,'').
nr_('viln',subst,'').
nr_('vilhelm',pers,'*').
nr_('viktori',subst,'').
nr_('viktor',pers,'').
nr_('vikipedi',subst,'').
nr_('vien',subst,'').
nr_('vezuvi',subst,'').
nr_('vezer',subst,'').
nr_('vestminstr',subst,'').
nr_('vestfali',subst,'').
nr_('vermont',subst,'').
nr_('vergili',pers,'').
nr_('venus',subst,'').
nr_('venezuel',subst,'8').
nr_('vener',subst,'').
nr_('veneci',subst,'').
nr_('vencesla',pers,'').
nr_('velington',subst,'').
nr_('vaŝington',subst,'*').
nr_('vaĝrajan',subst,'').
nr_('vatikan',subst,'').
nr_('vat',pers,'').
nr_('varsovi',subst,'*').
nr_('varingjen',subst,'').
nr_('vanuatu',subst,'').
nr_('valter',pers,'').
nr_('valoni',subst,'').
nr_('valet',subst,'').
nr_('valeri',pers,'').
nr_('valenten',pers,'').
nr_('valenci',subst,'').
nr_('valdorf',subst,'').
nr_('vajroĉan',subst,'').
nr_('vajoming',subst,'').
nr_('vajmar',subst,'').
nr_('vahabism',subst,'').
nr_('vagadugu',subst,'').
nr_('vaduz',subst,'').
nr_('uzbeki',subst,'').
nr_('utreĥt',subst,'').
nr_('utarpradeŝ',subst,'').
nr_('utarakand',subst,'').
nr_('utah',subst,'').
nr_('uson',subst,'9').
nr_('urumĉi',subst,'').
nr_('urugvaj',subst,'8').
nr_('uran',subst,'').
nr_('ural',subst,'').
nr_('uniks',subst,'').
nr_('unikod',subst,'').
nr_('unesk',subst,'').
nr_('ulanbator',subst,'').
nr_('ulamban',subst,'').
nr_('ukraini',subst,'').
nr_('ugand',subst,'').
nr_('tviter',subst,'').
nr_('tuval',subst,'').
nr_('turkmeni',subst,'').
nr_('turki',subst,'').
nr_('turingi',subst,'').
nr_('tunizi',subst,'8').
nr_('tuniz',subst,'').
nr_('tucidid',pers,'').
nr_('trondhejm',subst,'').
nr_('troj',subst,'').
nr_('tripur',subst,'').
nr_('tripol',subst,'').
nr_('tripitak',subst,'').
nr_('trinidad',subst,'').
nr_('trent',subst,'').
nr_('transilvani',subst,'').
nr_('toskani',subst,'').
nr_('toront',subst,'').
nr_('tora',subst,'').
nr_('tong',subst,'').
nr_('tomas',pers,'').
nr_('tokipon',subst,'').
nr_('toki',subst,'').
nr_('tokaj',subst,'').
nr_('togoland',subst,'').
nr_('tobi',pers,'').
nr_('tobag',subst,'').
nr_('tjanĝin',subst,'').
nr_('titikak',subst,'').
nr_('tirol',subst,'').
nr_('tiran',subst,'').
nr_('tinĉj',subst,'').
nr_('timote',pers,'').
nr_('timor',subst,'').
nr_('timbuktu',subst,'').
nr_('tigris',subst,'').
nr_('tiflis',subst,'').
nr_('tife',subst,'').
nr_('tician',subst,'').
nr_('tibet',subst,'').
nr_('tiberi',pers,'').
nr_('tiber',subst,'').
nr_('tet',subst,'').
nr_('teravad',subst,'').
nr_('teofil',pers,'').
nr_('teodor',pers,'*').
nr_('teobald',pers,'').
nr_('tenesi',subst,'').
nr_('telegram',subst,'').
nr_('telangan',subst,'').
nr_('teksas',subst,'').
nr_('teheran',subst,'').
nr_('tegucigalp',subst,'').
nr_('tegu',subst,'').
nr_('teb',subst,'').
nr_('taŝkent',subst,'').
nr_('taĝiki',subst,'').
nr_('tasmani',subst,'').
nr_('tars',subst,'').
nr_('tanzani',subst,'').
nr_('tantal',subst,'').
nr_('tamiz',subst,'').
nr_('talin',subst,'').
nr_('tales',subst,'').
nr_('tajpe',subst,'').
nr_('tahiti',subst,'').
nr_('tade',pers,'').
nr_('sĥeld',subst,'').
nr_('svisi',subst,'').
nr_('svedi',subst,'').
nr_('suĝoŭ',subst,'').
nr_('suv',subst,'').
nr_('surinam',subst,'').
nr_('surat',subst,'').
nr_('surabaj',subst,'').
nr_('suomi',subst,'').
nr_('suna',subst,'').
nr_('sumeri',subst,'').
nr_('sumatr',subst,'').
nr_('sulaves',subst,'').
nr_('sukot',subst,'').
nr_('suez',subst,'').
nr_('sudan',subst,'8').
nr_('stutgart',subst,'').
nr_('strasburg',subst,'').
nr_('strabon',subst,'').
nr_('stokholm',subst,'').
nr_('stiri',subst,'').
nr_('sten',subst,'').
nr_('stefan',pers,'*').
nr_('stanislav',pers,'').
nr_('srilank',subst,'').
nr_('spinoz',pers,'').
nr_('soveti',subst,'').
nr_('somali',subst,'').
nr_('solutre',subst,'').
nr_('sokrat',pers,'').
nr_('sofokl',pers,'').
nr_('sofi',pers,'*').
nr_('sofi',subst,'').
nr_('sloveni',subst,'').
nr_('slovaki',subst,'').
nr_('slavon',subst,'').
nr_('skoti',subst,'').
nr_('skopj',subst,'').
nr_('skiti',subst,'').
nr_('skeld',subst,'').
nr_('skandinavi',subst,'').
nr_('skajp',subst,'').
nr_('siĉŭan',subst,'').
nr_('siĉuan',subst,'').
nr_('sizif',subst,'').
nr_('sirius',subst,'').
nr_('siriak',subst,'').
nr_('siri',subst,'8').
nr_('sirdarj',subst,'').
nr_('sirakuz',subst,'').
nr_('singapur',subst,'').
nr_('simon',pers,'').
nr_('simeon',pers,'').
nr_('silvestr',pers,'').
nr_('silvan',pers,'').
nr_('silezi',subst,'').
nr_('sikim',subst,'').
nr_('sigmund',pers,'').
nr_('sigismund',pers,'').
nr_('sieraleon',subst,'').
nr_('sidnej',subst,'').
nr_('sicili',subst,'').
nr_('siberi',subst,'').
nr_('sevil',subst,'').
nr_('seul',subst,'').
nr_('sergi',pers,'').
nr_('serafen',pers,'').
nr_('septuagint',subst,'').
nr_('senek',subst,'').
nr_('senegal',subst,'').
nr_('selim',pers,'').
nr_('seborg',subst,'').
nr_('sebastian',pers,'').
nr_('scil',subst,'').
nr_('scientologi',subst,'').
nr_('saĥalen',subst,'').
nr_('savoj',subst,'').
nr_('saturn',subst,'').
nr_('saskaĉevan',subst,'').
nr_('sarajev',subst,'').
nr_('sar',subst,'').
nr_('santome',subst,'').
nr_('santiag',subst,'').
nr_('santeri',subst,'').
nr_('sanskrit',subst,'').
nr_('sansalvador',subst,'').
nr_('sanmarin',subst,'').
nr_('sana',subst,'').
nr_('san-Paŭl',subst,'').
nr_('samos',subst,'').
nr_('samo',subst,'').
nr_('samir',subst,'').
nr_('samg',subst,'').
nr_('sambr',subst,'').
nr_('samarkand',subst,'').
nr_('samari',subst,'').
nr_('salvador',subst,'').
nr_('salomon',pers,'').
nr_('salomon',subst,'').
nr_('salafism',subst,'').
nr_('sajgon',subst,'').
nr_('sajan',subst,'').
nr_('sahel',subst,'').
nr_('sahar',subst,'').
nr_('sadam',pers,'').
nr_('sad',subst,'').
nr_('ruso',subst,'').
nr_('rusi',subst,'').
nr_('rurik',pers,'').
nr_('rumani',subst,'').
nr_('rudolf',pers,'').
nr_('rubikon',subst,'').
nr_('ruand',subst,'').
nr_('roĝer',pers,'').
nr_('roterdam',subst,'').
nr_('romi',subst,'').
nr_('rome',pers,'').
nr_('rom',subst,'').
nr_('roland',pers,'').
nr_('rogaci',subst,'').
nr_('rodrig',pers,'').
nr_('rodos',subst,'').
nr_('rodolf',pers,'').
nr_('rodezi',subst,'').
nr_('rodan',subst,'').
nr_('robert',pers,'').
nr_('rio-de-Ĵanejr',subst,'').
nr_('riman',pers,'').
nr_('rikard',pers,'').
nr_('rig',subst,'').
nr_('riad',subst,'').
nr_('renat',pers,'').
nr_('remington',subst,'').
nr_('rejnland-Palatinat',subst,'').
nr_('rejn',subst,'').
nr_('rejkjavik',subst,'').
nr_('rejki',subst,'').
nr_('regensburg',subst,'').
nr_('reformaci',subst,'1').
nr_('recif',subst,'').
nr_('raŭm',subst,'').
nr_('raŝid',subst,'').
nr_('raĥel',pers,'').
nr_('raĝastan',subst,'').
nr_('rangun',subst,'').
nr_('ramajan',subst,'').
nr_('rajmund',pers,'').
nr_('rafael',pers,'').
nr_('rabat',subst,'').
nr_('puŝkin',subst,'').
nr_('purim',subst,'').
nr_('pune',subst,'').
nr_('ptoleme',pers,'').
nr_('psiĥ',subst,'').
nr_('prusi',subst,'').
nr_('provenc',subst,'').
nr_('promete',subst,'').
nr_('principe',subst,'').
nr_('pretori',subst,'').
nr_('prag',subst,'').
nr_('pozidon',subst,'').
nr_('portvila',subst,'').
nr_('portugali',subst,'').
nr_('portospen',subst,'').
nr_('portoprinc',subst,'').
nr_('portmoresb',subst,'').
nr_('porfiri',pers,'').
nr_('ponti',pers,'').
nr_('pompej',subst,'').
nr_('pomeri',subst,'').
nr_('poluks',subst,'').
nr_('polinezi',subst,'8').
nr_('poli',subst,'').
nr_('pocdam',subst,'').
nr_('pnompen',subst,'').
nr_('pluton',subst,'').
nr_('plut',subst,'').
nr_('plini',pers,'').
nr_('plejad',subst,'').
nr_('plaŭt',pers,'').
nr_('platon',pers,'').
nr_('pjonjang',subst,'').
nr_('pjanĝ',subst,'').
nr_('pitagor',subst,'').
nr_('pinokj',subst,'').
nr_('pinjin',subst,'').
nr_('pilat',subst,'').
nr_('picburg',subst,'').
nr_('peŝavar',subst,'').
nr_('petr',pers,'*').
nr_('peterburg',subst,'').
nr_('peru',subst,'8').
nr_('pert',subst,'').
nr_('perse',subst,'').
nr_('pentekost',subst,'*').
nr_('pentateŭk',subst,'').
nr_('pensilvani',subst,'').
nr_('pekin',subst,'').
nr_('pegaz',subst,'').
nr_('paŭl',pers,'*').
nr_('patrik',pers,'').
nr_('pasteŭr',pers,'').
nr_('paskal',pers,'').
nr_('pask',subst,'*').
nr_('pasion',subst,'').
nr_('parkinson',pers,'').
nr_('park',subst,'').
nr_('pariz',subst,'*').
nr_('parc',subst,'').
nr_('paramarib',subst,'').
nr_('paralimpik',subst,'').
nr_('paraklet',subst,'').
nr_('paragvaj',subst,'8').
nr_('papu',subst,'').
nr_('panĝab',subst,'').
nr_('pange',subst,'').
nr_('panam',subst,'8').
nr_('pali',subst,'').
nr_('palestin',subst,'').
nr_('palerm',subst,'').
nr_('palaŭ',subst,'').
nr_('pakistan',subst,'8').
nr_('pacifik',subst,'8').
nr_('pabl',pers,'').
nr_('oĥock',subst,'').
nr_('oziris',subst,'').
nr_('ovidi',pers,'').
nr_('overisel',subst,'').
nr_('otoman',subst,'').
nr_('otav',subst,'').
nr_('osvald',pers,'').
nr_('ostend',subst,'').
nr_('osman',pers,'').
nr_('osl',subst,'').
nr_('oskar',pers,'').
nr_('oskar',subst,'').
nr_('osak',subst,'').
nr_('orlean',subst,'').
nr_('ork',subst,'').
nr_('oris',subst,'').
nr_('orion',subst,'').
nr_('orfe',subst,'').
nr_('oregon',subst,'').
nr_('oomot',subst,'').
nr_('onufri',pers,'').
nr_('ontari',subst,'').
nr_('onesim',pers,'').
nr_('omdurman',subst,'').
nr_('omar',pers,'').
nr_('oman',subst,'').
nr_('om',pers,'').
nr_('oliver',pers,'').
nr_('olimpik',subst,'').
nr_('olimp',subst,'').
nr_('olav',pers,'').
nr_('oksford',subst,'').
nr_('oklahom',subst,'').
nr_('okcidental',subst,'').
nr_('oka',subst,'').
nr_('ohi',subst,'').
nr_('odr',subst,'').
nr_('odiŝ',subst,'').
nr_('odise',pers,'').
nr_('oceani',subst,'').
nr_('ob',subst,'').
nr_('nĝamen',subst,'').
nr_('nursultan',subst,'').
nr_('nurenberg',subst,'').
nr_('nunavut',subst,'').
nr_('nukualof',subst,'').
nr_('nuakŝot',subst,'').
nr_('noŭruz',subst,'').
nr_('novosibirsk',subst,'').
nr_('novial',subst,'').
nr_('novgorod',subst,'').
nr_('norvegi',subst,'').
nr_('noaĥ',pers,'').
nr_('niĝer',subst,'').
nr_('niĉiren',subst,'').
nr_('nis',subst,'').
nr_('nirvan',subst,'').
nr_('ningb',subst,'').
nr_('nimeg',subst,'').
nr_('nil',subst,'').
nr_('nikozi',subst,'').
nr_('nikola',pers,'*').
nr_('nikodem',pers,'*').
nr_('nikaragv',subst,'8').
nr_('nik',subst,'').
nr_('nic',subst,'').
nr_('nibelung',subst,'').
nr_('niame',subst,'').
nr_('niagar',subst,'').
nr_('neŭŝatel',subst,'').
nr_('neŭton',pers,'').
nr_('nevad',subst,'').
nr_('nestor',pers,'').
nr_('neptun',subst,'').
nr_('nepjid',subst,'').
nr_('neper',subst,'').
nr_('nepal',subst,'').
nr_('nekar',subst,'').
nr_('nederland',subst,'8').
nr_('nebrask',subst,'').
nr_('naur',subst,'').
nr_('nasaŭ',subst,'').
nr_('narcis',pers,'').
nr_('napoleon',pers,'').
nr_('napol',subst,'').
nr_('nanĉan',subst,'').
nr_('nant',subst,'').
nr_('nankin',subst,'').
nr_('naning',subst,'').
nr_('namur',subst,'').
nr_('namibi',subst,'').
nr_('najrobi',subst,'').
nr_('nagoj',subst,'').
nr_('nagasak',subst,'').
nr_('muzaik',subst,'').
nr_('munken',subst,'').
nr_('mumbaj',subst,'').
nr_('multan',subst,'').
nr_('muhamad',pers,'').
nr_('mozel',subst,'').
nr_('mozart',pers,'').
nr_('mozambik',subst,'').
nr_('moz',subst,'').
nr_('moskv',subst,'').
nr_('mose',subst,'').
nr_('mors',subst,'').
nr_('morfe',subst,'').
nr_('montreal',subst,'').
nr_('montevide',subst,'').
nr_('montenegr',subst,'').
nr_('montekarl',subst,'').
nr_('montan',subst,'').
nr_('monrovi',subst,'').
nr_('mongoli',subst,'').
nr_('monak',subst,'').
nr_('moluk',subst,'').
nr_('molier',pers,'').
nr_('moldavi',subst,'').
nr_('mogadiŝ',subst,'').
nr_('mjanma',subst,'').
nr_('miŝn',subst,'').
nr_('miĥael',pers,'*').
nr_('miĉigan',subst,'').
nr_('mizoram',subst,'').
nr_('misuri',subst,'').
nr_('misur',subst,'').
nr_('misisipi',subst,'').
nr_('misisip',subst,'').
nr_('mirz',pers,'').
nr_('minsk',subst,'').
nr_('minotaŭr',subst,'').
nr_('minesot',subst,'').
nr_('milan',subst,'').
nr_('mikrosoft',subst,'').
nr_('mikronezi',subst,'').
nr_('midelburg',subst,'').
nr_('midas',subst,'').
nr_('meĥlen',subst,'').
nr_('mezopotami',subst,'').
nr_('metodi',pers,'').
nr_('merkur',subst,'').
nr_('mendelev',pers,'').
nr_('mence',subst,'').
nr_('memfis',subst,'').
nr_('melburn',subst,'').
nr_('meksik',subst,'8').
nr_('mekong',subst,'').
nr_('meklenburg',subst,'').
nr_('mekk',subst,'').
nr_('megalaj',subst,'').
nr_('mediĉ',subst,'').
nr_('mediterane',subst,'8').
nr_('medi',subst,'').
nr_('medeĝin',subst,'').
nr_('mede',subst,'').
nr_('medan',subst,'').
nr_('mec',subst,'').
nr_('maŭric',pers,'').
nr_('maŝhad',subst,'').
nr_('maĥ',subst,'').
nr_('mate',pers,'').
nr_('mastriĥt',subst,'').
nr_('maskat',subst,'').
nr_('maseru',subst,'').
nr_('masaĉusec',subst,'').
nr_('marŝal',subst,'').
nr_('marten',pers,'').
nr_('marsejl',subst,'').
nr_('mars',subst,'').
nr_('marok',subst,'8').
nr_('marks',pers,'').
nr_('mark',pers,'').
nr_('mariland',subst,'').
nr_('mari',pers,'*').
nr_('margaret',pers,'').
nr_('marcial',pers,'').
nr_('marcel',pers,'').
nr_('marakajb',subst,'').
nr_('maput',subst,'').
nr_('manĵusr',subst,'').
nr_('maniĥe',pers,'').
nr_('manitob',subst,'').
nr_('manipur',subst,'').
nr_('manil',subst,'').
nr_('manik',subst,'').
nr_('manhejm',subst,'').
nr_('manaŭs',subst,'').
nr_('manam',subst,'').
nr_('managv',subst,'').
nr_('mameluk',subst,'').
nr_('malt',subst,'').
nr_('malkolm',pers,'').
nr_('malik',pers,'').
nr_('male',subst,'').
nr_('malavi',subst,'').
nr_('malajzi',subst,'').
nr_('maksimilian',pers,'').
nr_('makintoŝ',subst,'').
nr_('makedoni',subst,'').
nr_('maka',subst,'').
nr_('majork',subst,'').
nr_('majn',subst,'').
nr_('majenc',subst,'').
nr_('mahomet',subst,'').
nr_('mahavir',subst,'').
nr_('maharaŝtr',subst,'').
nr_('mahajan',subst,'').
nr_('mahabarat',subst,'').
nr_('magreb',subst,'').
nr_('madrid',subst,'').
nr_('madjapradeŝ',subst,'').
nr_('madejr',subst,'').
nr_('madagaskar',subst,'').
nr_('luzaci',subst,'').
nr_('luter',pers,'*').
nr_('lusak',subst,'').
nr_('luksemburgi',subst,'').
nr_('luksemburg',subst,'').
nr_('luk',pers,'').
nr_('luizian',subst,'').
nr_('luiz',pers,'').
nr_('ludovik',pers,'*').
nr_('lucian',pers,'').
nr_('luar',subst,'').
nr_('luand',subst,'').
nr_('loĵban',subst,'').
nr_('loven',subst,'').
nr_('losanĝeles',subst,'').
nr_('loren',subst,'').
nr_('london',subst,'*').
nr_('lome',subst,'').
nr_('loglan',subst,'').
nr_('ljubljan',subst,'').
nr_('liĥtenŝtejn',subst,'').
nr_('litv',subst,'').
nr_('litovi',subst,'').
nr_('litomiŝl',subst,'').
nr_('lisbon',subst,'').
nr_('lionel',pers,'').
nr_('lion',subst,'').
nr_('linuks',subst,'').
nr_('lingvafranka',subst,'').
nr_('linc',subst,'').
nr_('limburg',subst,'').
nr_('lim',subst,'').
nr_('lilit',subst,'').
nr_('liguri',subst,'').
nr_('lieĝ',subst,'').
nr_('lier',subst,'').
nr_('librevil',subst,'').
nr_('libi',subst,'8').
nr_('liberi',subst,'8').
nr_('liban',subst,'8').
nr_('lesot',subst,'').
nr_('lesb',subst,'').
nr_('lepsik',subst,'').
nr_('leopold',pers,'').
nr_('leonard',pers,'').
nr_('leningrad',subst,'').
nr_('len',subst,'').
nr_('lelistad',subst,'').
nr_('lejbnic',subst,'').
nr_('lebeg',pers,'').
nr_('lebanon',subst,'').
nr_('leandr',pers,'').
nr_('laŭrenc',pers,'').
nr_('laŭrazi',subst,'').
nr_('laŭr',pers,'').
nr_('lazar',pers,'').
nr_('latvi',subst,'').
nr_('latin',subst,'').
nr_('lati',subst,'').
nr_('laptev',subst,'').
nr_('laplac',pers,'').
nr_('laos',subst,'').
nr_('lanĝoŭ',subst,'').
nr_('laknaŭ',subst,'').
nr_('lahor',subst,'').
nr_('lagos',subst,'').
nr_('laert',pers,'').
nr_('ladisla',pers,'').
nr_('labrador',subst,'').
nr_('kvirin',subst,'').
nr_('kuvajt',subst,'').
nr_('kuritib',subst,'').
nr_('kupidon',subst,'').
nr_('kunming',subst,'').
nr_('kulomb',pers,'').
nr_('kub',subst,'8').
nr_('kuala-Lumpur',subst,'').
nr_('ksitigarb',subst,'').
nr_('ksenofon',pers,'').
nr_('ksaver',pers,'').
nr_('kron',subst,'').
nr_('kroati',subst,'').
nr_('kriŝn',subst,'').
nr_('kristofor',pers,'').
nr_('kristian',pers,'').
nr_('krist',subst,'*').
nr_('krime',subst,'').
nr_('kret',subst,'').
nr_('koŝi',subst,'').
nr_('kotdivuar',subst,'').
nr_('kostarik',subst,'8').
nr_('kosov',subst,'').
nr_('kortrejk',subst,'').
nr_('korneli',pers,'').
nr_('korfu',subst,'').
nr_('korei',subst,'').
nr_('kordob',subst,'').
nr_('koran',subst,'*').
nr_('kopernik',pers,'').
nr_('kopenhag',subst,'').
nr_('konstantinopol',subst,'').
nr_('konstanten',pers,'').
nr_('konrad',pers,'').
nr_('kong',subst,'').
nr_('konfuce',pers,'').
nr_('konektikut',subst,'').
nr_('konakri',subst,'').
nr_('komsomol',subst,'').
nr_('komod',subst,'').
nr_('komeni',subst,'').
nr_('kolĥid',subst,'').
nr_('kolumbi',subst,'').
nr_('kolumb',pers,'').
nr_('kolose',subst,'').
nr_('kolorad',subst,'').
nr_('kolonj',subst,'').
nr_('kolombi',subst,'').
nr_('kolkat',subst,'').
nr_('kluĵ',subst,'').
nr_('kluĉevskaj',subst,'').
nr_('klement',pers,'').
nr_('klaŭdi',pers,'').
nr_('klar',pers,'*').
nr_('kiŝinev',subst,'').
nr_('kit',subst,'').
nr_('kiribat',subst,'').
nr_('kirgizi',subst,'').
nr_('kipr',subst,'').
nr_('kiot',subst,'').
nr_('kinŝas',subst,'').
nr_('kimri',subst,'').
nr_('kiliki',subst,'').
nr_('kigali',subst,'').
nr_('kiev',subst,'').
nr_('keral',subst,'').
nr_('kepler',subst,'').
nr_('kentuki',subst,'').
nr_('kenj',subst,'').
nr_('kembriĝ',subst,'').
nr_('kelvin',pers,'').
nr_('kebeki',subst,'').
nr_('kebek',subst,'').
nr_('kaŭkaz',subst,'').
nr_('kaŝmir',subst,'').
nr_('kazimir',pers,'').
nr_('kazaĥi',subst,'').
nr_('kazablank',subst,'').
nr_('katmand',subst,'').
nr_('katar',subst,'').
nr_('kataluni',subst,'').
nr_('kastor',subst,'').
nr_('kaspi',subst,'').
nr_('kasiope',subst,'').
nr_('kartveli',subst,'').
nr_('kartezi',pers,'').
nr_('karolin',subst,'').
nr_('karol',pers,'').
nr_('karnatak',subst,'').
nr_('karloreĝ',subst,'').
nr_('karl',subst,'').
nr_('karinti',subst,'').
nr_('karib',subst,'').
nr_('karesm',subst,'').
nr_('karaĉi',subst,'').
nr_('karakas',subst,'').
nr_('kara',subst,'').
nr_('kaprikorn',subst,'').
nr_('kapitol',subst,'').
nr_('kapadoki',subst,'').
nr_('kanton',subst,'').
nr_('kantabri',subst,'').
nr_('kansas',subst,'').
nr_('kanber',subst,'').
nr_('kanad',subst,'8').
nr_('kamĉatk',subst,'').
nr_('kampin',subst,'').
nr_('kampani',subst,'').
nr_('kampal',subst,'').
nr_('kamil',pers,'').
nr_('kameruni',subst,'').
nr_('kamerun',subst,'').
nr_('kamboĝ',subst,'').
nr_('kam',subst,'').
nr_('kalvin',pers,'*').
nr_('kalvari',subst,'').
nr_('kaloĉaj',subst,'').
nr_('kaliningrad',subst,'').
nr_('kaliforni',subst,'').
nr_('kalez',subst,'').
nr_('kalabri',subst,'').
nr_('kair',subst,'').
nr_('kabul',subst,'').
nr_('kaboverd',subst,'').
nr_('kabe',pers,'').
nr_('kabal',subst,'1').
nr_('jutub',subst,'').
nr_('justinian',pers,'').
nr_('justen',pers,'').
nr_('jupiter',subst,'').
nr_('juli',pers,'').
nr_('jul',subst,'').
nr_('jugoslavi',subst,'').
nr_('jude',subst,'').
nr_('jozef',pers,'*').
nr_('jork',subst,'*').
nr_('jordani',subst,'').
nr_('jordan',subst,'').
nr_('jomkipur',subst,'').
nr_('jokoham',subst,'').
nr_('johanesburg',subst,'').
nr_('johan',pers,'*').
nr_('joakim',pers,'').
nr_('jesu',subst,'3').
nr_('jerusalem',subst,'').
nr_('jeriĥ',subst,'').
nr_('jenisej',subst,'').
nr_('jemen',subst,'').
nr_('jehov',subst,'').
nr_('jazon',pers,'').
nr_('jav',subst,'').
nr_('jaund',subst,'').
nr_('jaroslav',pers,'').
nr_('japani',subst,'').
nr_('jansen',subst,'').
nr_('jangzi',subst,'').
nr_('jamusukr',subst,'').
nr_('jamajk',subst,'').
nr_('jama',subst,'').
nr_('jakobi',pers,'').
nr_('jakob',pers,'').
nr_('izrael',subst,'*').
nr_('izmir',subst,'').
nr_('izis',subst,'').
nr_('izidor',pers,'').
nr_('iv',pers,'').
nr_('itali',subst,'').
nr_('istanbul',subst,'').
nr_('israel',subst,'9').
nr_('island',subst,'8').
nr_('islamabad',subst,'').
nr_('isel',subst,'').
nr_('isaak',pers,'').
nr_('irtiŝ',subst,'').
nr_('irland',subst,'8').
nr_('irene',pers,'').
nr_('iran',subst,'8').
nr_('irak',subst,'8').
nr_('iova',subst,'').
nr_('inĉon',subst,'').
nr_('inuktitut',subst,'').
nr_('interlingva',subst,'').
nr_('inocent',pers,'').
nr_('indus',subst,'').
nr_('indr',subst,'').
nr_('indiana',subst,'').
nr_('iluminat',subst,'').
nr_('ilinojs',subst,'').
nr_('iliad',subst,'').
nr_('ignac',pers,'').
nr_('idah',subst,'').
nr_('id',subst,'').
nr_('ibadan',subst,'').
nr_('husejn',pers,'').
nr_('hungari',subst,'').
nr_('humbert',pers,'').
nr_('hug',pers,'').
nr_('hudson',subst,'').
nr_('hubert',pers,'').
nr_('horus',subst,'').
nr_('horaci',pers,'').
nr_('honkong',subst,'').
nr_('homer',subst,'').
nr_('holstini',subst,'').
nr_('holand',subst,'').
nr_('hokajd',subst,'').
nr_('hispani',subst,'').
nr_('hiroŝim',subst,'').
nr_('hipolit',pers,'').
nr_('hipokrat',subst,'').
nr_('hindustan',subst,'').
nr_('hindukuŝ',subst,'').
nr_('hinajan',subst,'').
nr_('himaĉalpradeŝ',subst,'').
nr_('himalaj',subst,'').
nr_('hilel',subst,'').
nr_('hilbert',pers,'').
nr_('hieronim',pers,'').
nr_('heĝir',subst,'').
nr_('heziod',subst,'').
nr_('hevisid',pers,'').
nr_('herodot',subst,'').
nr_('herod',subst,'').
nr_('hermit',pers,'').
nr_('hermes',subst,'').
nr_('herman',pers,'').
nr_('herkul',pers,'').
nr_('hercegovin',subst,'').
nr_('herakl',subst,'').
nr_('henrik',pers,'').
nr_('henriet',pers,'*').
nr_('henegovi',subst,'').
nr_('helsink',subst,'').
nr_('helen',pers,'').
nr_('hektor',pers,'').
nr_('hefej',subst,'').
nr_('havan',subst,'').
nr_('havaj',subst,'').
nr_('hasan',pers,'').
nr_('harold',pers,'').
nr_('harlem',subst,'').
nr_('harian',subst,'').
nr_('harbin',subst,'').
nr_('harar',subst,'').
nr_('hanovr',subst,'').
nr_('hanoj',subst,'').
nr_('hanibal',pers,'').
nr_('hangĝoŭ',subst,'').
nr_('hanafism',subst,'').
nr_('hamurab',pers,'').
nr_('hampŝir',subst,'').
nr_('hamlet',subst,'').
nr_('hamburg',subst,'').
nr_('haman',subst,'').
nr_('haloven',subst,'').
nr_('halep',subst,'').
nr_('hajfong',subst,'').
nr_('hajderabad',subst,'').
nr_('haiti',subst,'').
nr_('hagad',subst,'').
nr_('hag',subst,'').
nr_('hades',subst,'').
nr_('gvine',subst,'8').
nr_('gvatemal',subst,'8').
nr_('guĝarat',subst,'').
nr_('gustav',pers,'').
nr_('gujan',subst,'').
nr_('gugl',subst,'').
nr_('gronland',subst,'').
nr_('groning',subst,'').
nr_('greziljon',subst,'').
nr_('grenad',subst,'').
nr_('greki',subst,'').
nr_('gregori',pers,'').
nr_('gravet',subst,'').
nr_('gotam',pers,'').
nr_('gonzal',pers,'').
nr_('gontran',pers,'').
nr_('gondvan',subst,'').
nr_('golgot',subst,'').
nr_('godfred',pers,'').
nr_('goa',subst,'').
nr_('glasgov',subst,'').
nr_('glagolic',subst,'').
nr_('giz',subst,'').
nr_('ginevr',subst,'').
nr_('gilgameŝ',subst,'').
nr_('gilbert',pers,'').
nr_('gervaz',pers,'').
nr_('germani',subst,'').
nr_('gerard',pers,'').
nr_('georg',pers,'*').
nr_('gent',subst,'').
nr_('gemar',subst,'').
nr_('gelderland',subst,'').
nr_('ge',subst,'').
nr_('gdinj',subst,'').
nr_('gdansk',subst,'').
nr_('gaŭs',pers,'').
nr_('gaston',pers,'').
nr_('gaspar',pers,'').
nr_('gana',subst,'').
nr_('gambi',subst,'').
nr_('galilej',subst,'').
nr_('galile',subst,'').
nr_('galez',pers,'').
nr_('gabriel',subst,'').
nr_('gabon',subst,'').
nr_('gaberon',subst,'').
nr_('fuĝoŭ',subst,'').
nr_('fritaŭn',subst,'').
nr_('frisi',subst,'').
nr_('freŭd',pers,'').
nr_('frederik',pers,'').
nr_('frankfurt',subst,'').
nr_('francisk',pers,'').
nr_('franci',subst,'').
nr_('fortunat',pers,'').
nr_('fortalez',subst,'').
nr_('fob',subst,'').
nr_('florid',subst,'').
nr_('florian',pers,'').
nr_('florenc',subst,'').
nr_('flevoland',subst,'').
nr_('flandri',subst,'').
nr_('fiĝi',subst,'').
nr_('finni',subst,'').
nr_('finland',subst,'').
nr_('filipin',subst,'').
nr_('filip',pers,'').
nr_('filibert',pers,'').
nr_('filadelfi',subst,'').
nr_('figar',subst,'').
nr_('fernand',pers,'').
nr_('ferdinand',pers,'').
nr_('fenoskandi',subst,'').
nr_('feniks',subst,'').
nr_('fenici',subst,'').
nr_('feliks',pers,'').
nr_('fejsbuk',subst,'').
nr_('farenhejt',pers,'').
nr_('farad',subst,'').
nr_('fanar',subst,'').
nr_('fajsalabad',subst,'').
nr_('fabrici',pers,'').
nr_('fabian',pers,'').
nr_('fabi',pers,'').
nr_('eŭzebi',pers,'').
nr_('eŭski',subst,'').
nr_('eŭrop',subst,'*').
nr_('eŭrjal',subst,'').
nr_('eŭripid',pers,'').
nr_('eŭrazi',subst,'').
nr_('eŭler',pers,'').
nr_('eŭklid',pers,'').
nr_('eŭgen',pers,'').
nr_('eŭfrat',subst,'').
nr_('ezop',pers,'').
nr_('everest',subst,'').
nr_('evelin',pers,'').
nr_('etiopi',subst,'').
nr_('esĥil',pers,'').
nr_('estoni',subst,'').
nr_('esperanti',subst,'').
nr_('esperant',subst,'*').
nr_('esfahan',subst,'').
nr_('ernest',pers,'*').
nr_('eritre',subst,'').
nr_('erik',pers,'').
nr_('eridan',subst,'').
nr_('eri',subst,'').
nr_('erfurt',subst,'').
nr_('erevan',subst,'').
nr_('erasm',subst,'').
nr_('epikur',subst,'').
nr_('epifani',subst,'2').
nr_('ene',pers,'').
nr_('emilian',pers,'').
nr_('emili',pers,'*').
nr_('emil',pers,'').
nr_('emanuel',pers,'').
nr_('emaks',subst,'').
nr_('elize',subst,'').
nr_('elizabet',pers,'*').
nr_('eliz',pers,'').
nr_('eli',pers,'').
nr_('elb',subst,'').
nr_('elam',subst,'').
nr_('ekvador',subst,'8').
nr_('ejnŝtejn',pers,'').
nr_('ejfel',subst,'').
nr_('egipti',subst,'').
nr_('efes',subst,'').
nr_('edvard',pers,'').
nr_('eduard',pers,'').
nr_('edmund',pers,'').
nr_('edip',subst,'').
nr_('edgar',pers,'').
nr_('eden',subst,'1').
nr_('edam',subst,'').
nr_('duŝanbe',subst,'').
nr_('duseldorf',subst,'').
nr_('durban',subst,'').
nr_('dunj',pers,'').
nr_('dublin',subst,'').
nr_('dubaj',subst,'').
nr_('duala',subst,'').
nr_('dresden',subst,'').
nr_('drent',subst,'').
nr_('dovr',subst,'').
nr_('dover',subst,'').
nr_('dorote',pers,'').
nr_('donguan',subst,'').
nr_('donald',pers,'').
nr_('don',subst,'').
nr_('dominik',pers,'').
nr_('doh',subst,'').
nr_('dodoma',subst,'').
nr_('dirak',pers,'').
nr_('dioskur',subst,'').
nr_('dionizi',pers,'').
nr_('dieg',pers,'').
nr_('dian',pers,'').
nr_('detrojt',subst,'').
nr_('demokrit',subst,'').
nr_('demetri',pers,'').
nr_('delhi',subst,'').
nr_('delavar',subst,'').
nr_('dekameron',subst,'').
nr_('dejm',subst,'').
nr_('dedekind',pers,'').
nr_('david',pers,'').
nr_('darvin',pers,'').
nr_('darmapad',subst,'').
nr_('darm',subst,'').
nr_('daresalam',subst,'').
nr_('danub',subst,'').
nr_('daniel',pers,'').
nr_('dani',subst,'').
nr_('dana',subst,'').
nr_('damian',pers,'').
nr_('damask',subst,'').
nr_('dalmati',subst,'').
nr_('dakot',subst,'').
nr_('dakar',subst,'').
nr_('dak',subst,'').
nr_('dagobert',pers,'').
nr_('ciril',pers,'').
nr_('ciprian',pers,'').
nr_('cion',subst,'').
nr_('cinda',subst,'').
nr_('ciceron',subst,'').
nr_('cezar',pers,'').
nr_('cerber',subst,'').
nr_('celsi',subst,'').
nr_('celesten',pers,'').
nr_('cefe',subst,'').
nr_('buĥor',subst,'').
nr_('butan',subst,'').
nr_('burund',subst,'').
nr_('burkin',subst,'').
nr_('burbon',subst,'').
nr_('bulonj',subst,'*').
nr_('bulgari',subst,'').
nr_('bule',subst,'').
nr_('bukareŝt',subst,'').
nr_('budapeŝt',subst,'').
nr_('bruĝ',subst,'').
nr_('brusel',subst,'').
nr_('brunsvik',subst,'').
nr_('brunej',subst,'').
nr_('brun',pers,'').
nr_('briti',subst,'').
nr_('brisban',subst,'').
nr_('brier',subst,'').
nr_('brest',subst,'').
nr_('bremen',subst,'').
nr_('brem',subst,'').
nr_('brazilj',subst,'').
nr_('brazil',subst,'8').
nr_('brazavil',subst,'').
nr_('bratislav',subst,'').
nr_('brandenburg',subst,'').
nr_('brabant',subst,'').
nr_('bospor',subst,'').
nr_('bosni',subst,'').
nr_('boris',pers,'').
nr_('borel',pers,'').
nr_('bopal',subst,'').
nr_('bonifac',pers,'').
nr_('bonaventur',pers,'').
nr_('bomarŝe',subst,'').
nr_('bolivi',subst,'8').
nr_('boleslav',pers,'').
nr_('bohemi',subst,'').
nr_('bogot',subst,'').
nr_('bofort',pers,'').
nr_('bodidarm',subst,'').
nr_('bocvan',subst,'').
nr_('blis',subst,'').
nr_('blez',subst,'').
nr_('blazi',pers,'').
nr_('biŝkek',subst,'').
nr_('bizanci',subst,'').
nr_('bizanc',subst,'').
nr_('birm',subst,'8').
nr_('bihar',subst,'').
nr_('bibli',subst,'1').
nr_('besarabi',subst,'').
nr_('bertrand',pers,'').
nr_('bertil',pers,'').
nr_('bert',pers,'*').
nr_('bernard',pers,'').
nr_('bern',subst,'').
nr_('berlin',subst,'*').
nr_('bering',pers,'').
nr_('beovulf',subst,'').
nr_('beograd',subst,'').
nr_('benjamen',pers,'').
nr_('benin',subst,'').
nr_('bengalur',subst,'').
nr_('bengal',subst,'').
nr_('beneluks',subst,'').
nr_('benedikt',pers,'').
nr_('belorusi',subst,'').
nr_('beliz',subst,'').
nr_('belgi',subst,'').
nr_('belarusi',subst,'').
nr_('bel-Horizont',subst,'').
nr_('bejrut',subst,'').
nr_('behemot',subst,'').
nr_('baĥ',subst,'').
nr_('bazil',pers,'').
nr_('bazik',subst,'').
nr_('bazel',subst,'').
nr_('batu',pers,'').
nr_('bastian',pers,'').
nr_('bartolome',pers,'').
nr_('barnab',pers,'').
nr_('barcelon',subst,'').
nr_('barbaros',subst,'').
nr_('barbad',subst,'').
nr_('barat',subst,'').
nr_('bankok',subst,'').
nr_('bang',subst,'').
nr_('bandung',subst,'').
nr_('banaĥ',pers,'').
nr_('bamak',subst,'').
nr_('baltik',subst,'').
nr_('baltazar',pers,'').
nr_('balkaŝ',subst,'').
nr_('balkan',subst,'').
nr_('balduen',pers,'').
nr_('baku',subst,'').
nr_('baktri',subst,'').
nr_('bajkal',subst,'').
nr_('baham',subst,'').
nr_('baha',subst,'').
nr_('bagdad',subst,'').
nr_('bagavadgit',subst,'').
nr_('badaĥoz',subst,'').
nr_('babiloni',subst,'').
nr_('babilon',subst,'').
nr_('babel',subst,'').
nr_('bab',subst,'').
nr_('aŭvernj',subst,'').
nr_('aŭstri',subst,'').
nr_('aŭstrali',subst,'8').
nr_('aŭrelian',pers,'').
nr_('aŭgusten',pers,'').
nr_('aŭgust',pers,'').
nr_('aŭgsburg',subst,'').
nr_('aŝok',subst,'').
nr_('aŝgabat',subst,'').
nr_('aĥil',pers,'').
nr_('azov',subst,'').
nr_('azi',subst,'8').
nr_('azeri',subst,'').
nr_('azerbajĝan',subst,'').
nr_('avogadr',pers,'').
nr_('avicen',pers,'').
nr_('avest',subst,'').
nr_('avejr',subst,'').
nr_('avalokiteŝvar',subst,'').
nr_('atomium',subst,'').
nr_('atlantik',subst,'8').
nr_('atlantid',subst,'').
nr_('atlant',subst,'').
nr_('aten',subst,'').
nr_('atalant',subst,'').
nr_('asuncion',subst,'').
nr_('asturi',subst,'').
nr_('aski',subst,'').
nr_('asiri',subst,'').
nr_('asen',subst,'').
nr_('asam',subst,'').
nr_('arĥimed',pers,'').
nr_('arunaĉalpradeŝ',subst,'').
nr_('artur',pers,'').
nr_('artemid',subst,'').
nr_('arnulf',pers,'').
nr_('arnold',pers,'').
nr_('arnhem',subst,'').
nr_('armeni',subst,'').
nr_('arkt',subst,'9').
nr_('arkansas',subst,'').
nr_('arizon',subst,'').
nr_('aristotel',pers,'').
nr_('aristofan',subst,'').
nr_('argonaŭt',subst,'').
nr_('argentin',subst,'').
nr_('ares',subst,'').
nr_('areopag',subst,'').
nr_('aral',subst,'').
nr_('apolon',subst,'').
nr_('api',subst,'').
nr_('anunciaci',subst,'*').
nr_('antverpen',subst,'').
nr_('antoni',pers,'').
nr_('antonen',pers,'').
nr_('anton',pers,'*').
nr_('antil',subst,'').
nr_('antigv',subst,'').
nr_('antarkt',subst,'9').
nr_('antananariv',subst,'').
nr_('anselm',pers,'').
nr_('ann',pers,'*').
nr_('ankar',subst,'').
nr_('angol',subst,'').
nr_('angli',subst,'').
nr_('angar',subst,'').
nr_('andromed',subst,'').
nr_('andre',pers,'').
nr_('andrapradeŝ',subst,'').
nr_('andor',subst,'').
nr_('andaluzi',subst,'').
nr_('and',subst,'').
nr_('anatoli',subst,'').
nr_('anatol',pers,'').
nr_('anastazi',pers,'').
nr_('anabaz',subst,'').
nr_('amudarj',subst,'').
nr_('amsterdam',subst,'').
nr_('amper',pers,'').
nr_('amitab',subst,'').
nr_('amir',pers,'').
nr_('amerik',subst,'8').
nr_('ambrozi',pers,'').
nr_('amazon',subst,'').
nr_('aman',subst,'').
nr_('amade',pers,'').
nr_('alĝeri',subst,'8').
nr_('alĝer',subst,'').
nr_('alzac',subst,'').
nr_('altaj',subst,'').
nr_('altair',subst,'').
nr_('almat',subst,'').
nr_('alfred',pers,'').
nr_('alfons',pers,'').
nr_('aleksandri',subst,'').
nr_('aleksandr',pers,'*').
nr_('albert',pers,'').
nr_('albert',subst,'').
nr_('albani',subst,'').
nr_('alask',subst,'').
nr_('alan',pers,'').
nr_('alah',subst,'').
nr_('alabam',subst,'').
nr_('akr',subst,'').
nr_('aken',subst,'').
nr_('akad',subst,'').
nr_('ahmadism',subst,'').
nr_('ahmadabad',subst,'').
nr_('agni',subst,'').
nr_('afrodit',subst,'').
nr_('afrik',subst,'8').
nr_('advent',subst,'1').
nr_('adriatik',subst,'').
nr_('adrian',pers,'').
nr_('adolf',pers,'').
nr_('adis-Abeb',subst,'').
nr_('adan',subst,'').
nr_('adam',pers,'').
nr_('adalbert',pers,'').
nr_('abuĝ',subst,'').
nr_('abudabi',subst,'').
nr_('abraham',pers,'').
nr_('abiĝan',subst,'').
nr_('abidarm',subst,'').
nr_('abel',pers,'').
nr_('abas',pers,'').
