#!/bin/bash

# kreas/eldonas la procezujon kun la analizilo
eldono=2o

# ni komprenas preparo | kreo | docker | servilo | etikedo
# kaj supozas "docker", se nenio donita argumente
target="${1}"
procezujo="voko-akrido"

case $target in
docker)
    ;;
servilo)
    ;;
preparo)
    # kontrolu ĉu la branĉo kongruas kun la agordita versio
    branch=$(git symbolic-ref --short HEAD)
    if [ "${branch}" != "${eldono}" ]; then
        echo "Ne kongruas la branĉo (${branch}) kun la eldono (${eldono})"
        echo "Agordu la variablon 'eldono' en tiu ĉi skripto por prepari novan eldonon."
        exit 1
    fi
    ;;
etikedo)
    echo "Provizante la aktualan staton per etikedo (git tag) v${eldono}"
    echo "kaj puŝante tiun staton al la centra deponejo"
    git tag -f v${eldono} && git push && git push origin v${eldono} -f
    ;;
kreo)
    echo "Kreante lokan procezujon (por docker) voko-araneo por eldono ${eldono}..."
    docker pull ghcr.io/revuloj/${procezujo}/${procezujo}:${eldono}
    docker build --build-arg VERSION=${eldono} -t ${procezujo} .
    ;;
esac
