v('ŭoŭ',intj).
v('ŝŝ',intj).
v('ŝpruc',intj).
v('ĉit',intj).
v('zzz',intj).
v('vaŭ',intj).
v('ups',intj).
v('tus',intj).
v('ts',intj).
v('trateratra',intj).
v('tpr',intj).
v('tin',intj).
v('tiktak',intj).
v('ta',intj).
v('sss',intj).
v('snuf',intj).
v('rukt',intj).
v('ruk',intj).
v('raĉ',intj).
v('pum',intj).
v('plaŭ',intj).
v('pland',intj).
v('pa',intj).
v('oj',intj).
v('mu',intj).
v('miaŭ',intj).
v('mek',intj).
v('maĉ',intj).
v('kŭaks',intj).
v('kvak',intj).
v('kva',intj).
v('kurre',intj).
v('kriĉ',intj).
v('kraŝ',intj).
v('krak',intj).
v('knar',intj).
v('kluk',intj).
v('klak',intj).
v('ia',intj).
v('hura',intj).
v('huj',intj).
v('hu',intj).
v('hrr',intj).
v('hot',intj).
v('hop',intj).
v('ho',intj).
v('hm',intj).
v('help',intj).
v('hej',intj).
v('he',intj).
v('ha',intj).
v('gut',intj).
v('glut',intj).
v('glu',intj).
v('fu',intj).
v('frap',intj).
v('ehe',intj).
v('dirlididi',intj).
v('bum',intj).
v('brr',intj).
v('boj',intj).
v('blabla',intj).
v('baŭ',intj).
v('bat',intj).
v('baf',intj).
v('bac',intj).
v('aŭ',intj).
v('aĥ',intj).
v('aj',intj).
v('aha',intj).
